/* eslint-disable prettier/prettier */
export default {
  username: 'Username',
  password: 'Password',
  Server: 'Server IP',
  login: 'Login',
  welcome: 'Welcome',
  change_language: 'Change language',
  Tabs: 'Home',

  Lista_instalaciones: 'Installations',
  Maintenance: 'Maintenance',
  DetallesInstalacion: 'Installation details',
  Grabar: 'Record',
  EstadoStore: 'Store status',
  Nodata: 'No data',
  DosimacRegistration: 'Registration',
  NewDmMaternity: 'New Dosimac maternity',
  DosimacG: 'Dosimac-G',
  DosimacI: 'Dosimac-I',
  UpdDmMaternity: 'Update Dosimac maternity',
  NewDmGestation: 'New Dosimac gestation',
  UpdDmGestation: 'Update Dosimac gestation',
  StartScan: 'Search DOSIMAC devices',
  DosimacList: 'DOSIMAC devices',
  PressToScan: 'Press',
  DosimacSetup: 'Configuration',
  TestoPresioneAlta: 'Press the button to search devices',
  Instalación_seleccionada: 'Selected installation',
  NoInstalacionSeleccionada: 'No installation selected',
  BorrarGranja: 'Delete farm',
  Deseaborrarlagranja: 'Do you want to delete the farm?',
  Guardar: 'Save',
  Cancelar: 'Cancel',
  Aceptar: 'Accept',
  NombreGranja: 'Farm name',
  Localidad: 'Location',
  Provincia: 'Province',
  NombreWifi: 'Wifi SSID',
  PasswordWifi: 'Wifi password',
  No_hay_dispositivos: 'No devices',
  Aviso: 'Notice',
  SearchingDevices: 'Searching devices...',
  NoSePuedeBorrarGranja: 'You cannot delete a new farm',
  settings: 'Settings',
  softwareVersion: 'Software version',
  numeroCoral: 'Pen number',
  numeroMaquina: 'Machine number',
  Enviar: 'Send',
  Salir: 'Exit',
  Informacion: 'Information',
  InicioConfiguracion: "Starting connection",
  ConfiguracionWifi: "Configuring...",
  ConfiguracionRealizada: "*Configuration completed*",
  ErrorConfiguracion: "*Configuration error*",
  CapturaTagCorral: "Capture corral tag",
  CorralTag: "Corral tag",
  versionUint16: "This device version only supports corral up to 65000",
  versionUint32: "This device version supports corral up to 4000000000",

  EnvioConfiguracion: "Sending configuration",
  NumeroCorral: "Pen number",
  NumeroMaquina: "Machine number",
  Corralnovalida: "Invalid corral",
  NumeroMaquinanovalida: "Invalid machine number",
  configuarIntalacion: "You must configure an installation to continue",

  login_title: "Sign in",
  login_subtitle: "Enter your details. It is necessary to configure the IP before signing in from the IP Settings menu.",
  login_username: "Username",
  login_password: "Password",
  login_button: "Sign in",
  login_loading: "Signing in...",
  login_footer: "Control panel",

  login_ipRequiredTitle: "IP configuration required",
  login_ipRequiredMessage: "You have not configured the server IP address. Enter it to be able to sign in.",
  login_serverIpLabel: "Server IP",
  login_cancel: "Cancel",
  login_accept: "Accept",
  login_invalidCredentials: "Incorrect username or password",

  login_configTitle: "Configuration",
  login_errorTitle: "Login error",
  login_genericErrorTitle: "Error",
  login_networkErrorTitle: "Network error",
  login_networkErrorMessage: "Could not connect to the server.",
  login_noTokenMessage: "The backend did not return any token.",
  login_missingDataTitle: "Missing data",
  login_missingDataMessage: "Enter username and password.",
  login_invalidIpTitle: "Invalid IP",
  login_invalidIpMessage: "Enter a valid IP or server address.",
  login_saveIpErrorMessage: "Could not save the IP configuration.",
  awrStartScan_title: "Configuración AWR",
  awrStartScan_description: "Screen to scan Agrident AWR readers.",
  awrStartScan_button: "Scan AWR",

  gestacionConfig_screenTitle: "Gestation Settings",
  gestacionConfig_chooseOptionTitle: "Choose an option",
  gestacionConfig_chooseOptionDescription: "Define the workflow before starting with the reader.",

  gestacionConfig_entry: "Entry",
  gestacionConfig_exit: "Exit",
  gestacionConfig_reading: "Reading",
  gestacionConfig_search: "Search",

  gestacionConfig_entryParamsTitle: "Entry parameters",
  gestacionConfig_exitParamsTitle: "Exit parameters",
  gestacionConfig_entryParamsDescription: "Select the pen and the workflow behavior.",
  gestacionConfig_exitParamsDescription: "Configure the exit workflow behavior.",

  gestacionConfig_corralLabel: "Pen",
  gestacionConfig_corralPlaceholder: "Ex: 1",
  gestacionConfig_corralRequired: "Enter the pen to continue.",

  gestacionConfig_detectUnknownTitle: "Identify unknown animals",
  gestacionConfig_detectUnknownDescription: "When you read an unidentified animal, you will be able to assign it an ID",

  gestacionConfig_confirmTitle: "Confirm submission",
  gestacionConfig_confirmDescription: "It will ask for confirmation before sending the records.",

  gestacionConfig_animalSearchTitle: "Animal search",
  gestacionConfig_animalSearchDescription: "Choose whether you want to search by ear tag or ID.",
  gestacionConfig_searchByCrotal: "By ear tag",
  gestacionConfig_searchById: "By ID",
  gestacionConfig_manual: "Manual",
  gestacionConfig_withSword: "With reader",

  gestacionConfig_crotalLabelSearch: "Ear tag",
  gestacionConfig_idLabelSearch: "ID",
  gestacionConfig_crotalPlaceholderSearch: "Ex: 982091072397436",
  gestacionConfig_idPlaceholderSearch: "Ex: A13",
  gestacionConfig_crotalRequiredSearch: "Enter an ear tag to continue.",
  gestacionConfig_idRequiredSearch: "Enter an ID to continue.",

  gestacionConfig_searchWithSwordHelp: "When you continue, the reader will scan on this screen and the animal will be searched using that ear tag.",

  gestacionConfig_readingSword: "Reading reader...",
  gestacionConfig_waitingMatch: "Waiting for match",
  gestacionConfig_searchingAnimal: "Searching animal...",

  gestacionConfig_readingSwordDescription: "Bring the ear tag close to the reader to identify the animal.",
  gestacionConfig_waitingMatchDescription: "Animal found. Now bring ear tag {{crotal}} close to the reader to confirm the match.",
  gestacionConfig_searchingAnimalDescription: "Checking animal information in the backend.",

  gestacionConfig_awrDisconnectedTitle: "AWR not connected",
  gestacionConfig_awrSavedDescription: "You have saved readers. Tap to select one.",
  gestacionConfig_awrNotSavedDescription: "You do not have any saved readers. Tap to scan one.",

  gestacionConfig_scan: "Scan",
  gestacionConfig_continue: "Continue",

  gestacionConfig_alerts_error: "Error",
  gestacionConfig_alerts_networkError: "Network error",
  gestacionConfig_alerts_networkErrorMessage: "Could not connect to the server.",
  gestacionConfig_alerts_backendNoValidCrotal: "The backend did not return a valid ear tag for comparison.",
  gestacionConfig_alerts_awrNotConnected: "AWR not connected",
  gestacionConfig_alerts_connectSwordBeforeContinue: "Connect a reader before continuing.",
  gestacionConfig_alerts_couldNotStartReading: "Could not start reading with the reader.",

  gestacionConfig_alerts_missingData: "Missing data",
  gestacionConfig_alerts_writeCrotalToSearch: "Enter an ear tag to search.",
  gestacionConfig_alerts_writeIdToSearch: "Enter an ID to search.",

  gestacionConfig_alerts_notFound: "Not found",
  gestacionConfig_alerts_animalNotFoundByCrotal: "No animal exists with that ear tag.",
  gestacionConfig_alerts_animalNotFoundById: "No animal exists with that ID.",

  gestacionConfig_alerts_warning: "Warning",
  gestacionConfig_alerts_searchError: "Search error",

  maternidadConfig_screenTitle: "Maternity Settings",
  maternidadConfig_chooseOptionTitle: "Choose an option",
  maternidadConfig_chooseOptionDescription: "Set the workflow before starting the reader.",
  maternidadConfig_entry: "Entry",
  maternidadConfig_exit: "Exit",
  maternidadConfig_reading: "Reading",
  maternidadConfig_search: "Search",
  maternidadConfig_entryParamsTitle: "Entry parameters",
  maternidadConfig_exitParamsTitle: "Exit parameters",
  maternidadConfig_entryParamsDescription: "Select the pen and workflow behavior.",
  maternidadConfig_exitParamsDescription: "Configure the exit workflow behavior.",
  maternidadConfig_corralLabel: "Pen",
  maternidadConfig_corralPlaceholder: "Ex: 1",
  maternidadConfig_corralRequired: "Enter the pen to continue.",
  maternidadConfig_detectUnknownTitle: "Identify unknown animals",
  maternidadConfig_detectUnknownDescription: "When you read an unidentified animal, you will be able to assign it an ID",
  maternidadConfig_confirmTitle: "Confirm sending",
  maternidadConfig_confirmDescription: "It will ask for confirmation before sending each record.",
  maternidadConfig_animalSearchTitle: "Animal search",
  maternidadConfig_animalSearchDescription: "Choose whether you want to search by ear tag or ID.",
  maternidadConfig_searchByCrotal: "By ear tag",
  maternidadConfig_searchById: "By ID",
  maternidadConfig_manual: "Manual",
  maternidadConfig_withSword: "With reader",
  maternidadConfig_crotalLabelSearch: "Ear tag",
  maternidadConfig_idLabelSearch: "ID",
  maternidadConfig_crotalPlaceholderSearch: "Ex: 982091072397436",
  maternidadConfig_idPlaceholderSearch: "Ex: A13",
  maternidadConfig_crotalRequiredSearch: "Enter an ear tag to continue.",
  maternidadConfig_idRequiredSearch: "Enter an ID to continue.",
  maternidadConfig_searchWithSwordHelp: "When you tap Scan, the reader will be used on this screen and the animal will be searched by that ear tag.",
  maternidadConfig_readingSword: "Reading reader...",
  maternidadConfig_waitingMatch: "Waiting for match",
  maternidadConfig_searchingAnimal: "Searching animal...",
  maternidadConfig_readingSwordDescription: "Bring the ear tag close to the reader to identify the animal.",
  maternidadConfig_waitingMatchDescription: "Animal found. Now bring ear tag {{crotal}} close to the reader to confirm the match.",
  maternidadConfig_searchingAnimalDescription: "Checking animal information in the backend.",
  maternidadConfig_awrDisconnectedTitle: "AWR not connected",
  maternidadConfig_awrSavedDescription: "You have saved AWR devices. Tap to select one.",
  maternidadConfig_awrNotSavedDescription: "You do not have any saved AWR devices. Tap to scan one.",
  maternidadConfig_scan: "Scan",
  maternidadConfig_continue: "Continue",
  maternidadConfig_alert_error: "Error",
  maternidadConfig_alert_invalidBackendCrotal: "The backend did not return a valid ear tag to compare.",
  maternidadConfig_alert_awrNotConnected: "AWR not connected",
  maternidadConfig_alert_connectSwordBeforeContinue: "Connect a reader before continuing.",
  maternidadConfig_alert_couldNotStartReading: "Could not start reading with the reader.",
  maternidadConfig_alert_missingData: "Missing data",
  maternidadConfig_alert_writeCrotalToSearch: "Enter an ear tag to search.",
  maternidadConfig_alert_writeIdToSearch: "Enter an ID to search.",
  maternidadConfig_alert_notFound: "Not found",
  maternidadConfig_alert_noAnimalWithCrotal: "There is no animal with that ear tag.",
  maternidadConfig_alert_noAnimalWithId: "There is no animal with that ID.",
  maternidadConfig_alert_warning: "Warning",
  maternidadConfig_alert_searchError: "Search error",
  maternidadConfig_alert_networkError: "Network error",
  maternidadConfig_alert_networkErrorMessage: "Could not connect to the server.",


  gestationReader_screenTitle: "Gestation Reader",

  gestationReader_animalInfoTitle: "Animal information",
  gestationReader_animalInfoDescription: "Data found in the search.",
  gestationReader_animalCardTitle: "Animal Record",
  gestationReader_animalIdLabel: "ID",
  gestationReader_animalCrotalLabel: "Ear tag",
  gestationReader_fieldCorral: "Pen",
  gestationReader_fieldHouse: "Barn",
  gestationReader_fieldState: "Status",
  gestationReader_fieldBodyCondition: "Body condition",
  gestationReader_fieldCycle: "Cycle",
  gestationReader_fieldSystemEntryDate: "System entry date",
  gestationReader_newSearch: "New search",

  gestationReader_summaryTitle: "Summary",
  gestationReader_summaryDescription: "Parameters chosen in Settings",
  gestationReader_mode: "Mode",
  gestationReader_corral: "Pen",
  gestationReader_modeEntry: "Entry",
  gestationReader_modeExit: "Exit",
  gestationReader_modeReading: "Reading",
  gestationReader_modeSearch: "Search",
  gestationReader_detectUnknownTitle: "Identify unknown animals",
  gestationReader_detectUnknownDescription: "When an animal without ID appears, allow assigning an ID.",
  gestationReader_confirmSendTitle: "Confirm sending",
  gestationReader_confirmSendDescription: "It will ask for confirmation before sending each record.",
  gestationReader_changeSettings: "Change settings",

  gestationReader_currentReadingTitle: "Current reading",
  gestationReader_currentReadingDescription: "The detected ear tag and associated ID will appear here.",
  gestationReader_awrDisconnected: "AWR not connected",
  gestationReader_readCrotal: "Read ear tag",
  gestationReader_readId: "ID",
  gestationReader_animalWithoutAssignedId: "Animal without assigned ID",
  gestationReader_unknownAnimal: "Unknown animal",

  gestationReader_animalWithoutIdTitle: "Animal without ID",
  gestationReader_animalWithoutIdDescription: "Enter a manual ID to update the scanned ear tag.",
  gestationReader_newIdLabel: "New ID",
  gestationReader_newIdPlaceholder: "Ex: A13",
  gestationReader_updateId: "Update ID",
  gestationReader_updatingId: "Updating...",

  gestationReader_sentRecordsTitle: "Sent records",
  gestationReader_noRecords: "No records.",
  gestationReader_tableHeaderCorral: "Pen",
  gestationReader_tableHeaderId: "ID",
  gestationReader_tableHeaderCrotal: "Ear tag",

  gestationReader_buttonAutoReading: "Automatic reading active",
  gestationReader_buttonAutoSending: "Automatic sending active",
  gestationReader_buttonSending: "Sending...",
  gestationReader_buttonSend: "Send",

  gestationReader_alertError: "Error",
  gestationReader_alertWarning: "Warning",
  gestationReader_alertNetworkError: "Network error",

  gestationReader_alertMissingCrotalTitle: "Ear tag missing",
  gestationReader_alertMissingCrotalMessage: "Bring the ear tag close to the reader before sending.",
  gestationReader_alertInvalidCrotalTitle: "Invalid ear tag",
  gestationReader_alertInvalidCrotalMessage: "The ear tag must be numeric.",
  gestationReader_alertReadErrorTitle: "Reading error",
  gestationReader_alertNetworkErrorMessage: "Could not connect to the server.",

  gestationReader_alertMissingCorralTitle: "Pen missing",
  gestationReader_alertMissingCorralMessage: "Enter the pen before sending.",
  gestationReader_alertInvalidCorralTitle: "Invalid pen",
  gestationReader_alertInvalidCorralMessage: "The pen must be a number.",
  gestationReader_alertSendErrorTitle: "Error sending",
  gestationReader_alertNoIpConfigured: "No IP configured.",

  gestationReader_alertMissingIdTitle: "ID missing",
  gestationReader_alertMissingIdMessage: "Enter the new ID before updating.",
  gestationReader_alertMissingAssociatedCrotalTitle: "Ear tag missing",
  gestationReader_alertMissingAssociatedCrotalMessage: "There is no associated ear tag to update.",
  gestationReader_alertInvalidAssociatedCrotalTitle: "Invalid ear tag",
  gestationReader_alertInvalidAssociatedCrotalMessage: "The associated ear tag is not valid.",
  gestationReader_alertUpdateIdErrorTitle: "Error updating ID",


  maternityReader_screenTitle: "Maternity Reader",
  maternityReader_alertMissingCrotalTitle: "Missing ear tag",
  maternityReader_alertMissingCrotalMessage: "Bring the ear tag close to the reader before sending.",
  maternityReader_alertInvalidCrotalTitle: "Invalid ear tag",
  maternityReader_alertInvalidCrotalMessage: "The ear tag must be numeric.",
  maternityReader_alertReadErrorTitle: "Read error",
  maternityReader_alertNetworkError: "Network error",
  maternityReader_alertNetworkErrorMessage: "Could not connect to the server.",
  maternityReader_alertMissingCorralTitle: "Missing pen",
  maternityReader_alertMissingCorralMessage: "Enter the pen before sending.",
  maternityReader_alertInvalidCorralTitle: "Invalid pen",
  maternityReader_alertInvalidCorralMessage: "The pen must be a number (e.g. 8).",
  maternityReader_alertError: "Error",
  maternityReader_alertNoIpConfigured: "No IP configured.",
  maternityReader_alertWarning: "Warning",
  maternityReader_alertSendErrorTitle: "Send error",
  maternityReader_alertMissingIdTitle: "Missing ID",
  maternityReader_alertMissingIdMessage: "Enter the new ID before updating.",
  maternityReader_alertMissingAssociatedCrotalTitle: "Missing ear tag",
  maternityReader_alertMissingAssociatedCrotalMessage: "There is no associated ear tag to update.",
  maternityReader_alertInvalidAssociatedCrotalTitle: "Invalid ear tag",
  maternityReader_alertInvalidAssociatedCrotalMessage: "The associated ear tag is not valid.",
  maternityReader_alertUpdateIdErrorTitle: "Error updating ID",
  maternityReader_animalInfoTitle: "Animal information",
  maternityReader_animalInfoDescription: "Data found in the search.",
  maternityReader_animalCardTitle: "Animal record",
  maternityReader_animalIdLabel: "ID",
  maternityReader_animalCrotalLabel: "Ear tag",
  maternityReader_fieldCorral: "Pen",
  maternityReader_fieldHouse: "House",
  maternityReader_fieldState: "Status",
  maternityReader_fieldBodyCondition: "Body condition",
  maternityReader_fieldCycle: "Cycle",
  maternityReader_fieldSystemEntryDate: "System entry",
  maternityReader_newSearch: "New search",
  maternityReader_summaryTitle: "Summary",
  maternityReader_summaryDescription: "Parameters selected in Settings",
  maternityReader_mode: "Mode",
  maternityReader_modeEntry: "Entry",
  maternityReader_modeExit: "Exit",
  maternityReader_modeReading: "Reading",
  maternityReader_corral: "Pen",
  maternityReader_detectUnknownTitle: "Identify unknown animals",
  maternityReader_detectUnknownDescription: "If an animal appears without an ID, allow assigning one.",
  maternityReader_confirmSendTitle: "Confirm send",
  maternityReader_confirmSendDescription: "It will ask for confirmation before sending each record.",
  maternityReader_changeSettings: "Change settings",
  maternityReader_currentReadingTitle: "Current reading",
  maternityReader_currentReadingDescription: "The detected ear tag will appear here.",
  maternityReader_awrDisconnected: "AWR not connected",
  maternityReader_readCrotal: "Read ear tag",
  maternityReader_readId: "ID",
  maternityReader_animalWithoutAssignedId: "Animal without assigned ID",
  maternityReader_unknownAnimal: "Unknown animal",
  maternityReader_animalWithoutIdTitle: "Animal without ID",
  maternityReader_animalWithoutIdDescription: "Enter a manual ID to update the read ear tag.",
  maternityReader_newIdLabel: "New ID",
  maternityReader_newIdPlaceholder: "E.g. A13",
  maternityReader_updatingId: "Updating...",
  maternityReader_updateId: "Update ID",
  maternityReader_sentRecordsTitle: "Sent records",
  maternityReader_tableHeaderCorral: "Pen",
  maternityReader_tableHeaderId: "ID",
  maternityReader_tableHeaderCrotal: "Ear tag",
  maternityReader_noRecords: "No records.",
  maternityReader_buttonAutoReading: "Automatic reading active",
  maternityReader_buttonAutoSending: "Automatic sending active",
  maternityReader_buttonSending: "Sending...",
  maternityReader_buttonSend: "Send",

  awrScanResults_title: "AWR – Scan Results",
  awrScanResults_searching: "Searching for AWR…",
  awrScanResults_warningTitle: "Warning",
  awrScanResults_noDevicesNearby: "No nearby AWR devices were found.",
  awrScanResults_connecting: "Connecting…",
  awrScanResults_connectErrorFallback: "Could not connect",
  awrScanResults_connectedTitle: "Connected",
  awrScanResults_connectedMessage: "Connection established with {{device}}.",
  awrScanResults_genericDevice: "the device",
  awrBluetoothPermissionMessage: "Turn on Bluetooth and accept the permission to be able to scan.",


  awrSavedList_title: "Scanned AWRs",
  awrSavedList_connecting: "Connecting…",
  awrSavedList_empty: "There are no saved AWR devices. Scan one from “AWR Settings”.",
  awrSavedList_connected: "Connected",
  awrSavedList_disconnected: "Disconnected",
  awrSavedList_renameAccessibility: "Rename",
  awrSavedList_deleteAccessibility: "Delete",
  awrSavedList_renameTitle: "Rename AWR",
  awrSavedList_nameLabel: "Name",
  awrSavedList_deleteTitle: "Delete saved AWR",
  awrSavedList_deleteMessage: "Are you sure you want to remove this AWR from the list?",
  awrSavedList_deleteAction: "Delete",

  ipConfig_title: "IP Settings",
  ipConfig_cardTitle: "CTIFEED Server",
  ipConfig_cardDescription: "Enter the server IP where the portal will be opened.",
  ipConfig_inputLabel: "IP (IP only)",
  ipConfig_saved: "Saved",
  ipConfig_alertSuccessTitle: "Correct",
  ipConfig_alertSuccessMessage: "Correct IP",
  ipConfig_alertWarningTitle: "Warning",
  ipConfig_alertServerNotUpdated: "Server not updated",
  ipConfig_alertErrorTitle: "Error",
  ipConfig_alertInvalidIp: "Invalid IP",

  portal_preparing: "Preparing portal...",
  portal_noSessionToken: "There is no session token. Please sign in again.",
  portal_noIpConfigured: "No IP is configured. Please configure the server IP first.",
  portal_prepareUrlError: "The portal URL could not be prepared.",
  portal_loadError: "The portal could not be loaded.",
  portal_checkingConnection: "Checking portal connection...",
  portal_noConnectionTitle: "No connection",
  portal_connectionTimeout: "The portal could not be reached. Please check that you are connected to the correct network.",
  portal_connectionError: "The portal could not be reached. Please check the network or the configured IP.",
  portal_httpError: "The portal could not be opened. HTTP error {{status}}.",
  portal_retry: "Retry",
  portal_loading: "Loading portal...",


  AltaDispositivos: "Device registration",
  LectorMaternidad: "Maternity Reader",
  LectorGestacion: "Gestation Reader",
  ConfiguracionIP: "IP Settings",
  ConfiguracionAWR: "AWR Settings",
  DarDeAltaAWR: "Register AWR",
  AWREscaneados: "Scanned AWRs",
  CerrarSesion: "Log out",

  Config_lastReadMismatchTitle: "The scanned animal does not match the search",
  Config_lastReadMismatchCrotal: "Ear tag",
  Config_lastReadMismatchId: "ID",

  gestacionConfig_lastReadMismatchTitle: "The scanned animal does not match the search",
   gestacionConfig_lastReadMismatchCrotal: "Ear tag",
   gestacionConfig_lastReadMismatchId: "ID",
    animalState: {
    gestation: "Gestation",
    maternity: "Maternity",
    out_of_gestation: "Out of gestation",
    out_of_maternity: "Out of maternity"
  },

Reader_readingTitle: "Ear Tag Reading",
Reader_labelId: "ID",
Reader_labelCrotal: "Ear Tag",
Reader_labelCorral: "Pen",
Reader_labelHouse: "House",
Reader_labelState: "State",
Reader_autoReadingBadge: "Automatic reading",

gestacionConfig_flowSectionTitle: "Flow configuration",
gestacionConfig_workModeTitle: "Work mode",
gestacionConfig_workModeDescription: "Select what the reader will do.",
gestacionConfig_entryDescription: "Register entry",
gestacionConfig_exitDescription: "Register exit",
gestacionConfig_readingDescription: "Read only",
gestacionConfig_searchDescription: "Search animal",

gestacionConfig_sendSettingsTitle: "Sending settings",
gestacionConfig_sendSettingsDescription: "Configure how the flow behaves when reading animals.",

gestacionConfig_corralSectionTitle: "Entry pen",
gestacionConfig_corralSectionDescription: "This field is required to continue with the record.",

gestacionConfig_alerts_notice: "Notice",
gestacionConfig_alerts_invalidCrotalFromBackend: "The backend did not return a valid ear tag to compare.",

common_accept: "Accept",

maternidadConfig_flowSectionTitle: "Flow configuration",
maternidadConfig_workModeTitle: "Work mode",
maternidadConfig_workModeDescription: "Select what the reader will do.",
maternidadConfig_entryDescription: "Register entry",
maternidadConfig_exitDescription: "Register exit",
maternidadConfig_readingDescription: "Read only",
maternidadConfig_searchDescription: "Search animal",

maternidadConfig_sendSettingsTitle: "Sending settings",
maternidadConfig_sendSettingsDescription: "Configure how the flow behaves when reading animals.",

maternidadConfig_corralSectionTitle: "Entry pen",
maternidadConfig_corralSectionDescription: "This field is required to continue with the record.",

maternidadConfig_alert_invalidCrotalFromBackend: "The backend did not return a valid ear tag to compare.",

maternidadConfig_readOnlyTitle: "Read-only permission",
maternidadConfig_readOnlyModifySettings: "This user only has read-only permissions. They cannot modify this configuration.",
maternidadConfig_readOnlyUseFunction: "This user only has read-only permissions. They cannot use this function.",


 ajustesEnvioMaternidad: {
    headerTitle: "Sending settings",
    headerSubtitle: "Configure how the flow behaves when reading animals.",
    cardTitle: "Record sending",
    cardSubtitle: "These settings are applied when continuing with the reading."
  },

  noAlimentadosMaternidad: {
  animalId: "ANIMAL ID",
  corral: "Pen",
  consumption: "Consumption",
  withoutFeeding: "Unfed",
  day: "day",
  days: "days",
  loadingAnimals: "Loading animals...",
  title: "Unfed animals",
  totalAnimalsMaternity: "Total maternity animals:",
  notSeen: "Not seen",
  all: "All",
  sort: "Sort",
  emptyTitle: "No pending animals",
  emptyText: "No unfed animals were found in maternity.",
  sortBy: "Sort by",
  daysWithoutFeeding: "Days without feeding",
  sortDaysHelp: "Sorts by the number of days without feeding",
  sortCorralHelp: "Sorts by pen number",
  descending: "Descending",
  ascending: "Ascending",
  filterAnimals: "Filter animals",
  allHelp: "Shows all animals",
  unmarked: "Unmarked",
  unmarkedHelp: "Hides animals that have already been reviewed",
  clearMarkedTitle: "Clear marked animals",
  clearMarkedText: "All marks from reviewed animals will be removed.",
  cancel: "Cancel",
  clear: "Clear",
  error: "Error",
  serverConnectionError: "Could not connect to the server."
},

noAlimentadosGestacion: {
  animalId: "ANIMAL ID",
  corral: "Pen",
  consumption: "Consumption",
  withoutFeeding: "Unfed",
  day: "day",
  days: "days",
  loadingAnimals: "Loading animals...",
  title: "Unfed animals",
  totalAnimalsGestation: "Total gestation animals:",
  notSeen: "Not seen",
  all: "All",
  sort: "Sort",
  emptyTitle: "No pending animals",
  emptyText: "No unfed animals were found in gestation.",
  sortBy: "Sort by",
  daysWithoutFeeding: "Days without feeding",
  sortDaysHelp: "Sorts by the number of days without feeding",
  sortCorralHelp: "Sorts by pen number",
  descending: "Descending",
  ascending: "Ascending",
  filterAnimals: "Filter animals",
  allHelp: "Shows all animals",
  unmarked: "Unmarked",
  unmarkedHelp: "Hides animals that have already been reviewed",
  clearMarkedTitle: "Clear marked animals",
  clearMarkedText: "All marks from reviewed animals will be removed.",
  cancel: "Cancel",
  clear: "Clear",
  error: "Error",
  serverConnectionError: "Could not connect to the server."
},

capturaAnimalHome: {
  selectOption: "Select an option",
  unfedAnimalsTitle: "Unfed animals",
  unfedAnimalsDescription: "Check animals that have not received the planned feeding.",
  twoFeedsTitle: "2 feeds",
  twoFeedsDescription: "Manage feed changes in the drop outlets.",
  animalStatusTitle: "Animal status",
animalStatusDescription: "Check or update the animal status.",
birthCaptureTitle: "Birth capture",
birthCaptureDescription: "Register live, dead and mummified piglets.",
},
cambioPiensoMaternidad: {
  error: "Error",
  loadTasksError: "Could not load feed change tasks.",
  loadingTasks: "Loading tasks...",
  title: "Feed change",
  pendingTask: "{{count}} pending task",
  pendingTasks: "{{count}} pending tasks",
  emptyTitle: "No pending tasks",
  emptyText: "No feed change tasks were found.",
  animalId: "ANIMAL ID",
  corral: "Pen",
  setTo: "Set to",
  destination: "Destination"
},
estadoAnimal: {
  queryLabel: "Query",
  title: "Animal status",
  subtitle: "Select how you want to identify the animal.",
  corral: "Pen",
  corralDescription: "Enter the pen number.",
  id: "ID",
  idDescription: "Enter the animal identifier.",
  animalId: "Animal ID",
  requiredData: "Required data",
  enterCorral: "Enter the pen number.",
  enterId: "Enter the animal identifier.",
  consulting: "Checking...",
  continue: "Continue",
  accept: "Accept",
  serverConnectionError: "Could not connect to the server.",
  noIpConfigured: "No IP address is configured.",
  nextScreenPending: "We will create the animal information screen in the next step."
},
matCorralDetail: {
  readOnlyPermission: "Read-only permission",
readOnlyPermissionText: "This user only has read permissions. They cannot perform operations on the animal.",
  animalStatus: "Animal status",
  id: "ID",
  earTag: "Ear tag",
  cycle: "Cycle",
  day: "Day",

  curve: "Curve",
  correction: "Correction",
  entryDate: "Entry date",
  farrowingDate: "Farrowing date",
  house: "House",
  pen: "Pen",
  lastFeeding: "Last feeding",
  presentPiglets: "Present piglets",
  inseminationDate: "Insemination date",
  teatsNumber: "No. of teats",

  operations: "Operations",

  consumption: "Consumption",
  ofGrams: "of {{amount}} g",
  oneDayWithoutFeeding: "1 day without feeding",
  daysWithoutFeeding: "{{count}} days without feeding",

  noAnimalData: "No animal data",
  noAnimalDataText: "No information has been received to display.",
  back: "Back",
  operationsPendingTitle: "Operations",
  operationsPendingText: "We will do the operations in the next step.",
  moveToWeaning: "Move to weaning",
  chooseOption: "Select an operation for this animal.",
  nextOperation: "Next operation",
  insertAnimal: "Insert animal",
  moveToLactation: "Move to lactation",
  nextStep: "Next step",
  actions: "Actions",

  bodyCondition: "Body condition",
  subState: "Sub-state",
  pigletCapture: "Piglet capture",
  animalExit: "Animal exit",
  replaceEarTag: "Replace ear tag",
  changePen: "Change pen",
  anonymousAnimalId: "Anonymous animal identifier",

  cancel: "Cancel",
  accept: "Accept",
  saving: "Saving...",
  error: "Error",

  operationDone: "Operation completed successfully.",
  changeStateDone: "Sub-state updated successfully.",
  changeStateError: "The animal state could not be changed.",
  confirmNextOperation: "Are you sure you want to move to the next operation?",
  pkidChangeStateNotFound: "The animal internal identifier was not found.",

  selectExitType: "Select the exit type you want to apply.",
  exitImmediate: "Immediate exit",
  exitScheduled: "Scheduled exit",
  exitScheduledEmptyHopper: "Scheduled exit with empty hopper",
  cancelScheduledExit: "Cancel scheduled exit",
  scheduledDate: "Scheduled date",
  exitDateLimitText: "You cannot select a date earlier than today or later than 3 days.",
  animalExitDone: "Animal exit completed successfully.",
  animalExitError: "The animal exit could not be completed.",
  pkidExitNotFound: "The animal internal identifier was not found.",

  selectCurve: "Select curve",
  selectCurveText: "Select the animal's new curve.",
  loadingCurves: "Loading curves...",
  noCurvesAvailable: "No curves available.",
  confirmChangeCurve: "Are you sure you want to change the curve?",
  loadCurvesError: "The curves could not be loaded.",
  pkidChangeCurveNotFound: "The animal internal identifier was not found.",
  changeCurveDone: "Curve updated successfully.",
  changeCurveError: "The curve could not be changed.",

  selectBodyConditionText: "Select the animal's new body condition.",
  loadingBodyConditions: "Loading body conditions...",
  noBodyConditionsAvailable: "No body conditions available.",
  confirmChangeBodyCondition: "Are you sure you want to change the body condition?",
  loadBodyConditionsError: "The body conditions could not be loaded.",
  pkidChangeBodyConditionNotFound: "The animal internal identifier was not found.",
  changeBodyConditionDone: "Body condition updated successfully.",
  changeBodyConditionError: "The body condition could not be changed.",

  selectSubStateText: "Manually select the animal's new sub-state.",
  confirmChangeSubState: "Are you sure you want to change the sub-state?",

  currentPen: "Current pen: {{pen}}",
  newPen: "New pen",
  enterNewPen: "Enter the new pen.",
  pkidChangePenNotFound: "The animal internal identifier was not found.",
  changePenDone: "Pen updated successfully.",
  changePenError: "The pen could not be changed.",

  currentEarTag: "Current ear tag: {{earTag}}",
  newEarTag: "New ear tag",
  enterNewEarTag: "Enter the new ear tag.",
  pkidEarTagNotFound: "The animal internal identifier was not found.",
  replaceEarTagDone: "Ear tag updated successfully.",
  replaceEarTagError: "The ear tag could not be replaced.",

  identifyAnonymousAnimalText: "Choose whether you want to assign an ID or an ear tag to the animal.",
  newId: "New ID",
  enterNewId: "Enter the new ID.",
  idExample: "Ex: 1010",
  earTagExample: "Ex: 123",
  notAnonymousAnimalText: "This animal is not anonymous because it already has an ID or ear tag assigned.",
  pkidIdentifyNotFound: "The animal internal identifier was not found.",
  identifyAnonymousAnimalDone: "Animal identifier updated successfully.",
  identifyAnonymousAnimalError: "The anonymous animal could not be identified.",

  livePiglets: "Live",
  deadPiglets: "Dead",
  mummifiedPiglets: "Mummified",
  totalBornPiglets: "Total born",
  pigletCaptureText: "Enter the live, dead and mummified piglets.",
  captureBeforeLactationText: "Register the born piglets before moving to lactation.",
  weaningPigletsOnlyRead: "In weaning, piglets can only be viewed.",
  pkidPigletsNotFound: "The animal internal identifier was not found.",
  pigletCaptureDone: "Piglet capture saved successfully.",
  pigletCaptureError: "The piglet capture could not be saved.",
},
subState: {
  prepartum: "Prepartum",
  lactation: "Lactation",
  weaning: "Weaning",
},

capturaParto: {
  birthDataTitle: "Birth data",
  birthDataSubtitle: "Review the animal data before registering the birth.",
  corral: "Pen",
  id: "ID",
  date: "Date",
  subState: "Sub-state",

  dataCollectionTitle: "Data collection",
  dataCollectionSubtitle: "Enter the live, dead and mummified piglets.",
  weaningReadOnly: "In weaning, the data can only be viewed.",

  totalBorn: "Total born",
  live: "Live",
  dead: "Dead",
  mummified: "Mummified",

  prepartum: "Prepartum",
  farrowing: "Farrowing",
  lactation: "Lactation",
  weaning: "Weaning",

  accept: "Accept",
  cancel: "Cancel",
  saving: "Saving...",

  sentTitle: "Capture sent",
  sentMessage: "The birth capture has been saved successfully.",

  errorTitle: "Error",
  invalidAnimalTitle: "Invalid animal",
  invalidAnimalText: "The animal internal identifier was not found.",
  reportSendError: "The birth capture could not be saved.",

  invalidDateTitle: "Invalid date",
  invalidDateMessage: "The farrowing date cannot be later than today.",
  changeDate: "Change date",

  selectDateTitle: "Select date",
  selectDateMessage: "Adjust the farrowing date using the buttons.",
},

capturaMaternidadEntrada: {
  title: "Birth capture",
  description: "Search for the animal by pen or ID to register the birth.",
  maternityLabel: "MATERNITY",

  corral: "Pen",
  corralDescription: "Search for the animal by pen number.",
  id: "ID",
  idDescription: "Search for the animal by its identifier.",
  animalId: "Animal ID",

  corralExample: "Ex: 102",
  idExample: "Ex: 1234",

  consulting: "Searching...",
  continue: "Continue",
  accept: "Accept",

  serverConnectionError: "Could not connect to the server.",
},
altaBajaStack: {
  tituloPantalla: "Piglet add/remove",
  descripcionPantalla: "Search for the sow by pen or ID to register piglet additions or removals.",
},
altaBajaLechones: {
  heroTitle: "Piglet movement",
  statusAlta: "Addition",
  statusBaja: "Removal",

  corralUpper: "PEN",
  idUpper: "ID",
  dateUpper: "DATE",

  movementType: "Movement type",
  movementSubtitle: "Select whether you want to register an addition or a removal.",
  adoption: "Adoption",
  baja: "Removal",

  adoptionData: "Adoption data",
  donorMother: "Donor sow",
  donatesPiglets: "Donates piglets",
  id: "ID",
  transferredPiglets: "Transferred piglets",
  totalAdopted: "Total adopted",
  total: "Total",

  bajaReason: "Removal reason",
  reasonCrushing: "Crushing",
  reasonDiarrhea: "Diarrhea",
  reasonLowViability: "Low viability",
  reasonDeformities: "Deformities",
  reasonOther: "Other",

  piglet: "piglet",
  piglets: "piglets",
  description: "Description",

  editReason: "Edit reason",
  addReason: "Add reason",
  reasonModalText: "Enter the number of piglets and describe the reason.",

  saving: "Saving...",
  saveAlta: "Save addition",
  saveBaja: "Save removal",
  accept: "Accept",
  cancel: "Cancel",

  error: "Error",
  missingData: "Missing data",
  saveError: "Save error",
  saveErrorText: "The operation could not be saved.",
  selectedAnimalPkidNotFound: "The internal identifier of the selected animal was not found.",

  enterTransferredPiglets: "Enter the number of transferred piglets.",
  invalidTotalTitle: "Invalid total",
  invalidPigletsNumber: "Enter a valid number of piglets.",

  missingDescriptionTitle: "Description required",
  missingDescriptionText: "Enter the reason description.",
  invalidQuantityTitle: "Invalid quantity",
  invalidPigletQuantity: "Enter a valid piglet quantity.",

  selectReasonRequired: "Select at least one removal reason.",

  adoptionSavedTitle: "Addition saved",
  adoptionSavedMessage: "{{count}} piglets have been registered successfully.",

  bajasSavedTitle: "Removals saved",
  bajasSavedMessage: "{{piglets}} removals have been registered successfully for {{reasons}} reason(s).",
},
avisoAplicacionNoConfigurada: {
  title: "Application not configured",
  text: "Configure the Server IP Address",
  link: "Tap here",
},
generalHome: {
  movementAnimalTitle: "Animal movement",
  readerDescription: "Ear tag reader.",
  keyboardDescription: "Keyboard",

  ctifeedTitle: "CTIFEED",
  ctifeedDescription: "Access the main portal.",

  modalApplicationNotConfiguredTitle: "Application not configured",
  modalNoSessionTitle: "Session not started",
  modalInstallationUnavailableTitle: "Installation unavailable",
  modalPreparingSessionTitle: "Preparing session",
  modalReadOnlyPermissionTitle: "Read-only permission",

  modalApplicationNotConfiguredText: "No installation is configured. Go to Installations and select one.",
  modalNoSessionText: "The installation has an IP address, but there is no active session. Check the Username and Password in Installations.",
  modalInstallationUnavailableText: "Cannot connect to the selected installation. Check that you are connected to the correct WiFi network or review the server IP.",
  modalPreparingSessionText: "The session is still loading. Try again in a few seconds.",
  modalReadOnlyPermissionText: "Your user does not have administrator permissions to access this feature.",

  accept: "Accept",

  connectingTitle: "Connecting...",
  connectingText: "Checking connection with the selected installation.",
},

movimientoAnimalMaternidad: {
  smallLabel: "MOVEMENT",
  title: "Maternity",
  subtitle: "Perform manual entries and exits using the keyboard.",

  movementType: "Movement type",
  entry: "Entry",
  exit: "Exit",

  searchAnimal: "Search animal",
  entryHelper: "Enter the destination pen and the animal ID.",
  exitHelper: "Select whether you want to exit by pen or by ID.",

  pen: "Pen",
  animalId: "Animal ID",
  type: "Type",

  sending: "Sending...",
  accept: "Accept",
  cancel: "Cancel",

  confirmEntry: "Confirm entry",
  confirmExit: "Confirm exit",
  confirmSubtitle: "Review the data before sending the movement.",

  incompleteDataTitle: "Incomplete data",
  entryIncompleteText: "Enter the pen and the animal ID.",
  exitPenIncompleteText: "Enter the pen to perform the exit.",
  exitIdIncompleteText: "Enter the animal ID to perform the exit.",

  invalidPenTitle: "Invalid pen",
  invalidPenText: "The pen must be a valid number greater than 0.",

  sendErrorTitle: "Send error",
  connectionErrorTitle: "Connection error",
  noIpConfigured: "No IP address is configured.",
  serverConnectionError: "Could not connect to the server.",
  serverEmptyResponse: "The server did not return a message. HTTP code {{status}}.",

  entrySentTitle: "Entry sent",
  entrySentText: "The entry movement has been sent successfully.",

  exitSentTitle: "Exit sent",
  exitByPenSentText: "The exit by pen has been sent successfully.",
  exitByIdSentText: "The exit by ID has been sent successfully.",
},
movimientoAnimalGestacion: {
  smallLabel: "GESTATION",
  title: "Animal movement",
  subtitle: "Perform manual entries and exits using the keyboard.",

  movementType: "Movement type",
  entry: "Entry",
  exit: "Exit",

  searchAnimal: "Search animal",
  entryHelper: "Enter the destination pen and the animal ID.",
  exitHelper: "Enter the animal ID to perform the gestation exit.",

  pen: "Pen",
  animalId: "Animal ID",
  type: "Type",

  sending: "Sending...",
  accept: "Accept",
  cancel: "Cancel",

  confirmEntry: "Confirm entry",
  confirmExit: "Confirm exit",
  confirmSubtitle: "Review the data before sending the movement.",

  incompleteDataTitle: "Incomplete data",
  entryIncompleteText: "Enter the pen and the animal ID.",
  exitIdIncompleteText: "Enter the animal ID to perform the exit.",

  invalidPenTitle: "Invalid pen",
  invalidPenText: "The pen must be a valid number greater than 0.",

  sendErrorTitle: "Send error",
  noIpConfigured: "No IP address is configured.",
  serverConnectionError: "Could not connect to the server.",
  serverEmptyResponse: "The server did not return a message. HTTP code {{status}}.",

  entrySentTitle: "Entry sent",
  entrySentText: "The gestation entry movement has been sent successfully.",

  exitSentTitle: "Exit sent",
  exitByIdSentText: "The gestation exit by ID has been sent successfully.",
},

};