/* eslint-disable prettier/prettier */
export default {
   username: 'Username',
   password: 'Password',
   Server: 'Server IP',
   login: 'Login',
   welcome: 'Welcome',
   change_language: 'Change language',
   Tabs: 'Home',

   Lista_instalaciones: 'Installations',
   Maintenance: 'Maintenance',
   DetallesInstalacion: 'Installation details',
   Grabar: 'Record',
   EstadoStore: 'Store status',
   Nodata: 'No data',
   DosimacRegistration: 'Registration',
   NewDmMaternity: 'New Dosimac maternity',
   DosimacG: 'Dosimac-G',
   DosimacI: 'Dosimac-I',
   UpdDmMaternity: 'Update Dosimac maternity',
   NewDmGestation: 'New Dosimac gestation',
   UpdDmGestation: 'Update Dosimac gestation',
   StartScan: 'Search DOSIMAC devices',
   DosimacList: 'DOSIMAC devices',
   PressToScan: 'Press',
   DosimacSetup: 'Configuration',
   TestoPresioneAlta: 'Press the button to search devices',
   Instalación_seleccionada: 'Selected installation',
   NoInstalacionSeleccionada: 'No installation selected',
   BorrarGranja: 'Delete farm',
   Deseaborrarlagranja: 'Do you want to delete the farm?',
   Guardar: 'Save',
   Cancelar: 'Cancel',
   Aceptar: 'Accept',
   NombreGranja: 'Farm name',
   Localidad: 'Location',
   Provincia: 'Province',
   NombreWifi: 'Wifi SSID',
   PasswordWifi: 'Wifi password',
   No_hay_dispositivos: 'No devices',
   Aviso: 'Notice',
   SearchingDevices: 'Searching devices...',
   NoSePuedeBorrarGranja: 'You cannot delete a new farm',
   settings: 'Settings',
   softwareVersion: 'Software version',
   numeroCoral: 'Pen number',
   numeroMaquina: 'Machine number',
   Enviar: 'Send',
   Salir: 'Exit',
   Informacion: 'Information',


};