export default {
    username: 'Utente',
    password: 'Password',
    login: 'Accedi',
    welcome: 'Benvenuto',
    change_language: 'Cambia lingua',
    Tabs: 'Home',

    Lista_instalaciones: 'Installazioni',
    Maintenance: 'Manutenzione',
    DetallesInstalacion: 'Dettagli installazione',
    Grabar: 'Salva',
    EstadoStore: 'Stato store',
    Nodata: 'Nessun dato',
    DosimacRegistration: 'Registrazione',
    NewDmMaternity: 'Nuovo Dosimac maternità',
    DosimacG: 'Dosimac-G',
    DosimacI: 'Dosimac-I',
    UpdDmMaternity: 'Aggiorna Dosimac maternità',
    NewDmGestation: 'Nuovo Dosimac gestazione',
    UpdDmGestation: 'Aggiorna Dosimac gestazione',
    StartScan: 'Cerca dispositivi DOSIMAC',
    DosimacList: 'Dispositivi DOSIMAC',
    PressToScan: 'Premi',
    DosimacSetup: 'Configurazione',
    TestoPresioneAlta: 'Premi il pulsante per cercare i dispositivi',
    Instalación_seleccionada: 'Installazione selezionata',
    NoInstalacionSeleccionada: 'Nessuna installazione selezionata',
    BorrarGranja: 'Elimina fattoria',
    Deseaborrarlagranja: 'Vuoi eliminare la fattoria?',
    Guardar: 'Salva',
    Cancelar: 'Annulla',
    Aceptar: 'Accetta',
    NombreGranja: 'Nome della fattoria',
    Localidad: 'Località',
    Provincia: 'Provincia',
    NombreWifi: 'Wifi SSID',
    PasswordWifi: 'Password Wifi',
    No_hay_dispositivos: 'Nessun dispositivo',
    Aviso: 'Avviso',
    SearchingDevices: 'Ricerca dispositivi...',
    NoSePuedeBorrarGranja: 'Non è possibile eliminare una nuova fattoria',
    settings: 'Impostazioni',
    softwareVersion: 'Versione software',
    numeroCoral: 'Numero del recinto',
    numeroMaquina: 'Numero della macchina',
    Enviar: 'Invia',
    Salir: 'Esci',
    Informacion: 'Informazioni',
};