export default {
    username: 'Utente',
    password: 'Password',
    login: 'Accedi',
    welcome: 'Benvenuto',
    change_language: 'Cambia lingua',
    Tabs: 'Home',

    Lista_instalaciones: 'Installazioni',
    Maintenance: 'Manutenzione',
    DetallesInstalacion: 'Dettagli installazione',
    Grabar: 'Salva',
    EstadoStore: 'Stato store',
    Nodata: 'Nessun dato',
    DosimacRegistration: 'Registrazione',
    NewDmMaternity: 'Nuovo Dosimac maternità',
    DosimacG: 'Dosimac-G',
    DosimacI: 'Dosimac-I',
    UpdDmMaternity: 'Aggiorna Dosimac maternità',
    NewDmGestation: 'Nuovo Dosimac gestazione',
    UpdDmGestation: 'Aggiorna Dosimac gestazione',
    StartScan: 'Cerca dispositivi DOSIMAC',
    DosimacList: 'Dispositivi DOSIMAC',
    PressToScan: 'Premi',
    DosimacSetup: 'Configurazione',
    TestoPresioneAlta: 'Premi il pulsante per cercare i dispositivi',
    Instalación_seleccionada: 'Installazione selezionata',
    NoInstalacionSeleccionada: 'Nessuna installazione selezionata',
    BorrarGranja: 'Elimina fattoria',
    Deseaborrarlagranja: 'Vuoi eliminare la fattoria?',
    Guardar: 'Salva',
    Cancelar: 'Annulla',
    Aceptar: 'Accetta',
    NombreGranja: 'Nome della fattoria',
    Localidad: 'Località',
    Provincia: 'Provincia',
    NombreWifi: 'Wifi SSID',
    PasswordWifi: 'Password Wifi',
    No_hay_dispositivos: 'Nessun dispositivo',
    Aviso: 'Avviso',
    SearchingDevices: 'Ricerca dispositivi...',
    NoSePuedeBorrarGranja: 'Non è possibile eliminare una nuova fattoria',
    settings: 'Impostazioni',
    softwareVersion: 'Versione software',
    numeroCoral: 'Numero del recinto',
    numeroMaquina: 'Numero della macchina',
    Enviar: 'Invia',
    Salir: 'Esci',
    Informacion: 'Informazioni',
    InicioConfiguracion: "Avvio connessione",
    ConfiguracionWifi: "Configurazione in corso...",
    ConfiguracionRealizada: "*Configurazione completata*",
    ErrorConfiguracion: "*Errore di configurazione*",
    CapturaTagCorral: "Acquisisci tag del recinto",
    CorralTag: "Tag recinto",
    versionUint16: "Questa versione del dispositivo supporta il recinto solo fino a 65000",
    versionUint32: "Questa versione del dispositivo supporta il recinto fino a 4000000000",
    EnvioConfiguracion: "Invio della configurazione",
    NumeroCorral: "Numero del recinto",
    NumeroMaquina: "Numero della macchina",
    Corralnovalida: "Recinto non valido",
    NumeroMaquinanovalida: "Numero della macchina non valido",
    configuarIntalacion: "È necessario configurare l'installazione prima di utilizzare questa funzione",

    login_title: "Accedi",
    login_subtitle: "Inserisci i tuoi dati. È necessario configurare l'IP prima di accedere dal menu Configurazione IP.",
    login_username: "Utente",
    login_password: "Password",
    login_button: "Accedi",
    login_loading: "Accesso in corso...",
    login_footer: "Pannello di controllo",

    login_ipRequiredTitle: "Configurazione IP richiesta",
    login_ipRequiredMessage: "Non hai configurato l'indirizzo IP del server. Inseriscilo per poter accedere.",
    login_serverIpLabel: "IP del server",
    login_cancel: "Annulla",
    login_accept: "Accetta",
    login_invalidCredentials: "Nome utente o password errati",

    login_configTitle: "Configurazione",
    login_errorTitle: "Errore di accesso",
    login_genericErrorTitle: "Errore",
    login_networkErrorTitle: "Errore di rete",
    login_networkErrorMessage: "Impossibile connettersi al server.",
    login_noTokenMessage: "Il backend non ha restituito alcun token.",
    login_missingDataTitle: "Dati mancanti",
    login_missingDataMessage: "Inserisci nome utente e password.",
    login_invalidIpTitle: "IP non valido",
    login_invalidIpMessage: "Inserisci un IP o un indirizzo server valido.",
    login_saveIpErrorMessage: "Impossibile salvare la configurazione IP.",
    awrStartScan_title: "Configurazione AWR",
    awrStartScan_description: "Schermata per scansionare i lettori Agrident AWR.",
    awrStartScan_button: "Scansiona AWR",

    gestacionConfig_screenTitle: "Configurazione Gestazione",
    gestacionConfig_chooseOptionTitle: "Scegli un'opzione",
    gestacionConfig_chooseOptionDescription: "Definisci il flusso prima di iniziare con il lettore.",

    gestacionConfig_entry: "Entrata",
    gestacionConfig_exit: "Uscita",
    gestacionConfig_reading: "Lettura",
    gestacionConfig_search: "Ricerca",

    gestacionConfig_entryParamsTitle: "Parametri di entrata",
    gestacionConfig_exitParamsTitle: "Parametri di uscita",
    gestacionConfig_entryParamsDescription: "Seleziona il recinto e il comportamento del flusso.",
    gestacionConfig_exitParamsDescription: "Configura il comportamento del flusso di uscita.",

    gestacionConfig_corralLabel: "Recinto",
    gestacionConfig_corralPlaceholder: "Es: 1",
    gestacionConfig_corralRequired: "Inserisci il recinto per continuare.",

    gestacionConfig_detectUnknownTitle: "Identificare animali sconosciuti",
    gestacionConfig_detectUnknownDescription: "Quando leggerai un animale non identificato, potrai assegnargli un ID",

    gestacionConfig_confirmTitle: "Confermare invio",
    gestacionConfig_confirmDescription: "Chiederà conferma prima di inviare i registri.",

    gestacionConfig_animalSearchTitle: "Ricerca animale",
    gestacionConfig_animalSearchDescription: "Scegli se vuoi cercare per crotale o per ID.",
    gestacionConfig_searchByCrotal: "Per crotale",
    gestacionConfig_searchById: "Per ID",
    gestacionConfig_manual: "Manuale",
    gestacionConfig_withSword: "Con spada",

    gestacionConfig_crotalLabelSearch: "Crotale",
    gestacionConfig_idLabelSearch: "ID",
    gestacionConfig_crotalPlaceholderSearch: "Es: 982091072397436",
    gestacionConfig_idPlaceholderSearch: "Es: A13",
    gestacionConfig_crotalRequiredSearch: "Inserisci un crotale per continuare.",
    gestacionConfig_idRequiredSearch: "Inserisci un ID per continuare.",

    gestacionConfig_searchWithSwordHelp: "Continuando, la spada verrà letta in questa schermata e l'animale verrà cercato con quel crotale.",

    gestacionConfig_readingSword: "Lettura spada...",
    gestacionConfig_waitingMatch: "In attesa di corrispondenza",
    gestacionConfig_searchingAnimal: "Ricerca animale...",

    gestacionConfig_readingSwordDescription: "Avvicina il crotale al lettore per identificare l'animale.",
    gestacionConfig_waitingMatchDescription: "Animale individuato. Ora avvicina alla spada il crotale {{crotal}} per confermare la corrispondenza.",
    gestacionConfig_searchingAnimalDescription: "Consultazione delle informazioni dell'animale nel backend.",

    gestacionConfig_awrDisconnectedTitle: "AWR non connesso",
    gestacionConfig_awrSavedDescription: "Hai spade salvate. Premi per selezionarne una.",
    gestacionConfig_awrNotSavedDescription: "Non hai spade salvate. Premi per scansionarne una.",

    gestacionConfig_scan: "Scansiona",
    gestacionConfig_continue: "Continua",

    gestacionConfig_alerts_error: "Errore",
    gestacionConfig_alerts_networkError: "Errore di rete",
    gestacionConfig_alerts_networkErrorMessage: "Impossibile connettersi al server.",
    gestacionConfig_alerts_backendNoValidCrotal: "Il backend non ha restituito un crotale valido da confrontare.",
    gestacionConfig_alerts_awrNotConnected: "AWR non connesso",
    gestacionConfig_alerts_connectSwordBeforeContinue: "Collega una spada prima di continuare.",
    gestacionConfig_alerts_couldNotStartReading: "Non è stato possibile avviare la lettura con la spada.",

    gestacionConfig_alerts_missingData: "Dato mancante",
    gestacionConfig_alerts_writeCrotalToSearch: "Inserisci un crotale da cercare.",
    gestacionConfig_alerts_writeIdToSearch: "Inserisci un ID da cercare.",

    gestacionConfig_alerts_notFound: "Non trovato",
    gestacionConfig_alerts_animalNotFoundByCrotal: "Non esiste alcun animale con questo crotale.",
    gestacionConfig_alerts_animalNotFoundById: "Non esiste alcun animale con questo ID.",

    gestacionConfig_alerts_warning: "Avviso",
    gestacionConfig_alerts_searchError: "Errore di ricerca",

    maternidadConfig_screenTitle: "Configurazione Maternità",
    maternidadConfig_chooseOptionTitle: "Scegli un'opzione",
    maternidadConfig_chooseOptionDescription: "Definisci il flusso prima di iniziare con il lettore.",
    maternidadConfig_entry: "Entrata",
    maternidadConfig_exit: "Uscita",
    maternidadConfig_reading: "Lettura",
    maternidadConfig_search: "Ricerca",
    maternidadConfig_entryParamsTitle: "Parametri di entrata",
    maternidadConfig_exitParamsTitle: "Parametri di uscita",
    maternidadConfig_entryParamsDescription: "Seleziona il recinto e il comportamento del flusso.",
    maternidadConfig_exitParamsDescription: "Configura il comportamento del flusso di uscita.",
    maternidadConfig_corralLabel: "Recinto",
    maternidadConfig_corralPlaceholder: "Es: 1",
    maternidadConfig_corralRequired: "Inserisci il recinto per continuare.",
    maternidadConfig_detectUnknownTitle: "Identificare animali sconosciuti",
    maternidadConfig_detectUnknownDescription: "Quando leggi un animale non identificato, potrai assegnargli un ID",
    maternidadConfig_confirmTitle: "Conferma invio",
    maternidadConfig_confirmDescription: "Chiederà conferma prima di inviare ogni registrazione.",
    maternidadConfig_animalSearchTitle: "Ricerca animale",
    maternidadConfig_animalSearchDescription: "Scegli se vuoi cercare per crotale o per ID.",
    maternidadConfig_searchByCrotal: "Per crotale",
    maternidadConfig_searchById: "Per ID",
    maternidadConfig_manual: "Manuale",
    maternidadConfig_withSword: "Con lettore",
    maternidadConfig_crotalLabelSearch: "Crotale",
    maternidadConfig_idLabelSearch: "ID",
    maternidadConfig_crotalPlaceholderSearch: "Es: 982091072397436",
    maternidadConfig_idPlaceholderSearch: "Es: A13",
    maternidadConfig_crotalRequiredSearch: "Inserisci un crotale per continuare.",
    maternidadConfig_idRequiredSearch: "Inserisci un ID per continuare.",
    maternidadConfig_searchWithSwordHelp: "Premendo Scansiona, il lettore verrà usato in questa schermata e l'animale verrà cercato con quel crotale.",
    maternidadConfig_readingSword: "Lettura del lettore...",
    maternidadConfig_waitingMatch: "In attesa di corrispondenza",
    maternidadConfig_searchingAnimal: "Ricerca animale...",
    maternidadConfig_readingSwordDescription: "Avvicina il crotale al lettore per identificare l'animale.",
    maternidadConfig_waitingMatchDescription: "Animale trovato. Ora avvicina al lettore il crotale {{crotal}} per confermare la corrispondenza.",
    maternidadConfig_searchingAnimalDescription: "Consultazione delle informazioni dell'animale nel backend.",
    maternidadConfig_awrDisconnectedTitle: "AWR non connesso",
    maternidadConfig_awrSavedDescription: "Hai AWR salvati. Premi per selezionarne uno.",
    maternidadConfig_awrNotSavedDescription: "Non hai nessun AWR salvato. Premi per eseguirne la scansione.",
    maternidadConfig_scan: "Scansiona",
    maternidadConfig_continue: "Continua",
    maternidadConfig_alert_error: "Errore",
    maternidadConfig_alert_invalidBackendCrotal: "Il backend non ha restituito un crotale valido da confrontare.",
    maternidadConfig_alert_awrNotConnected: "AWR non connesso",
    maternidadConfig_alert_connectSwordBeforeContinue: "Collega un lettore prima di continuare.",
    maternidadConfig_alert_couldNotStartReading: "Non è stato possibile avviare la lettura con il lettore.",
    maternidadConfig_alert_missingData: "Dato mancante",
    maternidadConfig_alert_writeCrotalToSearch: "Inserisci un crotale da cercare.",
    maternidadConfig_alert_writeIdToSearch: "Inserisci un ID da cercare.",
    maternidadConfig_alert_notFound: "Non trovato",
    maternidadConfig_alert_noAnimalWithCrotal: "Non esiste alcun animale con quel crotale.",
    maternidadConfig_alert_noAnimalWithId: "Non esiste alcun animale con quell'ID.",
    maternidadConfig_alert_warning: "Avviso",
    maternidadConfig_alert_searchError: "Errore nella ricerca",
    maternidadConfig_alert_networkError: "Errore di rete",
    maternidadConfig_alert_networkErrorMessage: "Non è stato possibile connettersi al server.",

    gestationReader_screenTitle: "Lettore Gestazione",
    gestationReader_animalInfoTitle: "Informazioni dell'animale",
    gestationReader_animalInfoDescription: "Dati trovati nella ricerca.",
    gestationReader_animalCardTitle: "Scheda Animale",
    gestationReader_animalIdLabel: "ID",
    gestationReader_animalCrotalLabel: "Crotale",
    gestationReader_fieldCorral: "Recinto",
    gestationReader_fieldHouse: "Capannone",
    gestationReader_fieldState: "Stato",
    gestationReader_fieldBodyCondition: "Condizione corporea",
    gestationReader_fieldCycle: "Ciclo",
    gestationReader_fieldSystemEntryDate: "Ingresso nel sistema",
    gestationReader_newSearch: "Nuova ricerca",
    gestationReader_summaryTitle: "Riepilogo",
    gestationReader_summaryDescription: "Parametri scelti nella Configurazione",
    gestationReader_mode: "Modalità",
    gestationReader_corral: "Recinto",
    gestationReader_modeEntry: "Entrata",
    gestationReader_modeExit: "Uscita",
    gestationReader_modeReading: "Lettura",
    gestationReader_modeSearch: "Ricerca",
    gestationReader_detectUnknownTitle: "Identificare animali sconosciuti",
    gestationReader_detectUnknownDescription: "Quando appare un animale senza ID, offrire l'assegnazione di un ID.",
    gestationReader_confirmSendTitle: "Confermare invio",
    gestationReader_confirmSendDescription: "Chiederà conferma prima di inviare ogni record.",
    gestationReader_changeSettings: "Cambia configurazione",
    gestationReader_currentReadingTitle: "Lettura attuale",
    gestationReader_currentReadingDescription: "Il crotale rilevato e l'ID associato appariranno qui.",
    gestationReader_awrDisconnected: "AWR non connesso",
    gestationReader_readCrotal: "Crotale letto",
    gestationReader_readId: "ID",
    gestationReader_animalWithoutAssignedId: "Animale senza ID assegnato",
    gestationReader_unknownAnimal: "Animale sconosciuto",
    gestationReader_animalWithoutIdTitle: "Animale senza ID",
    gestationReader_animalWithoutIdDescription: "Inserisci un ID manuale per aggiornare il crotale letto.",
    gestationReader_newIdLabel: "Nuovo ID",
    gestationReader_newIdPlaceholder: "Es: A13",
    gestationReader_updateId: "Aggiorna ID",
    gestationReader_updatingId: "Aggiornamento...",
    gestationReader_sentRecordsTitle: "Record inviati",
    gestationReader_noRecords: "Nessun record.",
    gestationReader_tableHeaderCorral: "Recinto",
    gestationReader_tableHeaderId: "ID",
    gestationReader_tableHeaderCrotal: "Crotale",
    gestationReader_buttonAutoReading: "Lettura automatica attiva",
    gestationReader_buttonAutoSending: "Invio automatico attivo",
    gestationReader_buttonSending: "Invio...",
    gestationReader_buttonSend: "Invia",
    gestationReader_alertError: "Errore",
    gestationReader_alertWarning: "Avviso",
    gestationReader_alertNetworkError: "Errore di rete",
    gestationReader_alertMissingCrotalTitle: "Crotale mancante",
    gestationReader_alertMissingCrotalMessage: "Avvicina il crotale al lettore prima di inviare.",
    gestationReader_alertInvalidCrotalTitle: "Crotale non valido",
    gestationReader_alertInvalidCrotalMessage: "Il crotale deve essere numerico.",
    gestationReader_alertReadErrorTitle: "Errore di lettura",
    gestationReader_alertNetworkErrorMessage: "Impossibile connettersi al server.",
    gestationReader_alertMissingCorralTitle: "Recinto mancante",
    gestationReader_alertMissingCorralMessage: "Inserisci il recinto prima di inviare.",
    gestationReader_alertInvalidCorralTitle: "Recinto non valido",
    gestationReader_alertInvalidCorralMessage: "Il recinto deve essere un numero.",
    gestationReader_alertSendErrorTitle: "Errore durante l'invio",
    gestationReader_alertNoIpConfigured: "Nessun IP configurato.",
    gestationReader_alertMissingIdTitle: "ID mancante",
    gestationReader_alertMissingIdMessage: "Inserisci il nuovo ID prima di aggiornare.",
    gestationReader_alertMissingAssociatedCrotalTitle: "Crotale mancante",
    gestationReader_alertMissingAssociatedCrotalMessage: "Non c'è alcun crotale associato da aggiornare.",
    gestationReader_alertInvalidAssociatedCrotalTitle: "Crotale non valido",
    gestationReader_alertInvalidAssociatedCrotalMessage: "Il crotale associato non è valido.",
    gestationReader_alertUpdateIdErrorTitle: "Errore durante l'aggiornamento dell'ID",


    maternityReader_screenTitle: "Lettore Maternità",
    maternityReader_alertMissingCrotalTitle: "Crotale mancante",
    maternityReader_alertMissingCrotalMessage: "Avvicina il crotale al lettore prima di inviare.",
    maternityReader_alertInvalidCrotalTitle: "Crotale non valido",
    maternityReader_alertInvalidCrotalMessage: "Il crotale deve essere numerico.",
    maternityReader_alertReadErrorTitle: "Errore di lettura",
    maternityReader_alertNetworkError: "Errore di rete",
    maternityReader_alertNetworkErrorMessage: "Impossibile connettersi al server.",
    maternityReader_alertMissingCorralTitle: "Recinto mancante",
    maternityReader_alertMissingCorralMessage: "Inserisci il recinto prima di inviare.",
    maternityReader_alertInvalidCorralTitle: "Recinto non valido",
    maternityReader_alertInvalidCorralMessage: "Il recinto deve essere un numero (es.: 8).",
    maternityReader_alertError: "Errore",
    maternityReader_alertNoIpConfigured: "Nessun IP configurato.",
    maternityReader_alertWarning: "Avviso",
    maternityReader_alertSendErrorTitle: "Errore durante l'invio",
    maternityReader_alertMissingIdTitle: "ID mancante",
    maternityReader_alertMissingIdMessage: "Inserisci il nuovo ID prima di aggiornare.",
    maternityReader_alertMissingAssociatedCrotalTitle: "Crotale mancante",
    maternityReader_alertMissingAssociatedCrotalMessage: "Non c'è alcun crotale associato da aggiornare.",
    maternityReader_alertInvalidAssociatedCrotalTitle: "Crotale non valido",
    maternityReader_alertInvalidAssociatedCrotalMessage: "Il crotale associato non è valido.",
    maternityReader_alertUpdateIdErrorTitle: "Errore durante l'aggiornamento dell'ID",
    maternityReader_animalInfoTitle: "Informazioni sull'animale",
    maternityReader_animalInfoDescription: "Dati trovati nella ricerca.",
    maternityReader_animalCardTitle: "Scheda Animale",
    maternityReader_animalIdLabel: "ID",
    maternityReader_animalCrotalLabel: "Crotale",
    maternityReader_fieldCorral: "Recinto",
    maternityReader_fieldHouse: "Capannone",
    maternityReader_fieldState: "Stato",
    maternityReader_fieldBodyCondition: "Condizione corporea",
    maternityReader_fieldCycle: "Ciclo",
    maternityReader_fieldSystemEntryDate: "Ingresso nel sistema",
    maternityReader_newSearch: "Nuova ricerca",
    maternityReader_summaryTitle: "Riepilogo",
    maternityReader_summaryDescription: "Parametri selezionati nella configurazione",
    maternityReader_mode: "Modalità",
    maternityReader_modeEntry: "Ingresso",
    maternityReader_modeExit: "Uscita",
    maternityReader_modeReading: "Lettura",
    maternityReader_corral: "Recinto",
    maternityReader_detectUnknownTitle: "Identificare animali sconosciuti",
    maternityReader_detectUnknownDescription: "Quando compare un animale senza ID, consentire l'assegnazione di un ID.",
    maternityReader_confirmSendTitle: "Conferma invio",
    maternityReader_confirmSendDescription: "Chiederà conferma prima di inviare ogni record.",
    maternityReader_changeSettings: "Cambia configurazione",
    maternityReader_currentReadingTitle: "Lettura attuale",
    maternityReader_currentReadingDescription: "Il crotale rilevato apparirà qui.",
    maternityReader_awrDisconnected: "AWR non connesso",
    maternityReader_readCrotal: "Crotale letto",
    maternityReader_readId: "ID",
    maternityReader_animalWithoutAssignedId: "Animale senza ID assegnato",
    maternityReader_unknownAnimal: "Animale sconosciuto",
    maternityReader_animalWithoutIdTitle: "Animale senza ID",
    maternityReader_animalWithoutIdDescription: "Inserisci un ID manuale per aggiornare il crotale letto.",
    maternityReader_newIdLabel: "Nuovo ID",
    maternityReader_newIdPlaceholder: "Es.: A13",
    maternityReader_updatingId: "Aggiornamento...",
    maternityReader_updateId: "Aggiorna ID",
    maternityReader_sentRecordsTitle: "Record inviati",
    maternityReader_tableHeaderCorral: "Recinto",
    maternityReader_tableHeaderId: "ID",
    maternityReader_tableHeaderCrotal: "Crotale",
    maternityReader_noRecords: "Nessun record.",
    maternityReader_buttonAutoReading: "Lettura automatica attiva",
    maternityReader_buttonAutoSending: "Invio automatico attivo",
    maternityReader_buttonSending: "Invio in corso...",
    maternityReader_buttonSend: "Invia",

    awrScanResults_title: "AWR – Risultati scansione",
    awrScanResults_searching: "Ricerca di AWR…",
    awrScanResults_warningTitle: "Avviso",
    awrScanResults_noDevicesNearby: "Nessun AWR nelle vicinanze trovato.",
    awrScanResults_connecting: "Connessione in corso…",
    awrScanResults_connectErrorFallback: "Impossibile connettersi",
    awrScanResults_connectedTitle: "Connesso",
    awrScanResults_connectedMessage: "Connessione stabilita con {{device}}.",
    awrScanResults_genericDevice: "il dispositivo",
    awrBluetoothPermissionMessage: "Attiva il Bluetooth e accetta il permesso per poter eseguire la scansione.",


    awrSavedList_title: "AWR scansionati",
    awrSavedList_connecting: "Connessione in corso…",
    awrSavedList_empty: "Non ci sono AWR salvati. Scansionane uno da “Configurazione AWR”.",
    awrSavedList_connected: "Connesso",
    awrSavedList_disconnected: "Disconnesso",
    awrSavedList_renameAccessibility: "Rinomina",
    awrSavedList_deleteAccessibility: "Elimina",
    awrSavedList_renameTitle: "Rinomina AWR",
    awrSavedList_nameLabel: "Nome",
    awrSavedList_deleteTitle: "Elimina AWR salvato",
    awrSavedList_deleteMessage: "Sei sicuro di voler eliminare questo AWR dall'elenco?",
    awrSavedList_deleteAction: "Elimina",


    ipConfig_title: "Configurazione IP",
    ipConfig_cardTitle: "Server CTIFEED",
    ipConfig_cardDescription: "Inserisci l'IP del server in cui verrà aperto il portale.",
    ipConfig_inputLabel: "IP (solo IP)",
    ipConfig_saved: "Salvato",
    ipConfig_alertSuccessTitle: "Corretto",
    ipConfig_alertSuccessMessage: "IP corretto",
    ipConfig_alertWarningTitle: "Avviso",
    ipConfig_alertServerNotUpdated: "Server non aggiornato",
    ipConfig_alertErrorTitle: "Errore",
    ipConfig_alertInvalidIp: "IP non valido",

    portal_preparing: "Preparazione del portale...",
    portal_noSessionToken: "Nessun token di sessione disponibile. Accedi di nuovo.",
    portal_noIpConfigured: "Nessun IP configurato. Configura prima l’IP del server.",
    portal_prepareUrlError: "Non è stato possibile preparare l’URL del portale.",
    portal_loadError: "Non è stato possibile caricare il portale.",
    portal_checkingConnection: "Verifica della connessione al portale...",
    portal_noConnectionTitle: "Nessuna connessione",
    portal_connectionTimeout: "Non è stato possibile connettersi al portale. Verifica di essere connesso alla rete corretta.",
    portal_connectionError: "Non è stato possibile connettersi al portale. Verifica la rete o l’IP configurato.",
    portal_httpError: "Non è stato possibile aprire il portale. Errore HTTP {{status}}.",
    portal_retry: "Riprova",
    portal_loading: "Caricamento del portale...",

    AltaDispositivos: "Registrazione dispositivi",
    LectorMaternidad: "Lettore Maternità",
    LectorGestacion: "Lettore Gestazione",
    ConfiguracionIP: "Configurazione IP",
    ConfiguracionAWR: "Configurazione AWR",
    DarDeAltaAWR: "Registrare AWR",
    AWREscaneados: "AWR scansionati",
    CerrarSesion: "Disconnettersi",

    Config_lastReadMismatchTitle: "L'animale letto non corrisponde alla ricerca",
    Config_lastReadMismatchCrotal: "Marchio auricolare",
    Config_lastReadMismatchId: "ID",

    animalState: {
    gestation: "Gestazione",
    maternity: "Maternità",
    out_of_gestation: "Fuori gestazione",
    out_of_maternity: "Fuori maternità"
  },

  
Reader_readingTitle: "Lettura dei marchi auricolari",
Reader_labelId: "ID",
Reader_labelCrotal: "Marchio auricolare",
Reader_labelCorral: "Recinto",
Reader_labelHouse: "Capannone",
Reader_labelState: "Stato",
Reader_autoReadingBadge: "Lettura automatica",
gestacionConfig_flowSectionTitle: "Configurazione del flusso",
gestacionConfig_workModeTitle: "Modalità di lavoro",
gestacionConfig_workModeDescription: "Seleziona cosa farà il lettore.",
gestacionConfig_entryDescription: "Registra entrata",
gestacionConfig_exitDescription: "Registra uscita",
gestacionConfig_readingDescription: "Solo consultazione",
gestacionConfig_searchDescription: "Cerca animale",

gestacionConfig_sendSettingsTitle: "Impostazioni di invio",
gestacionConfig_sendSettingsDescription: "Configura il comportamento del flusso durante la lettura degli animali.",

gestacionConfig_corralSectionTitle: "Recinto di entrata",
gestacionConfig_corralSectionDescription: "Questo dato è obbligatorio per continuare con la registrazione.",

gestacionConfig_alerts_notice: "Avviso",
gestacionConfig_alerts_invalidCrotalFromBackend: "Il backend non ha restituito una marca auricolare valida da confrontare.",

common_accept: "Accetta",

maternidadConfig_flowSectionTitle: "Configurazione del flusso",
maternidadConfig_workModeTitle: "Modalità di lavoro",
maternidadConfig_workModeDescription: "Seleziona cosa farà il lettore.",
maternidadConfig_entryDescription: "Registra entrata",
maternidadConfig_exitDescription: "Registra uscita",
maternidadConfig_readingDescription: "Solo consultazione",
maternidadConfig_searchDescription: "Cerca animale",

maternidadConfig_sendSettingsTitle: "Impostazioni di invio",
maternidadConfig_sendSettingsDescription: "Configura il comportamento del flusso durante la lettura degli animali.",

maternidadConfig_corralSectionTitle: "Recinto di entrata",
maternidadConfig_corralSectionDescription: "Questo dato è obbligatorio per continuare con la registrazione.",

maternidadConfig_alert_invalidCrotalFromBackend: "Il backend non ha restituito una marca auricolare valida da confrontare.",
maternidadConfig_readOnlyTitle: "Permesso di sola lettura",
maternidadConfig_readOnlyModifySettings: "Questo utente dispone solo di permessi di lettura. Non può modificare questa configurazione.",
maternidadConfig_readOnlyUseFunction: "Questo utente dispone solo di permessi di lettura. Non può usare questa funzione.",
 ajustesEnvioMaternidad: {
    headerTitle: "Impostazioni di invio",
    headerSubtitle: "Configura il comportamento del flusso durante la lettura degli animali.",
    cardTitle: "Invio dei registri",
    cardSubtitle: "Queste impostazioni vengono applicate quando si continua con la lettura."
  },

  noAlimentadosMaternidad: {
  animalId: "ID ANIMALE",
  corral: "Recinto",
  consumption: "Consumo",
  withoutFeeding: "Non alimentato",
  day: "giorno",
  days: "giorni",
  loadingAnimals: "Caricamento animali...",
  title: "Animali non alimentati",
  totalAnimalsMaternity: "Totale animali in maternità:",
  notSeen: "Non visualizzati",
  all: "Tutti",
  sort: "Ordina",
  emptyTitle: "Nessun animale in sospeso",
  emptyText: "Non sono stati trovati animali non alimentati in maternità.",
  sortBy: "Ordina per",
  daysWithoutFeeding: "Giorni senza alimentazione",
  sortDaysHelp: "Ordina per giorni senza alimentazione",
  sortCorralHelp: "Ordina per numero di recinto",
  descending: "Decrescente",
  ascending: "Crescente",
  filterAnimals: "Filtra animali",
  allHelp: "Mostra tutti gli animali",
  unmarked: "Non contrassegnati",
  unmarkedHelp: "Nasconde gli animali già controllati",
  clearMarkedTitle: "Cancella animali contrassegnati",
  clearMarkedText: "Verranno rimossi tutti i contrassegni degli animali controllati.",
  cancel: "Annulla",
  clear: "Cancella",
  error: "Errore",
  serverConnectionError: "Impossibile connettersi al server."
},

noAlimentadosGestacion: {
  animalId: "ID ANIMALE",
  corral: "Recinto",
  consumption: "Consumo",
  withoutFeeding: "Non alimentato",
  day: "giorno",
  days: "giorni",
  loadingAnimals: "Caricamento animali...",
  title: "Animali non alimentati",
  totalAnimalsGestation: "Totale animali in gestazione:",
  notSeen: "Non visualizzati",
  all: "Tutti",
  sort: "Ordina",
  emptyTitle: "Nessun animale in sospeso",
  emptyText: "Non sono stati trovati animali non alimentati in gestazione.",
  sortBy: "Ordina per",
  daysWithoutFeeding: "Giorni senza alimentazione",
  sortDaysHelp: "Ordina per giorni senza alimentazione",
  sortCorralHelp: "Ordina per numero di recinto",
  descending: "Decrescente",
  ascending: "Crescente",
  filterAnimals: "Filtra animali",
  allHelp: "Mostra tutti gli animali",
  unmarked: "Non contrassegnati",
  unmarkedHelp: "Nasconde gli animali già controllati",
  clearMarkedTitle: "Cancella animali contrassegnati",
  clearMarkedText: "Verranno rimossi tutti i contrassegni degli animali controllati.",
  cancel: "Annulla",
  clear: "Cancella",
  error: "Errore",
  serverConnectionError: "Impossibile connettersi al server."
},
capturaAnimalHome: {
  selectOption: "Seleziona un'opzione",
  unfedAnimalsTitle: "Animali non alimentati",
  unfedAnimalsDescription: "Consulta gli animali che non hanno ricevuto l'alimentazione prevista.",
  twoFeedsTitle: "2 mangimi",
  twoFeedsDescription: "Gestisci il cambio di alimentazione nelle bocche di caduta.",
  animalStatusTitle: "Stato animale",
animalStatusDescription: "Consultare o aggiornare lo stato dell'animale.",
birthCaptureTitle: "Registrazione parto",
birthCaptureDescription: "Registra i nati vivi, morti e mummificati.",
},
cambioPiensoMaternidad: {
  error: "Errore",
  loadTasksError: "Impossibile caricare le attività di cambio mangime.",
  loadingTasks: "Caricamento attività...",
  title: "Cambio mangime",
  pendingTask: "{{count}} attività in sospeso",
  pendingTasks: "{{count}} attività in sospeso",
  emptyTitle: "Nessuna attività in sospeso",
  emptyText: "Non sono state trovate attività di cambio mangime.",
  animalId: "ID ANIMALE",
  corral: "Recinto",
  setTo: "Imposta a",
  destination: "Destinazione"
},

estadoAnimal: {
  queryLabel: "Consulta",
  title: "Stato animale",
  subtitle: "Seleziona come vuoi identificare l'animale.",
  corral: "Recinto",
  corralDescription: "Inserisci il numero del recinto.",
  id: "ID",
  idDescription: "Inserisci l'identificativo dell'animale.",
  animalId: "ID animale",
  requiredData: "Dato obbligatorio",
  enterCorral: "Inserisci il numero del recinto.",
  enterId: "Inserisci l'identificativo dell'animale.",
  consulting: "Consultazione...",
  continue: "Continua",
  accept: "Accetta",
  serverConnectionError: "Impossibile connettersi al server.",
  noIpConfigured: "Nessun IP configurato.",
  nextScreenPending: "Creeremo la schermata delle informazioni dell'animale nel prossimo passaggio."
},
matCorralDetail: {
 readOnlyPermission: "Permesso di sola lettura",
readOnlyPermissionText: "Questo utente dispone solo dei permessi di lettura. Non può eseguire operazioni sull'animale.",
  animalStatus: "Stato animale",
  id: "ID",
  earTag: "Marca auricolare",
  cycle: "Ciclo",
  day: "Giorno",

  curve: "Curva",
  correction: "Correzione",
  entryDate: "Data ingresso",
  farrowingDate: "Data parto",
  house: "Capannone",
  pen: "Box",
  lastFeeding: "Ultima alimentazione",
  presentPiglets: "Suinetti presenti",
  inseminationDate: "Data inseminazione",
  teatsNumber: "Nº capezzoli",

  operations: "Operazioni",

  consumption: "Consumo",
  ofGrams: "di {{amount}} g",
  oneDayWithoutFeeding: "1 giorno senza alimentazione",
  daysWithoutFeeding: "{{count}} giorni senza alimentazione",

  noAnimalData: "Nessun dato dell'animale",
  noAnimalDataText: "Non sono state ricevute informazioni da mostrare.",
  back: "Indietro",
  operationsPendingTitle: "Operazioni",
  operationsPendingText: "Eseguiremo le operazioni nel passaggio successivo.",
  moveToWeaning: "Passare allo svezzamento",
  chooseOption: "Seleziona un'operazione per questo animale.",
  nextOperation: "Operazione successiva",
  insertAnimal: "Inserire animale",
  moveToLactation: "Passare alla lattazione",
  nextStep: "Passaggio successivo",
  actions: "Azioni",

  bodyCondition: "Condizione corporea",
  subState: "Sottostato",
  pigletCapture: "Registrazione suinetti",
  animalExit: "Uscita animale",
  replaceEarTag: "Sostituire marca auricolare",
  changePen: "Cambiare box",
  anonymousAnimalId: "Identificativo animale anonimo",

  cancel: "Annulla",
  accept: "Accetta",
  saving: "Salvataggio...",
  error: "Errore",

  operationDone: "Operazione completata correttamente.",
  changeStateDone: "Sottostato aggiornato correttamente.",
  changeStateError: "Impossibile cambiare lo stato dell'animale.",
  confirmNextOperation: "Sei sicuro di voler passare all'operazione successiva?",
  pkidChangeStateNotFound: "Identificativo interno dell'animale non trovato.",

  selectExitType: "Seleziona il tipo di uscita da applicare.",
  exitImmediate: "Uscita immediata",
  exitScheduled: "Uscita programmata",
  exitScheduledEmptyHopper: "Uscita programmata con tramoggia vuota",
  cancelScheduledExit: "Annulla uscita programmata",
  scheduledDate: "Data programmata",
  exitDateLimitText: "Non è possibile selezionare una data precedente a oggi né successiva a 3 giorni.",
  animalExitDone: "Uscita dell'animale completata correttamente.",
  animalExitError: "Impossibile completare l'uscita dell'animale.",
  pkidExitNotFound: "Identificativo interno dell'animale non trovato.",

  selectCurve: "Seleziona curva",
  selectCurveText: "Seleziona la nuova curva dell'animale.",
  loadingCurves: "Caricamento curve...",
  noCurvesAvailable: "Nessuna curva disponibile.",
  confirmChangeCurve: "Sei sicuro di voler cambiare la curva?",
  loadCurvesError: "Impossibile caricare le curve.",
  pkidChangeCurveNotFound: "Identificativo interno dell'animale non trovato.",
  changeCurveDone: "Curva aggiornata correttamente.",
  changeCurveError: "Impossibile cambiare la curva.",

  selectBodyConditionText: "Seleziona la nuova condizione corporea dell'animale.",
  loadingBodyConditions: "Caricamento condizioni corporee...",
  noBodyConditionsAvailable: "Nessuna condizione corporea disponibile.",
  confirmChangeBodyCondition: "Sei sicuro di voler cambiare la condizione corporea?",
  loadBodyConditionsError: "Impossibile caricare le condizioni corporee.",
  pkidChangeBodyConditionNotFound: "Identificativo interno dell'animale non trovato.",
  changeBodyConditionDone: "Condizione corporea aggiornata correttamente.",
  changeBodyConditionError: "Impossibile cambiare la condizione corporea.",

  selectSubStateText: "Seleziona manualmente il nuovo sottostato dell'animale.",
  confirmChangeSubState: "Sei sicuro di voler cambiare il sottostato?",

  currentPen: "Box attuale: {{pen}}",
  newPen: "Nuovo box",
  enterNewPen: "Inserisci il nuovo box.",
  pkidChangePenNotFound: "Identificativo interno dell'animale non trovato.",
  changePenDone: "Box aggiornato correttamente.",
  changePenError: "Impossibile cambiare il box.",

  currentEarTag: "Marca auricolare attuale: {{earTag}}",
  newEarTag: "Nuova marca auricolare",
  enterNewEarTag: "Inserisci la nuova marca auricolare.",
  pkidEarTagNotFound: "Identificativo interno dell'animale non trovato.",
  replaceEarTagDone: "Marca auricolare aggiornata correttamente.",
  replaceEarTagError: "Impossibile sostituire la marca auricolare.",

  identifyAnonymousAnimalText: "Scegli se assegnare un ID o una marca auricolare all'animale.",
  newId: "Nuovo ID",
  enterNewId: "Inserisci il nuovo ID.",
  idExample: "Es: 1010",
  earTagExample: "Es: 123",
  notAnonymousAnimalText: "Questo animale non è anonimo perché ha già un ID o una marca auricolare assegnata.",
  pkidIdentifyNotFound: "Identificativo interno dell'animale non trovato.",
  identifyAnonymousAnimalDone: "Identificativo dell'animale aggiornato correttamente.",
  identifyAnonymousAnimalError: "Impossibile identificare l'animale anonimo.",

  livePiglets: "Vivi",
  deadPiglets: "Morti",
  mummifiedPiglets: "Mummificati",
  totalBornPiglets: "Nati totali",
  pigletCaptureText: "Inserisci i suinetti vivi, morti e mummificati.",
  captureBeforeLactationText: "Registra i nati prima di passare alla lattazione.",
  weaningPigletsOnlyRead: "Durante lo svezzamento è possibile solo consultare i suinetti.",
  pkidPigletsNotFound: "Identificativo interno dell'animale non trovato.",
  pigletCaptureDone: "Registrazione dei suinetti salvata correttamente.",
  pigletCaptureError: "Impossibile salvare la registrazione dei suinetti.",
},
subState: {
  prepartum: "Preparto",
  lactation: "Lattazione",
  weaning: "Svezzamento",
},

capturaParto: {
  birthDataTitle: "Dati del parto",
  birthDataSubtitle: "Controlla i dati dell'animale prima di registrare il parto.",
  corral: "Box",
  id: "ID",
  date: "Data",
  subState: "Sottostato",

  dataCollectionTitle: "Raccolta dati",
  dataCollectionSubtitle: "Inserisci i nati vivi, morti e mummificati.",
  weaningReadOnly: "Durante lo svezzamento i dati possono solo essere consultati.",

  totalBorn: "Nati totali",
  live: "Vivi",
  dead: "Morti",
  mummified: "Mummificati",

  prepartum: "Preparto",
  farrowing: "Parto",
  lactation: "Lattazione",
  weaning: "Svezzamento",

  accept: "Accetta",
  cancel: "Annulla",
  saving: "Salvataggio...",

  sentTitle: "Registrazione inviata",
  sentMessage: "La registrazione del parto è stata salvata correttamente.",

  errorTitle: "Errore",
  invalidAnimalTitle: "Animale non valido",
  invalidAnimalText: "Identificativo interno dell'animale non trovato.",
  reportSendError: "Impossibile salvare la registrazione del parto.",

  invalidDateTitle: "Data non valida",
  invalidDateMessage: "La data del parto non può essere successiva a oggi.",
  changeDate: "Cambiare data",

  selectDateTitle: "Seleziona data",
  selectDateMessage: "Regola la data del parto con i pulsanti.",
},

capturaMaternidadEntrada: {
  title: "Registrazione parto",
  description: "Cerca l'animale per box o per ID per registrare il parto.",
  maternityLabel: "MATERNITÀ",

  corral: "Box",
  corralDescription: "Cerca l'animale tramite il numero del box.",
  id: "ID",
  idDescription: "Cerca l'animale tramite il suo identificativo.",
  animalId: "ID animale",

  corralExample: "Es: 102",
  idExample: "Es: 1234",

  consulting: "Ricerca...",
  continue: "Continua",
  accept: "Accetta",

  serverConnectionError: "Impossibile connettersi al server.",
},

altaBajaStack: {
  tituloPantalla: "Entrata/Uscita suinetti",
  descripcionPantalla: "Cerca la madre per box o ID per registrare entrate o uscite di suinetti.",
},
altaBajaLechones: {
  heroTitle: "Movimento suinetti",
  statusAlta: "Entrata",
  statusBaja: "Uscita",

  corralUpper: "BOX",
  idUpper: "ID",
  dateUpper: "DATA",

  movementType: "Tipo di movimento",
  movementSubtitle: "Seleziona se vuoi registrare un'entrata o un'uscita.",
  adoption: "Adozione",
  baja: "Uscita",

  adoptionData: "Dati di adozione",
  donorMother: "Madre donatrice",
  donatesPiglets: "Dona suinetti",
  id: "ID",
  transferredPiglets: "Suinetti trasferiti",
  totalAdopted: "Totale adottati",
  total: "Totale",

  bajaReason: "Motivo di uscita",
  reasonCrushing: "Schiacciamento",
  reasonDiarrhea: "Diarrea",
  reasonLowViability: "Bassa vitalità",
  reasonDeformities: "Deformità",
  reasonOther: "Altro",

  piglet: "suinetto",
  piglets: "suinetti",
  description: "Descrizione",

  editReason: "Modifica motivo",
  addReason: "Aggiungi motivo",
  reasonModalText: "Indica la quantità di suinetti e descrivi il motivo.",

  saving: "Salvataggio...",
  saveAlta: "Salva entrata",
  saveBaja: "Salva uscita",
  accept: "Accetta",
  cancel: "Annulla",

  error: "Errore",
  missingData: "Dati mancanti",
  saveError: "Errore durante il salvataggio",
  saveErrorText: "Impossibile salvare l'operazione.",
  selectedAnimalPkidNotFound: "Identificativo interno dell'animale selezionato non trovato.",

  enterTransferredPiglets: "Inserisci il numero di suinetti trasferiti.",
  invalidTotalTitle: "Totale non valido",
  invalidPigletsNumber: "Inserisci un numero valido di suinetti.",

  missingDescriptionTitle: "Descrizione obbligatoria",
  missingDescriptionText: "Inserisci la descrizione del motivo.",
  invalidQuantityTitle: "Quantità non valida",
  invalidPigletQuantity: "Inserisci una quantità valida di suinetti.",

  selectReasonRequired: "Seleziona almeno un motivo di uscita.",

  adoptionSavedTitle: "Entrata salvata",
  adoptionSavedMessage: "{{count}} suinetti sono stati registrati correttamente.",

  bajasSavedTitle: "Uscite salvate",
  bajasSavedMessage: "{{piglets}} uscite sono state registrate correttamente per {{reasons}} motivo/i.",
},
avisoAplicacionNoConfigurada: {
  title: "Applicazione non configurata",
  text: "Configura l'indirizzo IP del server",
  link: "Tocca qui",
},
generalHome: {
  movementAnimalTitle: "Movimento animale",
  readerDescription: "Lettore di marche auricolari.",
  keyboardDescription: "Tastiera",

  ctifeedTitle: "CTIFEED",
  ctifeedDescription: "Accedi al portale principale.",

  modalApplicationNotConfiguredTitle: "Applicazione non configurata",
  modalNoSessionTitle: "Sessione non avviata",
  modalInstallationUnavailableTitle: "Installazione non disponibile",
  modalPreparingSessionTitle: "Preparazione sessione",
  modalReadOnlyPermissionTitle: "Permesso di sola lettura",

  modalApplicationNotConfiguredText: "Non è configurata alcuna installazione. Vai su Installazioni e selezionane una.",
  modalNoSessionText: "L'installazione ha un IP, ma non è stata avviata alcuna sessione. Controlla Username e Password in Installazioni.",
  modalInstallationUnavailableText: "Impossibile connettersi all'installazione selezionata. Verifica di essere connesso alla rete WiFi corretta o controlla l'IP del server.",
  modalPreparingSessionText: "La sessione è ancora in caricamento. Riprova tra qualche secondo.",
  modalReadOnlyPermissionText: "Il tuo utente non dispone dei permessi di amministratore per accedere a questa funzionalità.",

  accept: "Accetta",

  connectingTitle: "Connessione...",
  connectingText: "Verifica della connessione con l'installazione selezionata.",
},
movimientoAnimalMaternidad: {
  smallLabel: "MOVIMENTO",
  title: "Maternità",
  subtitle: "Esegui entrate e uscite manuali tramite tastiera.",

  movementType: "Tipo di movimento",
  entry: "Entrata",
  exit: "Uscita",

  searchAnimal: "Cerca animale",
  entryHelper: "Inserisci il box di destinazione e l'ID dell'animale.",
  exitHelper: "Seleziona se vuoi effettuare l'uscita per box o per ID.",

  pen: "Box",
  animalId: "ID animale",
  type: "Tipo",

  sending: "Invio...",
  accept: "Accetta",
  cancel: "Annulla",

  confirmEntry: "Conferma entrata",
  confirmExit: "Conferma uscita",
  confirmSubtitle: "Controlla i dati prima di inviare il movimento.",

  incompleteDataTitle: "Dati incompleti",
  entryIncompleteText: "Inserisci il box e l'ID dell'animale.",
  exitPenIncompleteText: "Inserisci il box per effettuare l'uscita.",
  exitIdIncompleteText: "Inserisci l'ID dell'animale per effettuare l'uscita.",

  invalidPenTitle: "Box non valido",
  invalidPenText: "Il box deve essere un numero valido maggiore di 0.",

  sendErrorTitle: "Errore durante l'invio",
  connectionErrorTitle: "Errore di connessione",
  noIpConfigured: "Non è configurato alcun IP.",
  serverConnectionError: "Impossibile connettersi al server.",
  serverEmptyResponse: "Il server non ha restituito alcun messaggio. Codice HTTP {{status}}.",

  entrySentTitle: "Entrata inviata",
  entrySentText: "Il movimento di entrata è stato inviato correttamente.",

  exitSentTitle: "Uscita inviata",
  exitByPenSentText: "L'uscita per box è stata inviata correttamente.",
  exitByIdSentText: "L'uscita per ID è stata inviata correttamente.",
},
movimientoAnimalGestacion: {
  smallLabel: "GESTAZIONE",
  title: "Movimento animale",
  subtitle: "Esegui entrate e uscite manuali tramite tastiera.",

  movementType: "Tipo di movimento",
  entry: "Entrata",
  exit: "Uscita",

  searchAnimal: "Cerca animale",
  entryHelper: "Inserisci il box di destinazione e l'ID dell'animale.",
  exitHelper: "Inserisci l'ID dell'animale per effettuare l'uscita dalla gestazione.",

  pen: "Box",
  animalId: "ID animale",
  type: "Tipo",

  sending: "Invio...",
  accept: "Accetta",
  cancel: "Annulla",

  confirmEntry: "Conferma entrata",
  confirmExit: "Conferma uscita",
  confirmSubtitle: "Controlla i dati prima di inviare il movimento.",

  incompleteDataTitle: "Dati incompleti",
  entryIncompleteText: "Inserisci il box e l'ID dell'animale.",
  exitIdIncompleteText: "Inserisci l'ID dell'animale per effettuare l'uscita.",

  invalidPenTitle: "Box non valido",
  invalidPenText: "Il box deve essere un numero valido maggiore di 0.",

  sendErrorTitle: "Errore durante l'invio",
  noIpConfigured: "Non è configurato alcun IP.",
  serverConnectionError: "Impossibile connettersi al server.",
  serverEmptyResponse: "Il server non ha restituito alcun messaggio. Codice HTTP {{status}}.",

  entrySentTitle: "Entrata inviata",
  entrySentText: "Il movimento di entrata in gestazione è stato inviato correttamente.",

  exitSentTitle: "Uscita inviata",
  exitByIdSentText: "L'uscita dalla gestazione per ID è stata inviata correttamente.",
},
};