export default {
    username: 'Użytkownik',
    password: 'Hasło',
    login: 'Zaloguj się',
    welcome: 'Witamy',
    change_language: 'Zmień język',
    Tabs: 'Strona główna',

    Lista_instalaciones: 'Instalacje',
    Maintenance: 'Konserwacja',
    DetallesInstalacion: 'Szczegóły instalacji',
    Grabar: 'Zapisz',
    EstadoStore: 'Stan store',
    Nodata: 'Brak danych',
    DosimacRegistration: 'Rejestracja',
    NewDmMaternity: 'Nowy Dosimac macierzyństwo',
    DosimacG: 'Dosimac-G',
    DosimacI: 'Dosimac-I',
    UpdDmMaternity: 'Zmiana Dosimac macierzyństwo',
    NewDmGestation: 'Nowy Dosimac ciąża',
    UpdDmGestation: 'Zmiana Dosimac ciąża',
    StartScan: 'Szukaj urządzeń DOSIMAC',
    DosimacList: 'Urządzenia DOSIMAC',
    PressToScan: 'Naciśnij',
    DosimacSetup: 'Konfiguracja',
    TestoPresioneAlta: 'Naciśnij przycisk, aby wyszukać urządzenia',
    Instalación_seleccionada: 'Wybrana instalacja',
    NoInstalacionSeleccionada: 'Brak wybranej instalacji',
    BorrarGranja: 'Usuń farmę',
    Deseaborrarlagranja: 'Czy chcesz usunąć farmę?',
    Guardar: 'Zapisz',
    Cancelar: 'Anuluj',
    Aceptar: 'Akceptuj',
    NombreGranja: 'Nazwa farmy',
    Localidad: 'Miejscowość',
    Provincia: 'Województwo',
    NombreWifi: 'Wifi SSID',
    PasswordWifi: 'Hasło Wifi',
    No_hay_dispositivos: 'Brak urządzeń',
    Aviso: 'Uwaga',
    SearchingDevices: 'Wyszukiwanie urządzeń...',
    NoSePuedeBorrarGranja: 'Nie można usunąć nowej farmy',
    settings: 'Ustawienia',
    softwareVersion: 'Wersja oprogramowania',
    numeroCoral: 'Numer kojca',
    numeroMaquina: 'Numer maszyny',
    Enviar: 'Wyślij',
    Salir: 'Wyjdź',
    Informacion: 'Informacje',

};