export default {
  username: 'Użytkownik',
  password: 'Hasło',
  login: 'Zaloguj się',
  welcome: 'Witamy',
  change_language: 'Zmień język',
  Tabs: 'Strona główna',

  Lista_instalaciones: 'Instalacje',
  Maintenance: 'Konserwacja',
  DetallesInstalacion: 'Szczegóły instalacji',
  Grabar: 'Zapisz',
  EstadoStore: 'Stan store',
  Nodata: 'Brak danych',
  DosimacRegistration: 'Rejestracja',
  NewDmMaternity: 'Nowy Dosimac macierzyństwo',
  DosimacG: 'Dosimac-G',
  DosimacI: 'Dosimac-I',
  UpdDmMaternity: 'Zmiana Dosimac macierzyństwo',
  NewDmGestation: 'Nowy Dosimac ciąża',
  UpdDmGestation: 'Zmiana Dosimac ciąża',
  StartScan: 'Szukaj urządzeń DOSIMAC',
  DosimacList: 'Urządzenia DOSIMAC',
  PressToScan: 'Naciśnij',
  DosimacSetup: 'Konfiguracja',
  TestoPresioneAlta: 'Naciśnij przycisk, aby wyszukać urządzenia',
  Instalación_seleccionada: 'Wybrana instalacja',
  NoInstalacionSeleccionada: 'Brak wybranej instalacji',
  BorrarGranja: 'Usuń farmę',
  Deseaborrarlagranja: 'Czy chcesz usunąć farmę?',
  Guardar: 'Zapisz',
  Cancelar: 'Anuluj',
  Aceptar: 'Akceptuj',
  NombreGranja: 'Nazwa farmy',
  Localidad: 'Miejscowość',
  Provincia: 'Województwo',
  NombreWifi: 'Wifi SSID',
  PasswordWifi: 'Hasło Wifi',
  No_hay_dispositivos: 'Brak urządzeń',
  Aviso: 'Uwaga',
  SearchingDevices: 'Wyszukiwanie urządzeń...',
  NoSePuedeBorrarGranja: 'Nie można usunąć nowej farmy',
  settings: 'Ustawienia',
  softwareVersion: 'Wersja oprogramowania',
  numeroCoral: 'Numer kojca',
  numeroMaquina: 'Numer maszyny',
  Enviar: 'Wyślij',
  Salir: 'Wyjdź',
  Informacion: 'Informacje',
  InicioConfiguracion: "Rozpoczynanie łączenia",
  ConfiguracionWifi: "Konfigurowanie...",
  ConfiguracionRealizada: "*Konfiguracja zakończona*",
  ErrorConfiguracion: "*Błąd konfiguracji*",
  CapturaTagCorral: "Przechwyć tag kojca",
  CorralTag: "Tag kojca",
  versionUint16: "Ta wersja urządzenia obsługuje numery kojców tylko do 65000",
  versionUint32: "Ta wersja urządzenia obsługuje numery kojców do 4000000000",
  EnvioConfiguracion: "Wysyłanie konfiguracji",
  NumeroCorral: "Numer kojca",
  NumeroMaquina: "Numer maszyny",
  Corralnovalida: "Nieprawidłowy numer kojca",
  NumeroMaquinanovalida: "Nieprawidłowy numer maszyny",
  configuarIntalacion: "Należy skonfigurować instalację przed użyciem tej funkcji",

  login_title: "Zaloguj się",
  login_subtitle: "Wprowadź swoje dane. Przed zalogowaniem konieczne jest skonfigurowanie adresu IP w menu Konfiguracja IP.",
  login_username: "Użytkownik",
  login_password: "Hasło",
  login_button: "Zaloguj się",
  login_loading: "Logowanie...",
  login_footer: "Panel sterowania",

  login_ipRequiredTitle: "Wymagana konfiguracja IP",
  login_ipRequiredMessage: "Nie skonfigurowano adresu IP serwera. Wprowadź go, aby móc się zalogować.",
  login_serverIpLabel: "IP serwera",
  login_cancel: "Anuluj",
  login_accept: "Akceptuj",
  login_invalidCredentials: "Nieprawidłowa nazwa użytkownika lub hasło",

  login_configTitle: "Konfiguracja",
  login_errorTitle: "Błąd logowania",
  login_genericErrorTitle: "Błąd",
  login_networkErrorTitle: "Błąd sieci",
  login_networkErrorMessage: "Nie udało się połączyć z serwerem.",
  login_noTokenMessage: "Backend nie zwrócił żadnego tokena.",
  login_missingDataTitle: "Brak danych",
  login_missingDataMessage: "Wprowadź nazwę użytkownika i hasło.",
  login_invalidIpTitle: "Nieprawidłowy IP",
  login_invalidIpMessage: "Wprowadź prawidłowy adres IP lub adres serwera.",
  login_saveIpErrorMessage: "Nie udało się zapisać konfiguracji IP.",
  awrStartScan_title: "Ustawienia AWR",
  awrStartScan_description: "Ekran do skanowania czytników Agrident AWR.",
  awrStartScan_button: "Skanuj AWR",

  gestacionConfig_screenTitle: "Konfiguracja ciąży",
  gestacionConfig_chooseOptionTitle: "Wybierz opcję",
  gestacionConfig_chooseOptionDescription: "Zdefiniuj przepływ przed rozpoczęciem pracy z czytnikiem.",

  gestacionConfig_entry: "Wejście",
  gestacionConfig_exit: "Wyjście",
  gestacionConfig_reading: "Odczyt",
  gestacionConfig_search: "Wyszukiwanie",

  gestacionConfig_entryParamsTitle: "Parametry wejścia",
  gestacionConfig_exitParamsTitle: "Parametry wyjścia",
  gestacionConfig_entryParamsDescription: "Wybierz zagrodę i zachowanie przepływu.",
  gestacionConfig_exitParamsDescription: "Skonfiguruj zachowanie przepływu wyjścia.",

  gestacionConfig_corralLabel: "Zagroda",
  gestacionConfig_corralPlaceholder: "Np.: 1",
  gestacionConfig_corralRequired: "Wpisz zagrodę, aby kontynuować.",

  gestacionConfig_detectUnknownTitle: "Identyfikacja nieznanych zwierząt",
  gestacionConfig_detectUnknownDescription: "Gdy odczytasz niezidentyfikowane zwierzę, będziesz mógł przypisać mu ID",

  gestacionConfig_confirmTitle: "Potwierdź wysyłkę",
  gestacionConfig_confirmDescription: "Przed wysłaniem rekordów zostanie wymagane potwierdzenie.",

  gestacionConfig_animalSearchTitle: "Wyszukiwanie zwierzęcia",
  gestacionConfig_animalSearchDescription: "Wybierz, czy chcesz wyszukiwać po kolczyku czy po ID.",
  gestacionConfig_searchByCrotal: "Po kolczyku",
  gestacionConfig_searchById: "Po ID",
  gestacionConfig_manual: "Ręcznie",
  gestacionConfig_withSword: "Z czytnikiem",

  gestacionConfig_crotalLabelSearch: "Kolczyk",
  gestacionConfig_idLabelSearch: "ID",
  gestacionConfig_crotalPlaceholderSearch: "Np.: 982091072397436",
  gestacionConfig_idPlaceholderSearch: "Np.: A13",
  gestacionConfig_crotalRequiredSearch: "Wpisz kolczyk, aby kontynuować.",
  gestacionConfig_idRequiredSearch: "Wpisz ID, aby kontynuować.",

  gestacionConfig_searchWithSwordHelp: "Po kontynuacji czytnik odczyta na tym ekranie i wyszuka zwierzę po tym kolczyku.",

  gestacionConfig_readingSword: "Odczytywanie czytnika...",
  gestacionConfig_waitingMatch: "Oczekiwanie na zgodność",
  gestacionConfig_searchingAnimal: "Wyszukiwanie zwierzęcia...",

  gestacionConfig_readingSwordDescription: "Zbliż kolczyk do czytnika, aby zidentyfikować zwierzę.",
  gestacionConfig_waitingMatchDescription: "Zwierzę znalezione. Teraz zbliż do czytnika kolczyk {{crotal}}, aby potwierdzić zgodność.",
  gestacionConfig_searchingAnimalDescription: "Sprawdzanie informacji o zwierzęciu w backendzie.",

  gestacionConfig_awrDisconnectedTitle: "AWR niepołączony",
  gestacionConfig_awrSavedDescription: "Masz zapisane czytniki. Naciśnij, aby wybrać jeden.",
  gestacionConfig_awrNotSavedDescription: "Nie masz zapisanych czytników. Naciśnij, aby zeskanować jeden.",

  gestacionConfig_scan: "Skanuj",
  gestacionConfig_continue: "Kontynuuj",

  gestacionConfig_alerts_error: "Błąd",
  gestacionConfig_alerts_networkError: "Błąd sieci",
  gestacionConfig_alerts_networkErrorMessage: "Nie udało się połączyć z serwerem.",
  gestacionConfig_alerts_backendNoValidCrotal: "Backend nie zwrócił prawidłowego kolczyka do porównania.",
  gestacionConfig_alerts_awrNotConnected: "AWR niepołączony",
  gestacionConfig_alerts_connectSwordBeforeContinue: "Podłącz czytnik przed kontynuacją.",
  gestacionConfig_alerts_couldNotStartReading: "Nie udało się rozpocząć odczytu czytnikiem.",

  gestacionConfig_alerts_missingData: "Brak danych",
  gestacionConfig_alerts_writeCrotalToSearch: "Wpisz kolczyk do wyszukania.",
  gestacionConfig_alerts_writeIdToSearch: "Wpisz ID do wyszukania.",

  gestacionConfig_alerts_notFound: "Nie znaleziono",
  gestacionConfig_alerts_animalNotFoundByCrotal: "Nie istnieje zwierzę z takim kolczykiem.",
  gestacionConfig_alerts_animalNotFoundById: "Nie istnieje zwierzę z takim ID.",

  gestacionConfig_alerts_warning: "Ostrzeżenie",
  gestacionConfig_alerts_searchError: "Błąd wyszukiwania",

  maternidadConfig_screenTitle: "Konfiguracja porodówki",
  maternidadConfig_chooseOptionTitle: "Wybierz opcję",
  maternidadConfig_chooseOptionDescription: "Zdefiniuj przepływ przed rozpoczęciem pracy z czytnikiem.",
  maternidadConfig_entry: "Wejście",
  maternidadConfig_exit: "Wyjście",
  maternidadConfig_reading: "Odczyt",
  maternidadConfig_search: "Wyszukiwanie",
  maternidadConfig_entryParamsTitle: "Parametry wejścia",
  maternidadConfig_exitParamsTitle: "Parametry wyjścia",
  maternidadConfig_entryParamsDescription: "Wybierz kojec i sposób działania przepływu.",
  maternidadConfig_exitParamsDescription: "Skonfiguruj sposób działania przepływu wyjścia.",
  maternidadConfig_corralLabel: "Kojec",
  maternidadConfig_corralPlaceholder: "Np.: 1",
  maternidadConfig_corralRequired: "Wpisz kojec, aby kontynuować.",
  maternidadConfig_detectUnknownTitle: "Identyfikuj nieznane zwierzęta",
  maternidadConfig_detectUnknownDescription: "Gdy odczytasz niezidentyfikowane zwierzę, będziesz mógł przypisać mu ID",
  maternidadConfig_confirmTitle: "Potwierdź wysyłanie",
  maternidadConfig_confirmDescription: "Przed wysłaniem każdego rekordu zostanie wyświetlone potwierdzenie.",
  maternidadConfig_animalSearchTitle: "Wyszukiwanie zwierzęcia",
  maternidadConfig_animalSearchDescription: "Wybierz, czy chcesz wyszukiwać po crotal czy po ID.",
  maternidadConfig_searchByCrotal: "Po crotal",
  maternidadConfig_searchById: "Po ID",
  maternidadConfig_manual: "Ręcznie",
  maternidadConfig_withSword: "Ze skanerem",
  maternidadConfig_crotalLabelSearch: "Crotal",
  maternidadConfig_idLabelSearch: "ID",
  maternidadConfig_crotalPlaceholderSearch: "Np.: 982091072397436",
  maternidadConfig_idPlaceholderSearch: "Np.: A13",
  maternidadConfig_crotalRequiredSearch: "Wpisz crotal, aby kontynuować.",
  maternidadConfig_idRequiredSearch: "Wpisz ID, aby kontynuować.",
  maternidadConfig_searchWithSwordHelp: "Po naciśnięciu Skanuj skaner zostanie użyty na tym ekranie, a zwierzę zostanie wyszukane po tym crotal.",
  maternidadConfig_readingSword: "Odczytywanie skanera...",
  maternidadConfig_waitingMatch: "Oczekiwanie na dopasowanie",
  maternidadConfig_searchingAnimal: "Wyszukiwanie zwierzęcia...",
  maternidadConfig_readingSwordDescription: "Zbliż crotal do czytnika, aby zidentyfikować zwierzę.",
  maternidadConfig_waitingMatchDescription: "Zwierzę zostało znalezione. Teraz zbliż crotal {{crotal}} do skanera, aby potwierdzić dopasowanie.",
  maternidadConfig_searchingAnimalDescription: "Pobieranie informacji o zwierzęciu z backendu.",
  maternidadConfig_awrDisconnectedTitle: "AWR niepołączone",
  maternidadConfig_awrSavedDescription: "Masz zapisane urządzenia AWR. Naciśnij, aby wybrać jedno.",
  maternidadConfig_awrNotSavedDescription: "Nie masz zapisanych urządzeń AWR. Naciśnij, aby zeskanować jedno.",
  maternidadConfig_scan: "Skanuj",
  maternidadConfig_continue: "Kontynuuj",
  maternidadConfig_alert_error: "Błąd",
  maternidadConfig_alert_invalidBackendCrotal: "Backend nie zwrócił prawidłowego crotal do porównania.",
  maternidadConfig_alert_awrNotConnected: "AWR niepołączone",
  maternidadConfig_alert_connectSwordBeforeContinue: "Podłącz skaner przed kontynuowaniem.",
  maternidadConfig_alert_couldNotStartReading: "Nie udało się rozpocząć odczytu skanerem.",
  maternidadConfig_alert_missingData: "Brak danych",
  maternidadConfig_alert_writeCrotalToSearch: "Wpisz crotal do wyszukania.",
  maternidadConfig_alert_writeIdToSearch: "Wpisz ID do wyszukania.",
  maternidadConfig_alert_notFound: "Nie znaleziono",
  maternidadConfig_alert_noAnimalWithCrotal: "Nie istnieje żadne zwierzę z takim crotal.",
  maternidadConfig_alert_noAnimalWithId: "Nie istnieje żadne zwierzę z takim ID.",
  maternidadConfig_alert_warning: "Uwaga",
  maternidadConfig_alert_searchError: "Błąd wyszukiwania",
  maternidadConfig_alert_networkError: "Błąd sieci",
  maternidadConfig_alert_networkErrorMessage: "Nie udało się połączyć z serwerem.",

  gestationReader_screenTitle: "Czytnik ciąży",
  gestationReader_animalInfoTitle: "Informacje o zwierzęciu",
  gestationReader_animalInfoDescription: "Dane znalezione podczas wyszukiwania.",
  gestationReader_animalCardTitle: "Karta zwierzęcia",
  gestationReader_animalIdLabel: "ID",
  gestationReader_animalCrotalLabel: "Kolczyk",
  gestationReader_fieldCorral: "Kojec",
  gestationReader_fieldHouse: "Budynek",
  gestationReader_fieldState: "Stan",
  gestationReader_fieldBodyCondition: "Kondycja ciała",
  gestationReader_fieldCycle: "Cykl",
  gestationReader_fieldSystemEntryDate: "Data wejścia do systemu",
  gestationReader_newSearch: "Nowe wyszukiwanie",
  gestationReader_summaryTitle: "Podsumowanie",
  gestationReader_summaryDescription: "Parametry wybrane w konfiguracji",
  gestationReader_mode: "Tryb",
  gestationReader_corral: "Kojec",
  gestationReader_modeEntry: "Wejście",
  gestationReader_modeExit: "Wyjście",
  gestationReader_modeReading: "Odczyt",
  gestationReader_modeSearch: "Wyszukiwanie",
  gestationReader_detectUnknownTitle: "Identyfikuj nieznane zwierzęta",
  gestationReader_detectUnknownDescription: "Gdy pojawi się zwierzę bez ID, zaproponuj przypisanie ID.",
  gestationReader_confirmSendTitle: "Potwierdź wysyłkę",
  gestationReader_confirmSendDescription: "Przed wysłaniem każdego rekordu poprosi o potwierdzenie.",
  gestationReader_changeSettings: "Zmień konfigurację",
  gestationReader_currentReadingTitle: "Aktualny odczyt",
  gestationReader_currentReadingDescription: "Tutaj pojawi się wykryty kolczyk i powiązane ID.",
  gestationReader_awrDisconnected: "AWR niepołączone",
  gestationReader_readCrotal: "Odczytany kolczyk",
  gestationReader_readId: "ID",
  gestationReader_animalWithoutAssignedId: "Zwierzę bez przypisanego ID",
  gestationReader_unknownAnimal: "Nieznane zwierzę",
  gestationReader_animalWithoutIdTitle: "Zwierzę bez ID",
  gestationReader_animalWithoutIdDescription: "Wpisz ręcznie ID, aby zaktualizować odczytany kolczyk.",
  gestationReader_newIdLabel: "Nowe ID",
  gestationReader_newIdPlaceholder: "Np.: A13",
  gestationReader_updateId: "Zaktualizuj ID",
  gestationReader_updatingId: "Aktualizowanie...",
  gestationReader_sentRecordsTitle: "Wysłane rekordy",
  gestationReader_noRecords: "Brak rekordów.",
  gestationReader_tableHeaderCorral: "Kojec",
  gestationReader_tableHeaderId: "ID",
  gestationReader_tableHeaderCrotal: "Kolczyk",
  gestationReader_buttonAutoReading: "Automatyczny odczyt aktywny",
  gestationReader_buttonAutoSending: "Automatyczne wysyłanie aktywne",
  gestationReader_buttonSending: "Wysyłanie...",
  gestationReader_buttonSend: "Wyślij",
  gestationReader_alertError: "Błąd",
  gestationReader_alertWarning: "Uwaga",
  gestationReader_alertNetworkError: "Błąd sieci",
  gestationReader_alertMissingCrotalTitle: "Brak kolczyka",
  gestationReader_alertMissingCrotalMessage: "Przed wysłaniem zbliż kolczyk do czytnika.",
  gestationReader_alertInvalidCrotalTitle: "Nieprawidłowy kolczyk",
  gestationReader_alertInvalidCrotalMessage: "Kolczyk musi być numeryczny.",
  gestationReader_alertReadErrorTitle: "Błąd odczytu",
  gestationReader_alertNetworkErrorMessage: "Nie udało się połączyć z serwerem.",
  gestationReader_alertMissingCorralTitle: "Brak kojca",
  gestationReader_alertMissingCorralMessage: "Wpisz kojec przed wysłaniem.",
  gestationReader_alertInvalidCorralTitle: "Nieprawidłowy kojec",
  gestationReader_alertInvalidCorralMessage: "Kojec musi być liczbą.",
  gestationReader_alertSendErrorTitle: "Błąd podczas wysyłania",
  gestationReader_alertNoIpConfigured: "Brak skonfigurowanego IP.",
  gestationReader_alertMissingIdTitle: "Brak ID",
  gestationReader_alertMissingIdMessage: "Wpisz nowe ID przed aktualizacją.",
  gestationReader_alertMissingAssociatedCrotalTitle: "Brak kolczyka",
  gestationReader_alertMissingAssociatedCrotalMessage: "Brak powiązanego kolczyka do aktualizacji.",
  gestationReader_alertInvalidAssociatedCrotalTitle: "Nieprawidłowy kolczyk",
  gestationReader_alertInvalidAssociatedCrotalMessage: "Powiązany kolczyk jest nieprawidłowy.",
  gestationReader_alertUpdateIdErrorTitle: "Błąd podczas aktualizacji ID",
  gestationReader_readerMode: "Czytnik",
gestationReader_keyboardMode: "Klawiatura",

gestationReader_keyboardEntryTitle: "Wejście z klawiatury",
gestationReader_keyboardExitTitle: "Wyjście z klawiatury",
gestationReader_keyboardDescription: "Wprowadź dane ręcznie za pomocą klawiatury telefonu.",
gestationReader_keyboardId: "ID",
gestationReader_keyboardCrotal: "Kolczyk",
gestationReader_keyboardIdLabel: "ID zwierzęcia",
gestationReader_keyboardCrotalLabel: "Kolczyk",
gestationReader_keyboardIdPlaceholder: "Wpisz ID",
gestationReader_keyboardCrotalPlaceholder: "Wpisz kolczyk",
gestationReader_keyboardAdd: "Dodaj",
gestationReader_keyboardAdding: "Dodawanie...",

gestationReader_pendingRecordsTitle: "Rekordy niewysłane",
gestationReader_buttonSendingBatch: "Wysyłanie partii...",
gestationReader_buttonSendBatch: "Wyślij partię",
gestationReader_buttonSendBatchCount: "Wyślij partię ({{count}})",

gestationReader_noPendingRecordsTitle: "Brak rekordów",
gestationReader_noPendingRecordsText: "Brak rekordów oczekujących na wysłanie.",
gestationReader_batchSentTitle: "Partia wysłana",
gestationReader_batchSentText: "Wysłano poprawnie {{count}} rekord(y).",
gestationReader_batchWithErrorsTitle: "Partia z błędami",

gestationReader_recordSentTitle: "Rekord wysłany",
gestationReader_recordSentText: "Ruch został wysłany poprawnie.",

gestationReader_invalidAnimalId: "ID zwierzęcia jest nieprawidłowe.",
gestationReader_invalidPenRecord: "Kojec rekordu jest nieprawidłowy.",
gestationReader_invalidCrotalRecord: "Kolczyk rekordu jest nieprawidłowy.",
gestationReader_duplicateIdPending: "ID {{id}} znajduje się już w tabeli rekordów niewysłanych.",
gestationReader_duplicateCrotalPending: "Kolczyk {{crotal}} znajduje się już w tabeli rekordów niewysłanych.",
gestationReader_keyboardMissingId: "Wpisz ID zwierzęcia.",
gestationReader_keyboardMissingCrotal: "Wpisz kolczyk zwierzęcia.",
gestationReader_keyboardMissingPen: "Wybierz prawidłowy kojec przed dodaniem zwierzęcia.",
gestationReader_noAnimalById: "Nie istnieje zwierzę z ID {{id}}.",
gestationReader_noAnimalByCrotal: "Nie istnieje zwierzę z kolczykiem {{crotal}}.",
gestationReader_addAnimalError: "Nie można dodać zwierzęcia.",

gestationReader_pendingAnimalHint: "Odczytane zwierzęta pojawią się tutaj.",

gestationReader_changePenTitle: "Zmień kojec",
gestationReader_changePenDescription: "Wprowadź nowy kojec wejściowy.",
gestationReader_newPenLabel: "Nowy kojec",
gestationReader_newPenPlaceholder: "Np.: 1",
gestationReader_cancel: "Anuluj",
gestationReader_save: "Zapisz",
gestationReader_accept: "Akceptuj",
gestationReader_sentHistoryTitle: "Historia wysłanych",

  maternityReader_screenTitle: "Czytnik porodówki",
  maternityReader_alertMissingCrotalTitle: "Brak kolczyka",
  maternityReader_alertMissingCrotalMessage: "Przyłóż kolczyk do czytnika przed wysłaniem.",
  maternityReader_alertInvalidCrotalTitle: "Nieprawidłowy kolczyk",
  maternityReader_alertInvalidCrotalMessage: "Kolczyk musi być numeryczny.",
  maternityReader_alertReadErrorTitle: "Błąd odczytu",
  maternityReader_alertNetworkError: "Błąd sieci",
  maternityReader_alertNetworkErrorMessage: "Nie udało się połączyć z serwerem.",
  maternityReader_alertMissingCorralTitle: "Brak kojca",
  maternityReader_alertMissingCorralMessage: "Wpisz kojec przed wysłaniem.",
  maternityReader_alertInvalidCorralTitle: "Nieprawidłowy kojec",
  maternityReader_alertInvalidCorralMessage: "Kojec musi być liczbą (np. 8).",
  maternityReader_alertError: "Błąd",
  maternityReader_alertNoIpConfigured: "Nie skonfigurowano adresu IP.",
  maternityReader_alertWarning: "Uwaga",
  maternityReader_alertSendErrorTitle: "Błąd wysyłania",
  maternityReader_alertMissingIdTitle: "Brak ID",
  maternityReader_alertMissingIdMessage: "Wpisz nowe ID przed aktualizacją.",
  maternityReader_alertMissingAssociatedCrotalTitle: "Brak kolczyka",
  maternityReader_alertMissingAssociatedCrotalMessage: "Brak powiązanego kolczyka do aktualizacji.",
  maternityReader_alertInvalidAssociatedCrotalTitle: "Nieprawidłowy kolczyk",
  maternityReader_alertInvalidAssociatedCrotalMessage: "Powiązany kolczyk jest nieprawidłowy.",
  maternityReader_alertUpdateIdErrorTitle: "Błąd aktualizacji ID",
  maternityReader_animalInfoTitle: "Informacje o zwierzęciu",
  maternityReader_animalInfoDescription: "Dane znalezione w wyszukiwaniu.",
  maternityReader_animalCardTitle: "Karta zwierzęcia",
  maternityReader_animalIdLabel: "ID",
  maternityReader_animalCrotalLabel: "Kolczyk",
  maternityReader_fieldCorral: "Kojec",
  maternityReader_fieldHouse: "Budynek",
  maternityReader_fieldState: "Stan",
  maternityReader_fieldBodyCondition: "Kondycja ciała",
  maternityReader_fieldCycle: "Cykl",
  maternityReader_fieldSystemEntryDate: "Wejście do systemu",
  maternityReader_newSearch: "Nowe wyszukiwanie",
  maternityReader_summaryTitle: "Podsumowanie",
  maternityReader_summaryDescription: "Parametry wybrane w ustawieniach",
  maternityReader_mode: "Tryb",
  maternityReader_modeEntry: "Wejście",
  maternityReader_modeExit: "Wyjście",
  maternityReader_modeReading: "Odczyt",
  maternityReader_corral: "Kojec",
  maternityReader_detectUnknownTitle: "Identyfikuj nieznane zwierzęta",
  maternityReader_detectUnknownDescription: "Gdy pojawi się zwierzę bez ID, można przypisać mu ID.",
  maternityReader_confirmSendTitle: "Potwierdź wysyłanie",
  maternityReader_confirmSendDescription: "Przed wysłaniem każdego rekordu poprosi o potwierdzenie.",
  maternityReader_changeSettings: "Zmień ustawienia",
  maternityReader_currentReadingTitle: "Bieżący odczyt",
  maternityReader_currentReadingDescription: "Wykryty kolczyk pojawi się tutaj.",
  maternityReader_awrDisconnected: "AWR niepołączone",
  maternityReader_readCrotal: "Odczytany kolczyk",
  maternityReader_readId: "ID",
  maternityReader_animalWithoutAssignedId: "Zwierzę bez przypisanego ID",
  maternityReader_unknownAnimal: "Nieznane zwierzę",
  maternityReader_animalWithoutIdTitle: "Zwierzę bez ID",
  maternityReader_animalWithoutIdDescription: "Wpisz ręcznie ID, aby zaktualizować odczytany kolczyk.",
  maternityReader_newIdLabel: "Nowe ID",
  maternityReader_newIdPlaceholder: "Np.: A13",
  maternityReader_updatingId: "Aktualizowanie...",
  maternityReader_updateId: "Aktualizuj ID",
  maternityReader_sentRecordsTitle: "Wysłane rekordy",
  maternityReader_tableHeaderCorral: "Kojec",
  maternityReader_tableHeaderId: "ID",
  maternityReader_tableHeaderCrotal: "Kolczyk",
  maternityReader_noRecords: "Brak rekordów.",
  maternityReader_buttonAutoReading: "Automatyczny odczyt aktywny",
  maternityReader_buttonAutoSending: "Automatyczne wysyłanie aktywne",
  maternityReader_buttonSending: "Wysyłanie...",
  maternityReader_buttonSend: "Wyślij",

  awrScanResults_title: "AWR – Wyniki skanowania",
  awrScanResults_searching: "Wyszukiwanie AWR…",
  awrScanResults_warningTitle: "Ostrzeżenie",
  awrScanResults_noDevicesNearby: "Nie znaleziono pobliskich urządzeń AWR.",
  awrScanResults_connecting: "Łączenie…",
  awrScanResults_connectErrorFallback: "Nie udało się połączyć",
  awrScanResults_connectedTitle: "Połączono",
  awrScanResults_connectedMessage: "Połączenie nawiązano z {{device}}.",
  awrScanResults_genericDevice: "urządzeniem",

  awrSavedList_title: "Zeskanowane AWR",
  awrSavedList_connecting: "Łączenie…",
  awrSavedList_empty: "Brak zapisanych AWR. Zeskanuj jeden w sekcji „Configuración AWR”.",
  awrSavedList_connected: "Połączono",
  awrSavedList_disconnected: "Rozłączono",
  awrSavedList_renameAccessibility: "Zmień nazwę",
  awrSavedList_deleteAccessibility: "Usuń",
  awrSavedList_renameTitle: "Zmień nazwę AWR",
  awrSavedList_nameLabel: "Nazwa",
  awrSavedList_deleteTitle: "Usuń zapisany AWR",
  awrSavedList_deleteMessage: "Czy na pewno chcesz usunąć ten AWR z listy?",
  awrSavedList_deleteAction: "Usuń",

  ipConfig_title: "Konfiguracja IP",
  ipConfig_cardTitle: "Serwer CTIFEED",
  ipConfig_cardDescription: "Wprowadź adres IP serwera, na którym zostanie otwarty portal.",
  ipConfig_inputLabel: "IP (tylko IP)",
  ipConfig_saved: "Zapisano",
  ipConfig_alertSuccessTitle: "Poprawnie",
  ipConfig_alertSuccessMessage: "Poprawny adres IP",
  ipConfig_alertWarningTitle: "Ostrzeżenie",
  ipConfig_alertServerNotUpdated: "Serwer nie jest zaktualizowany",
  ipConfig_alertErrorTitle: "Błąd",
  ipConfig_alertInvalidIp: "Nieprawidłowy adres IP",

  portal_preparing: "Przygotowywanie portalu...",
  portal_noSessionToken: "Brak tokenu sesji. Zaloguj się ponownie.",
  portal_noIpConfigured: "Nie skonfigurowano adresu IP. Najpierw skonfiguruj adres IP serwera.",
  portal_prepareUrlError: "Nie udało się przygotować adresu URL portalu.",
  portal_loadError: "Nie udało się załadować portalu.",
  portal_checkingConnection: "Sprawdzanie połączenia z portalem...",
  portal_noConnectionTitle: "Brak połączenia",
  portal_connectionTimeout: "Nie udało się połączyć z portalem. Sprawdź, czy jesteś połączony z właściwą siecią.",
  portal_connectionError: "Nie udało się połączyć z portalem. Sprawdź sieć lub skonfigurowany adres IP.",
  portal_httpError: "Nie udało się otworzyć portalu. Błąd HTTP {{status}}.",
  portal_retry: "Spróbuj ponownie",
  portal_loading: "Ładowanie portalu...",


  AltaDispositivos: "Rejestracja urządzeń",
  LectorMaternidad: "Czytnik porodówki",
  LectorGestacion: "Czytnik ciąży",
  ConfiguracionIP: "Konfiguracja IP",
  ConfiguracionAWR: "Konfiguracja AWR",
  DarDeAltaAWR: "Zarejestruj AWR",
  AWREscaneados: "Zeskanowane AWR",
  CerrarSesion: "Wyloguj się",

  Config_lastReadMismatchTitle: "Odczytane zwierzę nie pasuje do wyszukiwania",
  Config_lastReadMismatchCrotal: "Kolczyk",
  Config_lastReadMismatchId: "ID",
  awrBluetoothPermissionMessage: "Włącz Bluetooth i zaakceptuj uprawnienie, aby móc skanować.", 

  animalState: {
    gestation: "Ciąża",
    maternity: "Macierzyństwo",
    out_of_gestation: "Poza ciążą",
    out_of_maternity: "Poza macierzyństwem"
  },

  
Reader_readingTitle: "Odczyt kolczyków",
Reader_labelId: "ID",
Reader_labelCrotal: "Kolczyk",
Reader_labelCorral: "Zagroda",
Reader_labelHouse: "Budynek",
Reader_labelState: "Stan",
Reader_autoReadingBadge: "Odczyt automatyczny", 

gestacionConfig_flowSectionTitle: "Konfiguracja przepływu",
gestacionConfig_workModeTitle: "Tryb pracy",
gestacionConfig_workModeDescription: "Wybierz, co ma zrobić czytnik.",
gestacionConfig_entryDescription: "Zarejestruj wejście",
gestacionConfig_exitDescription: "Zarejestruj wyjście",
gestacionConfig_readingDescription: "Tylko odczyt",
gestacionConfig_searchDescription: "Szukaj zwierzęcia",

gestacionConfig_sendSettingsTitle: "Ustawienia wysyłania",
gestacionConfig_sendSettingsDescription: "Skonfiguruj zachowanie przepływu podczas odczytu zwierząt.",

gestacionConfig_corralSectionTitle: "Kojec wejściowy",
gestacionConfig_corralSectionDescription: "To pole jest wymagane, aby kontynuować rejestrację.",

gestacionConfig_alerts_notice: "Powiadomienie",
gestacionConfig_alerts_invalidCrotalFromBackend: "Backend nie zwrócił prawidłowego kolczyka do porównania.",

common_accept: "Akceptuj",

maternidadConfig_flowSectionTitle: "Konfiguracja przepływu",
maternidadConfig_workModeTitle: "Tryb pracy",
maternidadConfig_workModeDescription: "Wybierz, co ma zrobić czytnik.",
maternidadConfig_entryDescription: "Zarejestruj wejście",
maternidadConfig_exitDescription: "Zarejestruj wyjście",
maternidadConfig_readingDescription: "Tylko odczyt",
maternidadConfig_searchDescription: "Szukaj zwierzęcia",

maternidadConfig_sendSettingsTitle: "Ustawienia wysyłania",
maternidadConfig_sendSettingsDescription: "Skonfiguruj zachowanie przepływu podczas odczytu zwierząt.",

maternidadConfig_corralSectionTitle: "Kojec wejściowy",
maternidadConfig_corralSectionDescription: "To pole jest wymagane, aby kontynuować rejestrację.",

maternidadConfig_alert_invalidCrotalFromBackend: "Backend nie zwrócił prawidłowego kolczyka do porównania.",


  maternidadConfig_readOnlyTitle: "Uprawnienia tylko do odczytu",
maternidadConfig_readOnlyModifySettings: "Ten użytkownik ma tylko uprawnienia do odczytu. Nie może modyfikować tej konfiguracji.",
maternidadConfig_readOnlyUseFunction: "Ten użytkownik ma tylko uprawnienia do odczytu. Nie może używać tej funkcji.",

  ajustesEnvioMaternidad: {
    headerTitle: "Ustawienia wysyłania",
    headerSubtitle: "Skonfiguruj zachowanie procesu podczas odczytu zwierząt.",
    cardTitle: "Wysyłanie rekordów",
    cardSubtitle: "Te ustawienia są stosowane podczas kontynuowania odczytu."
  },

  noAlimentadosMaternidad: {
  animalId: "ID ZWIERZĘCIA",
  corral: "Kojec",
  consumption: "Spożycie",
  withoutFeeding: "Bez karmienia",
  day: "dzień",
  days: "dni",
  loadingAnimals: "Wczytywanie zwierząt...",
  title: "Zwierzęta niekarmione",
  totalAnimalsMaternity: "Łączna liczba zwierząt na porodówce:",
  notSeen: "Niewidziane",
  all: "Wszystkie",
  sort: "Sortuj",
  emptyTitle: "Brak oczekujących zwierząt",
  emptyText: "Nie znaleziono niekarmionych zwierząt na porodówce.",
  sortBy: "Sortuj według",
  daysWithoutFeeding: "Dni bez karmienia",
  sortDaysHelp: "Sortuje według liczby dni bez karmienia",
  sortCorralHelp: "Sortuje według numeru kojca",
  descending: "Malejąco",
  ascending: "Rosnąco",
  filterAnimals: "Filtruj zwierzęta",
  allHelp: "Pokazuje wszystkie zwierzęta",
  unmarked: "Nieoznaczone",
  unmarkedHelp: "Ukrywa już sprawdzone zwierzęta",
  clearMarkedTitle: "Wyczyść oznaczone zwierzęta",
  clearMarkedText: "Wszystkie oznaczenia sprawdzonych zwierząt zostaną usunięte.",
  cancel: "Anuluj",
  clear: "Wyczyść",
  error: "Błąd",
  serverConnectionError: "Nie udało się połączyć z serwerem."
},

noAlimentadosGestacion: {
  animalId: "ID ZWIERZĘCIA",
  corral: "Kojec",
  consumption: "Spożycie",
  withoutFeeding: "Bez karmienia",
  day: "dzień",
  days: "dni",
  loadingAnimals: "Wczytywanie zwierząt...",
  title: "Zwierzęta niekarmione",
  totalAnimalsGestation: "Łączna liczba zwierząt w sektorze ciąży:",
  notSeen: "Niewidziane",
  all: "Wszystkie",
  sort: "Sortuj",
  emptyTitle: "Brak oczekujących zwierząt",
  emptyText: "Nie znaleziono niekarmionych zwierząt w sektorze ciąży.",
  sortBy: "Sortuj według",
  daysWithoutFeeding: "Dni bez karmienia",
  sortDaysHelp: "Sortuje według liczby dni bez karmienia",
  sortCorralHelp: "Sortuje według numeru kojca",
  descending: "Malejąco",
  ascending: "Rosnąco",
  filterAnimals: "Filtruj zwierzęta",
  allHelp: "Pokazuje wszystkie zwierzęta",
  unmarked: "Nieoznaczone",
  unmarkedHelp: "Ukrywa już sprawdzone zwierzęta",
  clearMarkedTitle: "Wyczyść oznaczone zwierzęta",
  clearMarkedText: "Wszystkie oznaczenia sprawdzonych zwierząt zostaną usunięte.",
  cancel: "Anuluj",
  clear: "Wyczyść",
  error: "Błąd",
  serverConnectionError: "Nie udało się połączyć z serwerem."
},
capturaAnimalHome: {
  selectOption: "Wybierz opcję",
  unfedAnimalsTitle: "Zwierzęta niekarmione",
  unfedAnimalsDescription: "Sprawdź zwierzęta, które nie otrzymały zaplanowanego karmienia.",
  twoFeedsTitle: "2 pasze",
  twoFeedsDescription: "Zarządzaj zmianą paszy w wylotach zrzutowych.",
  animalStatusTitle: "Stan zwierzęcia",
animalStatusDescription: "Sprawdź lub zaktualizuj stan zwierzęcia.",
birthCaptureTitle: "Rejestracja porodu",
birthCaptureDescription: "Zarejestruj urodzone żywe, martwe i zmumifikowane prosięta.",
},
cambioPiensoMaternidad: {
  error: "Błąd",
  loadTasksError: "Nie udało się wczytać zadań zmiany paszy.",
  loadingTasks: "Wczytywanie zadań...",
  title: "Zmiana paszy",
  pendingTask: "{{count}} zadanie oczekujące",
  pendingTasks: "{{count}} zadania oczekujące",
  emptyTitle: "Brak oczekujących zadań",
  emptyText: "Nie znaleziono zadań zmiany paszy.",
  animalId: "ID ZWIERZĘCIA",
  corral: "Kojec",
  setTo: "Ustaw na",
  destination: "Cel"
},
estadoAnimal: {
  queryLabel: "Konsultacja",
  title: "Stan zwierzęcia",
  subtitle: "Wybierz, jak chcesz zidentyfikować zwierzę.",
  corral: "Kojec",
  corralDescription: "Wprowadź numer kojca.",
  id: "ID",
  idDescription: "Wprowadź identyfikator zwierzęcia.",
  animalId: "ID zwierzęcia",
  requiredData: "Wymagane dane",
  enterCorral: "Wprowadź numer kojca.",
  enterId: "Wprowadź identyfikator zwierzęcia.",
  consulting: "Sprawdzanie...",
  continue: "Kontynuuj",
  accept: "Akceptuj",
  serverConnectionError: "Nie udało się połączyć z serwerem.",
  noIpConfigured: "Nie skonfigurowano adresu IP.",
  nextScreenPending: "Ekran informacji o zwierzęciu utworzymy w następnym kroku.",
  corralMaternityDescription: "Wprowadź numer kojca porodowego.",
idAnimalDescription: "Wyszukaj zwierzę w porodówce i ciąży.",
animalNotFound: "Nie znaleziono zwierzęcia",
},
matCorralDetail: {
  readOnlyPermission: "Uprawnienia tylko do odczytu",
readOnlyPermissionText: "Ten użytkownik ma tylko uprawnienia do odczytu. Nie może wykonywać operacji na zwierzęciu.",

  animalStatus: "Stan zwierzęcia",
  id: "ID",
  earTag: "Kolczyk",
  cycle: "Cykl",
  day: "Dzień",

  curve: "Krzywa",
  correction: "Korekta",
  entryDate: "Data wejścia",
  farrowingDate: "Data porodu",
  house: "Budynek",
  pen: "Kojec",
  lastFeeding: "Ostatnie karmienie",
  presentPiglets: "Obecne prosięta",
  inseminationDate: "Data inseminacji",
  teatsNumber: "Liczba sutków",

  operations: "Operacje",

  consumption: "Zużycie",
  ofGrams: "z {{amount}} g",
  oneDayWithoutFeeding: "1 dzień bez karmienia",
  daysWithoutFeeding: "{{count}} dni bez karmienia",

  noAnimalData: "Brak danych zwierzęcia",
  noAnimalDataText: "Nie otrzymano informacji do wyświetlenia.",
  back: "Wróć",
  operationsPendingTitle: "Operacje",
  operationsPendingText: "Operacje wykonamy w następnym kroku.",
  moveToWeaning: "Przenieś do odsadzenia",
  chooseOption: "Wybierz operację dla tego zwierzęcia.",
  nextOperation: "Następna operacja",
  insertAnimal: "Wstaw zwierzę",
  moveToLactation: "Przenieś do laktacji",
  nextStep: "Następny krok",
  actions: "Działania",

  bodyCondition: "Kondycja ciała",
  subState: "Podstan",
  pigletCapture: "Rejestracja prosiąt",
  animalExit: "Wyjście zwierzęcia",
  replaceEarTag: "Zastąp kolczyk",
  changePen: "Zmień kojec",
  anonymousAnimalId: "Identyfikator zwierzęcia anonimowego",

  cancel: "Anuluj",
  accept: "Akceptuj",
  saving: "Zapisywanie...",
  error: "Błąd",

  operationDone: "Operacja wykonana poprawnie.",
  changeStateDone: "Podstan zaktualizowany poprawnie.",
  changeStateError: "Nie można zmienić stanu zwierzęcia.",
  confirmNextOperation: "Czy na pewno chcesz przejść do następnej operacji?",
  pkidChangeStateNotFound: "Nie znaleziono wewnętrznego identyfikatora zwierzęcia.",

  selectExitType: "Wybierz typ wyjścia, który chcesz zastosować.",
  exitImmediate: "Wyjście natychmiastowe",
  exitScheduled: "Wyjście zaplanowane",
  exitScheduledEmptyHopper: "Wyjście zaplanowane z pustym zasobnikiem",
  cancelScheduledExit: "Anuluj zaplanowane wyjście",
  scheduledDate: "Data zaplanowana",
  exitDateLimitText: "Nie można wybrać daty wcześniejszej niż dziś ani późniejszej niż za 3 dni.",
  animalExitDone: "Wyjście zwierzęcia wykonane poprawnie.",
  animalExitError: "Nie można wykonać wyjścia zwierzęcia.",
  pkidExitNotFound: "Nie znaleziono wewnętrznego identyfikatora zwierzęcia.",

  selectCurve: "Wybierz krzywą",
  selectCurveText: "Wybierz nową krzywą zwierzęcia.",
  loadingCurves: "Ładowanie krzywych...",
  noCurvesAvailable: "Brak dostępnych krzywych.",
  confirmChangeCurve: "Czy na pewno chcesz zmienić krzywą?",
  loadCurvesError: "Nie można załadować krzywych.",
  pkidChangeCurveNotFound: "Nie znaleziono wewnętrznego identyfikatora zwierzęcia.",
  changeCurveDone: "Krzywa zaktualizowana poprawnie.",
  changeCurveError: "Nie można zmienić krzywej.",

  selectBodyConditionText: "Wybierz nową kondycję ciała zwierzęcia.",
  loadingBodyConditions: "Ładowanie kondycji ciała...",
  noBodyConditionsAvailable: "Brak dostępnych kondycji ciała.",
  confirmChangeBodyCondition: "Czy na pewno chcesz zmienić kondycję ciała?",
  loadBodyConditionsError: "Nie można załadować kondycji ciała.",
  pkidChangeBodyConditionNotFound: "Nie znaleziono wewnętrznego identyfikatora zwierzęcia.",
  changeBodyConditionDone: "Kondycja ciała zaktualizowana poprawnie.",
  changeBodyConditionError: "Nie można zmienić kondycji ciała.",

  selectSubStateText: "Ręcznie wybierz nowy podstan zwierzęcia.",
  confirmChangeSubState: "Czy na pewno chcesz zmienić podstan?",

  currentPen: "Aktualny kojec: {{pen}}",
  newPen: "Nowy kojec",
  enterNewPen: "Wprowadź nowy kojec.",
  pkidChangePenNotFound: "Nie znaleziono wewnętrznego identyfikatora zwierzęcia.",
  changePenDone: "Kojec zaktualizowany poprawnie.",
  changePenError: "Nie można zmienić kojca.",

  currentEarTag: "Aktualny kolczyk: {{earTag}}",
  newEarTag: "Nowy kolczyk",
  enterNewEarTag: "Wprowadź nowy kolczyk.",
  pkidEarTagNotFound: "Nie znaleziono wewnętrznego identyfikatora zwierzęcia.",
  replaceEarTagDone: "Kolczyk zaktualizowany poprawnie.",
  replaceEarTagError: "Nie można zastąpić kolczyka.",

  identifyAnonymousAnimalText: "Wybierz, czy chcesz przypisać zwierzęciu ID czy kolczyk.",
  newId: "Nowe ID",
  enterNewId: "Wprowadź nowe ID.",
  idExample: "Np.: 1010",
  earTagExample: "Np.: 123",
  notAnonymousAnimalText: "To zwierzę nie jest anonimowe, ponieważ ma już przypisane ID lub kolczyk.",
  pkidIdentifyNotFound: "Nie znaleziono wewnętrznego identyfikatora zwierzęcia.",
  identifyAnonymousAnimalDone: "Identyfikator zwierzęcia zaktualizowany poprawnie.",
  identifyAnonymousAnimalError: "Nie można zidentyfikować zwierzęcia anonimowego.",

  livePiglets: "Żywe",
  deadPiglets: "Martwe",
  mummifiedPiglets: "Zmumifikowane",
  totalBornPiglets: "Łącznie urodzone",
  pigletCaptureText: "Wprowadź liczbę prosiąt żywych, martwych i zmumifikowanych.",
  captureBeforeLactationText: "Zarejestruj urodzone prosięta przed przejściem do laktacji.",
  weaningPigletsOnlyRead: "Przy odsadzeniu można tylko przeglądać prosięta.",
  pkidPigletsNotFound: "Nie znaleziono wewnętrznego identyfikatora zwierzęcia.",
  pigletCaptureDone: "Rejestracja prosiąt zapisana poprawnie.",
  pigletCaptureError: "Nie można zapisać rejestracji prosiąt.",
},
subState: {
  prepartum: "Przed porodem",
  lactation: "Laktacja",
  weaning: "Odsadzenie",
},

capturaParto: {
  birthDataTitle: "Dane porodu",
  birthDataSubtitle: "Sprawdź dane zwierzęcia przed zarejestrowaniem porodu.",
  corral: "Kojec",
  id: "ID",
  date: "Data",
  subState: "Podstan",

  dataCollectionTitle: "Zbieranie danych",
  dataCollectionSubtitle: "Wprowadź urodzone żywe, martwe i zmumifikowane prosięta.",
  weaningReadOnly: "Przy odsadzeniu dane można tylko przeglądać.",

  totalBorn: "Łącznie urodzone",
  live: "Żywe",
  dead: "Martwe",
  mummified: "Zmumifikowane",

  prepartum: "Przed porodem",
  farrowing: "Poród",
  lactation: "Laktacja",
  weaning: "Odsadzenie",

  accept: "Akceptuj",
  cancel: "Anuluj",
  saving: "Zapisywanie...",

  sentTitle: "Rejestracja wysłana",
  sentMessage: "Rejestracja porodu została zapisana poprawnie.",

  errorTitle: "Błąd",
  invalidAnimalTitle: "Nieprawidłowe zwierzę",
  invalidAnimalText: "Nie znaleziono wewnętrznego identyfikatora zwierzęcia.",
  reportSendError: "Nie można zapisać rejestracji porodu.",

  invalidDateTitle: "Nieprawidłowa data",
  invalidDateMessage: "Data porodu nie może być późniejsza niż dzisiaj.",
  changeDate: "Zmień datę",

  selectDateTitle: "Wybierz datę",
  selectDateMessage: "Dostosuj datę porodu za pomocą przycisków.",
},
capturaMaternidadEntrada: {
  title: "Rejestracja porodu",
  description: "Wyszukaj zwierzę po kojcu lub ID, aby zarejestrować poród.",
  maternityLabel: "PORODÓWKA",

  corral: "Kojec",
  corralDescription: "Wyszukaj zwierzę po numerze kojca.",
  id: "ID",
  idDescription: "Wyszukaj zwierzę po jego identyfikatorze.",
  animalId: "ID zwierzęcia",

  corralExample: "Np.: 102",
  idExample: "Np.: 1234",

  consulting: "Wyszukiwanie...",
  continue: "Kontynuuj",
  accept: "Akceptuj",

  serverConnectionError: "Nie można połączyć się z serwerem.",
},
altaBajaStack: {
  tituloPantalla: "Dodanie/ubytek prosiąt",
  descripcionPantalla: "Wyszukaj lochę po kojcu lub ID, aby zarejestrować dodanie lub ubytek prosiąt.",
},
altaBajaLechones: {
  heroTitle: "Ruch prosiąt",
  statusAlta: "Dodanie",
  statusBaja: "Ubytek",

  corralUpper: "KOJEC",
  idUpper: "ID",
  dateUpper: "DATA",

  movementType: "Typ ruchu",
  movementSubtitle: "Wybierz, czy chcesz zarejestrować dodanie czy ubytek.",
  adoption: "Adopcja",
  baja: "Ubytek",

  adoptionData: "Dane adopcji",
  donorMother: "Locha dawczyni",
  donatesPiglets: "Oddaje prosięta",
  id: "ID",
  transferredPiglets: "Przeniesione prosięta",
  totalAdopted: "Łącznie adoptowane",
  total: "Łącznie",

  bajaReason: "Powód ubytku",
  reasonCrushing: "Przygniecenie",
  reasonDiarrhea: "Biegunka",
  reasonLowViability: "Niska żywotność",
  reasonDeformities: "Deformacje",
  reasonOther: "Inne",

  piglet: "prosię",
  piglets: "prosięta",
  description: "Opis",

  editReason: "Edytuj powód",
  addReason: "Dodaj powód",
  reasonModalText: "Podaj liczbę prosiąt i opisz powód.",

  saving: "Zapisywanie...",
  saveAlta: "Zapisz dodanie",
  saveBaja: "Zapisz ubytek",
  accept: "Akceptuj",
  cancel: "Anuluj",

  error: "Błąd",
  missingData: "Brakujące dane",
  saveError: "Błąd zapisu",
  saveErrorText: "Nie można zapisać operacji.",
  selectedAnimalPkidNotFound: "Nie znaleziono wewnętrznego identyfikatora wybranego zwierzęcia.",

  enterTransferredPiglets: "Wprowadź liczbę przeniesionych prosiąt.",
  invalidTotalTitle: "Nieprawidłowa suma",
  invalidPigletsNumber: "Wprowadź prawidłową liczbę prosiąt.",

  missingDescriptionTitle: "Opis jest wymagany",
  missingDescriptionText: "Wprowadź opis powodu.",
  invalidQuantityTitle: "Nieprawidłowa ilość",
  invalidPigletQuantity: "Wprowadź prawidłową liczbę prosiąt.",

  selectReasonRequired: "Wybierz co najmniej jeden powód ubytku.",

  adoptionSavedTitle: "Dodanie zapisane",
  adoptionSavedMessage: "Zarejestrowano poprawnie {{count}} prosiąt.",

  bajasSavedTitle: "Ubytki zapisane",
  bajasSavedMessage: "Zarejestrowano poprawnie {{piglets}} ubytków dla {{reasons}} powodu/powodów.",
},
avisoAplicacionNoConfigurada: {
  title: "Aplikacja nie jest skonfigurowana",
  text: "Skonfiguruj adres IP serwera",
  link: "Naciśnij tutaj",
},
generalHome: {
  movementAnimalTitle: "Ruch zwierząt",
  readerDescription: "Czytnik kolczyków.",
  keyboardDescription: "Klawiatura",

  ctifeedTitle: "CTIFEED",
  ctifeedDescription: "Przejdź do głównego portalu.",

  modalApplicationNotConfiguredTitle: "Aplikacja nie jest skonfigurowana",
  modalNoSessionTitle: "Sesja nie została rozpoczęta",
  modalInstallationUnavailableTitle: "Instalacja niedostępna",
  modalPreparingSessionTitle: "Przygotowywanie sesji",
  modalReadOnlyPermissionTitle: "Uprawnienia tylko do odczytu",

  modalApplicationNotConfiguredText: "Nie skonfigurowano żadnej instalacji. Przejdź do Instalacji i wybierz jedną.",
  modalNoSessionText: "Instalacja ma adres IP, ale sesja nie została rozpoczęta. Sprawdź nazwę użytkownika i hasło w Instalacjach.",
  modalInstallationUnavailableText: "Nie można połączyć się z wybraną instalacją. Sprawdź, czy jesteś połączony z właściwą siecią WiFi lub zweryfikuj adres IP serwera.",
  modalPreparingSessionText: "Sesja nadal się ładuje. Spróbuj ponownie za kilka sekund.",
  modalReadOnlyPermissionText: "Twój użytkownik nie ma uprawnień administratora do tej funkcji.",

  accept: "Akceptuj",

  connectingTitle: "Łączenie...",
  connectingText: "Sprawdzanie połączenia z wybraną instalacją.",
},
movimientoAnimalMaternidad: {
  smallLabel: "RUCH",
  title: "Porodówka",
  subtitle: "Wykonuj ręczne wejścia i wyjścia za pomocą klawiatury.",

  movementType: "Typ ruchu",
  entry: "Wejście",
  exit: "Wyjście",

  searchAnimal: "Szukaj zwierzęcia",
  entryHelper: "Wprowadź kojec docelowy i ID zwierzęcia.",
  exitHelper: "Wybierz, czy chcesz wykonać wyjście po kojcu czy po ID.",

  pen: "Kojec",
  animalId: "ID zwierzęcia",
  type: "Typ",

  sending: "Wysyłanie...",
  accept: "Akceptuj",
  cancel: "Anuluj",

  confirmEntry: "Potwierdź wejście",
  confirmExit: "Potwierdź wyjście",
  confirmSubtitle: "Sprawdź dane przed wysłaniem ruchu.",

  incompleteDataTitle: "Niekompletne dane",
  entryIncompleteText: "Wprowadź kojec i ID zwierzęcia.",
  exitPenIncompleteText: "Wprowadź kojec, aby wykonać wyjście.",
  exitIdIncompleteText: "Wprowadź ID zwierzęcia, aby wykonać wyjście.",

  invalidPenTitle: "Nieprawidłowy kojec",
  invalidPenText: "Kojec musi być prawidłową liczbą większą niż 0.",

  sendErrorTitle: "Błąd wysyłania",
  connectionErrorTitle: "Błąd połączenia",
  noIpConfigured: "Nie skonfigurowano adresu IP.",
  serverConnectionError: "Nie można połączyć się z serwerem.",
  serverEmptyResponse: "Serwer nie zwrócił komunikatu. Kod HTTP {{status}}.",

  entrySentTitle: "Wejście wysłane",
  entrySentText: "Ruch wejścia został wysłany poprawnie.",

  exitSentTitle: "Wyjście wysłane",
  exitByPenSentText: "Wyjście po kojcu zostało wysłane poprawnie.",
  exitByIdSentText: "Wyjście po ID zostało wysłane poprawnie.",
},
movimientoAnimalGestacion: {
  smallLabel: "GESTACJA",
  title: "Ruch zwierząt",
  subtitle: "Wykonuj ręczne wejścia i wyjścia za pomocą klawiatury.",

  movementType: "Typ ruchu",
  entry: "Wejście",
  exit: "Wyjście",

  searchAnimal: "Szukaj zwierzęcia",
  entryHelper: "Wprowadź kojec docelowy i ID zwierzęcia.",
  exitHelper: "Wprowadź ID zwierzęcia, aby wykonać wyjście z gestacji.",

  pen: "Kojec",
  animalId: "ID zwierzęcia",
  type: "Typ",

  sending: "Wysyłanie...",
  accept: "Akceptuj",
  cancel: "Anuluj",

  confirmEntry: "Potwierdź wejście",
  confirmExit: "Potwierdź wyjście",
  confirmSubtitle: "Sprawdź dane przed wysłaniem ruchu.",

  incompleteDataTitle: "Niekompletne dane",
  entryIncompleteText: "Wprowadź kojec i ID zwierzęcia.",
  exitIdIncompleteText: "Wprowadź ID zwierzęcia, aby wykonać wyjście.",

  invalidPenTitle: "Nieprawidłowy kojec",
  invalidPenText: "Kojec musi być prawidłową liczbą większą niż 0.",

  sendErrorTitle: "Błąd wysyłania",
  noIpConfigured: "Nie skonfigurowano adresu IP.",
  serverConnectionError: "Nie można połączyć się z serwerem.",
  serverEmptyResponse: "Serwer nie zwrócił komunikatu. Kod HTTP {{status}}.",

  entrySentTitle: "Wejście wysłane",
  entrySentText: "Ruch wejścia w gestacji został wysłany poprawnie.",

  exitSentTitle: "Wyjście wysłane",
  exitByIdSentText: "Wyjście z gestacji po ID zostało wysłane poprawnie.",
},
gestCorralDetail: {
    title: "Stan zwierzęcia w ciąży",
    emptyTitle: "W tym kojcu nie ma zwierzęcia",

    id: "ID",
    crotal: "Kolczyk",
    cycle: "Cykl",
    day: "Dzień",

    stateGestation: "Ciąża",
    stateOutOfGestation: "Poza ciążą",

    curve: "Krzywa",
    correction: "Korekta",
    entryDate: "Data wejścia",
    inseminationDate: "Data inseminacji",
    house: "Budynek",
    corral: "Kojec",
    estimatedFarrowingDate: "Szacowana data porodu",
    lastFeeding: "Ostatnie karmienie",

    oneDayWithoutFeeding: "1 dzień bez karmienia",
    daysWithoutFeeding: "{{count}} dni bez karmienia",
    of: "z",
},
};