import { config } from "process";

export default {
  username: 'Usuari',
  password: 'Clau',
  login: 'Inicia sessió',
  welcome: 'Benvingut',
  change_language: 'Canvia idioma',
  Tabs: 'Inici',

  Lista_instalaciones: 'Instal·lacions',
  Maintenance: 'Manteniment',
  DetallesInstalacion: 'Detalls instal·lació',
  Grabar: 'Gravar',
  EstadoStore: 'Estat store',
  Nodata: 'No hi ha dades',
  DosimacRegistration: 'Alta Dosimac',
  NewDmMaternity: 'Nou Dosimac maternitat',
  DosimacG: 'Dosimac-G',
  DosimacI: 'Dosimac-I',
  UpdDmMaternity: 'Canvi Dosimac maternitat',
  NewDmGestation: 'Nou Dosimac gestació',
  UpdDmGestation: 'Canvi Dosimac gestació',
  StartScan: 'Cercar equips DOSIMAC',
  DosimacList: 'Equips DOSIMAC',
  PressToScan: 'Premi',
  DosimacSetup: 'Configuració',
  TestoPresioneAlta: 'Premi el botó per cercar dispositius',
  Instalación_seleccionada: 'Instal·lació seleccionada',
  NoInstalacionSeleccionada: 'No hi ha instal·lació seleccionada',
  BorrarGranja: 'Esborrar granja',
  Deseaborrarlagranja: 'Vol esborrar la granja?',
  Guardar: 'Guardar',
  Cancelar: 'Cancel·lar',
  Aceptar: 'Acceptar',
  NombreGranja: 'Nom de la granja',
  Localidad: 'Localitat',
  Provincia: 'Província',
  NombreWifi: 'Wifi SSID',
  PasswordWifi: 'Contrasenya Wifi',
  No_hay_dispositivos: 'No hi ha dispositius',
  Aviso: 'Avís',
  SearchingDevices: 'Cercant equips...',
  NoSePuedeBorrarGranja: 'No es pot esborrar una granja nova',
  settings: 'Ajustos',
  softwareVersion: 'Versió de programari',
  numeroCoral: 'Número de corral',
  numeroMaquina: 'Número de màquina',
  Enviar: 'Enviar',
  Salir: 'Sortir',
  Informacion: 'Informació',

  InicioConfiguracion: "Iniciant connexió",
  ConfiguracionWifi: "Configurant...",
  ConfiguracionRealizada: "*Configuració realitzada*",
  ErrorConfiguracion: "*Error de configuració*",
  CapturaTagCorral: "Capturar etiqueta de corral",
  CorralTag: "Etiqueta de corral",
  versionUint16: "Aquesta versió de l'equip només admet corral fins a 65000",
  versionUint32: "Aquesta versió de l'equip admet corral fins a 4000000000",
  EnvioConfiguracion: "Enviant la configuració",
  NumeroCorral: "Número de corral",
  NumeroMaquina: "Número de màquina",
  Corralnovalida: "Corral no vàlid",
  NumeroMaquinanovalida: "Número de màquina no vàlid",
  configuarIntalacion: "Cal configurar la instal·lació abans d'usar aquesta funció",

  login_title: "Iniciar sessió",
  login_subtitle: "Introdueix les teves dades. Cal configurar la IP abans d'iniciar sessió des del menú Configuració IP.",
  login_username: "Usuari",
  login_password: "Contrasenya",
  login_button: "Entrar",
  login_loading: "Entrant...",
  login_footer: "Panell de control",

  login_ipRequiredTitle: "Configuració IP necessària",
  login_ipRequiredMessage: "No has configurat l'adreça IP del servidor. Introdueix-la per poder iniciar sessió.",
  login_serverIpLabel: "IP del servidor",
  login_cancel: "Cancel·lar",
  login_accept: "Acceptar",
  login_invalidCredentials: "Nom d'usuari o contrasenya incorrectes",

  login_configTitle: "Configuració",
  login_errorTitle: "Error d'inici de sessió",
  login_genericErrorTitle: "Error",
  login_networkErrorTitle: "Error de xarxa",
  login_networkErrorMessage: "No s'ha pogut connectar amb el servidor.",
  login_noTokenMessage: "El backend no ha retornat cap token.",
  login_missingDataTitle: "Falten dades",
  login_missingDataMessage: "Introdueix usuari i contrasenya.",
  login_invalidIpTitle: "IP no vàlida",
  login_invalidIpMessage: "Introdueix una IP o una adreça de servidor vàlida.",
  login_saveIpErrorMessage: "No s'ha pogut desar la configuració IP.",
  awrStartScan_title: "Configuració AWR",
  awrStartScan_description: "Pantalla per escanejar lectors Agrident AWR.",
  awrStartScan_button: "Escanejar AWR",

  gestacionConfig_screenTitle: "Configuració Gestació",
  gestacionConfig_chooseOptionTitle: "Tria una opció",
  gestacionConfig_chooseOptionDescription: "Defineix el flux abans de començar amb el lector.",

  gestacionConfig_entry: "Entrada",
  gestacionConfig_exit: "Sortida",
  gestacionConfig_reading: "Lectura",
  gestacionConfig_search: "Cerca",

  gestacionConfig_entryParamsTitle: "Paràmetres d'entrada",
  gestacionConfig_exitParamsTitle: "Paràmetres de sortida",
  gestacionConfig_entryParamsDescription: "Selecciona el corral i el comportament del flux.",
  gestacionConfig_exitParamsDescription: "Configura el comportament del flux de sortida.",

  gestacionConfig_corralLabel: "Corral",
  gestacionConfig_corralPlaceholder: "Ex: 1",
  gestacionConfig_corralRequired: "Escriu el corral per continuar.",

  gestacionConfig_detectUnknownTitle: "Identificar animals desconeguts",
  gestacionConfig_detectUnknownDescription: "Quan llegeixis un animal sense identificar, podràs assignar-li un ID",

  gestacionConfig_confirmTitle: "Confirmar enviament",
  gestacionConfig_confirmDescription: "Demanarà confirmació abans d'enviar els registres.",

  gestacionConfig_animalSearchTitle: "Cerca d'animal",
  gestacionConfig_animalSearchDescription: "Tria si vols cercar per crotal o per ID.",
  gestacionConfig_searchByCrotal: "Per crotal",
  gestacionConfig_searchById: "Per ID",
  gestacionConfig_manual: "Manual",
  gestacionConfig_withSword: "Amb espasa",

  gestacionConfig_crotalLabelSearch: "Crotal",
  gestacionConfig_idLabelSearch: "ID",
  gestacionConfig_crotalPlaceholderSearch: "Ex: 982091072397436",
  gestacionConfig_idPlaceholderSearch: "Ex: A13",
  gestacionConfig_crotalRequiredSearch: "Escriu un crotal per continuar.",
  gestacionConfig_idRequiredSearch: "Escriu un ID per continuar.",

  gestacionConfig_searchWithSwordHelp: "En continuar, es llegirà l'espasa en aquesta pantalla i es buscarà l'animal amb aquest crotal.",

  gestacionConfig_readingSword: "Llegint espasa...",
  gestacionConfig_waitingMatch: "Esperant coincidència",
  gestacionConfig_searchingAnimal: "Cercant animal...",

  gestacionConfig_readingSwordDescription: "Apropa el crotal al lector per identificar l'animal.",
  gestacionConfig_waitingMatchDescription: "Animal localitzat. Ara apropa a l'espasa el crotal {{crotal}} per confirmar la coincidència.",
  gestacionConfig_searchingAnimalDescription: "Consultant informació de l'animal al backend.",

  gestacionConfig_awrDisconnectedTitle: "AWR no connectat",
  gestacionConfig_awrSavedDescription: "Tens espases desades. Prem per seleccionar-ne una.",
  gestacionConfig_awrNotSavedDescription: "No tens cap espasa desada. Prem per escanejar-ne una.",

  gestacionConfig_scan: "Escanejar",
  gestacionConfig_continue: "Continuar",

  gestacionConfig_alerts_error: "Error",
  gestacionConfig_alerts_networkError: "Error de xarxa",
  gestacionConfig_alerts_networkErrorMessage: "No s'ha pogut connectar amb el servidor.",
  gestacionConfig_alerts_backendNoValidCrotal: "El backend no ha retornat un crotal vàlid per comparar.",
  gestacionConfig_alerts_awrNotConnected: "AWR no connectat",
  gestacionConfig_alerts_connectSwordBeforeContinue: "Connecta una espasa abans de continuar.",
  gestacionConfig_alerts_couldNotStartReading: "No s'ha pogut iniciar la lectura amb l'espasa.",

  gestacionConfig_alerts_missingData: "Falta dada",
  gestacionConfig_alerts_writeCrotalToSearch: "Escriu un crotal per cercar.",
  gestacionConfig_alerts_writeIdToSearch: "Escriu un ID per cercar.",

  gestacionConfig_alerts_notFound: "No trobat",
  gestacionConfig_alerts_animalNotFoundByCrotal: "No existeix cap animal amb aquest crotal.",
  gestacionConfig_alerts_animalNotFoundById: "No existeix cap animal amb aquest ID.",

  gestacionConfig_alerts_warning: "Avís",
  gestacionConfig_alerts_searchError: "Error en la cerca",

  maternidadConfig_screenTitle: "Configuració Maternitat",
  maternidadConfig_chooseOptionTitle: "Tria una opció",
  maternidadConfig_chooseOptionDescription: "Defineix el flux abans de començar amb el lector.",
  maternidadConfig_entry: "Entrada",
  maternidadConfig_exit: "Sortida",
  maternidadConfig_reading: "Lectura",
  maternidadConfig_search: "Cerca",
  maternidadConfig_entryParamsTitle: "Paràmetres d'entrada",
  maternidadConfig_exitParamsTitle: "Paràmetres de sortida",
  maternidadConfig_entryParamsDescription: "Selecciona el corral i el comportament del flux.",
  maternidadConfig_exitParamsDescription: "Configura el comportament del flux de sortida.",
  maternidadConfig_corralLabel: "Corral",
  maternidadConfig_corralPlaceholder: "Ex: 1",
  maternidadConfig_corralRequired: "Escriu el corral per continuar.",
  maternidadConfig_detectUnknownTitle: "Identificar animals desconeguts",
  maternidadConfig_detectUnknownDescription: "Quan llegeixis un animal sense identificar, podràs assignar-li un ID",
  maternidadConfig_confirmTitle: "Confirmar enviament",
  maternidadConfig_confirmDescription: "Demanarà confirmació abans d'enviar cada registre.",
  maternidadConfig_animalSearchTitle: "Cerca d'animal",
  maternidadConfig_animalSearchDescription: "Tria si vols cercar per crotal o per ID.",
  maternidadConfig_searchByCrotal: "Per crotal",
  maternidadConfig_searchById: "Per ID",
  maternidadConfig_manual: "Manual",
  maternidadConfig_withSword: "Amb espasa",
  maternidadConfig_crotalLabelSearch: "Crotal",
  maternidadConfig_idLabelSearch: "ID",
  maternidadConfig_crotalPlaceholderSearch: "Ex: 982091072397436",
  maternidadConfig_idPlaceholderSearch: "Ex: A13",
  maternidadConfig_crotalRequiredSearch: "Escriu un crotal per continuar.",
  maternidadConfig_idRequiredSearch: "Escriu un ID per continuar.",
  maternidadConfig_searchWithSwordHelp: "En prémer Escanejar, es llegirà l'espasa en aquesta pantalla i es buscarà l'animal amb aquest crotal.",
  maternidadConfig_readingSword: "Llegint espasa...",
  maternidadConfig_waitingMatch: "Esperant coincidència",
  maternidadConfig_searchingAnimal: "Cercant animal...",
  maternidadConfig_readingSwordDescription: "Apropa el crotal al lector per identificar l'animal.",
  maternidadConfig_waitingMatchDescription: "Animal localitzat. Ara apropa a l'espasa el crotal {{crotal}} per confirmar la coincidència.",
  maternidadConfig_searchingAnimalDescription: "Consultant informació de l'animal al backend.",
  maternidadConfig_awrDisconnectedTitle: "AWR no connectat",
  maternidadConfig_awrSavedDescription: "Tens AWR desades. Prem per seleccionar-ne una.",
  maternidadConfig_awrNotSavedDescription: "No tens cap AWR desada. Prem per escanejar-ne una.",
  maternidadConfig_scan: "Escanejar",
  maternidadConfig_continue: "Continuar",
  maternidadConfig_alert_error: "Error",
  maternidadConfig_alert_invalidBackendCrotal: "El backend no ha retornat un crotal vàlid per comparar.",
  maternidadConfig_alert_awrNotConnected: "AWR no connectat",
  maternidadConfig_alert_connectSwordBeforeContinue: "Connecta una espasa abans de continuar.",
  maternidadConfig_alert_couldNotStartReading: "No s'ha pogut iniciar la lectura amb l'espasa.",
  maternidadConfig_alert_missingData: "Falten dades",
  maternidadConfig_alert_writeCrotalToSearch: "Escriu un crotal per cercar.",
  maternidadConfig_alert_writeIdToSearch: "Escriu un ID per cercar.",
  maternidadConfig_alert_notFound: "No trobat",
  maternidadConfig_alert_noAnimalWithCrotal: "No existeix cap animal amb aquest crotal.",
  maternidadConfig_alert_noAnimalWithId: "No existeix cap animal amb aquest ID.",
  maternidadConfig_alert_warning: "Avís",
  maternidadConfig_alert_searchError: "Error en la cerca",
  maternidadConfig_alert_networkError: "Error de xarxa",
  maternidadConfig_alert_networkErrorMessage: "No s'ha pogut connectar amb el servidor.",

  gestationReader_screenTitle: "Lector Gestació",
  gestationReader_animalInfoTitle: "Informació de l'animal",
  gestationReader_animalInfoDescription: "Dades localitzades a la cerca.",
  gestationReader_animalCardTitle: "Fitxa Animal",
  gestationReader_animalIdLabel: "ID",
  gestationReader_animalCrotalLabel: "Crotal",
  gestationReader_fieldCorral: "Corral",
  gestationReader_fieldHouse: "Nau",
  gestationReader_fieldState: "Estat",
  gestationReader_fieldBodyCondition: "Condició corporal",
  gestationReader_fieldCycle: "Cicle",
  gestationReader_fieldSystemEntryDate: "Entrada al sistema",
  gestationReader_newSearch: "Nova cerca",
  gestationReader_summaryTitle: "Resum",
  gestationReader_summaryDescription: "Paràmetres triats a Configuració",
  gestationReader_mode: "Mode",
  gestationReader_corral: "Corral",
  gestationReader_modeEntry: "Entrada",
  gestationReader_modeExit: "Sortida",
  gestationReader_modeReading: "Lectura",
  gestationReader_modeSearch: "Cerca",
  gestationReader_detectUnknownTitle: "Identificar animals desconeguts",
  gestationReader_detectUnknownDescription: "Quan surti un animal sense ID, oferir assignar-li un ID.",
  gestationReader_confirmSendTitle: "Confirmar enviament",
  gestationReader_confirmSendDescription: "Demanarà confirmació abans d'enviar cada registre.",
  gestationReader_changeSettings: "Canviar configuració",
  gestationReader_currentReadingTitle: "Lectura actual",
  gestationReader_currentReadingDescription: "El crotal detectat i l'ID associat apareixeran aquí.",
  gestationReader_awrDisconnected: "AWR no connectat",
  gestationReader_readCrotal: "Crotal llegit",
  gestationReader_readId: "ID",
  gestationReader_animalWithoutAssignedId: "Animal sense ID assignat",
  gestationReader_unknownAnimal: "Animal desconegut",
  gestationReader_animalWithoutIdTitle: "Animal sense ID",
  gestationReader_animalWithoutIdDescription: "Escriu un ID manual per actualitzar el crotal llegit.",
  gestationReader_newIdLabel: "Nou ID",
  gestationReader_newIdPlaceholder: "Ex: A13",
  gestationReader_updateId: "Actualitzar ID",
  gestationReader_updatingId: "Actualitzant...",
  gestationReader_sentRecordsTitle: "Registres enviats",
  gestationReader_noRecords: "No hi ha registres.",
  gestationReader_tableHeaderCorral: "Corral",
  gestationReader_tableHeaderId: "ID",
  gestationReader_tableHeaderCrotal: "Crotal",
  gestationReader_buttonAutoReading: "Lectura automàtica activa",
  gestationReader_buttonAutoSending: "Enviament automàtic actiu",
  gestationReader_buttonSending: "Enviant...",
  gestationReader_buttonSend: "Enviar",
  gestationReader_alertError: "Error",
  gestationReader_alertWarning: "Avís",
  gestationReader_alertNetworkError: "Error de xarxa",
  gestationReader_alertMissingCrotalTitle: "Falta crotal",
  gestationReader_alertMissingCrotalMessage: "Apropa el crotal al lector abans d'enviar.",
  gestationReader_alertInvalidCrotalTitle: "Crotal invàlid",
  gestationReader_alertInvalidCrotalMessage: "El crotal ha de ser numèric.",
  gestationReader_alertReadErrorTitle: "Error de lectura",
  gestationReader_alertNetworkErrorMessage: "No s'ha pogut connectar amb el servidor.",
  gestationReader_alertMissingCorralTitle: "Falta corral",
  gestationReader_alertMissingCorralMessage: "Escriu el corral abans d'enviar.",
  gestationReader_alertInvalidCorralTitle: "Corral invàlid",
  gestationReader_alertInvalidCorralMessage: "El corral ha de ser un número.",
  gestationReader_alertSendErrorTitle: "Error en enviar",
  gestationReader_alertNoIpConfigured: "No hi ha IP configurada.",
  gestationReader_alertMissingIdTitle: "Falta ID",
  gestationReader_alertMissingIdMessage: "Escriu el nou ID abans d'actualitzar.",
  gestationReader_alertMissingAssociatedCrotalTitle: "Falta crotal",
  gestationReader_alertMissingAssociatedCrotalMessage: "No hi ha crotal associat per actualitzar.",
  gestationReader_alertInvalidAssociatedCrotalTitle: "Crotal invàlid",
  gestationReader_alertInvalidAssociatedCrotalMessage: "El crotal associat no és vàlid.",
  gestationReader_alertUpdateIdErrorTitle: "Error en actualitzar ID",

  maternityReader_screenTitle: "Lector Maternitat",
  maternityReader_alertMissingCrotalTitle: "Falta crotal",
  maternityReader_alertMissingCrotalMessage: "Apropa el crotal al lector abans d'enviar.",
  maternityReader_alertInvalidCrotalTitle: "Crotal no vàlid",
  maternityReader_alertInvalidCrotalMessage: "El crotal ha de ser numèric.",
  maternityReader_alertReadErrorTitle: "Error de lectura",
  maternityReader_alertNetworkError: "Error de xarxa",
  maternityReader_alertNetworkErrorMessage: "No s'ha pogut connectar amb el servidor.",
  maternityReader_alertMissingCorralTitle: "Falta corral",
  maternityReader_alertMissingCorralMessage: "Escriu el corral abans d'enviar.",
  maternityReader_alertInvalidCorralTitle: "Corral no vàlid",
  maternityReader_alertInvalidCorralMessage: "El corral ha de ser un número (ex.: 8).",
  maternityReader_alertError: "Error",
  maternityReader_alertNoIpConfigured: "No hi ha IP configurada.",
  maternityReader_alertWarning: "Avís",
  maternityReader_alertSendErrorTitle: "Error en enviar",
  maternityReader_alertMissingIdTitle: "Falta ID",
  maternityReader_alertMissingIdMessage: "Escriu el nou ID abans d'actualitzar.",
  maternityReader_alertMissingAssociatedCrotalTitle: "Falta crotal",
  maternityReader_alertMissingAssociatedCrotalMessage: "No hi ha crotal associat per actualitzar.",
  maternityReader_alertInvalidAssociatedCrotalTitle: "Crotal no vàlid",
  maternityReader_alertInvalidAssociatedCrotalMessage: "El crotal associat no és vàlid.",
  maternityReader_alertUpdateIdErrorTitle: "Error en actualitzar l'ID",
  maternityReader_animalInfoTitle: "Informació de l'animal",
  maternityReader_animalInfoDescription: "Dades localitzades a la cerca.",
  maternityReader_animalCardTitle: "Fitxa Animal",
  maternityReader_animalIdLabel: "ID",
  maternityReader_animalCrotalLabel: "Crotal",
  maternityReader_fieldCorral: "Corral",
  maternityReader_fieldHouse: "Nau",
  maternityReader_fieldState: "Estat",
  maternityReader_fieldBodyCondition: "Condició corporal",
  maternityReader_fieldCycle: "Cicle",
  maternityReader_fieldSystemEntryDate: "Entrada al sistema",
  maternityReader_newSearch: "Nova cerca",
  maternityReader_summaryTitle: "Resum",
  maternityReader_summaryDescription: "Paràmetres triats a Configuració",
  maternityReader_mode: "Mode",
  maternityReader_modeEntry: "Entrada",
  maternityReader_modeExit: "Sortida",
  maternityReader_modeReading: "Lectura",
  maternityReader_corral: "Corral",
  maternityReader_detectUnknownTitle: "Identificar animals desconeguts",
  maternityReader_detectUnknownDescription: "Quan surti un animal sense ID, oferir assignar-li un ID.",
  maternityReader_confirmSendTitle: "Confirmar enviament",
  maternityReader_confirmSendDescription: "Demanarà confirmació abans d'enviar cada registre.",
  maternityReader_changeSettings: "Canviar configuració",
  maternityReader_currentReadingTitle: "Lectura actual",
  maternityReader_currentReadingDescription: "El crotal detectat apareixerà aquí.",
  maternityReader_awrDisconnected: "AWR no connectat",
  maternityReader_readCrotal: "Crotal llegit",
  maternityReader_readId: "ID",
  maternityReader_animalWithoutAssignedId: "Animal sense ID assignat",
  maternityReader_unknownAnimal: "Animal desconegut",
  maternityReader_animalWithoutIdTitle: "Animal sense ID",
  maternityReader_animalWithoutIdDescription: "Escriu un ID manual per actualitzar el crotal llegit.",
  maternityReader_newIdLabel: "Nou ID",
  maternityReader_newIdPlaceholder: "Ex.: A13",
  maternityReader_updatingId: "Actualitzant...",
  maternityReader_updateId: "Actualitzar ID",
  maternityReader_sentRecordsTitle: "Registres enviats",
  maternityReader_tableHeaderCorral: "Corral",
  maternityReader_tableHeaderId: "ID",
  maternityReader_tableHeaderCrotal: "Crotal",
  maternityReader_noRecords: "No hi ha registres.",
  maternityReader_buttonAutoReading: "Lectura automàtica activa",
  maternityReader_buttonAutoSending: "Enviament automàtic actiu",
  maternityReader_buttonSending: "Enviant...",
  maternityReader_buttonSend: "Enviar",

  awrScanResults_title: "AWR – Resultats de l'escaneig",
  awrScanResults_searching: "Cercant AWR…",
  awrScanResults_warningTitle: "Avís",
  awrScanResults_noDevicesNearby: "No s'han trobat AWR propers.",
  awrScanResults_connecting: "Connectant…",
  awrScanResults_connectErrorFallback: "No s'ha pogut connectar",
  awrScanResults_connectedTitle: "Connectat",
  awrScanResults_connectedMessage: "Connexió establerta amb {{device}}.",
  awrScanResults_genericDevice: "el dispositiu",

  awrSavedList_title: "AWR escanejats",
  awrSavedList_connecting: "Connectant…",
  awrSavedList_empty: "No hi ha AWR desats. Escaneja'n un des de “Configuració AWR”.",
  awrSavedList_connected: "Connectat",
  awrSavedList_disconnected: "Desconnectat",
  awrSavedList_renameAccessibility: "Canviar el nom",
  awrSavedList_deleteAccessibility: "Eliminar",
  awrSavedList_renameTitle: "Canviar el nom de l'AWR",
  awrSavedList_nameLabel: "Nom",
  awrSavedList_deleteTitle: "Eliminar AWR desat",
  awrSavedList_deleteMessage: "Segur que vols eliminar aquest AWR de la llista?",
  awrSavedList_deleteAction: "Eliminar",

  ipConfig_title: "Configuració IP",
  ipConfig_cardTitle: "Servidor CTIFEED",
  ipConfig_cardDescription: "Introdueix la IP del servidor on s'obrirà el portal.",
  ipConfig_inputLabel: "IP (només la IP)",
  ipConfig_saved: "Desat",
  ipConfig_alertSuccessTitle: "Correcte",
  ipConfig_alertSuccessMessage: "IP correcta",
  ipConfig_alertWarningTitle: "Avís",
  ipConfig_alertServerNotUpdated: "Servidor no actualitzat",
  ipConfig_alertErrorTitle: "Error",
  ipConfig_alertInvalidIp: "IP no vàlida",

  portal_preparing: "Preparant el portal...",
  portal_noSessionToken: "No hi ha cap token de sessió. Torna a iniciar sessió.",
  portal_noIpConfigured: "No hi ha cap IP configurada. Configura primer la IP del servidor.",
  portal_prepareUrlError: "No s’ha pogut preparar l’URL del portal.",
  portal_loadError: "No s’ha pogut carregar el portal.",
  portal_checkingConnection: "Comprovant la connexió amb el portal...",
  portal_noConnectionTitle: "Sense connexió",
  portal_connectionTimeout: "No s’ha pogut connectar amb el portal. Verifica que estiguis connectat a la xarxa correcta.",
  portal_connectionError: "No s’ha pogut connectar amb el portal. Verifica la xarxa o la IP configurada.",
  portal_httpError: "No s’ha pogut obrir el portal. Error HTTP {{status}}.",
  portal_retry: "Torna-ho a provar",
  portal_loading: "Carregant el portal...",

  AltaDispositivos: "Alta de dispositius",
  LectorMaternidad: "Lector Maternitat",
  LectorGestacion: "Lector Gestació",
  ConfiguracionIP: "Configuració IP",
  ConfiguracionAWR: "Configuració AWR",
  DarDeAltaAWR: "Donar d'alta AWR",
  AWREscaneados: "AWR escanejats",
  CerrarSesion: "Tancar sessió",

  Config_lastReadMismatchTitle: "L'animal llegit no coincideix amb la cerca",
  Config_lastReadMismatchCrotal: "Crotal",
  Config_lastReadMismatchId: "ID",
  awrBluetoothPermissionMessage: "Activa el Bluetooth i accepta el permís per poder escanejar.", 

  animalState: {
    gestation: "Gestació",
    maternity: "Maternitat",
    out_of_gestation: "Fora de gestació",
    out_of_maternity: "Fora de maternitat"
  },

  
Reader_readingTitle: "Lectura de crotals",
Reader_labelId: "ID",
Reader_labelCrotal: "Crotal",
Reader_labelCorral: "Corral",
Reader_labelHouse: "Nau",
Reader_labelState: "Estat",
Reader_autoReadingBadge: "Lectura automàtica",

gestacionConfig_flowSectionTitle: "Configuració del flux",
gestacionConfig_workModeTitle: "Mode de treball",
gestacionConfig_workModeDescription: "Selecciona què farà el lector.",
gestacionConfig_entryDescription: "Registrar entrada",
gestacionConfig_exitDescription: "Registrar sortida",
gestacionConfig_readingDescription: "Només consultar",
gestacionConfig_searchDescription: "Buscar animal",

gestacionConfig_sendSettingsTitle: "Ajustos de l’enviament",
gestacionConfig_sendSettingsDescription: "Configura com es comporta el flux en llegir animals.",

gestacionConfig_corralSectionTitle: "Corral d’entrada",
gestacionConfig_corralSectionDescription: "Aquesta dada és obligatòria per continuar amb el registre.",

gestacionConfig_alerts_notice: "Avís",
gestacionConfig_alerts_invalidCrotalFromBackend: "El backend no ha retornat un cròtal vàlid per comparar.",

common_accept: "Acceptar",

maternidadConfig_flowSectionTitle: "Configuració del flux",
maternidadConfig_workModeTitle: "Mode de treball",
maternidadConfig_workModeDescription: "Selecciona què farà el lector.",
maternidadConfig_entryDescription: "Registrar entrada",
maternidadConfig_exitDescription: "Registrar sortida",
maternidadConfig_readingDescription: "Només consultar",
maternidadConfig_searchDescription: "Buscar animal",

maternidadConfig_sendSettingsTitle: "Ajustos de l’enviament",
maternidadConfig_sendSettingsDescription: "Configura com es comporta el flux en llegir animals.",

maternidadConfig_corralSectionTitle: "Corral d’entrada",
maternidadConfig_corralSectionDescription: "Aquesta dada és obligatòria per continuar amb el registre.",

maternidadConfig_alert_invalidCrotalFromBackend: "El backend no ha retornat un cròtal vàlid per comparar.",

};