export default {
    username: 'Usuari',
    password: 'Clau',
    login: 'Inicia sessió',
    welcome: 'Benvingut',
    change_language: 'Canvia idioma',
    Tabs: 'Inici',

    Lista_instalaciones: 'Instal·lacions',
    Maintenance: 'Manteniment',
    DetallesInstalacion: 'Detalls instal·lació',
    Grabar: 'Gravar',
    EstadoStore: 'Estat store',
    Nodata: 'No hi ha dades',
    DosimacRegistration: 'Alta Dosimac',
    NewDmMaternity: 'Nou Dosimac maternitat',
    DosimacG: 'Dosimac-G',
    DosimacI: 'Dosimac-I',
    UpdDmMaternity: 'Canvi Dosimac maternitat',
    NewDmGestation: 'Nou Dosimac gestació',
    UpdDmGestation: 'Canvi Dosimac gestació',
    StartScan: 'Cercar equips DOSIMAC',
    DosimacList: 'Equips DOSIMAC',
    PressToScan: 'Premi',
    DosimacSetup: 'Configuració',
    TestoPresioneAlta: 'Premi el botó per cercar dispositius',
    Instalación_seleccionada: 'Instal·lació seleccionada',
    NoInstalacionSeleccionada: 'No hi ha instal·lació seleccionada',
    BorrarGranja: 'Esborrar granja',
    Deseaborrarlagranja: 'Vol esborrar la granja?',
    Guardar: 'Guardar',
    Cancelar: 'Cancel·lar',
    Aceptar: 'Acceptar',
    NombreGranja: 'Nom de la granja',
    Localidad: 'Localitat',
    Provincia: 'Província',
    NombreWifi: 'Wifi SSID',
    PasswordWifi: 'Contrasenya Wifi',
    No_hay_dispositivos: 'No hi ha dispositius',
    Aviso: 'Avís',
    SearchingDevices: 'Cercant equips...',
    NoSePuedeBorrarGranja: 'No es pot esborrar una granja nova',
    settings: 'Ajustos',
    softwareVersion: 'Versió de programari',
    numeroCoral: 'Número de corral',
    numeroMaquina: 'Número de màquina',
    Enviar: 'Enviar',
    Salir: 'Sortir',
    Informacion: 'Informació',
};