import { Server } from "http";
import { config } from "process";

/* eslint-disable prettier/prettier */
export default {
   username: 'Username',
   password: 'Clave',
   Server: 'Server IP',
   login: 'Login',
   welcome: 'Bienvenido',
   change_language: 'Cambia idioma',
   Tabs: 'Inicio',


   Lista_instalaciones: 'Instalaciones',
   Maintenance: 'Mantenimiento',
   DetallesInstalacion: 'Detalles Instación',
   Grabar: 'Grabar',
   EstadoStore: 'Estado store',
   Nodata: 'No hay datos',
   DosimacRegistration: 'Alta Dosimac',
   NewDmMaternity: 'Nuevo Dosimac maternidad',
   DosimacG: 'Dosimac-G',
   DosimacI: 'Dosimac-I',
   UpdDmMaternity: 'Cambio Dosimac maternidad',
   NewDmGestation: 'Nuevo Dosimac gestación',
   UpdDmGestation: 'Cambio dosimac gestación',
   StartScan: 'Buscar equipos DOSIMAC',
   DosimacList: 'Equipos DOSIMAC',
   PressToScan: 'Pulse',
   DosimacSetup: 'Configuracion',
   TestoPresioneAlta: "Presione sobre el boton para buscar dispositivos DOSIMAC",
   Instalación_seleccionada: "Instalación seleccionada",
   NoInstalacionSeleccionada: "No hay instalación seleccionada",
   BorrarGranja: "Borrar granja",
   Deseaborrarlagranja: "¿Desea borrar la granja?",
   Guardar: 'Guardar',
   Cancelar: 'Cancelar',
   Aceptar: 'Aceptar',
   NombreGranja: 'Farm name',
   Localidad: 'Location',
   Provincia: 'Province',
   NombreWifi: 'Wifi SSID',
   PasswordWifi: 'Wifi password',

   No_hay_dispositivos: 'No hay dispositivos',
   Aviso: 'Aviso',
   SearchingDevices: 'Buscando equipos...',
   NoSePuedeBorrarGranja: "No se puede borrar una granja nueva",
   settings: 'Ajustes',
   softwareVersion: "software Version",
   configuarIntalacion: "Debe configurar al menos una instalación",
   numeroCoral: "Número de corral",
   numeroMaquina: "Número de máquina",
   Enviar: "Enviar",
   Salir: "Salir",
   Informacion: "Información",
   InicioConfiguracion: "Iniciando conexion",
   ConfiguracionWifi: "Configurando.... ",
   ConfiguracionRealizada: "*Configuracion realizada*",
   ErrorConfiguracion: "*Error de configuración*",
   CapturaTagCorral: "Capturar tag de corral",
   CorralTag: "Corral tag",
   versionUint16: "Esta versión del equipo solo soporta corral hasta 65000",
   versionUint32: "Esta versión del equipo soporta corral hasta 4000000000",

   EnvioConfiguracion: "Envio de configuración",
   NumeroCorral: "Número de corral",
   NumeroMaquina: "Número de máquina",
   Corralnovalida: "Corral no válido",
   NumeroMaquinanovalida: "Numero de máquina no válida",

   login_title: "Iniciar sesión",
   login_subtitle: "Introduce tus datos. Es necesario configurar la IP antes de iniciar sesión desde el menú Configuración IP.",
   login_username: "Usuario",
   login_password: "Contraseña",
   login_button: "Entrar",
   login_loading: "Entrando...",
   login_footer: "Panel de control",
   

   login_ipRequiredTitle: "Configuración IP requerida",
   login_ipRequiredMessage: "No has configurado la dirección IP del servidor. Introdúcela para poder iniciar sesión.",
   login_serverIpLabel: "IP del servidor",
   login_cancel: "Cancelar",
   login_accept: "Aceptar",
   login_invalidCredentials: "Usuario o contraseña incorrectos",

   login_configTitle: "Configuración",
   login_errorTitle: "Error de login",
   login_genericErrorTitle: "Error",
   login_networkErrorTitle: "Error de red",
   login_networkErrorMessage: "No se pudo conectar con el servidor.",
   login_noTokenMessage: "El backend no devolvió ningún token.",
   login_missingDataTitle: "Faltan datos",
   login_missingDataMessage: "Introduce usuario y contraseña.",
   login_invalidIpTitle: "IP no válida",
   login_invalidIpMessage: "Introduce una IP o dirección de servidor válida.",
   login_saveIpErrorMessage: "No se pudo guardar la configuración IP.",
   awrStartScan_title: "Configuracion AWR ",
   awrStartScan_description: "Pantalla para escanear lectores Agrident AWR.",
   awrStartScan_button: "Escanear AWR",
   awrBluetoothPermissionMessage: "Activa Bluetooth y acepta el permiso para poder escanear.",


   gestacionConfig_screenTitle: "Configuración Gestación",
   gestacionConfig_chooseOptionTitle: "Elige una opción",
   gestacionConfig_chooseOptionDescription: "Define el flujo antes de empezar con el lector.",

   gestacionConfig_entry: "Entrada",
   gestacionConfig_exit: "Salida",
   gestacionConfig_reading: "Lectura",
   gestacionConfig_search: "Búsqueda",

   gestacionConfig_entryParamsTitle: "Parámetros de entrada",
   gestacionConfig_exitParamsTitle: "Parámetros de salida",
   gestacionConfig_entryParamsDescription: "Selecciona el corral y el comportamiento del flujo.",
   gestacionConfig_exitParamsDescription: "Configura el comportamiento del flujo de salida.",

   gestacionConfig_corralLabel: "Corral",
   gestacionConfig_corralPlaceholder: "Ej: 1",
   gestacionConfig_corralRequired: "Escribe el corral para continuar.",

   gestacionConfig_detectUnknownTitle: "Identificar animales desconocidos",
   gestacionConfig_detectUnknownDescription: "Cuando leas un animal sin identificar, podrás asignarle un ID",

   gestacionConfig_confirmTitle: "Confirmar envío",
   gestacionConfig_confirmDescription: "Pedirá confirmación antes de enviar los registros.",

   gestacionConfig_animalSearchTitle: "Búsqueda de animal",
   gestacionConfig_animalSearchDescription: "Elige si quieres buscar por crotal o por ID.",
   gestacionConfig_searchByCrotal: "Por crotal",
   gestacionConfig_searchById: "Por ID",
   gestacionConfig_manual: "Manual",
   gestacionConfig_withSword: "Con espada",

   gestacionConfig_crotalLabelSearch: "Crotal",
   gestacionConfig_idLabelSearch: "ID",
   gestacionConfig_crotalPlaceholderSearch: "Ej: 982091072397436",
   gestacionConfig_idPlaceholderSearch: "Ej: A13",
   gestacionConfig_crotalRequiredSearch: "Escribe un crotal para continuar.",
   gestacionConfig_idRequiredSearch: "Escribe un ID para continuar.",

   gestacionConfig_searchWithSwordHelp: "Al continuar, se leerá la espada en esta pantalla y se buscará el animal con ese crotal.",

   gestacionConfig_readingSword: "Leyendo espada...",
   gestacionConfig_waitingMatch: "Esperando coincidencia",
   gestacionConfig_searchingAnimal: "Buscando animal...",

   gestacionConfig_readingSwordDescription: "Acerca el crotal al lector para identificar el animal.",
   gestacionConfig_waitingMatchDescription: "Animal localizado. Ahora acerca a la espada el crotal {{crotal}} para confirmar la coincidencia.",
   gestacionConfig_searchingAnimalDescription: "Consultando información del animal en el backend.",

   gestacionConfig_awrDisconnectedTitle: "AWR no conectado",
   gestacionConfig_awrSavedDescription: "Tienes espadas guardadas. Pulsa para seleccionar una.",
   gestacionConfig_awrNotSavedDescription: "No tienes ninguna espada guardada. Pulsa para escanear una.",

   gestacionConfig_scan: "Escanear",
   gestacionConfig_continue: "Continuar",

   gestacionConfig_alerts_error: "Error",
   gestacionConfig_alerts_networkError: "Error de red",
   gestacionConfig_alerts_networkErrorMessage: "No se pudo conectar con el servidor.",
   gestacionConfig_alerts_backendNoValidCrotal: "El backend no devolvió un crotal válido para comparar.",
   gestacionConfig_alerts_awrNotConnected: "AWR no conectado",
   gestacionConfig_alerts_connectSwordBeforeContinue: "Conecta una espada antes de continuar.",
   gestacionConfig_alerts_couldNotStartReading: "No se pudo iniciar la lectura con la espada.",

   gestacionConfig_alerts_missingData: "Falta dato",
   gestacionConfig_alerts_writeCrotalToSearch: "Escribe un crotal para buscar.",
   gestacionConfig_alerts_writeIdToSearch: "Escribe un ID para buscar.",

   gestacionConfig_alerts_notFound: "No encontrado",
   gestacionConfig_alerts_animalNotFoundByCrotal: "No existe ningún animal con ese crotal.",
   gestacionConfig_alerts_animalNotFoundById: "No existe ningún animal con ese ID.",

   gestacionConfig_alerts_warning: "Aviso",
   gestacionConfig_alerts_searchError: "Error en la búsqueda",


   maternidadConfig_screenTitle: "Configuración Maternidad",
   maternidadConfig_chooseOptionTitle: "Elige una opción",
   maternidadConfig_chooseOptionDescription: "Define el flujo antes de empezar con el lector.",
   maternidadConfig_entry: "Entrada",
   maternidadConfig_exit: "Salida",
   maternidadConfig_reading: "Lectura",
   maternidadConfig_search: "Búsqueda",
   maternidadConfig_entryParamsTitle: "Parámetros de entrada",
   maternidadConfig_exitParamsTitle: "Parámetros de salida",
   maternidadConfig_entryParamsDescription: "Selecciona el corral y el comportamiento del flujo.",
   maternidadConfig_exitParamsDescription: "Configura el comportamiento del flujo de salida.",
   maternidadConfig_corralLabel: "Corral",
   maternidadConfig_corralPlaceholder: "Ej: 1",
   maternidadConfig_corralRequired: "Escribe el corral para continuar.",
   maternidadConfig_detectUnknownTitle: "Identificar animales desconocidos",
   maternidadConfig_detectUnknownDescription: "Cuando leas un animal sin identificar, podrás asignarle un ID",
   maternidadConfig_confirmTitle: "Confirmar envío",
   maternidadConfig_confirmDescription: "Pedirá confirmación antes de enviar cada registro.",
   maternidadConfig_animalSearchTitle: "Búsqueda de animal",
   maternidadConfig_animalSearchDescription: "Elige si quieres buscar por crotal o por ID.",
   maternidadConfig_searchByCrotal: "Por crotal",
   maternidadConfig_searchById: "Por ID",
   maternidadConfig_manual: "Manual",
   maternidadConfig_withSword: "Con espada",
   maternidadConfig_crotalLabelSearch: "Crotal",
   maternidadConfig_idLabelSearch: "ID",
   maternidadConfig_crotalPlaceholderSearch: "Ej: 982091072397436",
   maternidadConfig_idPlaceholderSearch: "Ej: A13",
   maternidadConfig_crotalRequiredSearch: "Escribe un crotal para continuar.",
   maternidadConfig_idRequiredSearch: "Escribe un ID para continuar.",
   maternidadConfig_searchWithSwordHelp: "Al pulsar Escanear, se leerá la espada en esta pantalla y se buscará el animal con ese crotal.",
   maternidadConfig_readingSword: "Leyendo espada...",
   maternidadConfig_waitingMatch: "Esperando coincidencia",
   maternidadConfig_searchingAnimal: "Buscando animal...",
   maternidadConfig_readingSwordDescription: "Acerca el crotal al lector para identificar el animal.",
   maternidadConfig_waitingMatchDescription: "Animal localizado. Ahora acerca a la espada el crotal {{crotal}} para confirmar la coincidencia.",
   maternidadConfig_searchingAnimalDescription: "Consultando información del animal en el backend.",
   maternidadConfig_awrDisconnectedTitle: "AWR no conectado",
   maternidadConfig_awrSavedDescription: "Tienes AWR guardadas. Pulsa para seleccionar una.",
   maternidadConfig_awrNotSavedDescription: "No tienes ninguna AWR guardada. Pulsa para escanear una.",
   maternidadConfig_scan: "Escanear",
   maternidadConfig_continue: "Continuar",
   maternidadConfig_alert_error: "Error",
   maternidadConfig_alert_invalidBackendCrotal: "El backend no devolvió un crotal válido para comparar.",
   maternidadConfig_alert_awrNotConnected: "AWR no conectado",
   maternidadConfig_alert_connectSwordBeforeContinue: "Conecta una espada antes de continuar.",
   maternidadConfig_alert_couldNotStartReading: "No se pudo iniciar la lectura con la espada.",
   maternidadConfig_alert_missingData: "Falta dato",
   maternidadConfig_alert_writeCrotalToSearch: "Escribe un crotal para buscar.",
   maternidadConfig_alert_writeIdToSearch: "Escribe un ID para buscar.",
   maternidadConfig_alert_notFound: "No encontrado",
   maternidadConfig_alert_noAnimalWithCrotal: "No existe ningún animal con ese crotal.",
   maternidadConfig_alert_noAnimalWithId: "No existe ningún animal con ese ID.",
   maternidadConfig_alert_warning: "Aviso",
   maternidadConfig_alert_searchError: "Error en la búsqueda",
   maternidadConfig_alert_networkError: "Error de red",
   maternidadConfig_alert_networkErrorMessage: "No se pudo conectar con el servidor.",

   gestationReader_screenTitle: "Lector Gestación",

   gestationReader_animalInfoTitle: "Información del animal",
   gestationReader_animalInfoDescription: "Datos localizados en la búsqueda.",
   gestationReader_animalCardTitle: "Ficha Animal",
   gestationReader_animalIdLabel: "ID",
   gestationReader_animalCrotalLabel: "Crotal",
   gestationReader_fieldCorral: "Corral",
   gestationReader_fieldHouse: "Nave",
   gestationReader_fieldState: "Estado",
   gestationReader_fieldBodyCondition: "Condición corporal",
   gestationReader_fieldCycle: "Ciclo",
   gestationReader_fieldSystemEntryDate: "Entrada en sistema",
   gestationReader_newSearch: "Nueva búsqueda",

   gestationReader_summaryTitle: "Resumen",
   gestationReader_summaryDescription: "Parámetros elegidos en Configuración",
   gestationReader_mode: "Modo",
   gestationReader_corral: "Corral",
   gestationReader_modeEntry: "Entrada",
   gestationReader_modeExit: "Salida",
   gestationReader_modeReading: "Lectura",
   gestationReader_modeSearch: "Búsqueda",
   gestationReader_detectUnknownTitle: "Identificar animales desconocidos",
   gestationReader_detectUnknownDescription: "Cuando salga un animal sin ID, ofrecer asignarle un ID.",
   gestationReader_confirmSendTitle: "Confirmar envío",
   gestationReader_confirmSendDescription: "Pedirá confirmación antes de enviar cada registro.",
   gestationReader_changeSettings: "Cambiar configuración",

   gestationReader_currentReadingTitle: "Lectura actual",
   gestationReader_currentReadingDescription: "El crotal detectado y el ID asociado aparecerán aquí.",
   gestationReader_awrDisconnected: "AWR no conectado",
   gestationReader_readCrotal: "Crotal leído",
   gestationReader_readId: "ID",
   gestationReader_animalWithoutAssignedId: "Animal sin ID asignado",
   gestationReader_unknownAnimal: "Animal desconocido",

   gestationReader_animalWithoutIdTitle: "Animal sin ID",
   gestationReader_animalWithoutIdDescription: "Escribe un ID manual para actualizar el crotal leído.",
   gestationReader_newIdLabel: "Nuevo ID",
   gestationReader_newIdPlaceholder: "Ej: A13",
   gestationReader_updateId: "Actualizar ID",
   gestationReader_updatingId: "Actualizando...",

   gestationReader_sentRecordsTitle: "Registros enviados",
   gestationReader_noRecords: "No hay registros.",
   gestationReader_tableHeaderCorral: "Corral",
   gestationReader_tableHeaderId: "ID",
   gestationReader_tableHeaderCrotal: "Crotal",

   gestationReader_buttonAutoReading: "Lectura automática activa",
   gestationReader_buttonAutoSending: "Envío automático activo",
   gestationReader_buttonSending: "Enviando...",
   gestationReader_buttonSend: "Enviar",

   gestationReader_alertError: "Error",
   gestationReader_alertWarning: "Aviso",
   gestationReader_alertNetworkError: "Error de red",

   gestationReader_alertMissingCrotalTitle: "Falta crotal",
   gestationReader_alertMissingCrotalMessage: "Acerca el crotal al lector antes de enviar.",
   gestationReader_alertInvalidCrotalTitle: "Crotal inválido",
   gestationReader_alertInvalidCrotalMessage: "El crotal debe ser numérico.",
   gestationReader_alertReadErrorTitle: "Error en lectura",
   gestationReader_alertNetworkErrorMessage: "No se pudo conectar con el servidor.",

   gestationReader_alertMissingCorralTitle: "Falta corral",
   gestationReader_alertMissingCorralMessage: "Escribe el corral antes de enviar.",
   gestationReader_alertInvalidCorralTitle: "Corral inválido",
   gestationReader_alertInvalidCorralMessage: "El corral debe ser un número.",
   gestationReader_alertSendErrorTitle: "Error al enviar",
   gestationReader_alertNoIpConfigured: "No hay IP configurada.",

   gestationReader_alertMissingIdTitle: "Falta ID",
   gestationReader_alertMissingIdMessage: "Escribe el nuevo ID antes de actualizar.",
   gestationReader_alertMissingAssociatedCrotalTitle: "Falta crotal",
   gestationReader_alertMissingAssociatedCrotalMessage: "No hay crotal asociado para actualizar.",
   gestationReader_alertInvalidAssociatedCrotalTitle: "Crotal inválido",
   gestationReader_alertInvalidAssociatedCrotalMessage: "El crotal asociado no es válido.",
   gestationReader_alertUpdateIdErrorTitle: "Error al actualizar ID",

   maternityReader_screenTitle: "Lector Maternidad",
   maternityReader_alertMissingCrotalTitle: "Falta crotal",
   maternityReader_alertMissingCrotalMessage: "Acerca el crotal al lector antes de enviar.",
   maternityReader_alertInvalidCrotalTitle: "Crotal inválido",
   maternityReader_alertInvalidCrotalMessage: "El crotal debe ser numérico.",
   maternityReader_alertReadErrorTitle: "Error en lectura",
   maternityReader_alertNetworkError: "Error de red",
   maternityReader_alertNetworkErrorMessage: "No se pudo conectar con el servidor.",
   maternityReader_alertMissingCorralTitle: "Falta corral",
   maternityReader_alertMissingCorralMessage: "Escribe el corral antes de enviar.",
   maternityReader_alertInvalidCorralTitle: "Corral inválido",
   maternityReader_alertInvalidCorralMessage: "El corral debe ser un número (ej: 8).",
   maternityReader_alertError: "Error",
   maternityReader_alertNoIpConfigured: "No hay IP configurada.",
   maternityReader_alertWarning: "Aviso",
   maternityReader_alertSendErrorTitle: "Error al enviar",
   maternityReader_alertMissingIdTitle: "Falta ID",
   maternityReader_alertMissingIdMessage: "Escribe el nuevo ID antes de actualizar.",
   maternityReader_alertMissingAssociatedCrotalTitle: "Falta crotal",
   maternityReader_alertMissingAssociatedCrotalMessage: "No hay crotal asociado para actualizar.",
   maternityReader_alertInvalidAssociatedCrotalTitle: "Crotal inválido",
   maternityReader_alertInvalidAssociatedCrotalMessage: "El crotal asociado no es válido.",
   maternityReader_alertUpdateIdErrorTitle: "Error al actualizar ID",
   maternityReader_animalInfoTitle: "Información del animal",
   maternityReader_animalInfoDescription: "Datos localizados en la búsqueda.",
   maternityReader_animalCardTitle: "Ficha Animal",
   maternityReader_animalIdLabel: "ID",
   maternityReader_animalCrotalLabel: "Crotal",
   maternityReader_fieldCorral: "Corral",
   maternityReader_fieldHouse: "Nave",
   maternityReader_fieldState: "Estado",
   maternityReader_fieldBodyCondition: "Condición corporal",
   maternityReader_fieldCycle: "Ciclo",
   maternityReader_fieldSystemEntryDate: "Entrada en sistema",
   maternityReader_newSearch: "Nueva búsqueda",
   maternityReader_summaryTitle: "Resumen",
   maternityReader_summaryDescription: "Parámetros elegidos en Configuración",
   maternityReader_mode: "Modo",
   maternityReader_modeEntry: "Entrada",
   maternityReader_modeExit: "Salida",
   maternityReader_modeReading: "Lectura",
   maternityReader_corral: "Corral",
   maternityReader_detectUnknownTitle: "Identificar animales desconocidos",
   maternityReader_detectUnknownDescription: "Cuando salga un animal sin ID, ofrecer asignarle un ID.",
   maternityReader_confirmSendTitle: "Confirmar envío",
   maternityReader_confirmSendDescription: "Pedirá confirmación antes de enviar cada registro.",
   maternityReader_changeSettings: "Cambiar configuración",
   maternityReader_currentReadingTitle: "Lectura actual",
   maternityReader_currentReadingDescription: "El crotal detectado aparecerá aquí.",
   maternityReader_awrDisconnected: "AWR no conectado",
   maternityReader_readCrotal: "Crotal leído",
   maternityReader_readId: "ID",
   maternityReader_animalWithoutAssignedId: "Animal sin ID asignado",
   maternityReader_unknownAnimal: "Animal desconocido",
   maternityReader_animalWithoutIdTitle: "Animal sin ID",
   maternityReader_animalWithoutIdDescription: "Escribe un ID manual para actualizar el crotal leído.",
   maternityReader_newIdLabel: "Nuevo ID",
   maternityReader_newIdPlaceholder: "Ej: A13",
   maternityReader_updatingId: "Actualizando...",
   maternityReader_updateId: "Actualizar ID",
   maternityReader_sentRecordsTitle: "Registros enviados",
   maternityReader_tableHeaderCorral: "Corral",
   maternityReader_tableHeaderId: "ID",
   maternityReader_tableHeaderCrotal: "Crotal",
   maternityReader_noRecords: "No hay registros.",
   maternityReader_buttonAutoReading: "Lectura automática activa",
   maternityReader_buttonAutoSending: "Envío automático activo",
   maternityReader_buttonSending: "Enviando...",
   maternityReader_buttonSend: "Enviar",


   awrScanResults_title: "AWR – Resultados de escaneo",
   awrScanResults_searching: "Buscando AWR…",
   awrScanResults_warningTitle: "Aviso",
   awrScanResults_noDevicesNearby: "No se han encontrado AWR cercanos.",
   awrScanResults_connecting: "Conectando…",
   awrScanResults_connectErrorFallback: "No se pudo conectar",
   awrScanResults_connectedTitle: "Conectado",
   awrScanResults_connectedMessage: "Conexión establecida con {{device}}.",
   awrScanResults_genericDevice: "el dispositivo",

   awrSavedList_title: "AWR escaneados",
   awrSavedList_connecting: "Conectando…",
   awrSavedList_empty: "No hay AWR guardados. Escanea uno desde “Configuración AWR”.",
   awrSavedList_connected: "Conectado",
   awrSavedList_disconnected: "Desconectado",
   awrSavedList_renameAccessibility: "Renombrar",
   awrSavedList_deleteAccessibility: "Eliminar",
   awrSavedList_renameTitle: "Renombrar AWR",
   awrSavedList_nameLabel: "Nombre",
   awrSavedList_deleteTitle: "Eliminar AWR guardado",
   awrSavedList_deleteMessage: "¿Seguro que quieres eliminar este AWR de la lista?",
   awrSavedList_deleteAction: "Eliminar",

   ipConfig_title: "Configuración IP",
   ipConfig_cardTitle: "Servidor CTIFEED",
   ipConfig_cardDescription: "Introduce la IP del servidor donde se abrirá el portal.",
   ipConfig_inputLabel: "IP (solo la IP)",
   ipConfig_saved: "Guardado",
   ipConfig_alertSuccessTitle: "Correcto",
   ipConfig_alertSuccessMessage: "IP correcta",
   ipConfig_alertWarningTitle: "Aviso",
   ipConfig_alertServerNotUpdated: "Servidor no actualizado",
   ipConfig_alertErrorTitle: "Error",
   ipConfig_alertInvalidIp: "IP no válida",

   portal_preparing: "Preparando portal...",
   portal_noSessionToken: "No hay token de sesión. Inicia sesión de nuevo.",
   portal_noIpConfigured: "No hay IP configurada. Configura primero la IP del servidor.",
   portal_prepareUrlError: "No se pudo preparar la URL del portal.",
   portal_loadError: "No se pudo cargar el portal.",
   portal_checkingConnection: "Comprobando conexión con el portal...",
   portal_noConnectionTitle: "No hay conexión",
   portal_connectionTimeout: "No se ha podido conectar con el portal. Verifica que esté conectada la red correcta.",
   portal_connectionError: "No se ha podido conectar con el portal. Verifica la red o la IP configurada.",
   portal_httpError: "No se ha podido abrir el portal. Error HTTP {{status}}.",
   portal_retry: "Reintentar",
   portal_loading: "Cargando portal...",


   AltaDispositivos: "Alta dispositivos",
   LectorMaternidad: "Lector Maternidad",
   LectorGestacion: "Lector Gestación",
   ConfiguracionIP: "Configuración IP",
   ConfiguracionAWR: "Configuración AWR",
   DarDeAltaAWR: "Dar de Alta AWR",
   AWREscaneados: "AWR escaneados",
   CerrarSesion: "Cerrar sesión",


   Config_lastReadMismatchTitle: "El animal leído no coincide con la búsqueda",
   Config_lastReadMismatchCrotal: "Crotal",
   Config_lastReadMismatchId: "ID",

   animalState: {
      gestation: "Gestación",
      maternity: "Maternidad",
      out_of_gestation: "Fuera de gestación",
      out_of_maternity: "Fuera de maternidad"
   },

   Reader_readingTitle: "Lectura Crotales",
  Reader_labelId: "ID",
  Reader_labelCrotal: "Crotal",
  Reader_labelCorral: "Corral",
  Reader_labelHouse: "Nave",
  Reader_labelState: "Estado",
  Reader_autoReadingBadge: "Lectura automática"

};