# Usa el repositorio oficial de CocoaPods
source 'https://github.com/CocoaPods/Specs.git'

ENV['RCT_NEW_ARCH_ENABLED'] = '0'

# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

# Configuración de Flipper (debugging)
#flipper_config = ENV['NO_FLIPPER'] == "1" ? FlipperConfiguration.disabled : FlipperConfiguration.enabled
#flipper_config = FlipperConfiguration.disabled


# Enlazado dinámico/estático
linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
 # use_frameworks! :linkage => linkage.to_sym
 use_frameworks! :linkage => :static

end

target 'gptrnbluetooth' do
  config = use_native_modules!
  


  # ⚠️ IMPORTANTE:
  # Aquí ya NO añadimos boost manualmente.
  # Lo gestionará React Native, pero debes parchear
  # node_modules/react-native/third-party-podspecs/boost.podspec
  # cambiando la URL a:
  # spec.source = { :http => "https://archives.boost.io/release/1.76.0/source/boost_1_76_0.tar.bz2" }

  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'


  target 'gptrnbluetoothTests' do
    inherit! :complete
    
    # Pods for testing
  end

  post_install do |installer|
  react_native_post_install(
    installer,
    config[:reactNativePath],
    :mac_catalyst_enabled => false
  )
  # Fuerza el iOS Deployment Target en todos los pods
  installer.pods_project.targets.each do |t|
    t.build_configurations.each do |cfg|
cfg.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = min_ios_version_supported
    end
  end
end
end
