export default {
  username: '사용자',
  password: '비밀번호',
  login: '로그인',
  welcome: '환영합니다',
  change_language: '언어 변경',
  Tabs: '홈',

  Lista_instalaciones: '설치',
  Maintenance: '유지보수',
  DetallesInstalacion: '설치 세부 정보',
  Grabar: '저장',
  EstadoStore: '스토어 상태',
  Nodata: '데이터 없음',
  DosimacRegistration: ' 등록',
  NewDmMaternity: '새 Dosimac 모성',
  DosimacG: 'Dosimac-G',
  DosimacI: 'Dosimac-I',
  UpdDmMaternity: 'Dosimac 모성 변경',
  NewDmGestation: '새 Dosimac 임신',
  UpdDmGestation: 'Dosimac 임신 변경',
  StartScan: 'DOSIMAC 장치 검색',
  DosimacList: 'DOSIMAC 장치',
  PressToScan: '누르기',
  DosimacSetup: '구성',
  TestoPresioneAlta: '장치를 검색하려면 버튼을 누르세요',
  Instalación_seleccionada: '선택한 설치',
  NoInstalacionSeleccionada: '선택된 설치 없음',
  BorrarGranja: '농장 삭제',
  Deseaborrarlagranja: '농장을 삭제하시겠습니까?',
  Guardar: '저장',
  Cancelar: '취소',
  Aceptar: '확인',
  NombreGranja: '농장 이름',
  Localidad: '위치',
  Provincia: '주/도',
  NombreWifi: 'Wifi SSID',
  PasswordWifi: 'Wifi 비밀번호',
  No_hay_dispositivos: '장치 없음',
  Aviso: '알림',
  SearchingDevices: '장치 검색 중...',
  NoSePuedeBorrarGranja: '새 농장은 삭제할 수 없습니다',
  settings: '설정',
  softwareVersion: '소프트웨어 버전',
  numeroCoral: '우리 번호',
  numeroMaquina: '기계 번호',
  Enviar: '보내기',
  Salir: '나가기',
  Informacion: '정보',
  InicioConfiguracion: "연결 시작",
  ConfiguracionWifi: "구성 중...",
  ConfiguracionRealizada: "*구성이 완료되었습니다*",
  ErrorConfiguracion: "*구성 오류*",
  CapturaTagCorral: "우리 태그 캡처",
  CorralTag: "우리 태그",
  versionUint16: "이 기기 버전은 우리 번호를 최대 65000까지만 지원합니다",
  versionUint32: "이 기기 버전은 우리 번호를 최대 4000000000까지 지원합니다",
  EnvioConfiguracion: "구성 전송",
  NumeroCorral: "우리 번호",
  NumeroMaquina: "기계 번호",
  Corralnovalida: "유효하지 않은 우리 번호",
  NumeroMaquinanovalida: "유효하지 않은 기계 번호",
  configuarIntalacion: "이 기능을 사용하려면 설치를 구성해야 합니다",

  login_title: "로그인",
  login_subtitle: "정보를 입력하세요. 로그인하기 전에 IP 설정 메뉴에서 IP를 구성해야 합니다.",
  login_username: "사용자",
  login_password: "비밀번호",
  login_button: "로그인",
  login_loading: "로그인 중...",
  login_footer: "제어판",
  login_invalidCredentials: "사용자 이름 또는 비밀번호가 올바르지 않습니다",

  login_ipRequiredTitle: "IP 설정 필요",
  login_ipRequiredMessage: "서버 IP 주소가 설정되지 않았습니다. 로그인하려면 입력하세요.",
  login_serverIpLabel: "서버 IP",
  login_cancel: "취소",
  login_accept: "확인",

  login_configTitle: "설정",
  login_errorTitle: "로그인 오류",
  login_genericErrorTitle: "오류",
  login_networkErrorTitle: "네트워크 오류",
  login_networkErrorMessage: "서버에 연결할 수 없습니다.",
  login_noTokenMessage: "백엔드가 토큰을 반환하지 않았습니다.",
  login_missingDataTitle: "입력 누락",
  login_missingDataMessage: "사용자명과 비밀번호를 입력하세요.",
  login_invalidIpTitle: "잘못된 IP",
  login_invalidIpMessage: "유효한 IP 또는 서버 주소를 입력하세요.",
  login_saveIpErrorMessage: "IP 설정을 저장할 수 없습니다.",
  awrStartScan_title: "AWR 설정",
  awrStartScan_description: "Agrident AWR 리더기를 스캔하는 화면입니다.",
  awrStartScan_button: "AWR 스캔",

  gestacionConfig_entry: "입력",
  gestacionConfig_exit: "출력",
  gestacionConfig_reading: "읽기",
  gestacionConfig_search: "검색",

  gestacionConfig_entryParamsTitle: "입력 파라미터",
  gestacionConfig_exitParamsTitle: "출력 파라미터",
  gestacionConfig_entryParamsDescription: "우리 번호와 흐름 동작을 선택하세요.",
  gestacionConfig_exitParamsDescription: "출력 흐름 동작을 설정하세요.",

  gestacionConfig_corralLabel: "우리",
  gestacionConfig_corralPlaceholder: "예: 1",
  gestacionConfig_corralRequired: "계속하려면 우리 번호를 입력하세요.",

  gestacionConfig_detectUnknownTitle: "미확인 동물 식별",
  gestacionConfig_detectUnknownDescription: "식별되지 않은 동물을 읽으면 ID를 할당할 수 있습니다",

  gestacionConfig_confirmTitle: "전송 확인",
  gestacionConfig_confirmDescription: "기록을 전송하기 전에 확인을 요청합니다.",

  gestacionConfig_animalSearchTitle: "동물 검색",
  gestacionConfig_animalSearchDescription: "귀표 또는 ID로 검색할지 선택하세요.",
  gestacionConfig_searchByCrotal: "귀표로",
  gestacionConfig_searchById: "ID로",
  gestacionConfig_manual: "수동",
  gestacionConfig_withSword: "리더기로",

  gestacionConfig_crotalLabelSearch: "귀표",
  gestacionConfig_idLabelSearch: "ID",
  gestacionConfig_crotalPlaceholderSearch: "예: 982091072397436",
  gestacionConfig_idPlaceholderSearch: "예: A13",
  gestacionConfig_crotalRequiredSearch: "계속하려면 귀표를 입력하세요.",
  gestacionConfig_idRequiredSearch: "계속하려면 ID를 입력하세요.",

  gestacionConfig_searchWithSwordHelp: "계속하면 이 화면에서 리더기로 읽고 해당 귀표로 동물을 검색합니다.",

  gestacionConfig_readingSword: "리더기 읽는 중...",
  gestacionConfig_waitingMatch: "일치 대기 중",
  gestacionConfig_searchingAnimal: "동물 검색 중...",

  gestacionConfig_readingSwordDescription: "동물을 식별하려면 귀표를 리더기에 가까이 대세요.",
  gestacionConfig_waitingMatchDescription: "동물을 찾았습니다. 이제 일치를 확인하려면 귀표 {{crotal}}를 리더기에 가까이 대세요.",
  gestacionConfig_searchingAnimalDescription: "백엔드에서 동물 정보를 조회하는 중입니다.",

  gestacionConfig_awrDisconnectedTitle: "AWR 연결 안 됨",
  gestacionConfig_awrSavedDescription: "저장된 리더기가 있습니다. 선택하려면 누르세요.",
  gestacionConfig_awrNotSavedDescription: "저장된 리더기가 없습니다. 스캔하려면 누르세요.",

  gestacionConfig_scan: "스캔",
  gestacionConfig_continue: "계속",

  gestacionConfig_alerts_error: "오류",
  gestacionConfig_alerts_networkError: "네트워크 오류",
  gestacionConfig_alerts_networkErrorMessage: "서버에 연결할 수 없습니다.",
  gestacionConfig_alerts_backendNoValidCrotal: "백엔드가 비교할 수 있는 유효한 귀표를 반환하지 않았습니다.",
  gestacionConfig_alerts_awrNotConnected: "AWR 연결 안 됨",
  gestacionConfig_alerts_connectSwordBeforeContinue: "계속하기 전에 리더기를 연결하세요.",
  gestacionConfig_alerts_couldNotStartReading: "리더기로 읽기를 시작할 수 없습니다.",

  gestacionConfig_alerts_missingData: "데이터 누락",
  gestacionConfig_alerts_writeCrotalToSearch: "검색할 귀표를 입력하세요.",
  gestacionConfig_alerts_writeIdToSearch: "검색할 ID를 입력하세요.",

  gestacionConfig_alerts_notFound: "찾을 수 없음",
  gestacionConfig_alerts_animalNotFoundByCrotal: "해당 귀표를 가진 동물이 없습니다.",
  gestacionConfig_alerts_animalNotFoundById: "해당 ID를 가진 동물이 없습니다.",

  gestacionConfig_alerts_warning: "알림",
  gestacionConfig_alerts_searchError: "검색 오류",

  maternidadConfig_screenTitle: "모성 설정",
  maternidadConfig_chooseOptionTitle: "옵션 선택",
  maternidadConfig_chooseOptionDescription: "리더를 시작하기 전에 흐름을 설정하세요.",
  maternidadConfig_entry: "입장",
  maternidadConfig_exit: "퇴장",
  maternidadConfig_reading: "읽기",
  maternidadConfig_search: "검색",
  maternidadConfig_entryParamsTitle: "입장 파라미터",
  maternidadConfig_exitParamsTitle: "퇴장 파라미터",
  maternidadConfig_entryParamsDescription: "우리와 흐름 동작을 선택하세요.",
  maternidadConfig_exitParamsDescription: "퇴장 흐름 동작을 설정하세요.",
  maternidadConfig_corralLabel: "우리",
  maternidadConfig_corralPlaceholder: "예: 1",
  maternidadConfig_corralRequired: "계속하려면 우리를 입력하세요.",
  maternidadConfig_detectUnknownTitle: "미확인 동물 식별",
  maternidadConfig_detectUnknownDescription: "식별되지 않은 동물을 읽으면 ID를 할당할 수 있습니다",
  maternidadConfig_confirmTitle: "전송 확인",
  maternidadConfig_confirmDescription: "각 기록을 전송하기 전에 확인을 요청합니다.",
  maternidadConfig_animalSearchTitle: "동물 검색",
  maternidadConfig_animalSearchDescription: "귀표 또는 ID로 검색할지 선택하세요.",
  maternidadConfig_searchByCrotal: "귀표로",
  maternidadConfig_searchById: "ID로",
  maternidadConfig_manual: "수동",
  maternidadConfig_withSword: "리더로",
  maternidadConfig_crotalLabelSearch: "귀표",
  maternidadConfig_idLabelSearch: "ID",
  maternidadConfig_crotalPlaceholderSearch: "예: 982091072397436",
  maternidadConfig_idPlaceholderSearch: "예: A13",
  maternidadConfig_crotalRequiredSearch: "계속하려면 귀표를 입력하세요.",
  maternidadConfig_idRequiredSearch: "계속하려면 ID를 입력하세요.",
  maternidadConfig_searchWithSwordHelp: "스캔을 누르면 이 화면에서 리더를 읽고 해당 귀표로 동물을 검색합니다.",
  maternidadConfig_readingSword: "리더 읽는 중...",
  maternidadConfig_waitingMatch: "일치 대기 중",
  maternidadConfig_searchingAnimal: "동물 검색 중...",
  maternidadConfig_readingSwordDescription: "동물을 식별하려면 귀표를 리더 가까이에 대세요.",
  maternidadConfig_waitingMatchDescription: "동물을 찾았습니다. 이제 일치를 확인하려면 귀표 {{crotal}}를 리더에 가까이 대세요.",
  maternidadConfig_searchingAnimalDescription: "백엔드에서 동물 정보를 조회하는 중입니다.",
  maternidadConfig_awrDisconnectedTitle: "AWR 연결 안 됨",
  maternidadConfig_awrSavedDescription: "저장된 AWR이 있습니다. 선택하려면 누르세요.",
  maternidadConfig_awrNotSavedDescription: "저장된 AWR이 없습니다. 스캔하려면 누르세요.",
  maternidadConfig_scan: "스캔",
  maternidadConfig_continue: "계속",
  maternidadConfig_alert_error: "오류",
  maternidadConfig_alert_invalidBackendCrotal: "백엔드가 비교할 유효한 귀표를 반환하지 않았습니다.",
  maternidadConfig_alert_awrNotConnected: "AWR 연결 안 됨",
  maternidadConfig_alert_connectSwordBeforeContinue: "계속하기 전에 리더를 연결하세요.",
  maternidadConfig_alert_couldNotStartReading: "리더 읽기를 시작할 수 없습니다.",
  maternidadConfig_alert_missingData: "데이터 누락",
  maternidadConfig_alert_writeCrotalToSearch: "검색할 귀표를 입력하세요.",
  maternidadConfig_alert_writeIdToSearch: "검색할 ID를 입력하세요.",
  maternidadConfig_alert_notFound: "찾을 수 없음",
  maternidadConfig_alert_noAnimalWithCrotal: "해당 귀표를 가진 동물이 없습니다.",
  maternidadConfig_alert_noAnimalWithId: "해당 ID를 가진 동물이 없습니다.",
  maternidadConfig_alert_warning: "알림",
  maternidadConfig_alert_searchError: "검색 오류",
  maternidadConfig_alert_networkError: "네트워크 오류",
  maternidadConfig_alert_networkErrorMessage: "서버에 연결할 수 없습니다.",

  gestationReader_screenTitle: "임신 리더기",
  gestationReader_animalInfoTitle: "동물 정보",
  gestationReader_animalInfoDescription: "검색에서 찾은 데이터입니다.",
  gestationReader_animalCardTitle: "동물 카드",
  gestationReader_animalIdLabel: "ID",
  gestationReader_animalCrotalLabel: "귀표",
  gestationReader_fieldCorral: "우리",
  gestationReader_fieldHouse: "동",
  gestationReader_fieldState: "상태",
  gestationReader_fieldBodyCondition: "체형 상태",
  gestationReader_fieldCycle: "주기",
  gestationReader_fieldSystemEntryDate: "시스템 등록일",
  gestationReader_newSearch: "새 검색",
  gestationReader_summaryTitle: "요약",
  gestationReader_summaryDescription: "설정에서 선택한 매개변수",
  gestationReader_mode: "모드",
  gestationReader_corral: "우리",
  gestationReader_modeEntry: "입장",
  gestationReader_modeExit: "퇴장",
  gestationReader_modeReading: "읽기",
  gestationReader_modeSearch: "검색",
  gestationReader_detectUnknownTitle: "알 수 없는 동물 식별",
  gestationReader_detectUnknownDescription: "ID가 없는 동물이 나타나면 ID를 할당할 수 있도록 합니다.",
  gestationReader_confirmSendTitle: "전송 확인",
  gestationReader_confirmSendDescription: "각 기록을 보내기 전에 확인을 요청합니다.",
  gestationReader_changeSettings: "설정 변경",
  gestationReader_currentReadingTitle: "현재 읽기",
  gestationReader_currentReadingDescription: "감지된 귀표와 연결된 ID가 여기에 표시됩니다.",
  gestationReader_awrDisconnected: "AWR 연결 안 됨",
  gestationReader_readCrotal: "읽은 귀표",
  gestationReader_readId: "ID",
  gestationReader_animalWithoutAssignedId: "ID가 할당되지 않은 동물",
  gestationReader_unknownAnimal: "알 수 없는 동물",
  gestationReader_animalWithoutIdTitle: "ID 없는 동물",
  gestationReader_animalWithoutIdDescription: "읽은 귀표를 업데이트하려면 수동 ID를 입력하세요.",
  gestationReader_newIdLabel: "새 ID",
  gestationReader_newIdPlaceholder: "예: A13",
  gestationReader_updateId: "ID 업데이트",
  gestationReader_updatingId: "업데이트 중...",
  gestationReader_sentRecordsTitle: "전송된 기록",
  gestationReader_noRecords: "기록이 없습니다.",
  gestationReader_tableHeaderCorral: "우리",
  gestationReader_tableHeaderId: "ID",
  gestationReader_tableHeaderCrotal: "귀표",
  gestationReader_buttonAutoReading: "자동 읽기 활성화",
  gestationReader_buttonAutoSending: "자동 전송 활성화",
  gestationReader_buttonSending: "전송 중...",
  gestationReader_buttonSend: "보내기",
  gestationReader_alertError: "오류",
  gestationReader_alertWarning: "알림",
  gestationReader_alertNetworkError: "네트워크 오류",
  gestationReader_alertMissingCrotalTitle: "귀표 누락",
  gestationReader_alertMissingCrotalMessage: "전송하기 전에 귀표를 리더기에 가까이 가져가세요.",
  gestationReader_alertInvalidCrotalTitle: "유효하지 않은 귀표",
  gestationReader_alertInvalidCrotalMessage: "귀표는 숫자여야 합니다.",
  gestationReader_alertReadErrorTitle: "읽기 오류",
  gestationReader_alertNetworkErrorMessage: "서버에 연결할 수 없습니다.",
  gestationReader_alertMissingCorralTitle: "우리 누락",
  gestationReader_alertMissingCorralMessage: "전송하기 전에 우리를 입력하세요.",
  gestationReader_alertInvalidCorralTitle: "유효하지 않은 우리",
  gestationReader_alertInvalidCorralMessage: "우리는 숫자여야 합니다.",
  gestationReader_alertSendErrorTitle: "전송 오류",
  gestationReader_alertNoIpConfigured: "설정된 IP가 없습니다.",
  gestationReader_alertMissingIdTitle: "ID 누락",
  gestationReader_alertMissingIdMessage: "업데이트 전에 새 ID를 입력하세요.",
  gestationReader_alertMissingAssociatedCrotalTitle: "귀표 누락",
  gestationReader_alertMissingAssociatedCrotalMessage: "업데이트할 연결된 귀표가 없습니다.",
  gestationReader_alertInvalidAssociatedCrotalTitle: "유효하지 않은 귀표",
  gestationReader_alertInvalidAssociatedCrotalMessage: "연결된 귀표가 유효하지 않습니다.",
  gestationReader_alertUpdateIdErrorTitle: "ID 업데이트 오류",
  gestationReader_readerMode: "리더",
gestationReader_keyboardMode: "키보드",

gestationReader_keyboardEntryTitle: "키보드 입고",
gestationReader_keyboardExitTitle: "키보드 출고",
gestationReader_keyboardDescription: "휴대폰 키보드로 데이터를 직접 입력하세요.",
gestationReader_keyboardId: "ID",
gestationReader_keyboardCrotal: "이표",
gestationReader_keyboardIdLabel: "동물 ID",
gestationReader_keyboardCrotalLabel: "이표",
gestationReader_keyboardIdPlaceholder: "ID 입력",
gestationReader_keyboardCrotalPlaceholder: "이표 입력",
gestationReader_keyboardAdd: "추가",
gestationReader_keyboardAdding: "추가 중...",

gestationReader_pendingRecordsTitle: "전송되지 않은 기록",
gestationReader_buttonSendingBatch: "일괄 전송 중...",
gestationReader_buttonSendBatch: "일괄 전송",
gestationReader_buttonSendBatchCount: "일괄 전송 ({{count}})",

gestationReader_noPendingRecordsTitle: "기록 없음",
gestationReader_noPendingRecordsText: "전송 대기 중인 기록이 없습니다.",
gestationReader_batchSentTitle: "일괄 전송됨",
gestationReader_batchSentText: "{{count}}개의 기록이 성공적으로 전송되었습니다.",
gestationReader_batchWithErrorsTitle: "오류가 있는 일괄 전송",

gestationReader_recordSentTitle: "기록 전송됨",
gestationReader_recordSentText: "이동이 성공적으로 전송되었습니다.",

gestationReader_invalidAnimalId: "동물 ID가 올바르지 않습니다.",
gestationReader_invalidPenRecord: "기록의 우리가 올바르지 않습니다.",
gestationReader_invalidCrotalRecord: "기록의 이표가 올바르지 않습니다.",
gestationReader_duplicateIdPending: "ID {{id}}는 이미 전송되지 않은 기록 표에 있습니다.",
gestationReader_duplicateCrotalPending: "이표 {{crotal}}는 이미 전송되지 않은 기록 표에 있습니다.",
gestationReader_keyboardMissingId: "동물 ID를 입력하세요.",
gestationReader_keyboardMissingCrotal: "동물 이표를 입력하세요.",
gestationReader_keyboardMissingPen: "동물을 추가하기 전에 유효한 우리를 선택하세요.",
gestationReader_noAnimalById: "ID {{id}}에 해당하는 동물이 없습니다.",
gestationReader_noAnimalByCrotal: "이표 {{crotal}}에 해당하는 동물이 없습니다.",
gestationReader_addAnimalError: "동물을 추가할 수 없습니다.",

gestationReader_pendingAnimalHint: "읽은 동물이 여기에 표시됩니다.",

gestationReader_changePenTitle: "우리 변경",
gestationReader_changePenDescription: "새 입고 우리를 입력하세요.",
gestationReader_newPenLabel: "새 우리",
gestationReader_newPenPlaceholder: "예: 1",
gestationReader_cancel: "취소",
gestationReader_save: "저장",
gestationReader_accept: "확인",
gestationReader_sentHistoryTitle: "전송 기록",

  maternityReader_screenTitle: "분만 리더기",
  maternityReader_alertMissingCrotalTitle: "이표가 없습니다",
  maternityReader_alertMissingCrotalMessage: "전송하기 전에 이표를 리더기에 가까이 대세요.",
  maternityReader_alertInvalidCrotalTitle: "유효하지 않은 이표",
  maternityReader_alertInvalidCrotalMessage: "이표는 숫자여야 합니다.",
  maternityReader_alertReadErrorTitle: "읽기 오류",
  maternityReader_alertNetworkError: "네트워크 오류",
  maternityReader_alertNetworkErrorMessage: "서버에 연결할 수 없습니다.",
  maternityReader_alertMissingCorralTitle: "우리 정보가 없습니다",
  maternityReader_alertMissingCorralMessage: "전송하기 전에 우리를 입력하세요.",
  maternityReader_alertInvalidCorralTitle: "유효하지 않은 우리",
  maternityReader_alertInvalidCorralMessage: "우리는 숫자여야 합니다. (예: 8)",
  maternityReader_alertError: "오류",
  maternityReader_alertNoIpConfigured: "설정된 IP가 없습니다.",
  maternityReader_alertWarning: "알림",
  maternityReader_alertSendErrorTitle: "전송 오류",
  maternityReader_alertMissingIdTitle: "ID가 없습니다",
  maternityReader_alertMissingIdMessage: "업데이트하기 전에 새 ID를 입력하세요.",
  maternityReader_alertMissingAssociatedCrotalTitle: "이표가 없습니다",
  maternityReader_alertMissingAssociatedCrotalMessage: "업데이트할 연결된 이표가 없습니다.",
  maternityReader_alertInvalidAssociatedCrotalTitle: "유효하지 않은 이표",
  maternityReader_alertInvalidAssociatedCrotalMessage: "연결된 이표가 유효하지 않습니다.",
  maternityReader_alertUpdateIdErrorTitle: "ID 업데이트 오류",
  maternityReader_animalInfoTitle: "동물 정보",
  maternityReader_animalInfoDescription: "검색에서 찾은 데이터입니다.",
  maternityReader_animalCardTitle: "동물 정보",
  maternityReader_animalIdLabel: "ID",
  maternityReader_animalCrotalLabel: "이표",
  maternityReader_fieldCorral: "우리",
  maternityReader_fieldHouse: "동",
  maternityReader_fieldState: "상태",
  maternityReader_fieldBodyCondition: "체형 상태",
  maternityReader_fieldCycle: "주기",
  maternityReader_fieldSystemEntryDate: "시스템 등록일",
  maternityReader_newSearch: "새 검색",
  maternityReader_summaryTitle: "요약",
  maternityReader_summaryDescription: "설정에서 선택한 매개변수",
  maternityReader_mode: "모드",
  maternityReader_modeEntry: "입장",
  maternityReader_modeExit: "퇴장",
  maternityReader_modeReading: "읽기",
  maternityReader_corral: "우리",
  maternityReader_detectUnknownTitle: "미확인 동물 식별",
  maternityReader_detectUnknownDescription: "ID가 없는 동물이 나오면 ID를 할당할 수 있습니다.",
  maternityReader_confirmSendTitle: "전송 확인",
  maternityReader_confirmSendDescription: "각 기록을 전송하기 전에 확인을 요청합니다.",
  maternityReader_changeSettings: "설정 변경",
  maternityReader_currentReadingTitle: "현재 읽기",
  maternityReader_currentReadingDescription: "감지된 이표가 여기에 표시됩니다.",
  maternityReader_awrDisconnected: "AWR 연결 안 됨",
  maternityReader_readCrotal: "읽은 이표",
  maternityReader_readId: "ID",
  maternityReader_animalWithoutAssignedId: "ID가 할당되지 않은 동물",
  maternityReader_unknownAnimal: "알 수 없는 동물",
  maternityReader_animalWithoutIdTitle: "ID 없는 동물",
  maternityReader_animalWithoutIdDescription: "읽은 이표를 업데이트하려면 수동 ID를 입력하세요.",
  maternityReader_newIdLabel: "새 ID",
  maternityReader_newIdPlaceholder: "예: A13",
  maternityReader_updatingId: "업데이트 중...",
  maternityReader_updateId: "ID 업데이트",
  maternityReader_sentRecordsTitle: "전송된 기록",
  maternityReader_tableHeaderCorral: "우리",
  maternityReader_tableHeaderId: "ID",
  maternityReader_tableHeaderCrotal: "이표",
  maternityReader_noRecords: "기록이 없습니다.",
  maternityReader_buttonAutoReading: "자동 읽기 활성화",
  maternityReader_buttonAutoSending: "자동 전송 활성화",
  maternityReader_buttonSending: "전송 중...",
  maternityReader_buttonSend: "전송",

  awrScanResults_title: "AWR – 스캔 결과",
  awrScanResults_searching: "AWR 검색 중…",
  awrScanResults_warningTitle: "경고",
  awrScanResults_noDevicesNearby: "근처에서 AWR을 찾을 수 없습니다.",
  awrScanResults_connecting: "연결 중…",
  awrScanResults_connectErrorFallback: "연결할 수 없습니다",
  awrScanResults_connectedTitle: "연결됨",
  awrScanResults_connectedMessage: "{{device}}에 연결되었습니다.",
  awrScanResults_genericDevice: "장치",

  awrSavedList_title: "스캔된 AWR",
  awrSavedList_connecting: "연결 중…",
  awrSavedList_empty: "저장된 AWR가 없습니다. “Configuración AWR”에서 하나를 스캔하세요.",
  awrSavedList_connected: "연결됨",
  awrSavedList_disconnected: "연결 안 됨",
  awrSavedList_renameAccessibility: "이름 변경",
  awrSavedList_deleteAccessibility: "삭제",
  awrSavedList_renameTitle: "AWR 이름 변경",
  awrSavedList_nameLabel: "이름",
  awrSavedList_deleteTitle: "저장된 AWR 삭제",
  awrSavedList_deleteMessage: "이 AWR를 목록에서 삭제하시겠습니까?",
  awrSavedList_deleteAction: "삭제",

  ipConfig_title: "IP 설정",
  ipConfig_cardTitle: "CTIFEED 서버",
  ipConfig_cardDescription: "포털이 열릴 서버의 IP를 입력하세요.",
  ipConfig_inputLabel: "IP (IP만)",
  ipConfig_saved: "저장됨",
  ipConfig_alertSuccessTitle: "정상",
  ipConfig_alertSuccessMessage: "올바른 IP입니다",
  ipConfig_alertWarningTitle: "경고",
  ipConfig_alertServerNotUpdated: "서버가 업데이트되지 않았습니다",
  ipConfig_alertErrorTitle: "오류",
  ipConfig_alertInvalidIp: "유효하지 않은 IP",

  portal_preparing: "포털 준비 중...",
  portal_noSessionToken: "세션 토큰이 없습니다. 다시 로그인해 주세요.",
  portal_noIpConfigured: "설정된 IP가 없습니다. 먼저 서버 IP를 설정해 주세요.",
  portal_prepareUrlError: "포털 URL을 준비할 수 없습니다.",
  portal_loadError: "포털을 불러올 수 없습니다.",
  portal_checkingConnection: "포털 연결을 확인하는 중...",
  portal_noConnectionTitle: "연결 없음",
  portal_connectionTimeout: "포털에 연결할 수 없습니다. 올바른 네트워크에 연결되어 있는지 확인해 주세요.",
  portal_connectionError: "포털에 연결할 수 없습니다. 네트워크 또는 설정된 IP를 확인해 주세요.",
  portal_httpError: "포털을 열 수 없습니다. HTTP 오류 {{status}}.",
  portal_retry: "다시 시도",
  portal_loading: "포털 불러오는 중...",

  AltaDispositivos: "장치 등록",
  LectorMaternidad: "모성 리더기",
  LectorGestacion: "임신 리더기",
  ConfiguracionIP: "IP 설정",
  ConfiguracionAWR: "AWR 설정",
  DarDeAltaAWR: "AWR 등록",
  AWREscaneados: "스캔된 AWR",
  CerrarSesion: "로그아웃",

  Config_lastReadMismatchTitle: "읽은 동물이 검색 결과와 일치하지 않습니다",
  Config_lastReadMismatchCrotal: "귀표",
  Config_lastReadMismatchId: "ID",
  awrBluetoothPermissionMessage: "스캔하려면 Bluetooth를 켜고 권한을 허용하세요.",

  animalState: {
        gestation: "임신",
        maternity: "분만",
        out_of_gestation: "임신 아님",
        out_of_maternity: "분만 종료"
    },


    Reader_readingTitle: "이표 판독",
    Reader_labelId: "ID",
    Reader_labelCrotal: "이표",
    Reader_labelCorral: "우리",
    Reader_labelHouse: "축사",
    Reader_labelState: "상태",
    Reader_autoReadingBadge: "자동 판독",

    gestacionConfig_flowSectionTitle: "흐름 설정",
gestacionConfig_workModeTitle: "작업 모드",
gestacionConfig_workModeDescription: "리더기가 수행할 작업을 선택하세요.",
gestacionConfig_entryDescription: "입장 등록",
gestacionConfig_exitDescription: "퇴장 등록",
gestacionConfig_readingDescription: "조회만 하기",
gestacionConfig_searchDescription: "동물 검색",

gestacionConfig_sendSettingsTitle: "전송 설정",
gestacionConfig_sendSettingsDescription: "동물을 읽을 때 흐름이 어떻게 동작할지 설정하세요.",

gestacionConfig_corralSectionTitle: "입장 우리",
gestacionConfig_corralSectionDescription: "등록을 계속하려면 이 정보가 필요합니다.",

gestacionConfig_alerts_notice: "알림",
gestacionConfig_alerts_invalidCrotalFromBackend: "백엔드에서 비교할 유효한 귀표 번호를 반환하지 않았습니다.",

common_accept: "확인",  

maternidadConfig_flowSectionTitle: "흐름 설정",
maternidadConfig_workModeTitle: "작업 모드",
maternidadConfig_workModeDescription: "리더기가 수행할 작업을 선택하세요.",
maternidadConfig_entryDescription: "입장 등록",
maternidadConfig_exitDescription: "퇴장 등록",
maternidadConfig_readingDescription: "조회만 하기",
maternidadConfig_searchDescription: "동물 검색",

maternidadConfig_sendSettingsTitle: "전송 설정",
maternidadConfig_sendSettingsDescription: "동물을 읽을 때 흐름이 어떻게 동작할지 설정하세요.",

maternidadConfig_corralSectionTitle: "입장 우리",
maternidadConfig_corralSectionDescription: "등록을 계속하려면 이 정보가 필요합니다.",

maternidadConfig_alert_invalidCrotalFromBackend: "백엔드에서 비교할 유효한 귀표 번호를 반환하지 않았습니다.",
maternidadConfig_readOnlyTitle: "읽기 전용 권한",
maternidadConfig_readOnlyModifySettings: "이 사용자는 읽기 전용 권한만 있습니다. 이 설정을 수정할 수 없습니다.",
maternidadConfig_readOnlyUseFunction: "이 사용자는 읽기 전용 권한만 있습니다. 이 기능을 사용할 수 없습니다.",

 ajustesEnvioMaternidad: {
    headerTitle: "전송 설정",
    headerSubtitle: "동물을 읽을 때 흐름이 어떻게 동작할지 설정합니다.",
    cardTitle: "기록 전송",
    cardSubtitle: "이 설정은 읽기를 계속할 때 적용됩니다."
  },

  noAlimentadosMaternidad: {
  animalId: "동물 ID",
  corral: "돈방",
  consumption: "섭취량",
  withoutFeeding: "미급이",
  day: "일",
  days: "일",
  loadingAnimals: "동물을 불러오는 중...",
  title: "미급이 동물",
  totalAnimalsMaternity: "분만사 전체 동물 수:",
  notSeen: "미확인",
  all: "전체",
  sort: "정렬",
  emptyTitle: "대기 중인 동물이 없습니다",
  emptyText: "분만사에서 미급이 동물을 찾을 수 없습니다.",
  sortBy: "정렬 기준",
  daysWithoutFeeding: "미급이 일수",
  sortDaysHelp: "미급이 일수를 기준으로 정렬합니다",
  sortCorralHelp: "돈방 번호를 기준으로 정렬합니다",
  descending: "내림차순",
  ascending: "오름차순",
  filterAnimals: "동물 필터",
  allHelp: "모든 동물을 표시합니다",
  unmarked: "표시 안 됨",
  unmarkedHelp: "이미 확인한 동물을 숨깁니다",
  clearMarkedTitle: "표시된 동물 지우기",
  clearMarkedText: "확인한 동물의 모든 표시가 삭제됩니다.",
  cancel: "취소",
  clear: "지우기",
  error: "오류",
  serverConnectionError: "서버에 연결할 수 없습니다."
},

noAlimentadosGestacion: {
  animalId: "동물 ID",
  corral: "돈방",
  consumption: "섭취량",
  withoutFeeding: "미급이",
  day: "일",
  days: "일",
  loadingAnimals: "동물을 불러오는 중...",
  title: "미급이 동물",
  totalAnimalsGestation: "임신사 전체 동물 수:",
  notSeen: "미확인",
  all: "전체",
  sort: "정렬",
  emptyTitle: "대기 중인 동물이 없습니다",
  emptyText: "임신사에서 미급이 동물을 찾을 수 없습니다.",
  sortBy: "정렬 기준",
  daysWithoutFeeding: "미급이 일수",
  sortDaysHelp: "미급이 일수를 기준으로 정렬합니다",
  sortCorralHelp: "돈방 번호를 기준으로 정렬합니다",
  descending: "내림차순",
  ascending: "오름차순",
  filterAnimals: "동물 필터",
  allHelp: "모든 동물을 표시합니다",
  unmarked: "표시 안 됨",
  unmarkedHelp: "이미 확인한 동물을 숨깁니다",
  clearMarkedTitle: "표시된 동물 지우기",
  clearMarkedText: "확인한 동물의 모든 표시가 삭제됩니다.",
  cancel: "취소",
  clear: "지우기",
  error: "오류",
  serverConnectionError: "서버에 연결할 수 없습니다.",
  viewStatus: "상태 보기",
animalIdNotFound: "동물 식별자를 찾을 수 없습니다.",
openAnimalInfoError: "동물 정보를 열 수 없습니다.",

},
capturaAnimalHome: {
  selectOption: "옵션을 선택하세요",
  unfedAnimalsTitle: "미급이 동물",
  unfedAnimalsDescription: "예정된 급이를 받지 못한 동물을 확인합니다.",
  twoFeedsTitle: "사료 2종",
  twoFeedsDescription: "낙하구의 사료 변경을 관리합니다.",
  animalStatusTitle: "동물 상태",
animalStatusDescription: "동물 상태를 확인하거나 업데이트합니다.",
birthCaptureTitle: "분만 기록",
birthCaptureDescription: "생존, 사망 및 미라화 자돈을 기록합니다.",
},
cambioPiensoMaternidad: {
  error: "오류",
  loadTasksError: "사료 변경 작업을 불러올 수 없습니다.",
  loadingTasks: "작업을 불러오는 중...",
  title: "사료 변경",
  pendingTask: "{{count}}개 대기 작업",
  pendingTasks: "{{count}}개 대기 작업",
  emptyTitle: "대기 중인 작업이 없습니다",
  emptyText: "사료 변경 작업을 찾을 수 없습니다.",
  animalId: "동물 ID",
  corral: "돈방",
  setTo: "설정",
  destination: "목적지"
},
estadoAnimal: {
  queryLabel: "조회",
  title: "동물 상태",
  subtitle: "동물을 식별할 방법을 선택하세요.",
  corral: "돈방",
  corralDescription: "돈방 번호를 입력하세요.",
  id: "ID",
  idDescription: "동물 식별자를 입력하세요.",
  animalId: "동물 ID",
  requiredData: "필수 데이터",
  enterCorral: "돈방 번호를 입력하세요.",
  enterId: "동물 식별자를 입력하세요.",
  consulting: "조회 중...",
  continue: "계속",
  accept: "확인",
  serverConnectionError: "서버에 연결할 수 없습니다.",
  noIpConfigured: "IP가 설정되어 있지 않습니다.",
  nextScreenPending: "다음 단계에서 동물 정보 화면을 만들겠습니다.",
  corralMaternityDescription: "분만 우리 번호를 입력하세요.",
idAnimalDescription: "분만 및 임신 구역에서 동물을 검색합니다.",
animalNotFound: "동물을 찾을 수 없습니다",
},
matCorralDetail: {
  viewStatus: "상태 보기",
animalIdNotFound: "동물 식별자를 찾을 수 없습니다.",
openAnimalInfoError: "동물 정보를 열 수 없습니다.",
  penNotFound: "우리를 찾을 수 없습니다",
  earTagAlreadyAssigned: "이표가 다른 동물에게 할당되어 있습니다",
  readOnlyPermission: "읽기 전용 권한",
readOnlyPermissionText: "이 사용자는 읽기 권한만 있습니다. 동물에 대한 작업을 수행할 수 없습니다.",
  animalStatus: "동물 상태",
  id: "ID",
  earTag: "이표",
  cycle: "주기",
  day: "일",

  curve: "곡선",
  correction: "보정",
  entryDate: "입식일",
  farrowingDate: "분만일",
  house: "동",
  pen: "우리",
  lastFeeding: "마지막 급이",
presentPiglets: "생존 자돈",
  inseminationDate: "수정일",
  teatsNumber: "유두 수",

  operations: "작업",

  consumption: "섭취량",
  ofGrams: "{{amount}} g 중",
  oneDayWithoutFeeding: "1일 미급이",
  daysWithoutFeeding: "{{count}}일 미급이",

  noAnimalData: "동물 데이터 없음",
  noAnimalDataText: "표시할 정보를 받지 못했습니다.",
  back: "뒤로",
  operationsPendingTitle: "작업",
  operationsPendingText: "다음 단계에서 작업을 진행합니다.",
  moveToWeaning: "이유 단계로 이동",
  chooseOption: "이 동물에 대한 작업을 선택하세요.",
  nextOperation: "다음 작업",
  insertAnimal: "동물 추가",
  moveToLactation: "수유 단계로 이동",
  nextStep: "다음 단계",
  actions: "작업 목록",

  bodyCondition: "체형 상태",
  subState: "하위 상태",
  pigletCapture: "자돈 기록",
  animalExit: "동물 출하",
  replaceEarTag: "이표 교체",
  changePen: "우리 변경",
  anonymousAnimalId: "익명 동물 식별자",

  cancel: "취소",
  accept: "확인",
  saving: "저장 중...",
  error: "오류",

  operationDone: "작업이 성공적으로 완료되었습니다.",
  changeStateDone: "하위 상태가 성공적으로 업데이트되었습니다.",
  changeStateError: "동물 상태를 변경할 수 없습니다.",
  confirmNextOperation: "다음 작업으로 이동하시겠습니까?",
  pkidChangeStateNotFound: "동물 내부 식별자를 찾을 수 없습니다.",

  selectExitType: "적용할 출하 유형을 선택하세요.",
  exitImmediate: "즉시 출하",
  exitScheduled: "예약 출하",
  exitScheduledEmptyHopper: "빈 호퍼 예약 출하",
  cancelScheduledExit: "예약 출하 취소",
  scheduledDate: "예약 날짜",
  exitDateLimitText: "오늘 이전 날짜 또는 3일 이후 날짜는 선택할 수 없습니다.",
  animalExitDone: "동물 출하가 성공적으로 완료되었습니다.",
  animalExitError: "동물 출하를 완료할 수 없습니다.",
  pkidExitNotFound: "동물 내부 식별자를 찾을 수 없습니다.",

  selectCurve: "곡선 선택",
  selectCurveText: "동물의 새 곡선을 선택하세요.",
  loadingCurves: "곡선 로딩 중...",
  noCurvesAvailable: "사용 가능한 곡선이 없습니다.",
  confirmChangeCurve: "곡선을 변경하시겠습니까?",
  loadCurvesError: "곡선을 불러올 수 없습니다.",
  pkidChangeCurveNotFound: "동물 내부 식별자를 찾을 수 없습니다.",
  changeCurveDone: "곡선이 성공적으로 업데이트되었습니다.",
  changeCurveError: "곡선을 변경할 수 없습니다.",

  selectBodyConditionText: "동물의 새 체형 상태를 선택하세요.",
  loadingBodyConditions: "체형 상태 로딩 중...",
  noBodyConditionsAvailable: "사용 가능한 체형 상태가 없습니다.",
  confirmChangeBodyCondition: "체형 상태를 변경하시겠습니까?",
  loadBodyConditionsError: "체형 상태를 불러올 수 없습니다.",
  pkidChangeBodyConditionNotFound: "동물 내부 식별자를 찾을 수 없습니다.",
  changeBodyConditionDone: "체형 상태가 성공적으로 업데이트되었습니다.",
  changeBodyConditionError: "체형 상태를 변경할 수 없습니다.",

  selectSubStateText: "동물의 새 하위 상태를 수동으로 선택하세요.",
  confirmChangeSubState: "하위 상태를 변경하시겠습니까?",

  currentPen: "현재 우리: {{pen}}",
  newPen: "새 우리",
  enterNewPen: "새 우리를 입력하세요.",
  pkidChangePenNotFound: "동물 내부 식별자를 찾을 수 없습니다.",
  changePenDone: "우리가 성공적으로 업데이트되었습니다.",
  changePenError: "우리를 변경할 수 없습니다.",

  currentEarTag: "현재 이표: {{earTag}}",
  newEarTag: "새 이표",
  enterNewEarTag: "새 이표를 입력하세요.",
  pkidEarTagNotFound: "동물 내부 식별자를 찾을 수 없습니다.",
  replaceEarTagDone: "이표가 성공적으로 업데이트되었습니다.",
  replaceEarTagError: "이표를 교체할 수 없습니다.",

  identifyAnonymousAnimalText: "동물에게 ID 또는 이표를 할당할지 선택하세요.",
  newId: "새 ID",
  enterNewId: "새 ID를 입력하세요.",
  idExample: "예: 1010",
  earTagExample: "예: 123",
  notAnonymousAnimalText: "이 동물은 이미 ID 또는 이표가 할당되어 있어 익명 동물이 아닙니다.",
  pkidIdentifyNotFound: "동물 내부 식별자를 찾을 수 없습니다.",
  identifyAnonymousAnimalDone: "동물 식별자가 성공적으로 업데이트되었습니다.",
  identifyAnonymousAnimalError: "익명 동물을 식별할 수 없습니다.",

  livePiglets: "생존",
  deadPiglets: "사망",
  mummifiedPiglets: "미라화",
  totalBornPiglets: "총 출생 수",
  pigletCaptureText: "생존, 사망 및 미라화 자돈 수를 입력하세요.",
  captureBeforeLactationText: "수유 단계로 이동하기 전에 출생 자돈을 기록하세요.",
  weaningPigletsOnlyRead: "이유 단계에서는 자돈을 조회만 할 수 있습니다.",
  pkidPigletsNotFound: "동물 내부 식별자를 찾을 수 없습니다.",
  pigletCaptureDone: "자돈 기록이 성공적으로 저장되었습니다.",
  pigletCaptureError: "자돈 기록을 저장할 수 없습니다.",
},
subState: {
  prepartum: "분만 전",
  lactation: "수유",
  weaning: "이유",
},

capturaParto: {
  birthDataTitle: "분만 데이터",
  birthDataSubtitle: "분만을 기록하기 전에 동물 데이터를 확인하세요.",
  corral: "우리",
  id: "ID",
  date: "날짜",
  subState: "하위 상태",

  dataCollectionTitle: "데이터 수집",
  dataCollectionSubtitle: "생존, 사망 및 미라화 자돈 수를 입력하세요.",
  weaningReadOnly: "이유 단계에서는 데이터 조회만 가능합니다.",

  totalBorn: "총 출생 수",
  live: "생존",
  dead: "사망",
  mummified: "미라화",

  prepartum: "분만 전",
  farrowing: "분만",
  lactation: "수유",
  weaning: "이유",

  accept: "확인",
  cancel: "취소",
  saving: "저장 중...",

  sentTitle: "기록 전송됨",
  sentMessage: "분만 기록이 성공적으로 저장되었습니다.",

  errorTitle: "오류",
  invalidAnimalTitle: "유효하지 않은 동물",
  invalidAnimalText: "동물 내부 식별자를 찾을 수 없습니다.",
  reportSendError: "분만 기록을 저장할 수 없습니다.",

  invalidDateTitle: "유효하지 않은 날짜",
  invalidDateMessage: "분만일은 오늘 이후일 수 없습니다.",
  changeDate: "날짜 변경",

  selectDateTitle: "날짜 선택",
  selectDateMessage: "버튼을 사용하여 분만일을 조정하세요.",
},
capturaMaternidadEntrada: {
  title: "분만 기록",
  description: "분만을 기록하려면 우리 번호 또는 ID로 동물을 검색하세요.",
  maternityLabel: "분만사",

  corral: "우리",
  corralDescription: "우리 번호로 동물을 검색합니다.",
  id: "ID",
  idDescription: "동물의 식별자로 검색합니다.",
  animalId: "동물 ID",

  corralExample: "예: 102",
  idExample: "예: 1234",

  consulting: "검색 중...",
  continue: "계속",
  accept: "확인",

  serverConnectionError: "서버에 연결할 수 없습니다.",
},
altaBajaStack: {
  tituloPantalla: "자돈 추가/감소",
  descripcionPantalla: "자돈 추가 또는 감소를 등록하려면 어미를 우리 번호 또는 ID로 검색하세요.",
},
altaBajaLechones: {
  heroTitle: "자돈 이동",
  statusAlta: "추가",
  statusBaja: "감소",

  corralUpper: "우리",
  idUpper: "ID",
  dateUpper: "날짜",

  movementType: "이동 유형",
  movementSubtitle: "자돈 추가 또는 감소를 등록할지 선택하세요.",
  adoption: "입양",
  baja: "감소",

  adoptionData: "입양 데이터",
  donorMother: "공여 모돈",
  donatesPiglets: "자돈을 제공합니다",
  id: "ID",
  transferredPiglets: "이동된 자돈",
  totalAdopted: "총 입양 수",
  total: "총계",

  bajaReason: "감소 사유",
  reasonCrushing: "압사",
  reasonDiarrhea: "설사",
  reasonLowViability: "낮은 생존력",
  reasonDeformities: "기형",
  reasonOther: "기타",

  piglet: "자돈",
  piglets: "자돈",
  description: "설명",

  editReason: "사유 수정",
  addReason: "사유 추가",
  reasonModalText: "자돈 수를 입력하고 사유를 설명하세요.",

  saving: "저장 중...",
  saveAlta: "추가 저장",
  saveBaja: "감소 저장",
  accept: "확인",
  cancel: "취소",

  error: "오류",
  missingData: "누락된 데이터",
  saveError: "저장 오류",
  saveErrorText: "작업을 저장할 수 없습니다.",
  selectedAnimalPkidNotFound: "선택한 동물의 내부 식별자를 찾을 수 없습니다.",

  enterTransferredPiglets: "이동된 자돈 수를 입력하세요.",
  invalidTotalTitle: "유효하지 않은 총계",
  invalidPigletsNumber: "유효한 자돈 수를 입력하세요.",

  missingDescriptionTitle: "설명이 필요합니다",
  missingDescriptionText: "사유 설명을 입력하세요.",
  invalidQuantityTitle: "유효하지 않은 수량",
  invalidPigletQuantity: "유효한 자돈 수량을 입력하세요.",

  selectReasonRequired: "감소 사유를 하나 이상 선택하세요.",

  adoptionSavedTitle: "추가 저장됨",
  adoptionSavedMessage: "{{count}}마리 자돈이 성공적으로 등록되었습니다.",

  bajasSavedTitle: "감소 저장됨",
  bajasSavedMessage: "{{piglets}}건의 감소가 {{reasons}}개 사유로 성공적으로 등록되었습니다.",
},
avisoAplicacionNoConfigurada: {
  title: "애플리케이션이 구성되지 않았습니다",
  text: "서버 IP 주소를 설정하세요",
  link: "여기를 누르세요",
},
generalHome: {
  movementAnimalTitle: "동물 이동",
  readerDescription: "이표 리더기.",
  keyboardDescription: "키보드",

  ctifeedTitle: "CTIFEED",
  ctifeedDescription: "메인 포털에 접속합니다.",

  modalApplicationNotConfiguredTitle: "애플리케이션이 구성되지 않았습니다",
  modalNoSessionTitle: "세션이 시작되지 않았습니다",
  modalInstallationUnavailableTitle: "설치 항목을 사용할 수 없습니다",
  modalPreparingSessionTitle: "세션 준비 중",
  modalReadOnlyPermissionTitle: "읽기 전용 권한",

  modalApplicationNotConfiguredText: "구성된 설치 항목이 없습니다. 설치 목록으로 이동하여 하나를 선택하세요.",
  modalNoSessionText: "설치 항목에 IP는 있지만 활성 세션이 없습니다. 설치 목록에서 사용자 이름과 비밀번호를 확인하세요.",
  modalInstallationUnavailableText: "선택한 설치 항목에 연결할 수 없습니다. 올바른 WiFi 네트워크에 연결되어 있는지 확인하거나 서버 IP를 확인하세요.",
  modalPreparingSessionText: "세션이 아직 로딩 중입니다. 몇 초 후 다시 시도하세요.",
  modalReadOnlyPermissionText: "이 기능에 접근할 관리자 권한이 없습니다.",

  accept: "확인",

  connectingTitle: "연결 중...",
  connectingText: "선택한 설치 항목과의 연결을 확인하는 중입니다.",
},
movimientoAnimalMaternidad: {
  smallLabel: "이동",
  title: "분만사",
  subtitle: "키보드로 수동 입고 및 출고를 수행합니다.",

  movementType: "이동 유형",
  entry: "입고",
  exit: "출고",

  searchAnimal: "동물 검색",
  entryHelper: "목적지 우리와 동물 ID를 입력하세요.",
  exitHelper: "우리 번호 또는 ID로 출고할지 선택하세요.",

  pen: "우리",
  animalId: "동물 ID",
  type: "유형",

  sending: "전송 중...",
  accept: "확인",
  cancel: "취소",

  confirmEntry: "입고 확인",
  confirmExit: "출고 확인",
  confirmSubtitle: "이동을 전송하기 전에 데이터를 확인하세요.",

  incompleteDataTitle: "데이터가 불완전합니다",
  entryIncompleteText: "우리 번호와 동물 ID를 입력하세요.",
  exitPenIncompleteText: "출고할 우리 번호를 입력하세요.",
  exitIdIncompleteText: "출고할 동물 ID를 입력하세요.",

  invalidPenTitle: "유효하지 않은 우리",
  invalidPenText: "우리 번호는 0보다 큰 유효한 숫자여야 합니다.",

  sendErrorTitle: "전송 오류",
  connectionErrorTitle: "연결 오류",
  noIpConfigured: "설정된 IP가 없습니다.",
  serverConnectionError: "서버에 연결할 수 없습니다.",
  serverEmptyResponse: "서버가 메시지를 반환하지 않았습니다. HTTP 코드 {{status}}.",

  entrySentTitle: "입고 전송됨",
  entrySentText: "입고 이동이 성공적으로 전송되었습니다.",

  exitSentTitle: "출고 전송됨",
  exitByPenSentText: "우리 기준 출고가 성공적으로 전송되었습니다.",
  exitByIdSentText: "ID 기준 출고가 성공적으로 전송되었습니다.",
},
movimientoAnimalGestacion: {
  smallLabel: "임신사",
  title: "동물 이동",
  subtitle: "키보드로 수동 입고 및 출고를 수행합니다.",

  movementType: "이동 유형",
  entry: "입고",
  exit: "출고",

  searchAnimal: "동물 검색",
  entryHelper: "목적지 우리와 동물 ID를 입력하세요.",
  exitHelper: "임신사 출고를 위해 동물 ID를 입력하세요.",

  pen: "우리",
  animalId: "동물 ID",
  type: "유형",

  sending: "전송 중...",
  accept: "확인",
  cancel: "취소",

  confirmEntry: "입고 확인",
  confirmExit: "출고 확인",
  confirmSubtitle: "이동을 전송하기 전에 데이터를 확인하세요.",

  incompleteDataTitle: "데이터가 불완전합니다",
  entryIncompleteText: "우리 번호와 동물 ID를 입력하세요.",
  exitIdIncompleteText: "출고할 동물 ID를 입력하세요.",

  invalidPenTitle: "유효하지 않은 우리",
  invalidPenText: "우리 번호는 0보다 큰 유효한 숫자여야 합니다.",

  sendErrorTitle: "전송 오류",
  noIpConfigured: "설정된 IP가 없습니다.",
  serverConnectionError: "서버에 연결할 수 없습니다.",
  serverEmptyResponse: "서버가 메시지를 반환하지 않았습니다. HTTP 코드 {{status}}.",

  entrySentTitle: "입고 전송됨",
  entrySentText: "임신사 입고 이동이 성공적으로 전송되었습니다.",

  exitSentTitle: "출고 전송됨",
  exitByIdSentText: "ID 기준 임신사 출고가 성공적으로 전송되었습니다.",
},

gestCorralDetail: {
   title: "임신 동물 상태",
   emptyTitle: "이 우리에는 동물이 없습니다",

   id: "ID",
   crotal: "이표",
   cycle: "주기",
   day: "일차",

   stateGestation: "임신",
   stateOutOfGestation: "임신 아님",

   curve: "곡선",
   correction: "보정",
   entryDate: "입고일",
   inseminationDate: "수정일",
   house: "동",
   corral: "우리",
   estimatedFarrowingDate: "예상 분만일",
   lastFeeding: "마지막 급이",

   oneDayWithoutFeeding: "1일 미급이",
   daysWithoutFeeding: "{{count}}일 미급이",
   of: "중",

   operationsButton: "작업",
   operationsTitle: "작업",
   operationsSubtitle: "작업을 선택하세요",

   operationInseminationDate: "수정일",
   operationCurve: "곡선",
   operationBodyCondition: "체형 상태",
   operationChangePen: "우리 변경",
   operationExitAnimal: "동물 출고",
   operationReplaceEarTag: "이표 교체",

   cancel: "취소",
   accept: "확인",
   saving: "저장 중...",

   selectCurve: "곡선 선택",
   loadingCurves: "곡선을 불러오는 중...",
   noCurvesAvailable: "사용 가능한 곡선이 없습니다",

   selectBodyCondition: "체형 상태 선택",
   loadingBodyConditions: "체형 상태를 불러오는 중...",
   noBodyConditionsAvailable: "사용 가능한 체형 상태가 없습니다",

   changePenTitle: "우리 변경",
   currentPen: "현재 우리: {{corral}}",
   newPen: "새 우리",
   changePenPlaceholder: "이동할 우리를 입력하세요",

   replaceEarTagTitle: "이표 교체",
   currentEarTag: "현재 이표: {{crotal}}",
   newEarTag: "새 이표",
   replaceEarTagPlaceholder: "새 이표를 입력하세요",

   inseminationDateTitle: "수정일",
   selectDate: "날짜를 선택하세요",
   noFutureInseminationDate: "현재 날짜보다 이후의 날짜는 선택할 수 없습니다.",

   exitAnimalTitle: "동물 출고",
   exitAnimalGestation: "임신 동물 출고",
   exitDate: "출고일",
   noFutureExitDate: "출고일은 현재 날짜보다 이후일 수 없습니다.",

   penNotFound: "우리를 찾을 수 없습니다",
   changePenGenericError: "우리를 변경할 수 없습니다.",
   earTagAlreadyAssigned: "이표가 다른 동물에게 할당되어 있습니다",
   replaceEarTagGenericError: "이표를 교체할 수 없습니다.",
},

tareasMovimientos: {
  tabs: {
    tareas: "작업",
    historial: "기록"
  },

  secciones: {
    gestacion: "임신사",
    maternidad: "분만사",
    todos: "전체",
    todas: "전체"
  },

  operaciones: {
    entrada: "입고",
    salida: "출고",
    realizada: "완료됨"
  },

  tarjetas: {
    tareasPendientesMovimientos: "대기 중인 이동 작업",
    idAnimal: "동물 ID",
    sinCrotal: "이표 없음",
    corralDestino: "대상 돈방",
    corralOrigen: "출발 돈방",
    fecha: "날짜"
  },

  filtros: {
    titulo: "필터",
    filtrarPorFecha: "날짜로 필터링",
    hoy: "오늘",
    ayer: "어제",
    fecha: "날짜",
    formatoFecha: "DD/MM/YYYY"
  },

  carga: {
    cargandoHistorial: "기록을 불러오는 중..."
  },

  vacio: {
    sinResultados: "결과 없음",
    sinMovimientosConFiltros: "해당 필터와 일치하는 완료된 이동이 없습니다.",
    sinMovimientosTodavia: "아직 완료된 이동이 없습니다."
  },

  errores: {
    actualizarServidorTareas: "이동 작업 기능을 사용하려면 서버를 업데이트해야 합니다.",
    noCargarTareas: "작업을 불러올 수 없습니다.",
    noCargarHistorialTitulo: "기록을 불러올 수 없습니다",
    noCargarHistorial: "이동 기록을 불러올 수 없습니다.",
    historialNoDisponible: "기록을 사용할 수 없습니다",
    actualizarServidorHistorial: "이동 작업 기록을 사용하려면 서버를 업데이트해야 합니다."
  }
},
tareasMovimientosDetalle: {
  tabs: {
    gestacion: "임신사",
    maternidad: "분만사"
  },

  acciones: {
    filtros: "필터",
    ordenar: "정렬",
    marcarRealizado: "완료로 표시",
    marcarSeleccionadas: "표시 ({{total}})",
    marcando: "표시 중...",
    aceptar: "확인",
    cancelar: "취소",
    confirmar: "확인",
    validando: "확인 중..."
  },

  orden: {
    corralAscendente: "돈방 오름차순",
    corralDescendente: "돈방 내림차순"
  },

  operaciones: {
    entrada: "입고",
    salida: "출고",
    trasladoEntrada: "이동 입고",
    trasladoSalida: "이동 출고"
  },

  tarjetas: {
    idAnimal: "동물 ID",
    sinCrotal: "이표 없음",
    corralDestino: "대상 돈방",
    corralOrigen: "출발 돈방",
    fecha: "날짜"
  },

  estados: {
    cargandoTareas: "작업을 불러오는 중...",
    noCargarTareasTitulo: "작업을 불러올 수 없습니다",
    pulsaReintentar: "다시 시도하려면 누르세요",
    sinTareasConFiltros: "해당 필터에 맞는 작업이 없습니다",
    sinTareasPendientes: "대기 중인 작업이 없습니다",
    cambiaFiltros: "적용된 필터를 변경해 보세요.",
    sinMovimientosPendientes: "대기 중인 이동을 찾을 수 없습니다."
  },

  modalResultado: {
    tareasRealizadasTitulo: "작업 완료",
    tareasRealizadasMensaje: "선택한 작업이 완료로 표시되었습니다.",
    tareaRealizadaTitulo: "작업 완료",
    tareaRealizadaMensaje: "분만사 입고가 완료로 표시되었습니다.",
    errorTitulo: "오류"
  },

  modalCorral: {
    titulo: "돈방 확인",
    mensaje: "분만사 입고의 대상 돈방을 확인하세요.",
    labelCorralDestino: "대상 돈방",
    placeholderCorral: "돈방을 입력하세요"
  },

  errores: {
    noCargarTareas: "작업을 불러올 수 없습니다.",
    entradaMaternidadTitulo: "분만사 입고",
    soloUnaEntradaMaternidad: "분만사 입고는 한 번에 하나만 표시할 수 있습니다.",
    soloUnaEntradaMaternidadCadaVez: "분만사 입고는 매번 하나만 표시할 수 있습니다.",
    noMarcarTareas: "작업을 완료로 표시할 수 없습니다.",
    corralMaximo9: "최대 9자리의 유효한 돈방 번호를 입력하세요.",
    corralNoExiste: "돈방이 존재하지 않습니다.",
    corralOcupado: "돈방이 사용 중입니다.",
    noValidarCorral: "돈방을 확인할 수 없습니다.",
    noValidarCorralMaternidad: "분만사 돈방을 확인할 수 없습니다."
  }
},
filtrosTareasMovimientos: {
  cabecera: {
    titulo: "필터",
    subtituloTareasDe: "{{seccion}} 작업",
    limpiar: "초기화"
  },

  secciones: {
    gestacion: "임신사",
    maternidad: "분만사"
  },

  bloques: {
    tipoMovimiento: "이동 유형",
    fecha: "날짜",
    corral: "돈방",
    idAnimal: "동물 ID"
  },

  opciones: {
    todos: "전체",
    entrada: "입고",
    salida: "출고",
    todasLasFechas: "모든 날짜",
    hoy: "오늘",
    manana: "내일",
    fecha: "날짜",
    todosLosCorrales: "모든 돈방",
    porCorral: "돈방별",
    todosLosAnimales: "모든 동물",
    porId: "ID별"
  },

  placeholders: {
    dia: "DD",
    mes: "MM",
    anio: "YY/YYYY",
    introduceCorral: "돈방을 입력하세요",
    introduceIdAnimal: "동물 ID를 입력하세요"
  },

  validaciones: {
    fechaCompleta: "일, 월, 연도를 입력하세요.",
    diaDosCifras: "일은 2자리여야 합니다.",
    mesDosCifras: "월은 2자리여야 합니다.",
    anioDosOCuatroCifras: "연도는 2자리 또는 4자리여야 합니다.",
    diaRango: "일은 01에서 31 사이여야 합니다.",
    mesRango: "월은 01에서 12 사이여야 합니다.",
    fechaNoExiste: "해당 날짜는 존재하지 않습니다.",
    introduceCorral: "돈방 번호를 입력하세요.",
    introduceIdAnimal: "동물 ID를 입력하세요."
  },

  botones: {
    cancelar: "취소",
    aceptar: "확인"
  }
},
filtrosHistorialMovimientos: {
  cabecera: {
    titulo: "필터",
    subtitulo: "이동 기록",
    limpiar: "초기화"
  },

  bloques: {
    tipoMovimiento: "이동 유형",
    fecha: "날짜",
    corral: "돈방",
    idAnimal: "동물 ID"
  },

  opciones: {
    todos: "전체",
    entrada: "입고",
    salida: "출고",
    todasLasFechas: "모든 날짜",
    hoy: "오늘",
    manana: "내일",
    fecha: "날짜",
    todosLosCorrales: "모든 돈방",
    porCorral: "돈방별",
    todosLosAnimales: "모든 동물",
    porId: "ID별"
  },

  placeholders: {
    dia: "DD",
    mes: "MM",
    anio: "YY/YYYY",
    introduceCorral: "돈방을 입력하세요",
    introduceIdAnimal: "동물 ID를 입력하세요"
  },

  validaciones: {
    fechaCompleta: "일, 월, 연도를 입력하세요.",
    diaDosCifras: "일은 2자리여야 합니다.",
    mesDosCifras: "월은 2자리여야 합니다.",
    anioDosOCuatroCifras: "연도는 2자리 또는 4자리여야 합니다.",
    diaRango: "일은 01에서 31 사이여야 합니다.",
    mesRango: "월은 01에서 12 사이여야 합니다.",
    fechaNoExiste: "해당 날짜는 존재하지 않습니다.",
    introduceCorral: "돈방 번호를 입력하세요.",
    introduceIdAnimal: "동물 ID를 입력하세요."
  },

  botones: {
    cancelar: "취소",
    aceptar: "확인"
  }
}
};