export default {
    username: '사용자',
    password: '비밀번호',
    login: '로그인',
    welcome: '환영합니다',
    change_language: '언어 변경',
    Tabs: '홈',

    Lista_instalaciones: '설치',
    Maintenance: '유지보수',
    DetallesInstalacion: '설치 세부 정보',
    Grabar: '저장',
    EstadoStore: '스토어 상태',
    Nodata: '데이터 없음',
    DosimacRegistration: ' 등록',
    NewDmMaternity: '새 Dosimac 모성',
    DosimacG: 'Dosimac-G',
    DosimacI: 'Dosimac-I',
    UpdDmMaternity: 'Dosimac 모성 변경',
    NewDmGestation: '새 Dosimac 임신',
    UpdDmGestation: 'Dosimac 임신 변경',
    StartScan: 'DOSIMAC 장치 검색',
    DosimacList: 'DOSIMAC 장치',
    PressToScan: '누르기',
    DosimacSetup: '구성',
    TestoPresioneAlta: '장치를 검색하려면 버튼을 누르세요',
    Instalación_seleccionada: '선택한 설치',
    NoInstalacionSeleccionada: '선택된 설치 없음',
    BorrarGranja: '농장 삭제',
    Deseaborrarlagranja: '농장을 삭제하시겠습니까?',
    Guardar: '저장',
    Cancelar: '취소',
    Aceptar: '확인',
    NombreGranja: '농장 이름',
    Localidad: '위치',
    Provincia: '주/도',
    NombreWifi: 'Wifi SSID',
    PasswordWifi: 'Wifi 비밀번호',
    No_hay_dispositivos: '장치 없음',
    Aviso: '알림',
    SearchingDevices: '장치 검색 중...',
    NoSePuedeBorrarGranja: '새 농장은 삭제할 수 없습니다',
    settings: '설정',
    softwareVersion: '소프트웨어 버전',
    numeroCoral: '우리 번호',
    numeroMaquina: '기계 번호',
    Enviar: '보내기',
    Salir: '나가기',
    Informacion: '정보',

};