export default {
  username: '사용자',
  password: '비밀번호',
  login: '로그인',
  welcome: '환영합니다',
  change_language: '언어 변경',
  Tabs: '홈',

  Lista_instalaciones: '설치',
  Maintenance: '유지보수',
  DetallesInstalacion: '설치 세부 정보',
  Grabar: '저장',
  EstadoStore: '스토어 상태',
  Nodata: '데이터 없음',
  DosimacRegistration: ' 등록',
  NewDmMaternity: '새 Dosimac 모성',
  DosimacG: 'Dosimac-G',
  DosimacI: 'Dosimac-I',
  UpdDmMaternity: 'Dosimac 모성 변경',
  NewDmGestation: '새 Dosimac 임신',
  UpdDmGestation: 'Dosimac 임신 변경',
  StartScan: 'DOSIMAC 장치 검색',
  DosimacList: 'DOSIMAC 장치',
  PressToScan: '누르기',
  DosimacSetup: '구성',
  TestoPresioneAlta: '장치를 검색하려면 버튼을 누르세요',
  Instalación_seleccionada: '선택한 설치',
  NoInstalacionSeleccionada: '선택된 설치 없음',
  BorrarGranja: '농장 삭제',
  Deseaborrarlagranja: '농장을 삭제하시겠습니까?',
  Guardar: '저장',
  Cancelar: '취소',
  Aceptar: '확인',
  NombreGranja: '농장 이름',
  Localidad: '위치',
  Provincia: '주/도',
  NombreWifi: 'Wifi SSID',
  PasswordWifi: 'Wifi 비밀번호',
  No_hay_dispositivos: '장치 없음',
  Aviso: '알림',
  SearchingDevices: '장치 검색 중...',
  NoSePuedeBorrarGranja: '새 농장은 삭제할 수 없습니다',
  settings: '설정',
  softwareVersion: '소프트웨어 버전',
  numeroCoral: '우리 번호',
  numeroMaquina: '기계 번호',
  Enviar: '보내기',
  Salir: '나가기',
  Informacion: '정보',
  InicioConfiguracion: "연결 시작",
  ConfiguracionWifi: "구성 중...",
  ConfiguracionRealizada: "*구성이 완료되었습니다*",
  ErrorConfiguracion: "*구성 오류*",
  CapturaTagCorral: "우리 태그 캡처",
  CorralTag: "우리 태그",
  versionUint16: "이 기기 버전은 우리 번호를 최대 65000까지만 지원합니다",
  versionUint32: "이 기기 버전은 우리 번호를 최대 4000000000까지 지원합니다",
  EnvioConfiguracion: "구성 전송",
  NumeroCorral: "우리 번호",
  NumeroMaquina: "기계 번호",
  Corralnovalida: "유효하지 않은 우리 번호",
  NumeroMaquinanovalida: "유효하지 않은 기계 번호",
  configuarIntalacion: "이 기능을 사용하려면 설치를 구성해야 합니다",

  login_title: "로그인",
  login_subtitle: "정보를 입력하세요. 로그인하기 전에 IP 설정 메뉴에서 IP를 구성해야 합니다.",
  login_username: "사용자",
  login_password: "비밀번호",
  login_button: "로그인",
  login_loading: "로그인 중...",
  login_footer: "제어판",

  login_ipRequiredTitle: "IP 설정 필요",
  login_ipRequiredMessage: "서버 IP 주소가 설정되지 않았습니다. 로그인하려면 입력하세요.",
  login_serverIpLabel: "서버 IP",
  login_cancel: "취소",
  login_accept: "확인",

  login_configTitle: "설정",
  login_errorTitle: "로그인 오류",
  login_genericErrorTitle: "오류",
  login_networkErrorTitle: "네트워크 오류",
  login_networkErrorMessage: "서버에 연결할 수 없습니다.",
  login_noTokenMessage: "백엔드가 토큰을 반환하지 않았습니다.",
  login_missingDataTitle: "입력 누락",
  login_missingDataMessage: "사용자명과 비밀번호를 입력하세요.",
  login_invalidIpTitle: "잘못된 IP",
  login_invalidIpMessage: "유효한 IP 또는 서버 주소를 입력하세요.",
  login_saveIpErrorMessage: "IP 설정을 저장할 수 없습니다.",
  awrStartScan_title: "AWR 설정",
  awrStartScan_description: "Agrident AWR 리더기를 스캔하는 화면입니다.",
  awrStartScan_button: "AWR 스캔",

  gestacionConfig_entry: "입력",
  gestacionConfig_exit: "출력",
  gestacionConfig_reading: "읽기",
  gestacionConfig_search: "검색",

  gestacionConfig_entryParamsTitle: "입력 파라미터",
  gestacionConfig_exitParamsTitle: "출력 파라미터",
  gestacionConfig_entryParamsDescription: "우리 번호와 흐름 동작을 선택하세요.",
  gestacionConfig_exitParamsDescription: "출력 흐름 동작을 설정하세요.",

  gestacionConfig_corralLabel: "우리",
  gestacionConfig_corralPlaceholder: "예: 1",
  gestacionConfig_corralRequired: "계속하려면 우리 번호를 입력하세요.",

  gestacionConfig_detectUnknownTitle: "미확인 동물 식별",
  gestacionConfig_detectUnknownDescription: "식별되지 않은 동물을 읽으면 ID를 할당할 수 있습니다",

  gestacionConfig_confirmTitle: "전송 확인",
  gestacionConfig_confirmDescription: "기록을 전송하기 전에 확인을 요청합니다.",

  gestacionConfig_animalSearchTitle: "동물 검색",
  gestacionConfig_animalSearchDescription: "귀표 또는 ID로 검색할지 선택하세요.",
  gestacionConfig_searchByCrotal: "귀표로",
  gestacionConfig_searchById: "ID로",
  gestacionConfig_manual: "수동",
  gestacionConfig_withSword: "리더기로",

  gestacionConfig_crotalLabelSearch: "귀표",
  gestacionConfig_idLabelSearch: "ID",
  gestacionConfig_crotalPlaceholderSearch: "예: 982091072397436",
  gestacionConfig_idPlaceholderSearch: "예: A13",
  gestacionConfig_crotalRequiredSearch: "계속하려면 귀표를 입력하세요.",
  gestacionConfig_idRequiredSearch: "계속하려면 ID를 입력하세요.",

  gestacionConfig_searchWithSwordHelp: "계속하면 이 화면에서 리더기로 읽고 해당 귀표로 동물을 검색합니다.",

  gestacionConfig_readingSword: "리더기 읽는 중...",
  gestacionConfig_waitingMatch: "일치 대기 중",
  gestacionConfig_searchingAnimal: "동물 검색 중...",

  gestacionConfig_readingSwordDescription: "동물을 식별하려면 귀표를 리더기에 가까이 대세요.",
  gestacionConfig_waitingMatchDescription: "동물을 찾았습니다. 이제 일치를 확인하려면 귀표 {{crotal}}를 리더기에 가까이 대세요.",
  gestacionConfig_searchingAnimalDescription: "백엔드에서 동물 정보를 조회하는 중입니다.",

  gestacionConfig_awrDisconnectedTitle: "AWR 연결 안 됨",
  gestacionConfig_awrSavedDescription: "저장된 리더기가 있습니다. 선택하려면 누르세요.",
  gestacionConfig_awrNotSavedDescription: "저장된 리더기가 없습니다. 스캔하려면 누르세요.",

  gestacionConfig_scan: "스캔",
  gestacionConfig_continue: "계속",

  gestacionConfig_alerts_error: "오류",
  gestacionConfig_alerts_networkError: "네트워크 오류",
  gestacionConfig_alerts_networkErrorMessage: "서버에 연결할 수 없습니다.",
  gestacionConfig_alerts_backendNoValidCrotal: "백엔드가 비교할 수 있는 유효한 귀표를 반환하지 않았습니다.",
  gestacionConfig_alerts_awrNotConnected: "AWR 연결 안 됨",
  gestacionConfig_alerts_connectSwordBeforeContinue: "계속하기 전에 리더기를 연결하세요.",
  gestacionConfig_alerts_couldNotStartReading: "리더기로 읽기를 시작할 수 없습니다.",

  gestacionConfig_alerts_missingData: "데이터 누락",
  gestacionConfig_alerts_writeCrotalToSearch: "검색할 귀표를 입력하세요.",
  gestacionConfig_alerts_writeIdToSearch: "검색할 ID를 입력하세요.",

  gestacionConfig_alerts_notFound: "찾을 수 없음",
  gestacionConfig_alerts_animalNotFoundByCrotal: "해당 귀표를 가진 동물이 없습니다.",
  gestacionConfig_alerts_animalNotFoundById: "해당 ID를 가진 동물이 없습니다.",

  gestacionConfig_alerts_warning: "알림",
  gestacionConfig_alerts_searchError: "검색 오류",

  maternidadConfig_screenTitle: "모성 설정",
  maternidadConfig_chooseOptionTitle: "옵션 선택",
  maternidadConfig_chooseOptionDescription: "리더를 시작하기 전에 흐름을 설정하세요.",
  maternidadConfig_entry: "입장",
  maternidadConfig_exit: "퇴장",
  maternidadConfig_reading: "읽기",
  maternidadConfig_search: "검색",
  maternidadConfig_entryParamsTitle: "입장 파라미터",
  maternidadConfig_exitParamsTitle: "퇴장 파라미터",
  maternidadConfig_entryParamsDescription: "우리와 흐름 동작을 선택하세요.",
  maternidadConfig_exitParamsDescription: "퇴장 흐름 동작을 설정하세요.",
  maternidadConfig_corralLabel: "우리",
  maternidadConfig_corralPlaceholder: "예: 1",
  maternidadConfig_corralRequired: "계속하려면 우리를 입력하세요.",
  maternidadConfig_detectUnknownTitle: "미확인 동물 식별",
  maternidadConfig_detectUnknownDescription: "식별되지 않은 동물을 읽으면 ID를 할당할 수 있습니다",
  maternidadConfig_confirmTitle: "전송 확인",
  maternidadConfig_confirmDescription: "각 기록을 전송하기 전에 확인을 요청합니다.",
  maternidadConfig_animalSearchTitle: "동물 검색",
  maternidadConfig_animalSearchDescription: "귀표 또는 ID로 검색할지 선택하세요.",
  maternidadConfig_searchByCrotal: "귀표로",
  maternidadConfig_searchById: "ID로",
  maternidadConfig_manual: "수동",
  maternidadConfig_withSword: "리더로",
  maternidadConfig_crotalLabelSearch: "귀표",
  maternidadConfig_idLabelSearch: "ID",
  maternidadConfig_crotalPlaceholderSearch: "예: 982091072397436",
  maternidadConfig_idPlaceholderSearch: "예: A13",
  maternidadConfig_crotalRequiredSearch: "계속하려면 귀표를 입력하세요.",
  maternidadConfig_idRequiredSearch: "계속하려면 ID를 입력하세요.",
  maternidadConfig_searchWithSwordHelp: "스캔을 누르면 이 화면에서 리더를 읽고 해당 귀표로 동물을 검색합니다.",
  maternidadConfig_readingSword: "리더 읽는 중...",
  maternidadConfig_waitingMatch: "일치 대기 중",
  maternidadConfig_searchingAnimal: "동물 검색 중...",
  maternidadConfig_readingSwordDescription: "동물을 식별하려면 귀표를 리더 가까이에 대세요.",
  maternidadConfig_waitingMatchDescription: "동물을 찾았습니다. 이제 일치를 확인하려면 귀표 {{crotal}}를 리더에 가까이 대세요.",
  maternidadConfig_searchingAnimalDescription: "백엔드에서 동물 정보를 조회하는 중입니다.",
  maternidadConfig_awrDisconnectedTitle: "AWR 연결 안 됨",
  maternidadConfig_awrSavedDescription: "저장된 AWR이 있습니다. 선택하려면 누르세요.",
  maternidadConfig_awrNotSavedDescription: "저장된 AWR이 없습니다. 스캔하려면 누르세요.",
  maternidadConfig_scan: "스캔",
  maternidadConfig_continue: "계속",
  maternidadConfig_alert_error: "오류",
  maternidadConfig_alert_invalidBackendCrotal: "백엔드가 비교할 유효한 귀표를 반환하지 않았습니다.",
  maternidadConfig_alert_awrNotConnected: "AWR 연결 안 됨",
  maternidadConfig_alert_connectSwordBeforeContinue: "계속하기 전에 리더를 연결하세요.",
  maternidadConfig_alert_couldNotStartReading: "리더 읽기를 시작할 수 없습니다.",
  maternidadConfig_alert_missingData: "데이터 누락",
  maternidadConfig_alert_writeCrotalToSearch: "검색할 귀표를 입력하세요.",
  maternidadConfig_alert_writeIdToSearch: "검색할 ID를 입력하세요.",
  maternidadConfig_alert_notFound: "찾을 수 없음",
  maternidadConfig_alert_noAnimalWithCrotal: "해당 귀표를 가진 동물이 없습니다.",
  maternidadConfig_alert_noAnimalWithId: "해당 ID를 가진 동물이 없습니다.",
  maternidadConfig_alert_warning: "알림",
  maternidadConfig_alert_searchError: "검색 오류",
  maternidadConfig_alert_networkError: "네트워크 오류",
  maternidadConfig_alert_networkErrorMessage: "서버에 연결할 수 없습니다.",

  gestationReader_screenTitle: "임신 리더기",
  gestationReader_animalInfoTitle: "동물 정보",
  gestationReader_animalInfoDescription: "검색에서 찾은 데이터입니다.",
  gestationReader_animalCardTitle: "동물 카드",
  gestationReader_animalIdLabel: "ID",
  gestationReader_animalCrotalLabel: "귀표",
  gestationReader_fieldCorral: "우리",
  gestationReader_fieldHouse: "동",
  gestationReader_fieldState: "상태",
  gestationReader_fieldBodyCondition: "체형 상태",
  gestationReader_fieldCycle: "주기",
  gestationReader_fieldSystemEntryDate: "시스템 등록일",
  gestationReader_newSearch: "새 검색",
  gestationReader_summaryTitle: "요약",
  gestationReader_summaryDescription: "설정에서 선택한 매개변수",
  gestationReader_mode: "모드",
  gestationReader_corral: "우리",
  gestationReader_modeEntry: "입장",
  gestationReader_modeExit: "퇴장",
  gestationReader_modeReading: "읽기",
  gestationReader_modeSearch: "검색",
  gestationReader_detectUnknownTitle: "알 수 없는 동물 식별",
  gestationReader_detectUnknownDescription: "ID가 없는 동물이 나타나면 ID를 할당할 수 있도록 합니다.",
  gestationReader_confirmSendTitle: "전송 확인",
  gestationReader_confirmSendDescription: "각 기록을 보내기 전에 확인을 요청합니다.",
  gestationReader_changeSettings: "설정 변경",
  gestationReader_currentReadingTitle: "현재 읽기",
  gestationReader_currentReadingDescription: "감지된 귀표와 연결된 ID가 여기에 표시됩니다.",
  gestationReader_awrDisconnected: "AWR 연결 안 됨",
  gestationReader_readCrotal: "읽은 귀표",
  gestationReader_readId: "ID",
  gestationReader_animalWithoutAssignedId: "ID가 할당되지 않은 동물",
  gestationReader_unknownAnimal: "알 수 없는 동물",
  gestationReader_animalWithoutIdTitle: "ID 없는 동물",
  gestationReader_animalWithoutIdDescription: "읽은 귀표를 업데이트하려면 수동 ID를 입력하세요.",
  gestationReader_newIdLabel: "새 ID",
  gestationReader_newIdPlaceholder: "예: A13",
  gestationReader_updateId: "ID 업데이트",
  gestationReader_updatingId: "업데이트 중...",
  gestationReader_sentRecordsTitle: "전송된 기록",
  gestationReader_noRecords: "기록이 없습니다.",
  gestationReader_tableHeaderCorral: "우리",
  gestationReader_tableHeaderId: "ID",
  gestationReader_tableHeaderCrotal: "귀표",
  gestationReader_buttonAutoReading: "자동 읽기 활성화",
  gestationReader_buttonAutoSending: "자동 전송 활성화",
  gestationReader_buttonSending: "전송 중...",
  gestationReader_buttonSend: "보내기",
  gestationReader_alertError: "오류",
  gestationReader_alertWarning: "알림",
  gestationReader_alertNetworkError: "네트워크 오류",
  gestationReader_alertMissingCrotalTitle: "귀표 누락",
  gestationReader_alertMissingCrotalMessage: "전송하기 전에 귀표를 리더기에 가까이 가져가세요.",
  gestationReader_alertInvalidCrotalTitle: "유효하지 않은 귀표",
  gestationReader_alertInvalidCrotalMessage: "귀표는 숫자여야 합니다.",
  gestationReader_alertReadErrorTitle: "읽기 오류",
  gestationReader_alertNetworkErrorMessage: "서버에 연결할 수 없습니다.",
  gestationReader_alertMissingCorralTitle: "우리 누락",
  gestationReader_alertMissingCorralMessage: "전송하기 전에 우리를 입력하세요.",
  gestationReader_alertInvalidCorralTitle: "유효하지 않은 우리",
  gestationReader_alertInvalidCorralMessage: "우리는 숫자여야 합니다.",
  gestationReader_alertSendErrorTitle: "전송 오류",
  gestationReader_alertNoIpConfigured: "설정된 IP가 없습니다.",
  gestationReader_alertMissingIdTitle: "ID 누락",
  gestationReader_alertMissingIdMessage: "업데이트 전에 새 ID를 입력하세요.",
  gestationReader_alertMissingAssociatedCrotalTitle: "귀표 누락",
  gestationReader_alertMissingAssociatedCrotalMessage: "업데이트할 연결된 귀표가 없습니다.",
  gestationReader_alertInvalidAssociatedCrotalTitle: "유효하지 않은 귀표",
  gestationReader_alertInvalidAssociatedCrotalMessage: "연결된 귀표가 유효하지 않습니다.",
  gestationReader_alertUpdateIdErrorTitle: "ID 업데이트 오류",

  maternityReader_screenTitle: "분만 리더기",
  maternityReader_alertMissingCrotalTitle: "이표가 없습니다",
  maternityReader_alertMissingCrotalMessage: "전송하기 전에 이표를 리더기에 가까이 대세요.",
  maternityReader_alertInvalidCrotalTitle: "유효하지 않은 이표",
  maternityReader_alertInvalidCrotalMessage: "이표는 숫자여야 합니다.",
  maternityReader_alertReadErrorTitle: "읽기 오류",
  maternityReader_alertNetworkError: "네트워크 오류",
  maternityReader_alertNetworkErrorMessage: "서버에 연결할 수 없습니다.",
  maternityReader_alertMissingCorralTitle: "우리 정보가 없습니다",
  maternityReader_alertMissingCorralMessage: "전송하기 전에 우리를 입력하세요.",
  maternityReader_alertInvalidCorralTitle: "유효하지 않은 우리",
  maternityReader_alertInvalidCorralMessage: "우리는 숫자여야 합니다. (예: 8)",
  maternityReader_alertError: "오류",
  maternityReader_alertNoIpConfigured: "설정된 IP가 없습니다.",
  maternityReader_alertWarning: "알림",
  maternityReader_alertSendErrorTitle: "전송 오류",
  maternityReader_alertMissingIdTitle: "ID가 없습니다",
  maternityReader_alertMissingIdMessage: "업데이트하기 전에 새 ID를 입력하세요.",
  maternityReader_alertMissingAssociatedCrotalTitle: "이표가 없습니다",
  maternityReader_alertMissingAssociatedCrotalMessage: "업데이트할 연결된 이표가 없습니다.",
  maternityReader_alertInvalidAssociatedCrotalTitle: "유효하지 않은 이표",
  maternityReader_alertInvalidAssociatedCrotalMessage: "연결된 이표가 유효하지 않습니다.",
  maternityReader_alertUpdateIdErrorTitle: "ID 업데이트 오류",
  maternityReader_animalInfoTitle: "동물 정보",
  maternityReader_animalInfoDescription: "검색에서 찾은 데이터입니다.",
  maternityReader_animalCardTitle: "동물 정보",
  maternityReader_animalIdLabel: "ID",
  maternityReader_animalCrotalLabel: "이표",
  maternityReader_fieldCorral: "우리",
  maternityReader_fieldHouse: "동",
  maternityReader_fieldState: "상태",
  maternityReader_fieldBodyCondition: "체형 상태",
  maternityReader_fieldCycle: "주기",
  maternityReader_fieldSystemEntryDate: "시스템 등록일",
  maternityReader_newSearch: "새 검색",
  maternityReader_summaryTitle: "요약",
  maternityReader_summaryDescription: "설정에서 선택한 매개변수",
  maternityReader_mode: "모드",
  maternityReader_modeEntry: "입장",
  maternityReader_modeExit: "퇴장",
  maternityReader_modeReading: "읽기",
  maternityReader_corral: "우리",
  maternityReader_detectUnknownTitle: "미확인 동물 식별",
  maternityReader_detectUnknownDescription: "ID가 없는 동물이 나오면 ID를 할당할 수 있습니다.",
  maternityReader_confirmSendTitle: "전송 확인",
  maternityReader_confirmSendDescription: "각 기록을 전송하기 전에 확인을 요청합니다.",
  maternityReader_changeSettings: "설정 변경",
  maternityReader_currentReadingTitle: "현재 읽기",
  maternityReader_currentReadingDescription: "감지된 이표가 여기에 표시됩니다.",
  maternityReader_awrDisconnected: "AWR 연결 안 됨",
  maternityReader_readCrotal: "읽은 이표",
  maternityReader_readId: "ID",
  maternityReader_animalWithoutAssignedId: "ID가 할당되지 않은 동물",
  maternityReader_unknownAnimal: "알 수 없는 동물",
  maternityReader_animalWithoutIdTitle: "ID 없는 동물",
  maternityReader_animalWithoutIdDescription: "읽은 이표를 업데이트하려면 수동 ID를 입력하세요.",
  maternityReader_newIdLabel: "새 ID",
  maternityReader_newIdPlaceholder: "예: A13",
  maternityReader_updatingId: "업데이트 중...",
  maternityReader_updateId: "ID 업데이트",
  maternityReader_sentRecordsTitle: "전송된 기록",
  maternityReader_tableHeaderCorral: "우리",
  maternityReader_tableHeaderId: "ID",
  maternityReader_tableHeaderCrotal: "이표",
  maternityReader_noRecords: "기록이 없습니다.",
  maternityReader_buttonAutoReading: "자동 읽기 활성화",
  maternityReader_buttonAutoSending: "자동 전송 활성화",
  maternityReader_buttonSending: "전송 중...",
  maternityReader_buttonSend: "전송",

  awrScanResults_title: "AWR – 스캔 결과",
  awrScanResults_searching: "AWR 검색 중…",
  awrScanResults_warningTitle: "경고",
  awrScanResults_noDevicesNearby: "근처에서 AWR을 찾을 수 없습니다.",
  awrScanResults_connecting: "연결 중…",
  awrScanResults_connectErrorFallback: "연결할 수 없습니다",
  awrScanResults_connectedTitle: "연결됨",
  awrScanResults_connectedMessage: "{{device}}에 연결되었습니다.",
  awrScanResults_genericDevice: "장치",

  awrSavedList_title: "스캔된 AWR",
  awrSavedList_connecting: "연결 중…",
  awrSavedList_empty: "저장된 AWR가 없습니다. “Configuración AWR”에서 하나를 스캔하세요.",
  awrSavedList_connected: "연결됨",
  awrSavedList_disconnected: "연결 안 됨",
  awrSavedList_renameAccessibility: "이름 변경",
  awrSavedList_deleteAccessibility: "삭제",
  awrSavedList_renameTitle: "AWR 이름 변경",
  awrSavedList_nameLabel: "이름",
  awrSavedList_deleteTitle: "저장된 AWR 삭제",
  awrSavedList_deleteMessage: "이 AWR를 목록에서 삭제하시겠습니까?",
  awrSavedList_deleteAction: "삭제",

  ipConfig_title: "IP 설정",
  ipConfig_cardTitle: "CTIFEED 서버",
  ipConfig_cardDescription: "포털이 열릴 서버의 IP를 입력하세요.",
  ipConfig_inputLabel: "IP (IP만)",
  ipConfig_saved: "저장됨",
  ipConfig_alertSuccessTitle: "정상",
  ipConfig_alertSuccessMessage: "올바른 IP입니다",
  ipConfig_alertWarningTitle: "경고",
  ipConfig_alertServerNotUpdated: "서버가 업데이트되지 않았습니다",
  ipConfig_alertErrorTitle: "오류",
  ipConfig_alertInvalidIp: "유효하지 않은 IP",

  portal_preparing: "포털 준비 중...",
  portal_noSessionToken: "세션 토큰이 없습니다. 다시 로그인해 주세요.",
  portal_noIpConfigured: "설정된 IP가 없습니다. 먼저 서버 IP를 설정해 주세요.",
  portal_prepareUrlError: "포털 URL을 준비할 수 없습니다.",
  portal_loadError: "포털을 불러올 수 없습니다.",
  portal_checkingConnection: "포털 연결을 확인하는 중...",
  portal_noConnectionTitle: "연결 없음",
  portal_connectionTimeout: "포털에 연결할 수 없습니다. 올바른 네트워크에 연결되어 있는지 확인해 주세요.",
  portal_connectionError: "포털에 연결할 수 없습니다. 네트워크 또는 설정된 IP를 확인해 주세요.",
  portal_httpError: "포털을 열 수 없습니다. HTTP 오류 {{status}}.",
  portal_retry: "다시 시도",
  portal_loading: "포털 불러오는 중...",

  AltaDispositivos: "장치 등록",
  LectorMaternidad: "모성 리더기",
  LectorGestacion: "임신 리더기",
  ConfiguracionIP: "IP 설정",
  ConfiguracionAWR: "AWR 설정",
  DarDeAltaAWR: "AWR 등록",
  AWREscaneados: "스캔된 AWR",
  CerrarSesion: "로그아웃",

  Config_lastReadMismatchTitle: "읽은 동물이 검색 결과와 일치하지 않습니다",
  Config_lastReadMismatchCrotal: "귀표",
  Config_lastReadMismatchId: "ID",
  awrBluetoothPermissionMessage: "스캔하려면 Bluetooth를 켜고 권한을 허용하세요.",



};