export default {
  username: 'Пользователь',
  password: 'Пароль',
  login: 'Войти',
  welcome: 'Добро пожаловать',
  change_language: 'Сменить язык',
  Tabs: 'Главная',

  Lista_instalaciones: 'Установки',
  Maintenance: 'Техническое обслуживание',
  DetallesInstalacion: 'Детали установки',
  Grabar: 'Сохранить',
  EstadoStore: 'Статус store',
  Nodata: 'Нет данных',
  DosimacRegistration: 'Регистрация',
  NewDmMaternity: 'Новый Dosimac родильное',
  DosimacG: 'Dosimac-G',
  DosimacI: 'Dosimac-I',
  UpdDmMaternity: 'Изменение Dosimac родильное',
  NewDmGestation: 'Новый Dosimac беременность',
  UpdDmGestation: 'Изменение Dosimac беременность',
  StartScan: 'Поиск устройств DOSIMAC',
  DosimacList: 'Устройства DOSIMAC',
  PressToScan: 'Нажмите',
  DosimacSetup: 'Конфигурация',
  TestoPresioneAlta: 'Нажмите кнопку, чтобы найти устройства',
  Instalación_seleccionada: 'Выбранная установка',
  NoInstalacionSeleccionada: 'Нет выбранной установки',
  BorrarGranja: 'Удалить ферму',
  Deseaborrarlagranja: 'Хотите удалить ферму?',
  Guardar: 'Сохранить',
  Cancelar: 'Отмена',
  Aceptar: 'Принять',
  NombreGranja: 'Название фермы',
  Localidad: 'Местоположение',
  Provincia: 'Область',
  NombreWifi: 'Wifi SSID',
  PasswordWifi: 'Пароль Wifi',
  No_hay_dispositivos: 'Нет устройств',
  Aviso: 'Уведомление',
  SearchingDevices: 'Поиск устройств...',
  NoSePuedeBorrarGranja: 'Нельзя удалить новую ферму',
  settings: 'Настройки',
  softwareVersion: 'Версия ПО',
  numeroCoral: 'Номер загона',
  numeroMaquina: 'Номер машины',
  Enviar: 'Отправить',
  Salir: 'Выйти',
  Informacion: 'Информация',
  InicioConfiguracion: "Инициация подключения",
  ConfiguracionWifi: "Настройка...",
  ConfiguracionRealizada: "*Настройка выполнена*",
  ErrorConfiguracion: "*Ошибка настройки*",
  CapturaTagCorral: "Считать метку загона",
  CorralTag: "Метка загона",
  versionUint16: "Эта версия устройства поддерживает номер загона только до 65000",
  versionUint32: "Эта версия устройства поддерживает номер загона до 4000000000",
  EnvioConfiguracion: "Отправка конфигурации",
  NumeroCorral: "Номер загона",
  NumeroMaquina: "Номер машины",
  Corralnovalida: "Недопустимый номер загона",
  NumeroMaquinanovalida: "Недопустимый номер машины",
  configuarIntalacion: "Необходимо настроить установку перед использованием этой функции",

  login_title: "Войти",
  login_subtitle: "Введите свои данные. Перед входом необходимо настроить IP в меню Настройка IP.",
  login_username: "Пользователь",
  login_password: "Пароль",
  login_button: "Войти",
  login_loading: "Вход...",
  login_footer: "Панель управления",

  login_ipRequiredTitle: "Требуется настройка IP",
  login_ipRequiredMessage: "Вы не настроили IP-адрес сервера. Введите его, чтобы войти.",
  login_serverIpLabel: "IP сервера",
  login_cancel: "Отмена",
  login_accept: "Принять",
  login_invalidCredentials: "Неверное имя пользователя или пароль",

  login_configTitle: "Настройка",
  login_errorTitle: "Ошибка входа",
  login_genericErrorTitle: "Ошибка",
  login_networkErrorTitle: "Ошибка сети",
  login_networkErrorMessage: "Не удалось подключиться к серверу.",
  login_noTokenMessage: "Бэкенд не вернул токен.",
  login_missingDataTitle: "Отсутствуют данные",
  login_missingDataMessage: "Введите имя пользователя и пароль.",
  login_invalidIpTitle: "Неверный IP",
  login_invalidIpMessage: "Введите корректный IP или адрес сервера.",
  login_saveIpErrorMessage: "Не удалось сохранить настройки IP.",

  awrStartScan_title: "Настройки AWR",
  awrStartScan_description: "Экран для сканирования считывателей Agrident AWR.",
  awrStartScan_button: "Сканировать AWR",

  gestacionConfig_screenTitle: "Настройки гестации",
  gestacionConfig_chooseOptionTitle: "Выберите вариант",
  gestacionConfig_chooseOptionDescription: "Определите поток перед началом работы со считывателем.",

  gestacionConfig_entry: "Вход",
  gestacionConfig_exit: "Выход",
  gestacionConfig_reading: "Считывание",
  gestacionConfig_search: "Поиск",

  gestacionConfig_entryParamsTitle: "Параметры входа",
  gestacionConfig_exitParamsTitle: "Параметры выхода",
  gestacionConfig_entryParamsDescription: "Выберите загон и поведение потока.",
  gestacionConfig_exitParamsDescription: "Настройте поведение потока выхода.",

  gestacionConfig_corralLabel: "Загон",
  gestacionConfig_corralPlaceholder: "Напр.: 1",
  gestacionConfig_corralRequired: "Введите загон, чтобы продолжить.",

  gestacionConfig_detectUnknownTitle: "Определять неизвестных животных",
  gestacionConfig_detectUnknownDescription: "Когда вы считаете неидентифицированное животное, вы сможете назначить ему ID",

  gestacionConfig_confirmTitle: "Подтвердить отправку",
  gestacionConfig_confirmDescription: "Перед отправкой записей будет запрошено подтверждение.",

  gestacionConfig_animalSearchTitle: "Поиск животного",
  gestacionConfig_animalSearchDescription: "Выберите поиск по бирке или по ID.",
  gestacionConfig_searchByCrotal: "По бирке",
  gestacionConfig_searchById: "По ID",
  gestacionConfig_manual: "Вручную",
  gestacionConfig_withSword: "Со сканером",

  gestacionConfig_crotalLabelSearch: "Бирка",
  gestacionConfig_idLabelSearch: "ID",
  gestacionConfig_crotalPlaceholderSearch: "Напр.: 982091072397436",
  gestacionConfig_idPlaceholderSearch: "Напр.: A13",
  gestacionConfig_crotalRequiredSearch: "Введите бирку, чтобы продолжить.",
  gestacionConfig_idRequiredSearch: "Введите ID, чтобы продолжить.",

  gestacionConfig_searchWithSwordHelp: "После продолжения на этом экране будет выполнено считывание сканером, и животное будет найдено по этой бирке.",

  gestacionConfig_readingSword: "Считывание сканером...",
  gestacionConfig_waitingMatch: "Ожидание совпадения",
  gestacionConfig_searchingAnimal: "Поиск животного...",

  gestacionConfig_readingSwordDescription: "Поднесите бирку к считывателю, чтобы идентифицировать животное.",
  gestacionConfig_waitingMatchDescription: "Животное найдено. Теперь поднесите к сканеру бирку {{crotal}}, чтобы подтвердить совпадение.",
  gestacionConfig_searchingAnimalDescription: "Проверка информации о животном в backend.",

  gestacionConfig_awrDisconnectedTitle: "AWR не подключён",
  gestacionConfig_awrSavedDescription: "У вас есть сохранённые сканеры. Нажмите, чтобы выбрать один.",
  gestacionConfig_awrNotSavedDescription: "У вас нет сохранённых сканеров. Нажмите, чтобы отсканировать один.",

  gestacionConfig_scan: "Сканировать",
  gestacionConfig_continue: "Продолжить",

  gestacionConfig_alerts_error: "Ошибка",
  gestacionConfig_alerts_networkError: "Ошибка сети",
  gestacionConfig_alerts_networkErrorMessage: "Не удалось подключиться к серверу.",
  gestacionConfig_alerts_backendNoValidCrotal: "Backend не вернул корректную бирку для сравнения.",
  gestacionConfig_alerts_awrNotConnected: "AWR не подключён",
  gestacionConfig_alerts_connectSwordBeforeContinue: "Подключите сканер перед продолжением.",
  gestacionConfig_alerts_couldNotStartReading: "Не удалось начать считывание сканером.",

  gestacionConfig_alerts_missingData: "Недостаточно данных",
  gestacionConfig_alerts_writeCrotalToSearch: "Введите бирку для поиска.",
  gestacionConfig_alerts_writeIdToSearch: "Введите ID для поиска.",

  gestacionConfig_alerts_notFound: "Не найдено",
  gestacionConfig_alerts_animalNotFoundByCrotal: "Животное с такой биркой не существует.",
  gestacionConfig_alerts_animalNotFoundById: "Животное с таким ID не существует.",

  gestacionConfig_alerts_warning: "Предупреждение",
  gestacionConfig_alerts_searchError: "Ошибка поиска",

  maternidadConfig_screenTitle: "Настройки материнского отделения",
  maternidadConfig_chooseOptionTitle: "Выберите вариант",
  maternidadConfig_chooseOptionDescription: "Определите поток перед началом работы со считывателем.",
  maternidadConfig_entry: "Вход",
  maternidadConfig_exit: "Выход",
  maternidadConfig_reading: "Считывание",
  maternidadConfig_search: "Поиск",
  maternidadConfig_entryParamsTitle: "Параметры входа",
  maternidadConfig_exitParamsTitle: "Параметры выхода",
  maternidadConfig_entryParamsDescription: "Выберите загон и поведение потока.",
  maternidadConfig_exitParamsDescription: "Настройте поведение потока выхода.",
  maternidadConfig_corralLabel: "Загон",
  maternidadConfig_corralPlaceholder: "Напр.: 1",
  maternidadConfig_corralRequired: "Введите загон, чтобы продолжить.",
  maternidadConfig_detectUnknownTitle: "Определять неизвестных животных",
  maternidadConfig_detectUnknownDescription: "При считывании неидентифицированного животного вы сможете назначить ему ID",
  maternidadConfig_confirmTitle: "Подтверждать отправку",
  maternidadConfig_confirmDescription: "Перед отправкой каждой записи будет запрашиваться подтверждение.",
  maternidadConfig_animalSearchTitle: "Поиск животного",
  maternidadConfig_animalSearchDescription: "Выберите поиск по crotal или по ID.",
  maternidadConfig_searchByCrotal: "По crotal",
  maternidadConfig_searchById: "По ID",
  maternidadConfig_manual: "Вручную",
  maternidadConfig_withSword: "Со сканером",
  maternidadConfig_crotalLabelSearch: "Crotal",
  maternidadConfig_idLabelSearch: "ID",
  maternidadConfig_crotalPlaceholderSearch: "Напр.: 982091072397436",
  maternidadConfig_idPlaceholderSearch: "Напр.: A13",
  maternidadConfig_crotalRequiredSearch: "Введите crotal, чтобы продолжить.",
  maternidadConfig_idRequiredSearch: "Введите ID, чтобы продолжить.",
  maternidadConfig_searchWithSwordHelp: "При нажатии Сканировать сканер будет использоваться на этом экране, и животное будет найдено по этому crotal.",
  maternidadConfig_readingSword: "Считывание сканера...",
  maternidadConfig_waitingMatch: "Ожидание совпадения",
  maternidadConfig_searchingAnimal: "Поиск животного...",
  maternidadConfig_readingSwordDescription: "Поднесите crotal к считывателю, чтобы определить животное.",
  maternidadConfig_waitingMatchDescription: "Животное найдено. Теперь поднесите crotal {{crotal}} к сканеру, чтобы подтвердить совпадение.",
  maternidadConfig_searchingAnimalDescription: "Получение информации о животном из backend.",
  maternidadConfig_awrDisconnectedTitle: "AWR не подключен",
  maternidadConfig_awrSavedDescription: "У вас есть сохранённые AWR. Нажмите, чтобы выбрать одну.",
  maternidadConfig_awrNotSavedDescription: "У вас нет сохранённых AWR. Нажмите, чтобы просканировать одну.",
  maternidadConfig_scan: "Сканировать",
  maternidadConfig_continue: "Продолжить",
  maternidadConfig_alert_error: "Ошибка",
  maternidadConfig_alert_invalidBackendCrotal: "Backend не вернул корректный crotal для сравнения.",
  maternidadConfig_alert_awrNotConnected: "AWR не подключен",
  maternidadConfig_alert_connectSwordBeforeContinue: "Подключите сканер перед продолжением.",
  maternidadConfig_alert_couldNotStartReading: "Не удалось начать считывание со сканером.",
  maternidadConfig_alert_missingData: "Не хватает данных",
  maternidadConfig_alert_writeCrotalToSearch: "Введите crotal для поиска.",
  maternidadConfig_alert_writeIdToSearch: "Введите ID для поиска.",
  maternidadConfig_alert_notFound: "Не найдено",
  maternidadConfig_alert_noAnimalWithCrotal: "Животное с таким crotal не найдено.",
  maternidadConfig_alert_noAnimalWithId: "Животное с таким ID не найдено.",
  maternidadConfig_alert_warning: "Предупреждение",
  maternidadConfig_alert_searchError: "Ошибка поиска",
  maternidadConfig_alert_networkError: "Ошибка сети",
  maternidadConfig_alert_networkErrorMessage: "Не удалось подключиться к серверу.",

  gestationReader_screenTitle: "Считыватель гестации",
  gestationReader_animalInfoTitle: "Информация о животном",
  gestationReader_animalInfoDescription: "Данные, найденные при поиске.",
  gestationReader_animalCardTitle: "Карточка животного",
  gestationReader_animalIdLabel: "ID",
  gestationReader_animalCrotalLabel: "Бирка",
  gestationReader_fieldCorral: "Загон",
  gestationReader_fieldHouse: "Корпус",
  gestationReader_fieldState: "Состояние",
  gestationReader_fieldBodyCondition: "Физическое состояние",
  gestationReader_fieldCycle: "Цикл",
  gestationReader_fieldSystemEntryDate: "Дата входа в систему",
  gestationReader_newSearch: "Новый поиск",
  gestationReader_summaryTitle: "Сводка",
  gestationReader_summaryDescription: "Параметры, выбранные в настройках",
  gestationReader_mode: "Режим",
  gestationReader_corral: "Загон",
  gestationReader_modeEntry: "Вход",
  gestationReader_modeExit: "Выход",
  gestationReader_modeReading: "Считывание",
  gestationReader_modeSearch: "Поиск",
  gestationReader_detectUnknownTitle: "Определять неизвестных животных",
  gestationReader_detectUnknownDescription: "Если появится животное без ID, предложить назначить ему ID.",
  gestationReader_confirmSendTitle: "Подтверждать отправку",
  gestationReader_confirmSendDescription: "Перед отправкой каждой записи будет запрашиваться подтверждение.",
  gestationReader_changeSettings: "Изменить настройки",
  gestationReader_currentReadingTitle: "Текущее считывание",
  gestationReader_currentReadingDescription: "Здесь будут отображаться обнаруженная бирка и связанный ID.",
  gestationReader_awrDisconnected: "AWR не подключен",
  gestationReader_readCrotal: "Считанная бирка",
  gestationReader_readId: "ID",
  gestationReader_animalWithoutAssignedId: "Животное без назначенного ID",
  gestationReader_unknownAnimal: "Неизвестное животное",
  gestationReader_animalWithoutIdTitle: "Животное без ID",
  gestationReader_animalWithoutIdDescription: "Введите ID вручную, чтобы обновить считанную бирку.",
  gestationReader_newIdLabel: "Новый ID",
  gestationReader_newIdPlaceholder: "Пр.: A13",
  gestationReader_updateId: "Обновить ID",
  gestationReader_updatingId: "Обновление...",
  gestationReader_sentRecordsTitle: "Отправленные записи",
  gestationReader_noRecords: "Нет записей.",
  gestationReader_tableHeaderCorral: "Загон",
  gestationReader_tableHeaderId: "ID",
  gestationReader_tableHeaderCrotal: "Бирка",
  gestationReader_buttonAutoReading: "Автоматическое считывание активно",
  gestationReader_buttonAutoSending: "Автоматическая отправка активна",
  gestationReader_buttonSending: "Отправка...",
  gestationReader_buttonSend: "Отправить",
  gestationReader_alertError: "Ошибка",
  gestationReader_alertWarning: "Предупреждение",
  gestationReader_alertNetworkError: "Ошибка сети",
  gestationReader_alertMissingCrotalTitle: "Отсутствует бирка",
  gestationReader_alertMissingCrotalMessage: "Поднесите бирку к считывателю перед отправкой.",
  gestationReader_alertInvalidCrotalTitle: "Некорректная бирка",
  gestationReader_alertInvalidCrotalMessage: "Бирка должна быть числовой.",
  gestationReader_alertReadErrorTitle: "Ошибка считывания",
  gestationReader_alertNetworkErrorMessage: "Не удалось подключиться к серверу.",
  gestationReader_alertMissingCorralTitle: "Отсутствует загон",
  gestationReader_alertMissingCorralMessage: "Введите загон перед отправкой.",
  gestationReader_alertInvalidCorralTitle: "Некорректный загон",
  gestationReader_alertInvalidCorralMessage: "Загон должен быть числом.",
  gestationReader_alertSendErrorTitle: "Ошибка при отправке",
  gestationReader_alertNoIpConfigured: "IP не настроен.",
  gestationReader_alertMissingIdTitle: "Отсутствует ID",
  gestationReader_alertMissingIdMessage: "Введите новый ID перед обновлением.",
  gestationReader_alertMissingAssociatedCrotalTitle: "Отсутствует бирка",
  gestationReader_alertMissingAssociatedCrotalMessage: "Нет связанной бирки для обновления.",
  gestationReader_alertInvalidAssociatedCrotalTitle: "Некорректная бирка",
  gestationReader_alertInvalidAssociatedCrotalMessage: "Связанная бирка недействительна.",
  gestationReader_alertUpdateIdErrorTitle: "Ошибка при обновлении ID",
  gestationReader_readerMode: "Считыватель",
gestationReader_keyboardMode: "Клавиатура",

gestationReader_keyboardEntryTitle: "Ввод с клавиатуры",
gestationReader_keyboardExitTitle: "Вывод с клавиатуры",
gestationReader_keyboardDescription: "Введите данные вручную с клавиатуры телефона.",
gestationReader_keyboardId: "ID",
gestationReader_keyboardCrotal: "Бирка",
gestationReader_keyboardIdLabel: "ID животного",
gestationReader_keyboardCrotalLabel: "Бирка",
gestationReader_keyboardIdPlaceholder: "Введите ID",
gestationReader_keyboardCrotalPlaceholder: "Введите бирку",
gestationReader_keyboardAdd: "Добавить",
gestationReader_keyboardAdding: "Добавление...",

gestationReader_pendingRecordsTitle: "Неотправленные записи",
gestationReader_buttonSendingBatch: "Отправка партии...",
gestationReader_buttonSendBatch: "Отправить партию",
gestationReader_buttonSendBatchCount: "Отправить партию ({{count}})",

gestationReader_noPendingRecordsTitle: "Нет записей",
gestationReader_noPendingRecordsText: "Нет записей, ожидающих отправки.",
gestationReader_batchSentTitle: "Партия отправлена",
gestationReader_batchSentText: "{{count}} запись(ей) успешно отправлено.",
gestationReader_batchWithErrorsTitle: "Партия с ошибками",

gestationReader_recordSentTitle: "Запись отправлена",
gestationReader_recordSentText: "Перемещение успешно отправлено.",

gestationReader_invalidAnimalId: "ID животного недействителен.",
gestationReader_invalidPenRecord: "Станок записи недействителен.",
gestationReader_invalidCrotalRecord: "Бирка записи недействительна.",
gestationReader_duplicateIdPending: "ID {{id}} уже есть в таблице неотправленных записей.",
gestationReader_duplicateCrotalPending: "Бирка {{crotal}} уже есть в таблице неотправленных записей.",
gestationReader_keyboardMissingId: "Введите ID животного.",
gestationReader_keyboardMissingCrotal: "Введите бирку животного.",
gestationReader_keyboardMissingPen: "Выберите действительный станок перед добавлением животного.",
gestationReader_noAnimalById: "Животного с ID {{id}} не существует.",
gestationReader_noAnimalByCrotal: "Животного с биркой {{crotal}} не существует.",
gestationReader_addAnimalError: "Не удалось добавить животное.",

gestationReader_pendingAnimalHint: "Считанные животные появятся здесь.",

gestationReader_changePenTitle: "Изменить станок",
gestationReader_changePenDescription: "Введите новый станок для ввода.",
gestationReader_newPenLabel: "Новый станок",
gestationReader_newPenPlaceholder: "Напр.: 1",
gestationReader_cancel: "Отмена",
gestationReader_save: "Сохранить",
gestationReader_accept: "Принять",
gestationReader_sentHistoryTitle: "История отправленных",

  maternityReader_screenTitle: "Считыватель материнского отделения",
  maternityReader_alertMissingCrotalTitle: "Отсутствует бирка",
  maternityReader_alertMissingCrotalMessage: "Поднесите бирку к считывателю перед отправкой.",
  maternityReader_alertInvalidCrotalTitle: "Неверная бирка",
  maternityReader_alertInvalidCrotalMessage: "Бирка должна быть числовой.",
  maternityReader_alertReadErrorTitle: "Ошибка чтения",
  maternityReader_alertNetworkError: "Ошибка сети",
  maternityReader_alertNetworkErrorMessage: "Не удалось подключиться к серверу.",
  maternityReader_alertMissingCorralTitle: "Отсутствует загон",
  maternityReader_alertMissingCorralMessage: "Введите загон перед отправкой.",
  maternityReader_alertInvalidCorralTitle: "Неверный загон",
  maternityReader_alertInvalidCorralMessage: "Загон должен быть числом (например: 8).",
  maternityReader_alertError: "Ошибка",
  maternityReader_alertNoIpConfigured: "IP не настроен.",
  maternityReader_alertWarning: "Предупреждение",
  maternityReader_alertSendErrorTitle: "Ошибка отправки",
  maternityReader_alertMissingIdTitle: "Отсутствует ID",
  maternityReader_alertMissingIdMessage: "Введите новый ID перед обновлением.",
  maternityReader_alertMissingAssociatedCrotalTitle: "Отсутствует бирка",
  maternityReader_alertMissingAssociatedCrotalMessage: "Нет связанной бирки для обновления.",
  maternityReader_alertInvalidAssociatedCrotalTitle: "Неверная бирка",
  maternityReader_alertInvalidAssociatedCrotalMessage: "Связанная бирка недействительна.",
  maternityReader_alertUpdateIdErrorTitle: "Ошибка обновления ID",
  maternityReader_animalInfoTitle: "Информация о животном",
  maternityReader_animalInfoDescription: "Данные, найденные при поиске.",
  maternityReader_animalCardTitle: "Карточка животного",
  maternityReader_animalIdLabel: "ID",
  maternityReader_animalCrotalLabel: "Бирка",
  maternityReader_fieldCorral: "Загон",
  maternityReader_fieldHouse: "Корпус",
  maternityReader_fieldState: "Состояние",
  maternityReader_fieldBodyCondition: "Телесное состояние",
  maternityReader_fieldCycle: "Цикл",
  maternityReader_fieldSystemEntryDate: "Дата внесения в систему",
  maternityReader_newSearch: "Новый поиск",
  maternityReader_summaryTitle: "Сводка",
  maternityReader_summaryDescription: "Параметры, выбранные в настройках",
  maternityReader_mode: "Режим",
  maternityReader_modeEntry: "Вход",
  maternityReader_modeExit: "Выход",
  maternityReader_modeReading: "Чтение",
  maternityReader_corral: "Загон",
  maternityReader_detectUnknownTitle: "Определять неизвестных животных",
  maternityReader_detectUnknownDescription: "Если появляется животное без ID, можно назначить ему ID.",
  maternityReader_confirmSendTitle: "Подтверждать отправку",
  maternityReader_confirmSendDescription: "Перед отправкой каждой записи будет запрашиваться подтверждение.",
  maternityReader_changeSettings: "Изменить настройки",
  maternityReader_currentReadingTitle: "Текущее считывание",
  maternityReader_currentReadingDescription: "Обнаруженная бирка появится здесь.",
  maternityReader_awrDisconnected: "AWR не подключён",
  maternityReader_readCrotal: "Считанная бирка",
  maternityReader_readId: "ID",
  maternityReader_animalWithoutAssignedId: "Животное без назначенного ID",
  maternityReader_unknownAnimal: "Неизвестное животное",
  maternityReader_animalWithoutIdTitle: "Животное без ID",
  maternityReader_animalWithoutIdDescription: "Введите ID вручную, чтобы обновить считанную бирку.",
  maternityReader_newIdLabel: "Новый ID",
  maternityReader_newIdPlaceholder: "Напр.: A13",
  maternityReader_updatingId: "Обновление...",
  maternityReader_updateId: "Обновить ID",
  maternityReader_sentRecordsTitle: "Отправленные записи",
  maternityReader_tableHeaderCorral: "Загон",
  maternityReader_tableHeaderId: "ID",
  maternityReader_tableHeaderCrotal: "Бирка",
  maternityReader_noRecords: "Нет записей.",
  maternityReader_buttonAutoReading: "Автоматическое чтение активно",
  maternityReader_buttonAutoSending: "Автоматическая отправка активна",
  maternityReader_buttonSending: "Отправка...",
  maternityReader_buttonSend: "Отправить",

  awrScanResults_title: "AWR – Результаты сканирования",
  awrScanResults_searching: "Поиск AWR…",
  awrScanResults_warningTitle: "Предупреждение",
  awrScanResults_noDevicesNearby: "Близлежащие устройства AWR не найдены.",
  awrScanResults_connecting: "Подключение…",
  awrScanResults_connectErrorFallback: "Не удалось подключиться",
  awrScanResults_connectedTitle: "Подключено",
  awrScanResults_connectedMessage: "Соединение установлено с {{device}}.",
  awrScanResults_genericDevice: "устройством",

  awrSavedList_title: "Сканированные AWR",
  awrSavedList_connecting: "Подключение…",
  awrSavedList_empty: "Нет сохранённых AWR. Отсканируйте один в разделе «Configuración AWR».",
  awrSavedList_connected: "Подключено",
  awrSavedList_disconnected: "Отключено",
  awrSavedList_renameAccessibility: "Переименовать",
  awrSavedList_deleteAccessibility: "Удалить",
  awrSavedList_renameTitle: "Переименовать AWR",
  awrSavedList_nameLabel: "Имя",
  awrSavedList_deleteTitle: "Удалить сохранённый AWR",
  awrSavedList_deleteMessage: "Вы уверены, что хотите удалить этот AWR из списка?",
  awrSavedList_deleteAction: "Удалить",

  ipConfig_title: "Настройка IP",
  ipConfig_cardTitle: "Сервер CTIFEED",
  ipConfig_cardDescription: "Введите IP сервера, на котором будет открыт портал.",
  ipConfig_inputLabel: "IP (только IP)",
  ipConfig_saved: "Сохранено",
  ipConfig_alertSuccessTitle: "Успешно",
  ipConfig_alertSuccessMessage: "IP корректный",
  ipConfig_alertWarningTitle: "Предупреждение",
  ipConfig_alertServerNotUpdated: "Сервер не обновлён",
  ipConfig_alertErrorTitle: "Ошибка",
  ipConfig_alertInvalidIp: "Неверный IP",

  portal_preparing: "Подготовка портала...",
  portal_noSessionToken: "Нет токена сессии. Войдите в систему снова.",
  portal_noIpConfigured: "IP-адрес не настроен. Сначала настройте IP-адрес сервера.",
  portal_prepareUrlError: "Не удалось подготовить URL портала.",
  portal_loadError: "Не удалось загрузить портал.",
  portal_checkingConnection: "Проверка подключения к порталу...",
  portal_noConnectionTitle: "Нет подключения",
  portal_connectionTimeout: "Не удалось подключиться к порталу. Проверьте, подключены ли вы к правильной сети.",
  portal_connectionError: "Не удалось подключиться к порталу. Проверьте сеть или настроенный IP-адрес.",
  portal_httpError: "Не удалось открыть портал. Ошибка HTTP {{status}}.",
  portal_retry: "Повторить",
  portal_loading: "Загрузка портала...",

  AltaDispositivos: "Регистрация устройств",
  LectorMaternidad: "Считыватель материнского отделения",
  LectorGestacion: "Считыватель гестации",
  ConfiguracionIP: "Настройки IP",
  ConfiguracionAWR: "Настройки AWR",
  DarDeAltaAWR: "Зарегистрировать AWR",
  AWREscaneados: "Отсканированные AWR",
  CerrarSesion: "Выйти",

  Config_lastReadMismatchTitle: "Считанное животное не совпадает с результатом поиска",
  Config_lastReadMismatchCrotal: "Ушная бирка",
  Config_lastReadMismatchId: "ID",
  awrBluetoothPermissionMessage: "Включите Bluetooth и примите разрешение, чтобы можно было сканировать.",

  animalState: {
    gestation: "Гестация",
    maternity: "Материнство",
    out_of_gestation: "Вне гестации",
    out_of_maternity: "Вне материнства"
  },


  Reader_readingTitle: "Считывание бирок",
  Reader_labelId: "ID",
  Reader_labelCrotal: "Бирка",
  Reader_labelCorral: "Загон",
  Reader_labelHouse: "Корпус",
  Reader_labelState: "Состояние",
  Reader_autoReadingBadge: "Автоматическое считывание",

  gestacionConfig_flowSectionTitle: "Настройка процесса",
  gestacionConfig_workModeTitle: "Режим работы",
  gestacionConfig_workModeDescription: "Выберите, что будет делать считыватель.",
  gestacionConfig_entryDescription: "Зарегистрировать вход",
  gestacionConfig_exitDescription: "Зарегистрировать выход",
  gestacionConfig_readingDescription: "Только просмотр",
  gestacionConfig_searchDescription: "Найти животное",

  gestacionConfig_sendSettingsTitle: "Настройки отправки",
  gestacionConfig_sendSettingsDescription: "Настройте поведение процесса при считывании животных.",

  gestacionConfig_corralSectionTitle: "Загон для входа",
  gestacionConfig_corralSectionDescription: "Это поле обязательно для продолжения регистрации.",

  gestacionConfig_alerts_notice: "Уведомление",
  gestacionConfig_alerts_invalidCrotalFromBackend: "Сервер не вернул действительную ушную метку для сравнения.",

  common_accept: "Принять",

  maternidadConfig_flowSectionTitle: "Настройка процесса",
  maternidadConfig_workModeTitle: "Режим работы",
  maternidadConfig_workModeDescription: "Выберите, что будет делать считыватель.",
  maternidadConfig_entryDescription: "Зарегистрировать вход",
  maternidadConfig_exitDescription: "Зарегистрировать выход",
  maternidadConfig_readingDescription: "Только просмотр",
  maternidadConfig_searchDescription: "Найти животное",

  maternidadConfig_sendSettingsTitle: "Настройки отправки",
  maternidadConfig_sendSettingsDescription: "Настройте поведение процесса при считывании животных.",

  maternidadConfig_corralSectionTitle: "Загон для входа",
  maternidadConfig_corralSectionDescription: "Это поле обязательно для продолжения регистрации.",

  maternidadConfig_alert_invalidCrotalFromBackend: "Сервер не вернул действительную ушную метку для сравнения.",

  maternidadConfig_readOnlyTitle: "Разрешение только на чтение",
  maternidadConfig_readOnlyModifySettings: "У этого пользователя есть только права на чтение. Он не может изменять эту конфигурацию.",
  maternidadConfig_readOnlyUseFunction: "У этого пользователя есть только права на чтение. Он не может использовать эту функцию.",


  ajustesEnvioMaternidad: {
    headerTitle: "Настройки отправки",
    headerSubtitle: "Настройте поведение процесса при считывании животных.",
    cardTitle: "Отправка записей",
    cardSubtitle: "Эти настройки применяются при продолжении считывания."
  },


  noAlimentadosMaternidad: {
    animalId: "ИД ЖИВОТНОГО",
    corral: "Загон",
    consumption: "Потребление",
    withoutFeeding: "Без кормления",
    day: "день",
    days: "дней",
    loadingAnimals: "Загрузка животных...",
    title: "Животные без кормления",
    totalAnimalsMaternity: "Всего животных в родильном отделении:",
    notSeen: "Не просмотрены",
    all: "Все",
    sort: "Сортировка",
    emptyTitle: "Нет ожидающих животных",
    emptyText: "В родильном отделении не найдено животных без кормления.",
    sortBy: "Сортировать по",
    daysWithoutFeeding: "Дни без кормления",
    sortDaysHelp: "Сортировать по количеству дней без кормления",
    sortCorralHelp: "Сортировать по номеру загона",
    descending: "По убыванию",
    ascending: "По возрастанию",
    filterAnimals: "Фильтровать животных",
    allHelp: "Показать всех животных",
    unmarked: "Не отмечены",
    unmarkedHelp: "Скрыть уже проверенных животных",
    clearMarkedTitle: "Очистить отмеченных животных",
    clearMarkedText: "Все отметки проверенных животных будут удалены.",
    cancel: "Отмена",
    clear: "Очистить",
    error: "Ошибка",
    serverConnectionError: "Не удалось подключиться к серверу."
  },
  noAlimentadosGestacion: {
    animalId: "ИД ЖИВОТНОГО",
    corral: "Загон",
    consumption: "Потребление",
    withoutFeeding: "Без кормления",
    day: "день",
    days: "дней",
    loadingAnimals: "Загрузка животных...",
    title: "Животные без кормления",
    totalAnimalsGestation: "Всего животных в отделении супоросности:",
    notSeen: "Не просмотрены",
    all: "Все",
    sort: "Сортировка",
    emptyTitle: "Нет ожидающих животных",
    emptyText: "В отделении супоросности не найдено животных без кормления.",
    sortBy: "Сортировать по",
    daysWithoutFeeding: "Дни без кормления",
    sortDaysHelp: "Сортировать по количеству дней без кормления",
    sortCorralHelp: "Сортировать по номеру загона",
    descending: "По убыванию",
    ascending: "По возрастанию",
    filterAnimals: "Фильтровать животных",
    allHelp: "Показать всех животных",
    unmarked: "Не отмечены",
    unmarkedHelp: "Скрыть уже проверенных животных",
    clearMarkedTitle: "Очистить отмеченных животных",
    clearMarkedText: "Все отметки проверенных животных будут удалены.",
    cancel: "Отмена",
    clear: "Очистить",
    error: "Ошибка",
    serverConnectionError: "Не удалось подключиться к серверу."
  },
  capturaAnimalHome: {
    selectOption: "Выберите вариант",
    unfedAnimalsTitle: "Животные без кормления",
    unfedAnimalsDescription: "Просмотр животных, которые не получили запланированное кормление.",
    twoFeedsTitle: "2 корма",
    twoFeedsDescription: "Управление сменой корма в выпускных отверстиях.",
    birthCaptureTitle: "Регистрация опороса",
    birthCaptureDescription: "Зарегистрируйте живорождённых, мёртвых и мумифицированных поросят.",
  },
  cambioPiensoMaternidad: {
    error: "Ошибка",
    loadTasksError: "Не удалось загрузить задачи смены корма.",
    loadingTasks: "Загрузка задач...",
    title: "Смена корма",
    pendingTask: "{{count}} ожидающая задача",
    pendingTasks: "{{count}} ожидающих задач",
    emptyTitle: "Нет ожидающих задач",
    emptyText: "Задачи смены корма не найдены.",
    animalId: "ИД ЖИВОТНОГО",
    corral: "Загон",
    setTo: "Установить на",
    destination: "Назначение"
  },
  estadoAnimal: {
    queryLabel: "Запрос",
    title: "Состояние животного",
    subtitle: "Выберите, как вы хотите идентифицировать животное.",
    corral: "Загон",
    corralDescription: "Введите номер загона.",
    id: "ID",
    idDescription: "Введите идентификатор животного.",
    animalId: "ID животного",
    requiredData: "Обязательные данные",
    enterCorral: "Введите номер загона.",
    enterId: "Введите идентификатор животного.",
    consulting: "Проверка...",
    continue: "Продолжить",
    accept: "Принять",
    serverConnectionError: "Не удалось подключиться к серверу.",
    noIpConfigured: "IP-адрес не настроен.",
    nextScreenPending: "Экран информации о животном мы создадим на следующем шаге.",
    corralMaternityDescription: "Введите номер станка в маточнике.",
idAnimalDescription: "Поиск животного в маточнике и супоросности.",
animalNotFound: "Животное не найдено",
  },
  matCorralDetail: {
    readOnlyPermission: "Разрешение только на чтение",
readOnlyPermissionText: "У этого пользователя есть только права на чтение. Он не может выполнять операции с животным.",
    animalStatus: "Состояние животного",
    id: "ID",
    earTag: "Бирка",
    cycle: "Цикл",
    day: "День",

    curve: "Кривая",
    correction: "Коррекция",
    entryDate: "Дата поступления",
    farrowingDate: "Дата опороса",
    house: "Корпус",
    pen: "Станок",
    lastFeeding: "Последнее кормление",
    presentPiglets: "Поросята в наличии",
    inseminationDate: "Дата осеменения",
    teatsNumber: "Кол-во сосков",

    operations: "Операции",

    consumption: "Потребление",
    ofGrams: "из {{amount}} г",
    oneDayWithoutFeeding: "1 день без кормления",
    daysWithoutFeeding: "{{count}} дней без кормления",

    noAnimalData: "Нет данных о животном",
    noAnimalDataText: "Не получена информация для отображения.",
    back: "Назад",
    operationsPendingTitle: "Операции",
    operationsPendingText: "Операции выполним на следующем шаге.",
    moveToWeaning: "Перевести на отъём",
    chooseOption: "Выберите операцию для этого животного.",
    nextOperation: "Следующая операция",
    insertAnimal: "Добавить животное",
    moveToLactation: "Перевести в лактацию",
    nextStep: "Следующий шаг",
    actions: "Действия",

    bodyCondition: "Упитанность",
    subState: "Подсостояние",
    pigletCapture: "Регистрация поросят",
    animalExit: "Вывод животного",
    replaceEarTag: "Заменить бирку",
    changePen: "Сменить станок",
    anonymousAnimalId: "Идентификатор анонимного животного",

    cancel: "Отмена",
    accept: "Принять",
    saving: "Сохранение...",
    error: "Ошибка",

    operationDone: "Операция выполнена успешно.",
    changeStateDone: "Подсостояние успешно обновлено.",
    changeStateError: "Не удалось изменить состояние животного.",
    confirmNextOperation: "Вы уверены, что хотите перейти к следующей операции?",
    pkidChangeStateNotFound: "Внутренний идентификатор животного не найден.",

    selectExitType: "Выберите тип вывода, который хотите применить.",
    exitImmediate: "Немедленный вывод",
    exitScheduled: "Запланированный вывод",
    exitScheduledEmptyHopper: "Запланированный вывод с пустым бункером",
    cancelScheduledExit: "Отменить запланированный вывод",
    scheduledDate: "Запланированная дата",
    exitDateLimitText: "Нельзя выбрать дату раньше сегодняшней или позже чем через 3 дня.",
    animalExitDone: "Вывод животного выполнен успешно.",
    animalExitError: "Не удалось выполнить вывод животного.",
    pkidExitNotFound: "Внутренний идентификатор животного не найден.",

    selectCurve: "Выбрать кривую",
    selectCurveText: "Выберите новую кривую для животного.",
    loadingCurves: "Загрузка кривых...",
    noCurvesAvailable: "Нет доступных кривых.",
    confirmChangeCurve: "Вы уверены, что хотите изменить кривую?",
    loadCurvesError: "Не удалось загрузить кривые.",
    pkidChangeCurveNotFound: "Внутренний идентификатор животного не найден.",
    changeCurveDone: "Кривая успешно обновлена.",
    changeCurveError: "Не удалось изменить кривую.",

    selectBodyConditionText: "Выберите новую упитанность животного.",
    loadingBodyConditions: "Загрузка состояний упитанности...",
    noBodyConditionsAvailable: "Нет доступных состояний упитанности.",
    confirmChangeBodyCondition: "Вы уверены, что хотите изменить упитанность?",
    loadBodyConditionsError: "Не удалось загрузить состояния упитанности.",
    pkidChangeBodyConditionNotFound: "Внутренний идентификатор животного не найден.",
    changeBodyConditionDone: "Упитанность успешно обновлена.",
    changeBodyConditionError: "Не удалось изменить упитанность.",

    selectSubStateText: "Вручную выберите новое подсостояние животного.",
    confirmChangeSubState: "Вы уверены, что хотите изменить подсостояние?",

    currentPen: "Текущий станок: {{pen}}",
    newPen: "Новый станок",
    enterNewPen: "Введите новый станок.",
    pkidChangePenNotFound: "Внутренний идентификатор животного не найден.",
    changePenDone: "Станок успешно обновлён.",
    changePenError: "Не удалось изменить станок.",

    currentEarTag: "Текущая бирка: {{earTag}}",
    newEarTag: "Новая бирка",
    enterNewEarTag: "Введите новую бирку.",
    pkidEarTagNotFound: "Внутренний идентификатор животного не найден.",
    replaceEarTagDone: "Бирка успешно обновлена.",
    replaceEarTagError: "Не удалось заменить бирку.",

    identifyAnonymousAnimalText: "Выберите, назначить животному ID или бирку.",
    newId: "Новый ID",
    enterNewId: "Введите новый ID.",
    idExample: "Напр.: 1010",
    earTagExample: "Напр.: 123",
    notAnonymousAnimalText: "Это животное не является анонимным, так как у него уже назначен ID или бирка.",
    pkidIdentifyNotFound: "Внутренний идентификатор животного не найден.",
    identifyAnonymousAnimalDone: "Идентификатор животного успешно обновлён.",
    identifyAnonymousAnimalError: "Не удалось идентифицировать анонимное животное.",

    livePiglets: "Живые",
    deadPiglets: "Мёртвые",
    mummifiedPiglets: "Мумифицированные",
    totalBornPiglets: "Всего родилось",
    pigletCaptureText: "Введите количество живых, мёртвых и мумифицированных поросят.",
    captureBeforeLactationText: "Зарегистрируйте рождённых поросят перед переводом в лактацию.",
    weaningPigletsOnlyRead: "На этапе отъёма поросят можно только просматривать.",
    pkidPigletsNotFound: "Внутренний идентификатор животного не найден.",
    pigletCaptureDone: "Регистрация поросят успешно сохранена.",
    pigletCaptureError: "Не удалось сохранить регистрацию поросят.",
  },
  subState: {
    prepartum: "Предродовой период",
    lactation: "Лактация",
    weaning: "Отъём",
  },

  capturaParto: {
  birthDataTitle: "Данные опороса",
  birthDataSubtitle: "Проверьте данные животного перед регистрацией опороса.",
  corral: "Станок",
  id: "ID",
  date: "Дата",
  subState: "Подсостояние",

  dataCollectionTitle: "Сбор данных",
  dataCollectionSubtitle: "Введите количество живорождённых, мёртвых и мумифицированных поросят.",
  weaningReadOnly: "На этапе отъёма данные можно только просматривать.",

  totalBorn: "Всего родилось",
  live: "Живые",
  dead: "Мёртвые",
  mummified: "Мумифицированные",

  prepartum: "Предродовой период",
  farrowing: "Опорос",
  lactation: "Лактация",
  weaning: "Отъём",

  accept: "Принять",
  cancel: "Отмена",
  saving: "Сохранение...",

  sentTitle: "Запись отправлена",
  sentMessage: "Регистрация опороса успешно сохранена.",

  errorTitle: "Ошибка",
  invalidAnimalTitle: "Недействительное животное",
  invalidAnimalText: "Внутренний идентификатор животного не найден.",
  reportSendError: "Не удалось сохранить регистрацию опороса.",

  invalidDateTitle: "Недействительная дата",
  invalidDateMessage: "Дата опороса не может быть позже сегодняшней.",
  changeDate: "Изменить дату",

  selectDateTitle: "Выбрать дату",
  selectDateMessage: "Настройте дату опороса с помощью кнопок.",
},

capturaMaternidadEntrada: {
  title: "Регистрация опороса",
  description: "Найдите животное по станку или ID, чтобы зарегистрировать опорос.",
  maternityLabel: "МАТЕРИНСТВО",

  corral: "Станок",
  corralDescription: "Найдите животное по номеру станка.",
  id: "ID",
  idDescription: "Найдите животное по его идентификатору.",
  animalId: "ID животного",

  corralExample: "Напр.: 102",
  idExample: "Напр.: 1234",

  consulting: "Поиск...",
  continue: "Продолжить",
  accept: "Принять",

  serverConnectionError: "Не удалось подключиться к серверу.",
},
altaBajaStack: {
  tituloPantalla: "Добавление/убыль поросят",
  descripcionPantalla: "Найдите свиноматку по станку или ID, чтобы зарегистрировать добавление или убыль поросят.",
},
altaBajaLechones: {
  heroTitle: "Перемещение поросят",
  statusAlta: "Добавление",
  statusBaja: "Убыль",

  corralUpper: "СТАНОК",
  idUpper: "ID",
  dateUpper: "ДАТА",

  movementType: "Тип движения",
  movementSubtitle: "Выберите, хотите ли вы зарегистрировать добавление или убыль.",
  adoption: "Усыновление",
  baja: "Убыль",

  adoptionData: "Данные усыновления",
  donorMother: "Свиноматка-донор",
  donatesPiglets: "Отдаёт поросят",
  id: "ID",
  transferredPiglets: "Перемещённые поросята",
  totalAdopted: "Всего усыновлено",
  total: "Всего",

  bajaReason: "Причина убыли",
  reasonCrushing: "Задавливание",
  reasonDiarrhea: "Диарея",
  reasonLowViability: "Низкая жизнеспособность",
  reasonDeformities: "Деформации",
  reasonOther: "Другое",

  piglet: "поросёнок",
  piglets: "поросята",
  description: "Описание",

  editReason: "Редактировать причину",
  addReason: "Добавить причину",
  reasonModalText: "Укажите количество поросят и опишите причину.",

  saving: "Сохранение...",
  saveAlta: "Сохранить добавление",
  saveBaja: "Сохранить убыль",
  accept: "Принять",
  cancel: "Отмена",

  error: "Ошибка",
  missingData: "Не хватает данных",
  saveError: "Ошибка сохранения",
  saveErrorText: "Не удалось сохранить операцию.",
  selectedAnimalPkidNotFound: "Внутренний идентификатор выбранного животного не найден.",

  enterTransferredPiglets: "Введите количество перемещённых поросят.",
  invalidTotalTitle: "Недействительное общее количество",
  invalidPigletsNumber: "Введите допустимое количество поросят.",

  missingDescriptionTitle: "Описание обязательно",
  missingDescriptionText: "Введите описание причины.",
  invalidQuantityTitle: "Недействительное количество",
  invalidPigletQuantity: "Введите допустимое количество поросят.",

  selectReasonRequired: "Выберите хотя бы одну причину убыли.",

  adoptionSavedTitle: "Добавление сохранено",
  adoptionSavedMessage: "{{count}} поросят успешно зарегистрировано.",

  bajasSavedTitle: "Убыль сохранена",
  bajasSavedMessage: "{{piglets}} случаев убыли успешно зарегистрировано по {{reasons}} причине(ам).",
},
avisoAplicacionNoConfigurada: {
  title: "Приложение не настроено",
  text: "Настройте IP-адрес сервера",
  link: "Нажмите здесь",
},
generalHome: {
  movementAnimalTitle: "Перемещение животных",
  readerDescription: "Считыватель ушных меток.",
  keyboardDescription: "Клавиатура",

  ctifeedTitle: "CTIFEED",
  ctifeedDescription: "Перейти на главный портал.",

  modalApplicationNotConfiguredTitle: "Приложение не настроено",
  modalNoSessionTitle: "Сессия не начата",
  modalInstallationUnavailableTitle: "Установка недоступна",
  modalPreparingSessionTitle: "Подготовка сессии",
  modalReadOnlyPermissionTitle: "Разрешение только на чтение",

  modalApplicationNotConfiguredText: "Нет настроенной установки. Перейдите в раздел Установки и выберите одну.",
  modalNoSessionText: "Установка имеет IP-адрес, но сессия не начата. Проверьте имя пользователя и пароль в разделе Установки.",
  modalInstallationUnavailableText: "Не удаётся подключиться к выбранной установке. Проверьте подключение к правильной сети WiFi или проверьте IP-адрес сервера.",
  modalPreparingSessionText: "Сессия ещё загружается. Повторите попытку через несколько секунд.",
  modalReadOnlyPermissionText: "У вашего пользователя нет прав администратора для доступа к этой функции.",

  accept: "Принять",

  connectingTitle: "Подключение...",
  connectingText: "Проверка соединения с выбранной установкой.",
},
movimientoAnimalMaternidad: {
  smallLabel: "ПЕРЕМЕЩЕНИЕ",
  title: "Материнство",
  subtitle: "Выполняйте ручной ввод и вывод через клавиатуру.",

  movementType: "Тип перемещения",
  entry: "Ввод",
  exit: "Вывод",

  searchAnimal: "Найти животное",
  entryHelper: "Введите целевой станок и ID животного.",
  exitHelper: "Выберите, хотите ли выполнить вывод по станку или по ID.",

  pen: "Станок",
  animalId: "ID животного",
  type: "Тип",

  sending: "Отправка...",
  accept: "Принять",
  cancel: "Отмена",

  confirmEntry: "Подтвердить ввод",
  confirmExit: "Подтвердить вывод",
  confirmSubtitle: "Проверьте данные перед отправкой перемещения.",

  incompleteDataTitle: "Неполные данные",
  entryIncompleteText: "Введите станок и ID животного.",
  exitPenIncompleteText: "Введите станок для выполнения вывода.",
  exitIdIncompleteText: "Введите ID животного для выполнения вывода.",

  invalidPenTitle: "Недействительный станок",
  invalidPenText: "Станок должен быть допустимым числом больше 0.",

  sendErrorTitle: "Ошибка отправки",
  connectionErrorTitle: "Ошибка соединения",
  noIpConfigured: "IP-адрес не настроен.",
  serverConnectionError: "Не удалось подключиться к серверу.",
  serverEmptyResponse: "Сервер не вернул сообщение. HTTP-код {{status}}.",

  entrySentTitle: "Ввод отправлен",
  entrySentText: "Перемещение ввода успешно отправлено.",

  exitSentTitle: "Вывод отправлен",
  exitByPenSentText: "Вывод по станку успешно отправлен.",
  exitByIdSentText: "Вывод по ID успешно отправлен.",
},
movimientoAnimalGestacion: {
  smallLabel: "СУПОРОСНОСТЬ",
  title: "Перемещение животных",
  subtitle: "Выполняйте ручной ввод и вывод через клавиатуру.",

  movementType: "Тип перемещения",
  entry: "Ввод",
  exit: "Вывод",

  searchAnimal: "Найти животное",
  entryHelper: "Введите целевой станок и ID животного.",
  exitHelper: "Введите ID животного, чтобы выполнить вывод из супоросности.",

  pen: "Станок",
  animalId: "ID животного",
  type: "Тип",

  sending: "Отправка...",
  accept: "Принять",
  cancel: "Отмена",

  confirmEntry: "Подтвердить ввод",
  confirmExit: "Подтвердить вывод",
  confirmSubtitle: "Проверьте данные перед отправкой перемещения.",

  incompleteDataTitle: "Неполные данные",
  entryIncompleteText: "Введите станок и ID животного.",
  exitIdIncompleteText: "Введите ID животного для выполнения вывода.",

  invalidPenTitle: "Недействительный станок",
  invalidPenText: "Станок должен быть допустимым числом больше 0.",

  sendErrorTitle: "Ошибка отправки",
  noIpConfigured: "IP-адрес не настроен.",
  serverConnectionError: "Не удалось подключиться к серверу.",
  serverEmptyResponse: "Сервер не вернул сообщение. HTTP-код {{status}}.",

  entrySentTitle: "Ввод отправлен",
  entrySentText: "Перемещение ввода в супоросности успешно отправлено.",

  exitSentTitle: "Вывод отправлен",
  exitByIdSentText: "Вывод из супоросности по ID успешно отправлен.",
},
gestCorralDetail: {
    title: "Статус животного в супоросности",
    emptyTitle: "В этом станке нет животного",

    id: "ID",
    crotal: "Бирка",
    cycle: "Цикл",
    day: "День",

    stateGestation: "Супоросность",
    stateOutOfGestation: "Вне супоросности",

    curve: "Кривая",
    correction: "Коррекция",
    entryDate: "Дата входа",
    inseminationDate: "Дата осеменения",
    house: "Помещение",
    corral: "Станок",
    estimatedFarrowingDate: "Ожидаемая дата опороса",
    lastFeeding: "Последнее кормление",

    oneDayWithoutFeeding: "1 день без кормления",
    daysWithoutFeeding: "{{count}} дн. без кормления",
    of: "из",
},
};