export default {
    username: 'Пользователь',
    password: 'Пароль',
    login: 'Войти',
    welcome: 'Добро пожаловать',
    change_language: 'Сменить язык',
    Tabs: 'Главная',

    Lista_instalaciones: 'Установки',
    Maintenance: 'Техническое обслуживание',
    DetallesInstalacion: 'Детали установки',
    Grabar: 'Сохранить',
    EstadoStore: 'Статус store',
    Nodata: 'Нет данных',
    DosimacRegistration: 'Регистрация',
    NewDmMaternity: 'Новый Dosimac родильное',
    DosimacG: 'Dosimac-G',
    DosimacI: 'Dosimac-I',
    UpdDmMaternity: 'Изменение Dosimac родильное',
    NewDmGestation: 'Новый Dosimac беременность',
    UpdDmGestation: 'Изменение Dosimac беременность',
    StartScan: 'Поиск устройств DOSIMAC',
    DosimacList: 'Устройства DOSIMAC',
    PressToScan: 'Нажмите',
    DosimacSetup: 'Конфигурация',
    TestoPresioneAlta: 'Нажмите кнопку, чтобы найти устройства',
    Instalación_seleccionada: 'Выбранная установка',
    NoInstalacionSeleccionada: 'Нет выбранной установки',
    BorrarGranja: 'Удалить ферму',
    Deseaborrarlagranja: 'Хотите удалить ферму?',
    Guardar: 'Сохранить',
    Cancelar: 'Отмена',
    Aceptar: 'Принять',
    NombreGranja: 'Название фермы',
    Localidad: 'Местоположение',
    Provincia: 'Область',
    NombreWifi: 'Wifi SSID',
    PasswordWifi: 'Пароль Wifi',
    No_hay_dispositivos: 'Нет устройств',
    Aviso: 'Уведомление',
    SearchingDevices: 'Поиск устройств...',
    NoSePuedeBorrarGranja: 'Нельзя удалить новую ферму',
    settings: 'Настройки',
    softwareVersion: 'Версия ПО',
    numeroCoral: 'Номер загона',
    numeroMaquina: 'Номер машины',
    Enviar: 'Отправить',
    Salir: 'Выйти',
    Informacion: 'Информация',
    InicioConfiguracion: "Инициация подключения",
  ConfiguracionWifi: "Настройка...",
  ConfiguracionRealizada: "*Настройка выполнена*",
  ErrorConfiguracion: "*Ошибка настройки*",
  CapturaTagCorral: "Считать метку загона",
  CorralTag: "Метка загона",
  versionUint16: "Эта версия устройства поддерживает номер загона только до 65000",
  versionUint32: "Эта версия устройства поддерживает номер загона до 4000000000",
  EnvioConfiguracion: "Отправка конфигурации",
NumeroCorral: "Номер загона",
NumeroMaquina: "Номер машины",
Corralnovalida: "Недопустимый номер загона",
NumeroMaquinanovalida: "Недопустимый номер машины",
};