export default {
    username: 'Utilizador',
    password: 'Palavra-passe',
    login: 'Iniciar sessão',
    welcome: 'Bem-vindo',
    change_language: 'Mudar idioma',
    Tabs: 'Início',

    Lista_instalaciones: 'Instalações',
    Maintenance: 'Manutenção',
    DetallesInstalacion: 'Detalhes da instalação',
    Grabar: 'Gravar',
    EstadoStore: 'Estado da store',
    Nodata: 'Sem dados',
    DosimacRegistration: 'Registo',
    NewDmMaternity: 'Novo Dosimac maternidade',
    DosimacG: 'Dosimac-G',
    DosimacI: 'Dosimac-I',
    UpdDmMaternity: 'Atualizar Dosimac maternidade',
    NewDmGestation: 'Novo Dosimac gestação',
    UpdDmGestation: 'Atualizar Dosimac gestação',
    StartScan: 'Procurar equipamentos DOSIMAC',
    DosimacList: 'Equipamentos DOSIMAC',
    PressToScan: 'Prima',
    DosimacSetup: 'Configuração',
    TestoPresioneAlta: 'Prima o botão para procurar dispositivos',
    Instalación_seleccionada: 'Instalação selecionada',
    NoInstalacionSeleccionada: 'Nenhuma instalação selecionada',
    BorrarGranja: 'Eliminar quinta',
    Deseaborrarlagranja: 'Deseja eliminar a quinta?',
    Guardar: 'Guardar',
    Cancelar: 'Cancelar',
    Aceptar: 'Aceitar',
    NombreGranja: 'Nome da quinta',
    Localidad: 'Localidade',
    Provincia: 'Província',
    NombreWifi: 'Wifi SSID',
    PasswordWifi: 'Palavra-passe do Wifi',
    No_hay_dispositivos: 'Sem dispositivos',
    Aviso: 'Aviso',
    SearchingDevices: 'A procurar dispositivos...',
    NoSePuedeBorrarGranja: 'Não é possível eliminar uma quinta nova',
    settings: 'Definições',
    softwareVersion: 'Versão do software',
    numeroCoral: 'Número do curral',
    numeroMaquina: 'Número da máquina',
    Enviar: 'Enviar',
    Salir: 'Sair',
    Informacion: 'Informação',
}