export default {
    username: 'Utilizador',
    password: 'Palavra-passe',
    login: 'Iniciar sessão',
    welcome: 'Bem-vindo',
    change_language: 'Mudar idioma',
    Tabs: 'Início',

    Lista_instalaciones: 'Instalações',
    Maintenance: 'Manutenção',
    DetallesInstalacion: 'Detalhes da instalação',
    Grabar: 'Gravar',
    EstadoStore: 'Estado da store',
    Nodata: 'Sem dados',
    DosimacRegistration: 'Registo',
    NewDmMaternity: 'Novo Dosimac maternidade',
    DosimacG: 'Dosimac-G',
    DosimacI: 'Dosimac-I',
    UpdDmMaternity: 'Atualizar Dosimac maternidade',
    NewDmGestation: 'Novo Dosimac gestação',
    UpdDmGestation: 'Atualizar Dosimac gestação',
    StartScan: 'Procurar equipamentos DOSIMAC',
    DosimacList: 'Equipamentos DOSIMAC',
    PressToScan: 'Prima',
    DosimacSetup: 'Configuração',
    TestoPresioneAlta: 'Prima o botão para procurar dispositivos',
    Instalación_seleccionada: 'Instalação selecionada',
    NoInstalacionSeleccionada: 'Nenhuma instalação selecionada',
    BorrarGranja: 'Eliminar quinta',
    Deseaborrarlagranja: 'Deseja eliminar a quinta?',
    Guardar: 'Guardar',
    Cancelar: 'Cancelar',
    Aceptar: 'Aceitar',
    NombreGranja: 'Nome da quinta',
    Localidad: 'Localidade',
    Provincia: 'Província',
    NombreWifi: 'Wifi SSID',
    PasswordWifi: 'Palavra-passe do Wifi',
    No_hay_dispositivos: 'Sem dispositivos',
    Aviso: 'Aviso',
    SearchingDevices: 'A procurar dispositivos...',
    NoSePuedeBorrarGranja: 'Não é possível eliminar uma quinta nova',
    settings: 'Definições',
    softwareVersion: 'Versão do software',
    numeroCoral: 'Número do curral',
    numeroMaquina: 'Número da máquina',
    Enviar: 'Enviar',
    Salir: 'Sair',
    Informacion: 'Informação',
    InicioConfiguracion: "A iniciar ligação",
    ConfiguracionWifi: "A configurar...",
    ConfiguracionRealizada: "*Configuração concluída*",
    ErrorConfiguracion: "*Erro de configuração*",
    CapturaTagCorral: "Capturar etiqueta do curral",
    CorralTag: "Etiqueta do curral",
    versionUint16: "Esta versão do equipamento só suporta curral até 65000",
    versionUint32: "Esta versão do equipamento suporta curral até 4000000000",
    EnvioConfiguracion: "A enviar a configuração",
    NumeroCorral: "Número do curral",
    NumeroMaquina: "Número da máquina",
    Corralnovalida: "Número do curral inválido",
    NumeroMaquinanovalida: "Número da máquina inválido",
    configuarIntalacion: "É necessário configurar a instalação antes de usar esta funcionalidade",

    login_title: "Iniciar sessão",
    login_subtitle: "Introduza os seus dados. É necessário configurar o IP antes de iniciar sessão a partir do menu Configuração IP.",
    login_username: "Utilizador",
    login_password: "Palavra-passe",
    login_button: "Entrar",
    login_loading: "A entrar...",
    login_footer: "Painel de controlo",

    login_ipRequiredTitle: "Configuração IP necessária",
    login_ipRequiredMessage: "Não configurou o endereço IP do servidor. Introduza-o para poder iniciar sessão.",
    login_serverIpLabel: "IP do servidor",
    login_cancel: "Cancelar",
    login_accept: "Aceitar",

    login_configTitle: "Configuração",
    login_errorTitle: "Erro de início de sessão",
    login_genericErrorTitle: "Erro",
    login_networkErrorTitle: "Erro de rede",
    login_networkErrorMessage: "Não foi possível ligar ao servidor.",
    login_noTokenMessage: "O backend não devolveu nenhum token.",
    login_missingDataTitle: "Faltam dados",
    login_missingDataMessage: "Introduza utilizador e palavra-passe.",
    login_invalidIpTitle: "IP inválido",
    login_invalidIpMessage: "Introduza um IP ou endereço de servidor válido.",
    login_saveIpErrorMessage: "Não foi possível guardar a configuração IP.",
    awrStartScan_title: "Configuração AWR",
    awrStartScan_description: "Ecrã para digitalizar leitores Agrident AWR.",
    awrStartScan_button: "Digitalizar AWR",

    gestacionConfig_entry: "Entrada",
    gestacionConfig_exit: "Saída",
    gestacionConfig_reading: "Leitura",
    gestacionConfig_search: "Pesquisa",

    gestacionConfig_entryParamsTitle: "Parâmetros de entrada",
    gestacionConfig_exitParamsTitle: "Parâmetros de saída",
    gestacionConfig_entryParamsDescription: "Seleciona o curral e o comportamento do fluxo.",
    gestacionConfig_exitParamsDescription: "Configura o comportamento do fluxo de saída.",

    gestacionConfig_corralLabel: "Curral",
    gestacionConfig_corralPlaceholder: "Ex: 1",
    gestacionConfig_corralRequired: "Escreve o curral para continuar.",

    gestacionConfig_detectUnknownTitle: "Identificar animais desconhecidos",
    gestacionConfig_detectUnknownDescription: "Quando leres um animal sem identificação, poderás atribuir-lhe um ID",

    gestacionConfig_confirmTitle: "Confirmar envio",
    gestacionConfig_confirmDescription: "Vai pedir confirmação antes de enviar os registos.",

    gestacionConfig_animalSearchTitle: "Pesquisa de animal",
    gestacionConfig_animalSearchDescription: "Escolhe se queres pesquisar por crotal ou por ID.",
    gestacionConfig_searchByCrotal: "Por crotal",
    gestacionConfig_searchById: "Por ID",
    gestacionConfig_manual: "Manual",
    gestacionConfig_withSword: "Com espada",

    gestacionConfig_crotalLabelSearch: "Crotal",
    gestacionConfig_idLabelSearch: "ID",
    gestacionConfig_crotalPlaceholderSearch: "Ex: 982091072397436",
    gestacionConfig_idPlaceholderSearch: "Ex: A13",
    gestacionConfig_crotalRequiredSearch: "Escreve um crotal para continuar.",
    gestacionConfig_idRequiredSearch: "Escreve um ID para continuar.",

    gestacionConfig_searchWithSwordHelp: "Ao continuar, a espada será lida neste ecrã e o animal será pesquisado com esse crotal.",

    gestacionConfig_readingSword: "A ler espada...",
    gestacionConfig_waitingMatch: "À espera de correspondência",
    gestacionConfig_searchingAnimal: "A pesquisar animal...",

    gestacionConfig_readingSwordDescription: "Aproxima o crotal do leitor para identificar o animal.",
    gestacionConfig_waitingMatchDescription: "Animal localizado. Agora aproxima à espada o crotal {{crotal}} para confirmar a correspondência.",
    gestacionConfig_searchingAnimalDescription: "A consultar informação do animal no backend.",

    gestacionConfig_awrDisconnectedTitle: "AWR não ligado",
    gestacionConfig_awrSavedDescription: "Tens espadas guardadas. Prime para selecionar uma.",
    gestacionConfig_awrNotSavedDescription: "Não tens nenhuma espada guardada. Prime para digitalizar uma.",

    gestacionConfig_scan: "Digitalizar",
    gestacionConfig_continue: "Continuar",

    gestacionConfig_alerts_error: "Erro",
    gestacionConfig_alerts_networkError: "Erro de rede",
    gestacionConfig_alerts_networkErrorMessage: "Não foi possível ligar ao servidor.",
    gestacionConfig_alerts_backendNoValidCrotal: "O backend não devolveu um crotal válido para comparar.",
    gestacionConfig_alerts_awrNotConnected: "AWR não ligado",
    gestacionConfig_alerts_connectSwordBeforeContinue: "Liga uma espada antes de continuar.",
    gestacionConfig_alerts_couldNotStartReading: "Não foi possível iniciar a leitura com a espada.",

    gestacionConfig_alerts_missingData: "Falta dado",
    gestacionConfig_alerts_writeCrotalToSearch: "Escreve um crotal para pesquisar.",
    gestacionConfig_alerts_writeIdToSearch: "Escreve um ID para pesquisar.",

    gestacionConfig_alerts_notFound: "Não encontrado",
    gestacionConfig_alerts_animalNotFoundByCrotal: "Não existe nenhum animal com esse crotal.",
    gestacionConfig_alerts_animalNotFoundById: "Não existe nenhum animal com esse ID.",

    gestacionConfig_alerts_warning: "Aviso",
    gestacionConfig_alerts_searchError: "Erro na pesquisa",

    maternidadConfig_screenTitle: "Configuração Maternidade",
    maternidadConfig_chooseOptionTitle: "Escolhe uma opção",
    maternidadConfig_chooseOptionDescription: "Define o fluxo antes de começar com o leitor.",
    maternidadConfig_entry: "Entrada",
    maternidadConfig_exit: "Saída",
    maternidadConfig_reading: "Leitura",
    maternidadConfig_search: "Pesquisa",
    maternidadConfig_entryParamsTitle: "Parâmetros de entrada",
    maternidadConfig_exitParamsTitle: "Parâmetros de saída",
    maternidadConfig_entryParamsDescription: "Seleciona o curral e o comportamento do fluxo.",
    maternidadConfig_exitParamsDescription: "Configura o comportamento do fluxo de saída.",
    maternidadConfig_corralLabel: "Curral",
    maternidadConfig_corralPlaceholder: "Ex: 1",
    maternidadConfig_corralRequired: "Escreve o curral para continuar.",
    maternidadConfig_detectUnknownTitle: "Identificar animais desconhecidos",
    maternidadConfig_detectUnknownDescription: "Quando leres um animal sem identificação, poderás atribuir-lhe um ID",
    maternidadConfig_confirmTitle: "Confirmar envio",
    maternidadConfig_confirmDescription: "Irá pedir confirmação antes de enviar cada registo.",
    maternidadConfig_animalSearchTitle: "Pesquisa de animal",
    maternidadConfig_animalSearchDescription: "Escolhe se queres pesquisar por crotal ou por ID.",
    maternidadConfig_searchByCrotal: "Por crotal",
    maternidadConfig_searchById: "Por ID",
    maternidadConfig_manual: "Manual",
    maternidadConfig_withSword: "Com espada",
    maternidadConfig_crotalLabelSearch: "Crotal",
    maternidadConfig_idLabelSearch: "ID",
    maternidadConfig_crotalPlaceholderSearch: "Ex: 982091072397436",
    maternidadConfig_idPlaceholderSearch: "Ex: A13",
    maternidadConfig_crotalRequiredSearch: "Escreve um crotal para continuar.",
    maternidadConfig_idRequiredSearch: "Escreve um ID para continuar.",
    maternidadConfig_searchWithSwordHelp: "Ao premir Digitalizar, a espada será lida neste ecrã e o animal será pesquisado com esse crotal.",
    maternidadConfig_readingSword: "A ler espada...",
    maternidadConfig_waitingMatch: "À espera de correspondência",
    maternidadConfig_searchingAnimal: "A pesquisar animal...",
    maternidadConfig_readingSwordDescription: "Aproxima o crotal do leitor para identificar o animal.",
    maternidadConfig_waitingMatchDescription: "Animal localizado. Agora aproxima à espada o crotal {{crotal}} para confirmar a correspondência.",
    maternidadConfig_searchingAnimalDescription: "A consultar informação do animal no backend.",
    maternidadConfig_awrDisconnectedTitle: "AWR não ligado",
    maternidadConfig_awrSavedDescription: "Tens AWR guardadas. Toca para selecionar uma.",
    maternidadConfig_awrNotSavedDescription: "Não tens nenhuma AWR guardada. Toca para digitalizar uma.",
    maternidadConfig_scan: "Digitalizar",
    maternidadConfig_continue: "Continuar",
    maternidadConfig_alert_error: "Erro",
    maternidadConfig_alert_invalidBackendCrotal: "O backend não devolveu um crotal válido para comparar.",
    maternidadConfig_alert_awrNotConnected: "AWR não ligado",
    maternidadConfig_alert_connectSwordBeforeContinue: "Liga uma espada antes de continuar.",
    maternidadConfig_alert_couldNotStartReading: "Não foi possível iniciar a leitura com a espada.",
    maternidadConfig_alert_missingData: "Falta dado",
    maternidadConfig_alert_writeCrotalToSearch: "Escreve um crotal para pesquisar.",
    maternidadConfig_alert_writeIdToSearch: "Escreve um ID para pesquisar.",
    maternidadConfig_alert_notFound: "Não encontrado",
    maternidadConfig_alert_noAnimalWithCrotal: "Não existe nenhum animal com esse crotal.",
    maternidadConfig_alert_noAnimalWithId: "Não existe nenhum animal com esse ID.",
    maternidadConfig_alert_warning: "Aviso",
    maternidadConfig_alert_searchError: "Erro na pesquisa",
    maternidadConfig_alert_networkError: "Erro de rede",
    maternidadConfig_alert_networkErrorMessage: "Não foi possível ligar ao servidor.",

    gestationReader_screenTitle: "Leitor Gestação",
    gestationReader_animalInfoTitle: "Informação do animal",
    gestationReader_animalInfoDescription: "Dados localizados na pesquisa.",
    gestationReader_animalCardTitle: "Ficha Animal",
    gestationReader_animalIdLabel: "ID",
    gestationReader_animalCrotalLabel: "Crotal",
    gestationReader_fieldCorral: "Curral",
    gestationReader_fieldHouse: "Nave",
    gestationReader_fieldState: "Estado",
    gestationReader_fieldBodyCondition: "Condição corporal",
    gestationReader_fieldCycle: "Ciclo",
    gestationReader_fieldSystemEntryDate: "Entrada no sistema",
    gestationReader_newSearch: "Nova pesquisa",
    gestationReader_summaryTitle: "Resumo",
    gestationReader_summaryDescription: "Parâmetros escolhidos na Configuração",
    gestationReader_mode: "Modo",
    gestationReader_corral: "Curral",
    gestationReader_modeEntry: "Entrada",
    gestationReader_modeExit: "Saída",
    gestationReader_modeReading: "Leitura",
    gestationReader_modeSearch: "Pesquisa",
    gestationReader_detectUnknownTitle: "Identificar animais desconhecidos",
    gestationReader_detectUnknownDescription: "Quando aparecer um animal sem ID, oferecer a atribuição de um ID.",
    gestationReader_confirmSendTitle: "Confirmar envio",
    gestationReader_confirmSendDescription: "Irá pedir confirmação antes de enviar cada registo.",
    gestationReader_changeSettings: "Mudar configuração",
    gestationReader_currentReadingTitle: "Leitura atual",
    gestationReader_currentReadingDescription: "O crotal detetado e o ID associado aparecerão aqui.",
    gestationReader_awrDisconnected: "AWR não conectado",
    gestationReader_readCrotal: "Crotal lido",
    gestationReader_readId: "ID",
    gestationReader_animalWithoutAssignedId: "Animal sem ID atribuído",
    gestationReader_unknownAnimal: "Animal desconhecido",
    gestationReader_animalWithoutIdTitle: "Animal sem ID",
    gestationReader_animalWithoutIdDescription: "Escreve um ID manual para atualizar o crotal lido.",
    gestationReader_newIdLabel: "Novo ID",
    gestationReader_newIdPlaceholder: "Ex: A13",
    gestationReader_updateId: "Atualizar ID",
    gestationReader_updatingId: "A atualizar...",
    gestationReader_sentRecordsTitle: "Registos enviados",
    gestationReader_noRecords: "Não há registos.",
    gestationReader_tableHeaderCorral: "Curral",
    gestationReader_tableHeaderId: "ID",
    gestationReader_tableHeaderCrotal: "Crotal",
    gestationReader_buttonAutoReading: "Leitura automática ativa",
    gestationReader_buttonAutoSending: "Envio automático ativo",
    gestationReader_buttonSending: "A enviar...",
    gestationReader_buttonSend: "Enviar",
    gestationReader_alertError: "Erro",
    gestationReader_alertWarning: "Aviso",
    gestationReader_alertNetworkError: "Erro de rede",
    gestationReader_alertMissingCrotalTitle: "Falta crotal",
    gestationReader_alertMissingCrotalMessage: "Aproxima o crotal do leitor antes de enviar.",
    gestationReader_alertInvalidCrotalTitle: "Crotal inválido",
    gestationReader_alertInvalidCrotalMessage: "O crotal tem de ser numérico.",
    gestationReader_alertReadErrorTitle: "Erro na leitura",
    gestationReader_alertNetworkErrorMessage: "Não foi possível ligar ao servidor.",
    gestationReader_alertMissingCorralTitle: "Falta curral",
    gestationReader_alertMissingCorralMessage: "Escreve o curral antes de enviar.",
    gestationReader_alertInvalidCorralTitle: "Curral inválido",
    gestationReader_alertInvalidCorralMessage: "O curral tem de ser um número.",
    gestationReader_alertSendErrorTitle: "Erro ao enviar",
    gestationReader_alertNoIpConfigured: "Não há IP configurado.",
    gestationReader_alertMissingIdTitle: "Falta ID",
    gestationReader_alertMissingIdMessage: "Escreve o novo ID antes de atualizar.",
    gestationReader_alertMissingAssociatedCrotalTitle: "Falta crotal",
    gestationReader_alertMissingAssociatedCrotalMessage: "Não há crotal associado para atualizar.",
    gestationReader_alertInvalidAssociatedCrotalTitle: "Crotal inválido",
    gestationReader_alertInvalidAssociatedCrotalMessage: "O crotal associado não é válido.",
    gestationReader_alertUpdateIdErrorTitle: "Erro ao atualizar ID",

    maternityReader_screenTitle: "Leitor Maternidade",
    maternityReader_alertMissingCrotalTitle: "Falta brinco",
    maternityReader_alertMissingCrotalMessage: "Aproxime o brinco do leitor antes de enviar.",
    maternityReader_alertInvalidCrotalTitle: "Brinco inválido",
    maternityReader_alertInvalidCrotalMessage: "O brinco deve ser numérico.",
    maternityReader_alertReadErrorTitle: "Erro de leitura",
    maternityReader_alertNetworkError: "Erro de rede",
    maternityReader_alertNetworkErrorMessage: "Não foi possível conectar ao servidor.",
    maternityReader_alertMissingCorralTitle: "Falta curral",
    maternityReader_alertMissingCorralMessage: "Digite o curral antes de enviar.",
    maternityReader_alertInvalidCorralTitle: "Curral inválido",
    maternityReader_alertInvalidCorralMessage: "O curral deve ser um número (ex.: 8).",
    maternityReader_alertError: "Erro",
    maternityReader_alertNoIpConfigured: "Não há IP configurado.",
    maternityReader_alertWarning: "Aviso",
    maternityReader_alertSendErrorTitle: "Erro ao enviar",
    maternityReader_alertMissingIdTitle: "Falta ID",
    maternityReader_alertMissingIdMessage: "Digite o novo ID antes de atualizar.",
    maternityReader_alertMissingAssociatedCrotalTitle: "Falta brinco",
    maternityReader_alertMissingAssociatedCrotalMessage: "Não há brinco associado para atualizar.",
    maternityReader_alertInvalidAssociatedCrotalTitle: "Brinco inválido",
    maternityReader_alertInvalidAssociatedCrotalMessage: "O brinco associado não é válido.",
    maternityReader_alertUpdateIdErrorTitle: "Erro ao atualizar ID",
    maternityReader_animalInfoTitle: "Informações do animal",
    maternityReader_animalInfoDescription: "Dados localizados na busca.",
    maternityReader_animalCardTitle: "Ficha do Animal",
    maternityReader_animalIdLabel: "ID",
    maternityReader_animalCrotalLabel: "Brinco",
    maternityReader_fieldCorral: "Curral",
    maternityReader_fieldHouse: "Galpão",
    maternityReader_fieldState: "Estado",
    maternityReader_fieldBodyCondition: "Condição corporal",
    maternityReader_fieldCycle: "Ciclo",
    maternityReader_fieldSystemEntryDate: "Entrada no sistema",
    maternityReader_newSearch: "Nova busca",
    maternityReader_summaryTitle: "Resumo",
    maternityReader_summaryDescription: "Parâmetros escolhidos na configuração",
    maternityReader_mode: "Modo",
    maternityReader_modeEntry: "Entrada",
    maternityReader_modeExit: "Saída",
    maternityReader_modeReading: "Leitura",
    maternityReader_corral: "Curral",
    maternityReader_detectUnknownTitle: "Identificar animais desconhecidos",
    maternityReader_detectUnknownDescription: "Quando aparecer um animal sem ID, permitir atribuir um ID.",
    maternityReader_confirmSendTitle: "Confirmar envio",
    maternityReader_confirmSendDescription: "Pedirá confirmação antes de enviar cada registro.",
    maternityReader_changeSettings: "Alterar configuração",
    maternityReader_currentReadingTitle: "Leitura atual",
    maternityReader_currentReadingDescription: "O brinco detectado aparecerá aqui.",
    maternityReader_awrDisconnected: "AWR não conectado",
    maternityReader_readCrotal: "Brinco lido",
    maternityReader_readId: "ID",
    maternityReader_animalWithoutAssignedId: "Animal sem ID atribuído",
    maternityReader_unknownAnimal: "Animal desconhecido",
    maternityReader_animalWithoutIdTitle: "Animal sem ID",
    maternityReader_animalWithoutIdDescription: "Digite um ID manual para atualizar o brinco lido.",
    maternityReader_newIdLabel: "Novo ID",
    maternityReader_newIdPlaceholder: "Ex.: A13",
    maternityReader_updatingId: "Atualizando...",
    maternityReader_updateId: "Atualizar ID",
    maternityReader_sentRecordsTitle: "Registros enviados",
    maternityReader_tableHeaderCorral: "Curral",
    maternityReader_tableHeaderId: "ID",
    maternityReader_tableHeaderCrotal: "Brinco",
    maternityReader_noRecords: "Não há registros.",
    maternityReader_buttonAutoReading: "Leitura automática ativa",
    maternityReader_buttonAutoSending: "Envio automático ativo",
    maternityReader_buttonSending: "Enviando...",
    maternityReader_buttonSend: "Enviar",

    awrScanResults_title: "AWR – Resultados da digitalização",
    awrScanResults_searching: "A procurar AWR…",
    awrScanResults_warningTitle: "Aviso",
    awrScanResults_noDevicesNearby: "Não foram encontrados dispositivos AWR próximos.",
    awrScanResults_connecting: "A ligar…",
    awrScanResults_connectErrorFallback: "Não foi possível ligar",
    awrScanResults_connectedTitle: "Ligado",
    awrScanResults_connectedMessage: "Ligação estabelecida com {{device}}.",
    awrScanResults_genericDevice: "o dispositivo",

    awrSavedList_title: "AWR digitalizados",
    awrSavedList_connecting: "A ligar…",
    awrSavedList_empty: "Não há AWR guardados. Digitalize um em “Configuración AWR”.",
    awrSavedList_connected: "Ligado",
    awrSavedList_disconnected: "Desligado",
    awrSavedList_renameAccessibility: "Renomear",
    awrSavedList_deleteAccessibility: "Eliminar",
    awrSavedList_renameTitle: "Renomear AWR",
    awrSavedList_nameLabel: "Nome",
    awrSavedList_deleteTitle: "Eliminar AWR guardado",
    awrSavedList_deleteMessage: "Tem a certeza de que quer eliminar este AWR da lista?",
    awrSavedList_deleteAction: "Eliminar",

    ipConfig_title: "Configuração IP",
    ipConfig_cardTitle: "Servidor CTIFEED",
    ipConfig_cardDescription: "Introduza o IP do servidor onde o portal será aberto.",
    ipConfig_inputLabel: "IP (apenas o IP)",
    ipConfig_saved: "Guardado",
    ipConfig_alertSuccessTitle: "Correto",
    ipConfig_alertSuccessMessage: "IP correto",
    ipConfig_alertWarningTitle: "Aviso",
    ipConfig_alertServerNotUpdated: "Servidor não atualizado",
    ipConfig_alertErrorTitle: "Erro",
    ipConfig_alertInvalidIp: "IP inválido",

    portal_preparing: "A preparar o portal...",
    portal_noSessionToken: "Não existe token de sessão. Inicie sessão novamente.",
    portal_noIpConfigured: "Não há nenhum IP configurado. Configure primeiro o IP do servidor.",
    portal_prepareUrlError: "Não foi possível preparar o URL do portal.",
    portal_loadError: "Não foi possível carregar o portal.",
    portal_checkingConnection: "A verificar a ligação ao portal...",
    portal_noConnectionTitle: "Sem ligação",
    portal_connectionTimeout: "Não foi possível ligar ao portal. Verifique se está ligado à rede correta.",
    portal_connectionError: "Não foi possível ligar ao portal. Verifique a rede ou o IP configurado.",
    portal_httpError: "Não foi possível abrir o portal. Erro HTTP {{status}}.",
    portal_retry: "Tentar novamente",
    portal_loading: "A carregar o portal...",


    AltaDispositivos: "Registo de dispositivos",
    LectorMaternidad: "Leitor Maternidade",
    LectorGestacion: "Leitor Gestação",
    ConfiguracionIP: "Configuração IP",
    ConfiguracionAWR: "Configuração AWR",
    DarDeAltaAWR: "Registar AWR",
    AWREscaneados: "AWR digitalizados",
    CerrarSesion: "Terminar sessão",

    Config_lastReadMismatchTitle: "O animal lido não corresponde à pesquisa",
    Config_lastReadMismatchCrotal: "Brinco",
    Config_lastReadMismatchId: "ID",
    awrBluetoothPermissionMessage: "Ative o Bluetooth e aceite a permissão para poder digitalizar.", 

}