export default {
  username: 'Utilizador',
  password: 'Palavra-passe',
  login: 'Iniciar sessão',
  welcome: 'Bem-vindo',
  change_language: 'Mudar idioma',
  Tabs: 'Início',

  Lista_instalaciones: 'Instalações',
  Maintenance: 'Manutenção',
  DetallesInstalacion: 'Detalhes da instalação',
  Grabar: 'Gravar',
  EstadoStore: 'Estado da store',
  Nodata: 'Sem dados',
  DosimacRegistration: 'Registo',
  NewDmMaternity: 'Novo Dosimac maternidade',
  DosimacG: 'Dosimac-G',
  DosimacI: 'Dosimac-I',
  UpdDmMaternity: 'Atualizar Dosimac maternidade',
  NewDmGestation: 'Novo Dosimac gestação',
  UpdDmGestation: 'Atualizar Dosimac gestação',
  StartScan: 'Procurar equipamentos DOSIMAC',
  DosimacList: 'Equipamentos DOSIMAC',
  PressToScan: 'Prima',
  DosimacSetup: 'Configuração',
  TestoPresioneAlta: 'Prima o botão para procurar dispositivos',
  Instalación_seleccionada: 'Instalação selecionada',
  NoInstalacionSeleccionada: 'Nenhuma instalação selecionada',
  BorrarGranja: 'Eliminar quinta',
  Deseaborrarlagranja: 'Deseja eliminar a quinta?',
  Guardar: 'Guardar',
  Cancelar: 'Cancelar',
  Aceptar: 'Aceitar',
  NombreGranja: 'Nome da quinta',
  Localidad: 'Localidade',
  Provincia: 'Província',
  NombreWifi: 'Wifi SSID',
  PasswordWifi: 'Palavra-passe do Wifi',
  colocaQrInstalacionCamara: "Coloque o código QR da instalação dentro da câmara.",
  escaneaCodigoQr: "Digitalize o código QR",
  permisoCamaraNecesario: "Permissão da câmara necessária",
permisoCamaraQrTexto: "Precisa permitir o acesso à câmara para digitalizar o código QR.",
qrNoValido: "Código QR inválido",
qrNoEsInstalacionDosimac: "Este não é um código QR de instalação DOSIMAC.",
ipAplicadaSinCredenciales: "O IP foi aplicado corretamente, mas esta instalação não tem Username nem Palavra-passe.",
instalacionSeleccionada: "Instalação selecionada",
conexionExitosa: "Ligação bem-sucedida",
instalacionConectadaCorrectamente: "A instalação foi ligada corretamente.",
noPuedeConectarInstalacionSeleccionada: "Não é possível ligar à instalação selecionada. Verifique a rede WiFi ou o IP do servidor.",
conectando: "A ligar",
conectandoInstalacionSeleccionada: "A ligar à instalação selecionada...",



  No_hay_dispositivos: 'Sem dispositivos',
  Aviso: 'Aviso',
  SearchingDevices: 'A procurar dispositivos...',
  NoSePuedeBorrarGranja: 'Não é possível eliminar uma quinta nova',
  settings: 'Definições',
  softwareVersion: 'Versão do software',
  numeroCoral: 'Número do curral',
  numeroMaquina: 'Número da máquina',
  Enviar: 'Enviar',
  Salir: 'Sair',
  Informacion: 'Informação',
  InicioConfiguracion: "A iniciar ligação",
  ConfiguracionWifi: "A configurar...",
  ConfiguracionRealizada: "*Configuração concluída*",
  ErrorConfiguracion: "*Erro de configuração*",
  CapturaTagCorral: "Capturar etiqueta do curral",
  CorralTag: "Etiqueta do curral",
  versionUint16: "Esta versão do equipamento só suporta curral até 65000",
  versionUint32: "Esta versão do equipamento suporta curral até 4000000000",
  EnvioConfiguracion: "A enviar a configuração",
  NumeroCorral: "Número do curral",
  NumeroMaquina: "Número da máquina",
  Corralnovalida: "Número do curral inválido",
  NumeroMaquinanovalida: "Número da máquina inválido",
  configuarIntalacion: "É necessário configurar a instalação antes de usar esta funcionalidade",

  login_title: "Iniciar sessão",
  login_subtitle: "Introduza os seus dados. É necessário configurar o IP antes de iniciar sessão a partir do menu Configuração IP.",
  login_username: "Utilizador",
  login_password: "Palavra-passe",
  login_button: "Entrar",
  login_loading: "A entrar...",
  login_footer: "Painel de controlo",

  login_ipRequiredTitle: "Configuração IP necessária",
  login_ipRequiredMessage: "Não configurou o endereço IP do servidor. Introduza-o para poder iniciar sessão.",
  login_serverIpLabel: "IP do servidor",
  login_cancel: "Cancelar",
  login_accept: "Aceitar",
  login_invalidCredentials: "Nome de utilizador ou palavra-passe incorretos",

  login_configTitle: "Configuração",
  login_errorTitle: "Erro de início de sessão",
  login_genericErrorTitle: "Erro",
  login_networkErrorTitle: "Erro de rede",
  login_networkErrorMessage: "Não foi possível ligar ao servidor.",
  login_noTokenMessage: "O backend não devolveu nenhum token.",
  login_missingDataTitle: "Faltam dados",
  login_missingDataMessage: "Introduza utilizador e palavra-passe.",
  login_invalidIpTitle: "IP inválido",
  login_invalidIpMessage: "Introduza um IP ou endereço de servidor válido.",
  login_saveIpErrorMessage: "Não foi possível guardar a configuração IP.",
  awrStartScan_title: "Configuração AWR",
  awrStartScan_description: "Ecrã para digitalizar leitores Agrident AWR.",
  awrStartScan_button: "Digitalizar AWR",

  gestacionConfig_entry: "Entrada",
  gestacionConfig_exit: "Saída",
  gestacionConfig_reading: "Leitura",
  gestacionConfig_search: "Pesquisa",

  gestacionConfig_entryParamsTitle: "Parâmetros de entrada",
  gestacionConfig_exitParamsTitle: "Parâmetros de saída",
  gestacionConfig_entryParamsDescription: "Seleciona o curral e o comportamento do fluxo.",
  gestacionConfig_exitParamsDescription: "Configura o comportamento do fluxo de saída.",

  gestacionConfig_corralLabel: "Curral",
  gestacionConfig_corralPlaceholder: "Ex: 1",
  gestacionConfig_corralRequired: "Escreve o curral para continuar.",

  gestacionConfig_detectUnknownTitle: "Identificar animais desconhecidos",
  gestacionConfig_detectUnknownDescription: "Quando leres um animal sem identificação, poderás atribuir-lhe um ID",

  gestacionConfig_confirmTitle: "Confirmar envio",
  gestacionConfig_confirmDescription: "Vai pedir confirmação antes de enviar os registos.",

  gestacionConfig_animalSearchTitle: "Pesquisa de animal",
  gestacionConfig_animalSearchDescription: "Escolhe se queres pesquisar por crotal ou por ID.",
  gestacionConfig_searchByCrotal: "Por crotal",
  gestacionConfig_searchById: "Por ID",
  gestacionConfig_manual: "Manual",
  gestacionConfig_withSword: "Com espada",

  gestacionConfig_crotalLabelSearch: "Crotal",
  gestacionConfig_idLabelSearch: "ID",
  gestacionConfig_crotalPlaceholderSearch: "Ex: 982091072397436",
  gestacionConfig_idPlaceholderSearch: "Ex: A13",
  gestacionConfig_crotalRequiredSearch: "Escreve um crotal para continuar.",
  gestacionConfig_idRequiredSearch: "Escreve um ID para continuar.",

  gestacionConfig_searchWithSwordHelp: "Ao continuar, a espada será lida neste ecrã e o animal será pesquisado com esse crotal.",

  gestacionConfig_readingSword: "A ler espada...",
  gestacionConfig_waitingMatch: "À espera de correspondência",
  gestacionConfig_searchingAnimal: "A pesquisar animal...",

  gestacionConfig_readingSwordDescription: "Aproxima o crotal do leitor para identificar o animal.",
  gestacionConfig_waitingMatchDescription: "Animal localizado. Agora aproxima à espada o crotal {{crotal}} para confirmar a correspondência.",
  gestacionConfig_searchingAnimalDescription: "A consultar informação do animal no backend.",

  gestacionConfig_awrDisconnectedTitle: "AWR não ligado",
  gestacionConfig_awrSavedDescription: "Tens espadas guardadas. Prime para selecionar uma.",
  gestacionConfig_awrNotSavedDescription: "Não tens nenhuma espada guardada. Prime para digitalizar uma.",

  gestacionConfig_scan: "Digitalizar",
  gestacionConfig_continue: "Continuar",

  gestacionConfig_alerts_error: "Erro",
  gestacionConfig_alerts_networkError: "Erro de rede",
  gestacionConfig_alerts_networkErrorMessage: "Não foi possível ligar ao servidor.",
  gestacionConfig_alerts_backendNoValidCrotal: "O backend não devolveu um crotal válido para comparar.",
  gestacionConfig_alerts_awrNotConnected: "AWR não ligado",
  gestacionConfig_alerts_connectSwordBeforeContinue: "Liga uma espada antes de continuar.",
  gestacionConfig_alerts_couldNotStartReading: "Não foi possível iniciar a leitura com a espada.",

  gestacionConfig_alerts_missingData: "Falta dado",
  gestacionConfig_alerts_writeCrotalToSearch: "Escreve um crotal para pesquisar.",
  gestacionConfig_alerts_writeIdToSearch: "Escreve um ID para pesquisar.",

  gestacionConfig_alerts_notFound: "Não encontrado",
  gestacionConfig_alerts_animalNotFoundByCrotal: "Não existe nenhum animal com esse crotal.",
  gestacionConfig_alerts_animalNotFoundById: "Não existe nenhum animal com esse ID.",

  gestacionConfig_alerts_warning: "Aviso",
  gestacionConfig_alerts_searchError: "Erro na pesquisa",

  maternidadConfig_screenTitle: "Configuração Maternidade",
  maternidadConfig_chooseOptionTitle: "Escolhe uma opção",
  maternidadConfig_chooseOptionDescription: "Define o fluxo antes de começar com o leitor.",
  maternidadConfig_entry: "Entrada",
  maternidadConfig_exit: "Saída",
  maternidadConfig_reading: "Leitura",
  maternidadConfig_search: "Pesquisa",
  maternidadConfig_entryParamsTitle: "Parâmetros de entrada",
  maternidadConfig_exitParamsTitle: "Parâmetros de saída",
  maternidadConfig_entryParamsDescription: "Seleciona o curral e o comportamento do fluxo.",
  maternidadConfig_exitParamsDescription: "Configura o comportamento do fluxo de saída.",
  maternidadConfig_corralLabel: "Curral",
  maternidadConfig_corralPlaceholder: "Ex: 1",
  maternidadConfig_corralRequired: "Escreve o curral para continuar.",
  maternidadConfig_detectUnknownTitle: "Identificar animais desconhecidos",
  maternidadConfig_detectUnknownDescription: "Quando leres um animal sem identificação, poderás atribuir-lhe um ID",
  maternidadConfig_confirmTitle: "Confirmar envio",
  maternidadConfig_confirmDescription: "Irá pedir confirmação antes de enviar cada registo.",
  maternidadConfig_animalSearchTitle: "Pesquisa de animal",
  maternidadConfig_animalSearchDescription: "Escolhe se queres pesquisar por crotal ou por ID.",
  maternidadConfig_searchByCrotal: "Por crotal",
  maternidadConfig_searchById: "Por ID",
  maternidadConfig_manual: "Manual",
  maternidadConfig_withSword: "Com espada",
  maternidadConfig_crotalLabelSearch: "Crotal",
  maternidadConfig_idLabelSearch: "ID",
  maternidadConfig_crotalPlaceholderSearch: "Ex: 982091072397436",
  maternidadConfig_idPlaceholderSearch: "Ex: A13",
  maternidadConfig_crotalRequiredSearch: "Escreve um crotal para continuar.",
  maternidadConfig_idRequiredSearch: "Escreve um ID para continuar.",
  maternidadConfig_searchWithSwordHelp: "Ao premir Digitalizar, a espada será lida neste ecrã e o animal será pesquisado com esse crotal.",
  maternidadConfig_readingSword: "A ler espada...",
  maternidadConfig_waitingMatch: "À espera de correspondência",
  maternidadConfig_searchingAnimal: "A pesquisar animal...",
  maternidadConfig_readingSwordDescription: "Aproxima o crotal do leitor para identificar o animal.",
  maternidadConfig_waitingMatchDescription: "Animal localizado. Agora aproxima à espada o crotal {{crotal}} para confirmar a correspondência.",
  maternidadConfig_searchingAnimalDescription: "A consultar informação do animal no backend.",
  maternidadConfig_awrDisconnectedTitle: "AWR não ligado",
  maternidadConfig_awrSavedDescription: "Tens AWR guardadas. Toca para selecionar uma.",
  maternidadConfig_awrNotSavedDescription: "Não tens nenhuma AWR guardada. Toca para digitalizar uma.",
  maternidadConfig_scan: "Digitalizar",
  maternidadConfig_continue: "Continuar",
  maternidadConfig_alert_error: "Erro",
  maternidadConfig_alert_invalidBackendCrotal: "O backend não devolveu um crotal válido para comparar.",
  maternidadConfig_alert_awrNotConnected: "AWR não ligado",
  maternidadConfig_alert_connectSwordBeforeContinue: "Liga uma espada antes de continuar.",
  maternidadConfig_alert_couldNotStartReading: "Não foi possível iniciar a leitura com a espada.",
  maternidadConfig_alert_missingData: "Falta dado",
  maternidadConfig_alert_writeCrotalToSearch: "Escreve um crotal para pesquisar.",
  maternidadConfig_alert_writeIdToSearch: "Escreve um ID para pesquisar.",
  maternidadConfig_alert_notFound: "Não encontrado",
  maternidadConfig_alert_noAnimalWithCrotal: "Não existe nenhum animal com esse crotal.",
  maternidadConfig_alert_noAnimalWithId: "Não existe nenhum animal com esse ID.",
  maternidadConfig_alert_warning: "Aviso",
  maternidadConfig_alert_searchError: "Erro na pesquisa",
  maternidadConfig_alert_networkError: "Erro de rede",
  maternidadConfig_alert_networkErrorMessage: "Não foi possível ligar ao servidor.",

  gestationReader_screenTitle: "Leitor Gestação",
  gestationReader_animalInfoTitle: "Informação do animal",
  gestationReader_animalInfoDescription: "Dados localizados na pesquisa.",
  gestationReader_animalCardTitle: "Ficha Animal",
  gestationReader_animalIdLabel: "ID",
  gestationReader_animalCrotalLabel: "Crotal",
  gestationReader_fieldCorral: "Curral",
  gestationReader_fieldHouse: "Nave",
  gestationReader_fieldState: "Estado",
  gestationReader_fieldBodyCondition: "Condição corporal",
  gestationReader_fieldCycle: "Ciclo",
  gestationReader_fieldSystemEntryDate: "Entrada no sistema",
  gestationReader_newSearch: "Nova pesquisa",
  gestationReader_summaryTitle: "Resumo",
  gestationReader_summaryDescription: "Parâmetros escolhidos na Configuração",
  gestationReader_mode: "Modo",
  gestationReader_corral: "Curral",
  gestationReader_modeEntry: "Entrada",
  gestationReader_modeExit: "Saída",
  gestationReader_modeReading: "Leitura",
  gestationReader_modeSearch: "Pesquisa",
  gestationReader_detectUnknownTitle: "Identificar animais desconhecidos",
  gestationReader_detectUnknownDescription: "Quando aparecer um animal sem ID, oferecer a atribuição de um ID.",
  gestationReader_confirmSendTitle: "Confirmar envio",
  gestationReader_confirmSendDescription: "Irá pedir confirmação antes de enviar cada registo.",
  gestationReader_changeSettings: "Mudar configuração",
  gestationReader_currentReadingTitle: "Leitura atual",
  gestationReader_currentReadingDescription: "O crotal detetado e o ID associado aparecerão aqui.",
  gestationReader_awrDisconnected: "AWR não conectado",
  gestationReader_readCrotal: "Crotal lido",
  gestationReader_readId: "ID",
  gestationReader_animalWithoutAssignedId: "Animal sem ID atribuído",
  gestationReader_unknownAnimal: "Animal desconhecido",
  gestationReader_animalWithoutIdTitle: "Animal sem ID",
  gestationReader_animalWithoutIdDescription: "Escreve um ID manual para atualizar o crotal lido.",
  gestationReader_newIdLabel: "Novo ID",
  gestationReader_newIdPlaceholder: "Ex: A13",
  gestationReader_updateId: "Atualizar ID",
  gestationReader_updatingId: "A atualizar...",
  gestationReader_sentRecordsTitle: "Registos enviados",
  gestationReader_noRecords: "Não há registos.",
  gestationReader_tableHeaderCorral: "Curral",
  gestationReader_tableHeaderId: "ID",
  gestationReader_tableHeaderCrotal: "Crotal",
  gestationReader_buttonAutoReading: "Leitura automática ativa",
  gestationReader_buttonAutoSending: "Envio automático ativo",
  gestationReader_buttonSending: "A enviar...",
  gestationReader_buttonSend: "Enviar",
  gestationReader_alertError: "Erro",
  gestationReader_alertWarning: "Aviso",
  gestationReader_alertNetworkError: "Erro de rede",
  gestationReader_alertMissingCrotalTitle: "Falta crotal",
  gestationReader_alertMissingCrotalMessage: "Aproxima o crotal do leitor antes de enviar.",
  gestationReader_alertInvalidCrotalTitle: "Crotal inválido",
  gestationReader_alertInvalidCrotalMessage: "O crotal tem de ser numérico.",
  gestationReader_alertReadErrorTitle: "Erro na leitura",
  gestationReader_alertNetworkErrorMessage: "Não foi possível ligar ao servidor.",
  gestationReader_alertMissingCorralTitle: "Falta curral",
  gestationReader_alertMissingCorralMessage: "Escreve o curral antes de enviar.",
  gestationReader_alertInvalidCorralTitle: "Curral inválido",
  gestationReader_alertInvalidCorralMessage: "O curral tem de ser um número.",
  gestationReader_alertSendErrorTitle: "Erro ao enviar",
  gestationReader_alertNoIpConfigured: "Não há IP configurado.",
  gestationReader_alertMissingIdTitle: "Falta ID",
  gestationReader_alertMissingIdMessage: "Escreve o novo ID antes de atualizar.",
  gestationReader_alertMissingAssociatedCrotalTitle: "Falta crotal",
  gestationReader_alertMissingAssociatedCrotalMessage: "Não há crotal associado para atualizar.",
  gestationReader_alertInvalidAssociatedCrotalTitle: "Crotal inválido",
  gestationReader_alertInvalidAssociatedCrotalMessage: "O crotal associado não é válido.",
  gestationReader_alertUpdateIdErrorTitle: "Erro ao atualizar ID",
  gestationReader_readerMode: "Leitor",
  gestationReader_keyboardMode: "Teclado",

  gestationReader_keyboardEntryTitle: "Entrada por teclado",
  gestationReader_keyboardExitTitle: "Saída por teclado",
  gestationReader_keyboardDescription: "Introduza o dado manualmente com o teclado do telefone.",
  gestationReader_keyboardId: "ID",
  gestationReader_keyboardCrotal: "Brinco",
  gestationReader_keyboardIdLabel: "ID animal",
  gestationReader_keyboardCrotalLabel: "Brinco",
  gestationReader_keyboardIdPlaceholder: "Introduza o ID",
  gestationReader_keyboardCrotalPlaceholder: "Introduza o brinco",
  gestationReader_keyboardAdd: "Adicionar",
  gestationReader_keyboardAdding: "A adicionar...",

  gestationReader_pendingRecordsTitle: "Registos não enviados",
  gestationReader_buttonSendingBatch: "A enviar lote...",
  gestationReader_buttonSendBatch: "Enviar lote",
  gestationReader_buttonSendBatchCount: "Enviar lote ({{count}})",

  gestationReader_noPendingRecordsTitle: "Sem registos",
  gestationReader_noPendingRecordsText: "Não há registos pendentes para enviar.",
  gestationReader_batchSentTitle: "Lote enviado",
  gestationReader_batchSentText: "{{count}} registo(s) enviados corretamente.",
  gestationReader_batchWithErrorsTitle: "Lote com erros",

  gestationReader_recordSentTitle: "Registo enviado",
  gestationReader_recordSentText: "O movimento foi enviado corretamente.",

  gestationReader_invalidAnimalId: "O ID do animal não é válido.",
  gestationReader_invalidPenRecord: "O curral do registo não é válido.",
  gestationReader_invalidCrotalRecord: "O brinco do registo não é válido.",
  gestationReader_duplicateIdPending: "O ID {{id}} já está na tabela de registos não enviados.",
  gestationReader_duplicateCrotalPending: "O brinco {{crotal}} já está na tabela de registos não enviados.",
  gestationReader_keyboardMissingId: "Introduza o ID do animal.",
  gestationReader_keyboardMissingCrotal: "Introduza o brinco do animal.",
  gestationReader_keyboardMissingPen: "Selecione um curral válido antes de adicionar o animal.",
  gestationReader_noAnimalById: "Não existe nenhum animal com o ID {{id}}.",
  gestationReader_noAnimalByCrotal: "Não existe nenhum animal com o brinco {{crotal}}.",
  gestationReader_addAnimalError: "Não foi possível adicionar o animal.",

  gestationReader_pendingAnimalHint: "Os animais lidos aparecerão aqui.",

  gestationReader_changePenTitle: "Alterar curral",
  gestationReader_changePenDescription: "Introduza o novo curral de entrada.",
  gestationReader_newPenLabel: "Novo curral",
  gestationReader_newPenPlaceholder: "Ex.: 1",
  gestationReader_cancel: "Cancelar",
  gestationReader_save: "Guardar",
  gestationReader_accept: "Aceitar",
  gestationReader_sentHistoryTitle: "Histórico de enviados",

  maternityReader_screenTitle: "Leitor Maternidade",
  maternityReader_alertMissingCrotalTitle: "Falta brinco",
  maternityReader_alertMissingCrotalMessage: "Aproxime o brinco do leitor antes de enviar.",
  maternityReader_alertInvalidCrotalTitle: "Brinco inválido",
  maternityReader_alertInvalidCrotalMessage: "O brinco deve ser numérico.",
  maternityReader_alertReadErrorTitle: "Erro de leitura",
  maternityReader_alertNetworkError: "Erro de rede",
  maternityReader_alertNetworkErrorMessage: "Não foi possível conectar ao servidor.",
  maternityReader_alertMissingCorralTitle: "Falta curral",
  maternityReader_alertMissingCorralMessage: "Digite o curral antes de enviar.",
  maternityReader_alertInvalidCorralTitle: "Curral inválido",
  maternityReader_alertInvalidCorralMessage: "O curral deve ser um número (ex.: 8).",
  maternityReader_alertError: "Erro",
  maternityReader_alertNoIpConfigured: "Não há IP configurado.",
  maternityReader_alertWarning: "Aviso",
  maternityReader_alertSendErrorTitle: "Erro ao enviar",
  maternityReader_alertMissingIdTitle: "Falta ID",
  maternityReader_alertMissingIdMessage: "Digite o novo ID antes de atualizar.",
  maternityReader_alertMissingAssociatedCrotalTitle: "Falta brinco",
  maternityReader_alertMissingAssociatedCrotalMessage: "Não há brinco associado para atualizar.",
  maternityReader_alertInvalidAssociatedCrotalTitle: "Brinco inválido",
  maternityReader_alertInvalidAssociatedCrotalMessage: "O brinco associado não é válido.",
  maternityReader_alertUpdateIdErrorTitle: "Erro ao atualizar ID",
  maternityReader_animalInfoTitle: "Informações do animal",
  maternityReader_animalInfoDescription: "Dados localizados na busca.",
  maternityReader_animalCardTitle: "Ficha do Animal",
  maternityReader_animalIdLabel: "ID",
  maternityReader_animalCrotalLabel: "Brinco",
  maternityReader_fieldCorral: "Curral",
  maternityReader_fieldHouse: "Galpão",
  maternityReader_fieldState: "Estado",
  maternityReader_fieldBodyCondition: "Condição corporal",
  maternityReader_fieldCycle: "Ciclo",
  maternityReader_fieldSystemEntryDate: "Entrada no sistema",
  maternityReader_newSearch: "Nova busca",
  maternityReader_summaryTitle: "Resumo",
  maternityReader_summaryDescription: "Parâmetros escolhidos na configuração",
  maternityReader_mode: "Modo",
  maternityReader_modeEntry: "Entrada",
  maternityReader_modeExit: "Saída",
  maternityReader_modeReading: "Leitura",
  maternityReader_corral: "Curral",
  maternityReader_detectUnknownTitle: "Identificar animais desconhecidos",
  maternityReader_detectUnknownDescription: "Quando aparecer um animal sem ID, permitir atribuir um ID.",
  maternityReader_confirmSendTitle: "Confirmar envio",
  maternityReader_confirmSendDescription: "Pedirá confirmação antes de enviar cada registro.",
  maternityReader_changeSettings: "Alterar configuração",
  maternityReader_currentReadingTitle: "Leitura atual",
  maternityReader_currentReadingDescription: "O brinco detectado aparecerá aqui.",
  maternityReader_awrDisconnected: "AWR não conectado",
  maternityReader_readCrotal: "Brinco lido",
  maternityReader_readId: "ID",
  maternityReader_animalWithoutAssignedId: "Animal sem ID atribuído",
  maternityReader_unknownAnimal: "Animal desconhecido",
  maternityReader_animalWithoutIdTitle: "Animal sem ID",
  maternityReader_animalWithoutIdDescription: "Digite um ID manual para atualizar o brinco lido.",
  maternityReader_newIdLabel: "Novo ID",
  maternityReader_newIdPlaceholder: "Ex.: A13",
  maternityReader_updatingId: "Atualizando...",
  maternityReader_updateId: "Atualizar ID",
  maternityReader_sentRecordsTitle: "Registros enviados",
  maternityReader_tableHeaderCorral: "Curral",
  maternityReader_tableHeaderId: "ID",
  maternityReader_tableHeaderCrotal: "Brinco",
  maternityReader_noRecords: "Não há registros.",
  maternityReader_buttonAutoReading: "Leitura automática ativa",
  maternityReader_buttonAutoSending: "Envio automático ativo",
  maternityReader_buttonSending: "Enviando...",
  maternityReader_buttonSend: "Enviar",

  awrScanResults_title: "AWR – Resultados da digitalização",
  awrScanResults_searching: "A procurar AWR…",
  awrScanResults_warningTitle: "Aviso",
  awrScanResults_noDevicesNearby: "Não foram encontrados dispositivos AWR próximos.",
  awrScanResults_connecting: "A ligar…",
  awrScanResults_connectErrorFallback: "Não foi possível ligar",
  awrScanResults_connectedTitle: "Ligado",
  awrScanResults_connectedMessage: "Ligação estabelecida com {{device}}.",
  awrScanResults_genericDevice: "o dispositivo",

  awrSavedList_title: "AWR digitalizados",
  awrSavedList_connecting: "A ligar…",
  awrSavedList_empty: "Não há AWR guardados. Digitalize um em “Configuración AWR”.",
  awrSavedList_connected: "Ligado",
  awrSavedList_disconnected: "Desligado",
  awrSavedList_renameAccessibility: "Renomear",
  awrSavedList_deleteAccessibility: "Eliminar",
  awrSavedList_renameTitle: "Renomear AWR",
  awrSavedList_nameLabel: "Nome",
  awrSavedList_deleteTitle: "Eliminar AWR guardado",
  awrSavedList_deleteMessage: "Tem a certeza de que quer eliminar este AWR da lista?",
  awrSavedList_deleteAction: "Eliminar",

  ipConfig_title: "Configuração IP",
  ipConfig_cardTitle: "Servidor CTIFEED",
  ipConfig_cardDescription: "Introduza o IP do servidor onde o portal será aberto.",
  ipConfig_inputLabel: "IP (apenas o IP)",
  ipConfig_saved: "Guardado",
  ipConfig_alertSuccessTitle: "Correto",
  ipConfig_alertSuccessMessage: "IP correto",
  ipConfig_alertWarningTitle: "Aviso",
  ipConfig_alertServerNotUpdated: "Servidor não atualizado",
  ipConfig_alertErrorTitle: "Erro",
  ipConfig_alertInvalidIp: "IP inválido",

  portal_preparing: "A preparar o portal...",
  portal_noSessionToken: "Não existe token de sessão. Inicie sessão novamente.",
  portal_noIpConfigured: "Não há nenhum IP configurado. Configure primeiro o IP do servidor.",
  portal_prepareUrlError: "Não foi possível preparar o URL do portal.",
  portal_loadError: "Não foi possível carregar o portal.",
  portal_checkingConnection: "A verificar a ligação ao portal...",
  portal_noConnectionTitle: "Sem ligação",
  portal_connectionTimeout: "Não foi possível ligar ao portal. Verifique se está ligado à rede correta.",
  portal_connectionError: "Não foi possível ligar ao portal. Verifique a rede ou o IP configurado.",
  portal_httpError: "Não foi possível abrir o portal. Erro HTTP {{status}}.",
  portal_retry: "Tentar novamente",
  portal_loading: "A carregar o portal...",


  AltaDispositivos: "Registo de dispositivos",
  LectorMaternidad: "Leitor Maternidade",
  LectorGestacion: "Leitor Gestação",
  ConfiguracionIP: "Configuração IP",
  ConfiguracionAWR: "Configuração AWR",
  DarDeAltaAWR: "Registar AWR",
  AWREscaneados: "AWR digitalizados",
  CerrarSesion: "Terminar sessão",

  Config_lastReadMismatchTitle: "O animal lido não corresponde à pesquisa",
  Config_lastReadMismatchCrotal: "Brinco",
  Config_lastReadMismatchId: "ID",
  awrBluetoothPermissionMessage: "Ative o Bluetooth e aceite a permissão para poder digitalizar.",

  animalState: {
    gestation: "Gestação",
    maternity: "Maternidade",
    out_of_gestation: "Fora da gestação",
    out_of_maternity: "Fora da maternidade"
  },


  Reader_readingTitle: "Leitura de brincos",
  Reader_labelId: "ID",
  Reader_labelCrotal: "Brinco",
  Reader_labelCorral: "Curral",
  Reader_labelHouse: "Pavilhão",
  Reader_labelState: "Estado",
  Reader_autoReadingBadge: "Leitura automática",

  gestacionConfig_flowSectionTitle: "Configuração do fluxo",
  gestacionConfig_workModeTitle: "Modo de trabalho",
  gestacionConfig_workModeDescription: "Selecione o que o leitor irá fazer.",
  gestacionConfig_entryDescription: "Registrar entrada",
  gestacionConfig_exitDescription: "Registrar saída",
  gestacionConfig_readingDescription: "Apenas consultar",
  gestacionConfig_searchDescription: "Buscar animal",

  gestacionConfig_sendSettingsTitle: "Configurações de envio",
  gestacionConfig_sendSettingsDescription: "Configure como o fluxo se comporta ao ler animais.",

  gestacionConfig_corralSectionTitle: "Curral de entrada",
  gestacionConfig_corralSectionDescription: "Este dado é obrigatório para continuar com o registro.",

  gestacionConfig_alerts_notice: "Aviso",
  gestacionConfig_alerts_invalidCrotalFromBackend: "O backend não retornou uma identificação auricular válida para comparar.",

  common_accept: "Aceitar",

  maternidadConfig_flowSectionTitle: "Configuração do fluxo",
  maternidadConfig_workModeTitle: "Modo de trabalho",
  maternidadConfig_workModeDescription: "Selecione o que o leitor irá fazer.",
  maternidadConfig_entryDescription: "Registrar entrada",
  maternidadConfig_exitDescription: "Registrar saída",
  maternidadConfig_readingDescription: "Apenas consultar",
  maternidadConfig_searchDescription: "Buscar animal",

  maternidadConfig_sendSettingsTitle: "Configurações de envio",
  maternidadConfig_sendSettingsDescription: "Configure como o fluxo se comporta ao ler animais.",

  maternidadConfig_corralSectionTitle: "Curral de entrada",
  maternidadConfig_corralSectionDescription: "Este dado é obrigatório para continuar com o registro.",

  maternidadConfig_alert_invalidCrotalFromBackend: "O backend não retornou uma identificação auricular válida para comparar.",

  maternidadConfig_readOnlyTitle: "Permissão apenas de leitura",
  maternidadConfig_readOnlyModifySettings: "Este utilizador tem apenas permissões de leitura. Não pode modificar esta configuração.",
  maternidadConfig_readOnlyUseFunction: "Este utilizador tem apenas permissões de leitura. Não pode usar esta função.",

  ajustesEnvioMaternidad: {
    headerTitle: "Definições de envio",
    headerSubtitle: "Configure o comportamento do fluxo ao ler animais.",
    cardTitle: "Envio de registos",
    cardSubtitle: "Estas definições são aplicadas ao continuar com a leitura."
  },

  noAlimentadosMaternidad: {
    animalId: "ID DO ANIMAL",
    corral: "Curral",
    consumption: "Consumo",
    withoutFeeding: "Sem alimentação",
    day: "dia",
    days: "dias",
    loadingAnimals: "A carregar animais...",
    title: "Animais não alimentados",
    totalAnimalsMaternity: "Total de animais da maternidade:",
    notSeen: "Não vistos",
    all: "Todos",
    sort: "Ordenar",
    emptyTitle: "Não há animais pendentes",
    emptyText: "Não foram encontrados animais não alimentados na maternidade.",
    sortBy: "Ordenar por",
    daysWithoutFeeding: "Dias sem alimentação",
    sortDaysHelp: "Ordena pelos dias sem alimentação",
    sortCorralHelp: "Ordena pelo número do curral",
    descending: "Descendente",
    ascending: "Ascendente",
    filterAnimals: "Filtrar animais",
    allHelp: "Mostra todos os animais",
    unmarked: "Não marcados",
    unmarkedHelp: "Oculta os animais já revistos",
    clearMarkedTitle: "Limpar animais marcados",
    clearMarkedText: "Serão removidas todas as marcações dos animais revistos.",
    cancel: "Cancelar",
    clear: "Limpar",
    error: "Erro",
    serverConnectionError: "Não foi possível ligar ao servidor."
  },
  noAlimentadosGestacion: {
    animalId: "ID DO ANIMAL",
    corral: "Curral",
    consumption: "Consumo",
    withoutFeeding: "Sem alimentação",
    day: "dia",
    days: "dias",
    loadingAnimals: "A carregar animais...",
    title: "Animais não alimentados",
    totalAnimalsGestation: "Total de animais em gestação:",
    notSeen: "Não vistos",
    all: "Todos",
    sort: "Ordenar",
    emptyTitle: "Não há animais pendentes",
    emptyText: "Não foram encontrados animais não alimentados em gestação.",
    sortBy: "Ordenar por",
    daysWithoutFeeding: "Dias sem alimentação",
    sortDaysHelp: "Ordena pelos dias sem alimentação",
    sortCorralHelp: "Ordena pelo número do curral",
    descending: "Descendente",
    ascending: "Ascendente",
    filterAnimals: "Filtrar animais",
    allHelp: "Mostra todos os animais",
    unmarked: "Não marcados",
    unmarkedHelp: "Oculta os animais já revistos",
    clearMarkedTitle: "Limpar animais marcados",
    clearMarkedText: "Serão removidas todas as marcações dos animais revistos.",
    cancel: "Cancelar",
    clear: "Limpar",
    error: "Erro",
    serverConnectionError: "Não foi possível ligar ao servidor.",
    viewStatus: "Ver estado",
    animalIdNotFound: "Identificador do animal não encontrado.",
    openAnimalInfoError: "Não foi possível abrir as informações do animal.",
  },
  capturaAnimalHome: {
    selectOption: "Selecione uma opção",
    unfedAnimalsTitle: "Animais não alimentados",
    unfedAnimalsDescription: "Consultar os animais que não receberam a alimentação prevista.",
    twoFeedsTitle: "2 rações",
    twoFeedsDescription: "Gerir a mudança de alimentação nas bocas de queda.",
    animalStatusTitle: "Estado do animal",
    animalStatusDescription: "Consultar ou atualizar o estado do animal.",
    birthCaptureTitle: "Registo de parto",
    birthCaptureDescription: "Registe os nascidos vivos, mortos e mumificados.",
  },
  cambioPiensoMaternidad: {
    error: "Erro",
    loadTasksError: "Não foi possível carregar as tarefas de mudança de ração.",
    loadingTasks: "A carregar tarefas...",
    title: "Mudança de ração",
    pendingTask: "{{count}} tarefa pendente",
    pendingTasks: "{{count}} tarefas pendentes",
    emptyTitle: "Não há tarefas pendentes",
    emptyText: "Não foram encontradas tarefas de mudança de ração.",
    animalId: "ID DO ANIMAL",
    corral: "Curral",
    setTo: "Definir para",
    destination: "Destino"
  },
  estadoAnimal: {
    queryLabel: "Consulta",
    title: "Estado do animal",
    subtitle: "Selecione como pretende identificar o animal.",
    corral: "Curral",
    corralDescription: "Introduza o número do curral.",
    id: "ID",
    idDescription: "Introduza o identificador do animal.",
    animalId: "ID do animal",
    requiredData: "Dado obrigatório",
    enterCorral: "Introduza o número do curral.",
    enterId: "Introduza o identificador do animal.",
    consulting: "A consultar...",
    continue: "Continuar",
    accept: "Aceitar",
    serverConnectionError: "Não foi possível ligar ao servidor.",
    noIpConfigured: "Não há nenhum IP configurado.",
    nextScreenPending: "Vamos criar o ecrã de informação do animal no próximo passo.",
    corralMaternityDescription: "Introduza o número do curral de maternidade.",
    idAnimalDescription: "Procura o animal em maternidade e gestação.",
    animalNotFound: "Animal não encontrado",
  },

  matCorralDetail: {
    viewStatus: "Ver estado",
    animalIdNotFound: "Identificador do animal não encontrado.",
    openAnimalInfoError: "Não foi possível abrir as informações do animal.",
    earTagAlreadyAssigned: "O brinco está atribuído a outro animal",
    readOnlyPermission: "Permissão só de leitura",
    readOnlyPermissionText: "Este utilizador tem apenas permissões de leitura. Não pode realizar operações sobre o animal.",
    animalStatus: "Estado do animal",
    id: "ID",
    earTag: "Brinco",
    cycle: "Ciclo",
    day: "Dia",

    curve: "Curva",
    correction: "Correção",
    entryDate: "Data de entrada",
    farrowingDate: "Data do parto",
    house: "Nave",
    pen: "Curral",
    lastFeeding: "Última alimentação",
    presentPiglets: "Leitões vivos",
    inseminationDate: "Data de inseminação",
    teatsNumber: "N.º de tetas",

    operations: "Operações",

    consumption: "Consumo",
    ofGrams: "de {{amount}} g",
    oneDayWithoutFeeding: "1 dia sem alimentação",
    daysWithoutFeeding: "{{count}} dias sem alimentação",

    noAnimalData: "Não há dados do animal",
    noAnimalDataText: "Não foi recebida informação para mostrar.",
    back: "Voltar",
    operationsPendingTitle: "Operações",
    operationsPendingText: "Faremos as operações no passo seguinte.",
    moveToWeaning: "Passar para o desmame",
    chooseOption: "Selecione uma operação para este animal.",
    nextOperation: "Próxima operação",
    insertAnimal: "Inserir animal",
    moveToLactation: "Passar para a lactação",
    nextStep: "Próximo passo",
    actions: "Ações",

    bodyCondition: "Condição corporal",
    subState: "Subestado",
    pigletCapture: "Registo de leitões",
    animalExit: "Saída do animal",
    replaceEarTag: "Substituir brinco",
    changePen: "Alterar curral",
    anonymousAnimalId: "Identificador de animal anónimo",

    cancel: "Cancelar",
    accept: "Aceitar",
    saving: "A guardar...",
    error: "Erro",

    operationDone: "Operação realizada corretamente.",
    changeStateDone: "Subestado atualizado corretamente.",
    changeStateError: "Não foi possível alterar o estado do animal.",
    confirmNextOperation: "Tem a certeza de que pretende passar para a próxima operação?",
    pkidChangeStateNotFound: "Não foi encontrado o identificador interno do animal.",

    selectExitType: "Selecione o tipo de saída que pretende aplicar.",
    exitImmediate: "Saída imediata",
    exitScheduled: "Saída programada",
    exitScheduledEmptyHopper: "Saída programada com tremonha vazia",
    cancelScheduledExit: "Cancelar saída programada",
    scheduledDate: "Data programada",
    exitDateLimitText: "Não é possível selecionar uma data anterior a hoje nem posterior a 3 dias.",
    animalExitDone: "Saída do animal realizada corretamente.",
    animalExitError: "Não foi possível realizar a saída do animal.",
    pkidExitNotFound: "Não foi encontrado o identificador interno do animal.",

    selectCurve: "Selecionar curva",
    selectCurveText: "Selecione a nova curva do animal.",
    loadingCurves: "A carregar curvas...",
    noCurvesAvailable: "Não há curvas disponíveis.",
    confirmChangeCurve: "Tem a certeza de que pretende alterar a curva?",
    loadCurvesError: "Não foi possível carregar as curvas.",
    pkidChangeCurveNotFound: "Não foi encontrado o identificador interno do animal.",
    changeCurveDone: "Curva atualizada corretamente.",
    changeCurveError: "Não foi possível alterar a curva.",

    selectBodyConditionText: "Selecione a nova condição corporal do animal.",
    loadingBodyConditions: "A carregar condições corporais...",
    noBodyConditionsAvailable: "Não há condições corporais disponíveis.",
    confirmChangeBodyCondition: "Tem a certeza de que pretende alterar a condição corporal?",
    loadBodyConditionsError: "Não foi possível carregar as condições corporais.",
    pkidChangeBodyConditionNotFound: "Não foi encontrado o identificador interno do animal.",
    changeBodyConditionDone: "Condição corporal atualizada corretamente.",
    changeBodyConditionError: "Não foi possível alterar a condição corporal.",

    selectSubStateText: "Selecione manualmente o novo subestado do animal.",
    confirmChangeSubState: "Tem a certeza de que pretende alterar o subestado?",

    currentPen: "Curral atual: {{pen}}",
    newPen: "Novo curral",
    enterNewPen: "Introduza o novo curral.",
    pkidChangePenNotFound: "Não foi encontrado o identificador interno do animal.",
    changePenDone: "Curral atualizado corretamente.",
    changePenError: "Não foi possível alterar o curral.",

    currentEarTag: "Brinco atual: {{earTag}}",
    newEarTag: "Novo brinco",
    enterNewEarTag: "Introduza o novo brinco.",
    pkidEarTagNotFound: "Não foi encontrado o identificador interno do animal.",
    replaceEarTagDone: "Brinco atualizado corretamente.",
    replaceEarTagError: "Não foi possível substituir o brinco.",

    identifyAnonymousAnimalText: "Escolha se pretende atribuir um ID ou um brinco ao animal.",
    newId: "Novo ID",
    enterNewId: "Introduza o novo ID.",
    idExample: "Ex.: 1010",
    earTagExample: "Ex.: 123",
    notAnonymousAnimalText: "Este animal não é anónimo porque já tem um ID ou brinco atribuído.",
    pkidIdentifyNotFound: "Não foi encontrado o identificador interno do animal.",
    identifyAnonymousAnimalDone: "Identificador do animal atualizado corretamente.",
    identifyAnonymousAnimalError: "Não foi possível identificar o animal anónimo.",

    livePiglets: "Vivos",
    deadPiglets: "Mortos",
    mummifiedPiglets: "Mumificados",
    totalBornPiglets: "Total nascidos",
    pigletCaptureText: "Introduza os leitões vivos, mortos e mumificados.",
    captureBeforeLactationText: "Registe os nascidos antes de passar para a lactação.",
    weaningPigletsOnlyRead: "No desmame, os leitões apenas podem ser consultados.",
    pkidPigletsNotFound: "Não foi encontrado o identificador interno do animal.",
    pigletCaptureDone: "Registo de leitões guardado corretamente.",
    pigletCaptureError: "Não foi possível guardar o registo de leitões.",
    penNotFound: "Curral não encontrado",

  },
  subState: {
    prepartum: "Pré-parto",
    lactation: "Lactação",
    weaning: "Desmame",
  },

  capturaParto: {
    birthDataTitle: "Dados do parto",
    birthDataSubtitle: "Reveja os dados do animal antes de registar o parto.",
    corral: "Curral",
    id: "ID",
    date: "Data",
    subState: "Subestado",

    dataCollectionTitle: "Recolha de dados",
    dataCollectionSubtitle: "Introduza os nascidos vivos, mortos e mumificados.",
    weaningReadOnly: "No desmame, os dados apenas podem ser consultados.",

    totalBorn: "Total nascidos",
    live: "Vivos",
    dead: "Mortos",
    mummified: "Mumificados",

    prepartum: "Pré-parto",
    farrowing: "Parto",
    lactation: "Lactação",
    weaning: "Desmame",

    accept: "Aceitar",
    cancel: "Cancelar",
    saving: "A guardar...",

    sentTitle: "Registo enviado",
    sentMessage: "O registo do parto foi guardado corretamente.",

    errorTitle: "Erro",
    invalidAnimalTitle: "Animal inválido",
    invalidAnimalText: "Não foi encontrado o identificador interno do animal.",
    reportSendError: "Não foi possível guardar o registo do parto.",

    invalidDateTitle: "Data inválida",
    invalidDateMessage: "A data do parto não pode ser posterior a hoje.",
    changeDate: "Alterar data",

    selectDateTitle: "Selecionar data",
    selectDateMessage: "Ajuste a data do parto com os botões.",
  },
  capturaMaternidadEntrada: {
    title: "Registo de parto",
    description: "Procure o animal por curral ou por ID para registar o parto.",
    maternityLabel: "MATERNIDADE",

    corral: "Curral",
    corralDescription: "Procure o animal pelo número do curral.",
    id: "ID",
    idDescription: "Procure o animal pelo seu identificador.",
    animalId: "ID animal",

    corralExample: "Ex.: 102",
    idExample: "Ex.: 1234",

    consulting: "A consultar...",
    continue: "Continuar",
    accept: "Aceitar",

    serverConnectionError: "Não foi possível ligar ao servidor.",
  },
  altaBajaStack: {
    tituloPantalla: "Entrada/Baixa de leitões",
    descripcionPantalla: "Procure a mãe por curral ou ID para registar entradas ou baixas de leitões.",
  },
  altaBajaLechones: {
    heroTitle: "Movimento de leitões",
    statusAlta: "Entrada",
    statusBaja: "Baixa",

    corralUpper: "CURRAL",
    idUpper: "ID",
    dateUpper: "DATA",

    movementType: "Tipo de movimento",
    movementSubtitle: "Selecione se pretende registar uma entrada ou uma baixa.",
    adoption: "Adoção",
    baja: "Baixa",

    adoptionData: "Dados de adoção",
    donorMother: "Mãe dadora",
    donatesPiglets: "Doa leitões",
    id: "ID",
    transferredPiglets: "Leitões transferidos",
    totalAdopted: "Total adotados",
    total: "Total",

    bajaReason: "Motivo da baixa",
    reasonCrushing: "Esmagamento",
    reasonDiarrhea: "Diarreia",
    reasonLowViability: "Baixa viabilidade",
    reasonDeformities: "Deformidades",
    reasonOther: "Outros",

    piglet: "leitão",
    piglets: "leitões",
    description: "Descrição",

    editReason: "Editar motivo",
    addReason: "Adicionar motivo",
    reasonModalText: "Indique a quantidade de leitões e descreva o motivo.",

    saving: "A guardar...",
    saveAlta: "Guardar entrada",
    saveBaja: "Guardar baixa",
    accept: "Aceitar",
    cancel: "Cancelar",

    error: "Erro",
    missingData: "Dados em falta",
    saveError: "Erro ao guardar",
    saveErrorText: "Não foi possível guardar a operação.",
    selectedAnimalPkidNotFound: "Não foi encontrado o identificador interno do animal selecionado.",

    enterTransferredPiglets: "Introduza o número de leitões transferidos.",
    invalidTotalTitle: "Total inválido",
    invalidPigletsNumber: "Introduza um número válido de leitões.",

    missingDescriptionTitle: "Descrição obrigatória",
    missingDescriptionText: "Introduza a descrição do motivo.",
    invalidQuantityTitle: "Quantidade inválida",
    invalidPigletQuantity: "Introduza uma quantidade válida de leitões.",

    selectReasonRequired: "Selecione pelo menos um motivo de baixa.",

    adoptionSavedTitle: "Entrada guardada",
    adoptionSavedMessage: "{{count}} leitões foram registados corretamente.",

    bajasSavedTitle: "Baixas guardadas",
    bajasSavedMessage: "{{piglets}} baixas foram registadas corretamente em {{reasons}} motivo(s).",
  },
  avisoAplicacionNoConfigurada: {
    title: "Aplicação não configurada",
    text: "Configure o endereço IP do servidor",
    link: "Toque aqui",
  },
  generalHome: {
    servidorCtifeedDesactualizadoTitulo: "Servidor CTIFEED desatualizado",
  servidorCtifeedDesactualizadoTexto: "É necessário atualizar o servidor CTIFEED para usar esta funcionalidade.",
    tareasMovimientosTitulo: "Tarefas de movimentos",
tareasMovimientosDescripcion: "Consulta e gestão de tarefas pendentes de movimentos.",
    movementAnimalTitle: "Movimento animal",
    readerDescription: "Leitor de brincos.",
    keyboardDescription: "Teclado",

    ctifeedTitle: "CTIFEED",
    ctifeedDescription: "Aceda ao portal principal.",

    modalApplicationNotConfiguredTitle: "Aplicação não configurada",
    modalNoSessionTitle: "Sessão não iniciada",
    modalInstallationUnavailableTitle: "Instalação indisponível",
    modalPreparingSessionTitle: "A preparar sessão",
    modalReadOnlyPermissionTitle: "Permissão só de leitura",

    modalApplicationNotConfiguredText: "Não existe nenhuma instalação configurada. Vá a Instalações e selecione uma.",
    modalNoSessionText: "A instalação tem IP, mas não existe sessão iniciada. Verifique o nome de utilizador e a palavra-passe em Instalações.",
    modalInstallationUnavailableText: "Não é possível ligar à instalação selecionada. Verifique se está ligado à rede WiFi correta ou reveja o IP do servidor.",
    modalPreparingSessionText: "A sessão ainda está a carregar. Tente novamente dentro de alguns segundos.",
    modalReadOnlyPermissionText: "O seu utilizador não tem permissões de administrador para aceder a esta funcionalidade.",

    accept: "Aceitar",

    connectingTitle: "A ligar...",
    connectingText: "A verificar a ligação com a instalação selecionada.",
  },
  movimientoAnimalMaternidad: {
    smallLabel: "MOVIMENTO",
    title: "Maternidade",
    subtitle: "Realize entradas e saídas manuais pelo teclado.",

    movementType: "Tipo de movimento",
    entry: "Entrada",
    exit: "Saída",

    searchAnimal: "Procurar animal",
    entryHelper: "Introduza o curral de destino e o ID do animal.",
    exitHelper: "Selecione se pretende fazer a saída por curral ou por ID.",

    pen: "Curral",
    animalId: "ID animal",
    type: "Tipo",

    sending: "A enviar...",
    accept: "Aceitar",
    cancel: "Cancelar",

    confirmEntry: "Confirmar entrada",
    confirmExit: "Confirmar saída",
    confirmSubtitle: "Reveja os dados antes de enviar o movimento.",

    incompleteDataTitle: "Dados incompletos",
    entryIncompleteText: "Introduza o curral e o ID do animal.",
    exitPenIncompleteText: "Introduza o curral para fazer a saída.",
    exitIdIncompleteText: "Introduza o ID do animal para fazer a saída.",

    invalidPenTitle: "Curral inválido",
    invalidPenText: "O curral deve ser um número válido maior que 0.",

    sendErrorTitle: "Erro ao enviar",
    connectionErrorTitle: "Erro de ligação",
    noIpConfigured: "Não existe IP configurado.",
    serverConnectionError: "Não foi possível ligar ao servidor.",
    serverEmptyResponse: "O servidor não devolveu mensagem. Código HTTP {{status}}.",

    entrySentTitle: "Entrada enviada",
    entrySentText: "O movimento de entrada foi enviado corretamente.",

    exitSentTitle: "Saída enviada",
    exitByPenSentText: "A saída por curral foi enviada corretamente.",
    exitByIdSentText: "A saída por ID foi enviada corretamente.",
  },

  movimientoAnimalGestacion: {
    smallLabel: "GESTAÇÃO",
    title: "Movimento animal",
    subtitle: "Realize entradas e saídas manuais pelo teclado.",

    movementType: "Tipo de movimento",
    entry: "Entrada",
    exit: "Saída",

    searchAnimal: "Procurar animal",
    entryHelper: "Introduza o curral de destino e o ID do animal.",
    exitHelper: "Introduza o ID do animal para fazer a saída de gestação.",

    pen: "Curral",
    animalId: "ID animal",
    type: "Tipo",

    sending: "A enviar...",
    accept: "Aceitar",
    cancel: "Cancelar",

    confirmEntry: "Confirmar entrada",
    confirmExit: "Confirmar saída",
    confirmSubtitle: "Reveja os dados antes de enviar o movimento.",

    incompleteDataTitle: "Dados incompletos",
    entryIncompleteText: "Introduza o curral e o ID do animal.",
    exitIdIncompleteText: "Introduza o ID do animal para fazer a saída.",

    invalidPenTitle: "Curral inválido",
    invalidPenText: "O curral deve ser um número válido maior que 0.",

    sendErrorTitle: "Erro ao enviar",
    noIpConfigured: "Não existe IP configurado.",
    serverConnectionError: "Não foi possível ligar ao servidor.",
    serverEmptyResponse: "O servidor não devolveu mensagem. Código HTTP {{status}}.",

    entrySentTitle: "Entrada enviada",
    entrySentText: "O movimento de entrada em gestação foi enviado corretamente.",

    exitSentTitle: "Saída enviada",
    exitByIdSentText: "A saída por ID em gestação foi enviada corretamente.",
  },
  gestCorralDetail: {
    title: "Estado animal gestação",
    emptyTitle: "Não há animal neste curral",

    id: "ID",
    crotal: "Brinco",
    cycle: "Ciclo",
    day: "Dia",

    stateGestation: "Gestação",
    stateOutOfGestation: "Fora de gestação",

    curve: "Curva",
    correction: "Correção",
    entryDate: "Data de entrada",
    inseminationDate: "Data de inseminação",
    house: "Pavilhão",
    corral: "Curral",
    estimatedFarrowingDate: "Data estimada de parto",
    lastFeeding: "Última alimentação",

    oneDayWithoutFeeding: "1 dia sem alimentação",
    daysWithoutFeeding: "{{count}} dias sem alimentação",
    of: "de",

    operationsButton: "Operações",
    operationsTitle: "Operações",
    operationsSubtitle: "Selecione uma operação",

    operationInseminationDate: "Data de inseminação",
    operationCurve: "Curva",
    operationBodyCondition: "Condição corporal",
    operationChangePen: "Mudança de curral",
    operationExitAnimal: "Saída animal",
    operationReplaceEarTag: "Substituir brinco",

    cancel: "Cancelar",
    accept: "Aceitar",
    saving: "A guardar...",

    selectCurve: "Selecionar curva",
    loadingCurves: "A carregar curvas...",
    noCurvesAvailable: "Não há curvas disponíveis",

    selectBodyCondition: "Selecionar condição corporal",
    loadingBodyConditions: "A carregar condições corporais...",
    noBodyConditionsAvailable: "Não há condições corporais disponíveis",

    changePenTitle: "Mudar curral",
    currentPen: "Curral atual: {{corral}}",
    newPen: "Novo curral",
    changePenPlaceholder: "Introduza o curral de destino",

    replaceEarTagTitle: "Substituir brinco",
    currentEarTag: "Brinco atual: {{crotal}}",
    newEarTag: "Novo brinco",
    replaceEarTagPlaceholder: "Introduza o novo brinco",

    inseminationDateTitle: "Data de inseminação",
    selectDate: "Selecione a data",
    noFutureInseminationDate: "Não é permitido selecionar uma data posterior à atual.",

    exitAnimalTitle: "Saída animal",
    exitAnimalGestation: "Saída animal gestação",
    exitDate: "Data de saída",
    noFutureExitDate: "A data de saída não pode ser posterior à data atual.",

    penNotFound: "Curral não encontrado",
    changePenGenericError: "Não foi possível mudar o curral.",
    earTagAlreadyAssigned: "O brinco está atribuído a outro animal",
    replaceEarTagGenericError: "Não foi possível substituir o brinco.",
  },
  tareasMovimientos: {
    tabs: {
      tareas: "Tarefas",
      historial: "Histórico"
    },

    secciones: {
      gestacion: "Gestação",
      maternidad: "Maternidade",
      todos: "Todos",
      todas: "Todas"
    },

    operaciones: {
      entrada: "Entrada",
      salida: "Saída",
      realizada: "Concluída"
    },

    tarjetas: {
      tareasPendientesMovimientos: "Tarefas pendentes de movimentos",
      idAnimal: "ID animal",
      sinCrotal: "Sem brinco",
      corralDestino: "Curral de destino",
      corralOrigen: "Curral de origem",
      fecha: "Data programada",
      fechaRealizado: "Data realizada",
    },

    filtros: {
      titulo: "Filtros",
      filtrarPorFecha: "Filtrar por data",
      hoy: "Hoje",
      ayer: "Ontem",
      fecha: "Data",
      formatoFecha: "DD/MM/AAAA"
    },

    carga: {
      cargandoHistorial: "A carregar histórico..."
    },

    vacio: {
      sinResultados: "Sem resultados",
      sinMovimientosConFiltros: "Não há movimentos concluídos com estes filtros.",
      sinMovimientosTodavia: "Ainda não há movimentos concluídos."
    },

    errores: {
      actualizarServidorTareas: "É necessário atualizar o servidor para utilizar a função de tarefas de movimentos.",
      noCargarTareas: "Não foi possível carregar as tarefas.",
      noCargarHistorialTitulo: "Não foi possível carregar o histórico",
      noCargarHistorial: "Não foi possível carregar o histórico de movimentos.",
      historialNoDisponible: "Histórico indisponível",
      actualizarServidorHistorial: "É necessário atualizar o servidor para utilizar o histórico de tarefas de movimentos."
    }
  },
  tareasMovimientosDetalle: {
    tabs: {
      gestacion: "Gestação",
      maternidad: "Maternidade"
    },

    acciones: {
      filtros: "Filtros",
      ordenar: "Ordenar",
      marcarRealizado: "Marcar como concluída",
      marcarSeleccionadas: "Marcar ({{total}})",
      marcando: "A marcar...",
      aceptar: "Aceitar",
      cancelar: "Cancelar",
      confirmar: "Confirmar",
      validando: "A validar..."
    },

    orden: {
      corralAscendente: "Curral ascendente",
      corralDescendente: "Curral descendente"
    },

    operaciones: {
      entrada: "Entrada",
      salida: "Saída",
      trasladoEntrada: "Entrada por transferência",
      trasladoSalida: "Saída por transferência"
    },

    tarjetas: {
      idAnimal: "ID animal",
      sinCrotal: "Sem brinco",
      corralDestino: "Curral de destino",
      corralOrigen: "Curral de origem",
      fecha: "Data"
    },

    estados: {
      cargandoTareas: "A carregar tarefas...",
      noCargarTareasTitulo: "Não foi possível carregar as tarefas",
      pulsaReintentar: "Toque para tentar novamente",
      sinTareasConFiltros: "Não há tarefas com estes filtros",
      sinTareasPendientes: "Não há tarefas pendentes",
      cambiaFiltros: "Experimente alterar os filtros aplicados.",
      sinMovimientosPendientes: "Não foram encontrados movimentos pendentes."
    },

    modalResultado: {
      tareasRealizadasTitulo: "Tarefas concluídas",
      tareasRealizadasMensaje: "As tarefas selecionadas foram marcadas como concluídas.",
      tareaRealizadaTitulo: "Tarefa concluída",
      tareaRealizadaMensaje: "A entrada de maternidade foi marcada como concluída.",
      errorTitulo: "Erro"
    },

    modalCorral: {
      titulo: "Confirmar curral",
      mensaje: "Verifique o curral de destino da entrada em maternidade.",
      labelCorralDestino: "Curral de destino",
      placeholderCorral: "Introduza o curral"
    },

    errores: {
      noCargarTareas: "Não foi possível carregar as tarefas.",
      entradaMaternidadTitulo: "Entrada de maternidade",
      soloUnaEntradaMaternidad: "Só pode marcar uma entrada de maternidade de cada vez.",
      soloUnaEntradaMaternidadCadaVez: "Só pode marcar uma entrada de maternidade por vez.",
      noMarcarTareas: "Não foi possível marcar as tarefas como concluídas.",
      corralMaximo9: "Introduza um curral válido com no máximo 9 dígitos.",
      corralNoExiste: "O curral não existe.",
      corralOcupado: "O curral está ocupado.",
      noValidarCorral: "Não foi possível validar o curral.",
      noValidarCorralMaternidad: "Não foi possível validar o curral de maternidade."
    }
  },
  filtrosTareasMovimientos: {
    cabecera: {
      titulo: "Filtros",
      subtituloTareasDe: "Tarefas de {{seccion}}",
      limpiar: "Limpar"
    },

    secciones: {
      gestacion: "Gestação",
      maternidad: "Maternidade"
    },

    bloques: {
      tipoMovimiento: "Tipo de movimento",
      fecha: "Data",
      corral: "Curral",
      idAnimal: "ID animal"
    },

    opciones: {
      todos: "Todos",
      entrada: "Entrada",
      salida: "Saída",
      todasLasFechas: "Todas as datas",
      hoy: "Hoje",
      manana: "Amanhã",
      fecha: "Data",
      todosLosCorrales: "Todos os currais",
      porCorral: "Por curral",
      todosLosAnimales: "Todos os animais",
      porId: "Por ID"
    },

    placeholders: {
      dia: "DD",
      mes: "MM",
      anio: "AA/AAAA",
      introduceCorral: "Introduza o curral",
      introduceIdAnimal: "Introduza o ID animal"
    },

    validaciones: {
      fechaCompleta: "Introduza dia, mês e ano.",
      diaDosCifras: "O dia deve ter 2 dígitos.",
      mesDosCifras: "O mês deve ter 2 dígitos.",
      anioDosOCuatroCifras: "O ano deve ter 2 ou 4 dígitos.",
      diaRango: "O dia deve estar entre 01 e 31.",
      mesRango: "O mês deve estar entre 01 e 12.",
      fechaNoExiste: "A data não existe.",
      introduceCorral: "Introduza um número de curral.",
      introduceIdAnimal: "Introduza um ID animal."
    },

    botones: {
      cancelar: "Cancelar",
      aceptar: "Aceitar"
    }
  },
  filtrosHistorialMovimientos: {
    cabecera: {
      titulo: "Filtros",
      subtitulo: "Histórico de movimentos",
      limpiar: "Limpar"
    },

    bloques: {
      tipoMovimiento: "Tipo de movimento",
      fecha: "Data",
      corral: "Curral",
      idAnimal: "ID animal"
    },

    opciones: {
      todos: "Todos",
      entrada: "Entrada",
      salida: "Saída",
      todasLasFechas: "Todas as datas",
      hoy: "Hoje",
      manana: "Amanhã",
      fecha: "Data",
      todosLosCorrales: "Todos os currais",
      porCorral: "Por curral",
      todosLosAnimales: "Todos os animais",
      porId: "Por ID"
    },

    placeholders: {
      dia: "DD",
      mes: "MM",
      anio: "AA/AAAA",
      introduceCorral: "Introduza o curral",
      introduceIdAnimal: "Introduza o ID animal"
    },

    validaciones: {
      fechaCompleta: "Introduza dia, mês e ano.",
      diaDosCifras: "O dia deve ter 2 dígitos.",
      mesDosCifras: "O mês deve ter 2 dígitos.",
      anioDosOCuatroCifras: "O ano deve ter 2 ou 4 dígitos.",
      diaRango: "O dia deve estar entre 01 e 31.",
      mesRango: "O mês deve estar entre 01 e 12.",
      fechaNoExiste: "A data não existe.",
      introduceCorral: "Introduza um número de curral.",
      introduceIdAnimal: "Introduza um ID animal."
    },

    botones: {
      cancelar: "Cancelar",
      aceptar: "Aceitar"
    }
  },
  modalSalidaPendiente: {
    titulo: "Saída pendente",
    mensaje: "Este animal tem uma tarefa de saída pendente. Pretende concluir primeiro a saída e depois realizar a entrada selecionada?",
    animal: "Animal",
    botonConfirmar: "Realizar operação",
    trasladoEntradaTitulo: "Transferência de entrada",
    soloUnTrasladoEntrada: "Só pode selecionar uma transferência de entrada de cada vez.",
  }
}