export default {
  username: 'Пользователь',
  password: 'Пароль',
  login: 'Войти',
  welcome: 'Добро пожаловать',
  change_language: 'Сменить язык',
  Tabs: 'Главная',

  Lista_instalaciones: 'Установки',
  Maintenance: 'Техническое обслуживание',
  DetallesInstalacion: 'Детали установки',
  Grabar: 'Сохранить',
  EstadoStore: 'Статус store',
  Nodata: 'Нет данных',
  DosimacRegistration: 'Регистрация',
  NewDmMaternity: 'Новый Dosimac родильное',
  DosimacG: 'Dosimac-G',
  DosimacI: 'Dosimac-I',
  UpdDmMaternity: 'Изменение Dosimac родильное',
  NewDmGestation: 'Новый Dosimac беременность',
  UpdDmGestation: 'Изменение Dosimac беременность',
  StartScan: 'Поиск устройств DOSIMAC',
  DosimacList: 'Устройства DOSIMAC',
  PressToScan: 'Нажмите',
  DosimacSetup: 'Конфигурация',
  TestoPresioneAlta: 'Нажмите кнопку, чтобы найти устройства',
  Instalación_seleccionada: 'Выбранная установка',
  NoInstalacionSeleccionada: 'Нет выбранной установки',
  BorrarGranja: 'Удалить ферму',
  Deseaborrarlagranja: 'Хотите удалить ферму?',
  Guardar: 'Сохранить',
  Cancelar: 'Отмена',
  Aceptar: 'Принять',
  NombreGranja: 'Название фермы',
  Localidad: 'Местоположение',
  Provincia: 'Область',
  NombreWifi: 'Wifi SSID',
  PasswordWifi: 'Пароль Wifi',
  No_hay_dispositivos: 'Нет устройств',
  Aviso: 'Уведомление',
  SearchingDevices: 'Поиск устройств...',
  NoSePuedeBorrarGranja: 'Нельзя удалить новую ферму',
  settings: 'Настройки',
  softwareVersion: 'Версия ПО',
  numeroCoral: 'Номер загона',
  numeroMaquina: 'Номер машины',
  Enviar: 'Отправить',
  Salir: 'Выйти',
  Informacion: 'Информация',
  InicioConfiguracion: "Початок підключення",
  ConfiguracionWifi: "Налаштування...",
  ConfiguracionRealizada: "*Налаштування виконано*",
  ErrorConfiguracion: "*Помилка налаштування*",
  CapturaTagCorral: "Зчитати тег загону",
  CorralTag: "Тег загону",
  versionUint16: "Ця версія пристрою підтримує номер загону лише до 65000",
  versionUint32: "Ця версія пристрою підтримує номер загону до 4000000000",
  EnvioConfiguracion: "Відправка конфігурації",
  NumeroCorral: "Номер загону",
  NumeroMaquina: "Номер машини",
  Corralnovalida: "Недійсний номер загону",
  NumeroMaquinanovalida: "Недійсний номер машини",
  configuarIntalacion: "Необхідно налаштувати установку перед використанням цієї функції",

  login_title: "Увійти",
  login_subtitle: "Введіть свої дані. Перед входом необхідно налаштувати IP у меню Налаштування IP.",
  login_username: "Користувач",
  login_password: "Пароль",
  login_button: "Увійти",
  login_loading: "Вхід...",
  login_footer: "Панель керування",

  login_ipRequiredTitle: "Потрібне налаштування IP",
  login_ipRequiredMessage: "Ви не налаштували IP-адресу сервера. Введіть її, щоб увійти.",
  login_serverIpLabel: "IP сервера",
  login_cancel: "Скасувати",
  login_accept: "Прийняти",
  login_invalidCredentials: "Неправильне ім’я користувача або пароль",

  login_configTitle: "Налаштування",
  login_errorTitle: "Помилка входу",
  login_genericErrorTitle: "Помилка",
  login_networkErrorTitle: "Помилка мережі",
  login_networkErrorMessage: "Не вдалося підключитися до сервера.",
  login_noTokenMessage: "Бекенд не повернув жодного токена.",
  login_missingDataTitle: "Бракує даних",
  login_missingDataMessage: "Введіть ім’я користувача та пароль.",
  login_invalidIpTitle: "Неправильний IP",
  login_invalidIpMessage: "Введіть дійсний IP або адресу сервера.",
  login_saveIpErrorMessage: "Не вдалося зберегти налаштування IP.",
  awrStartScan_title: "Налаштування AWR",
  awrStartScan_description: "Екран для сканування зчитувачів Agrident AWR.",
  awrStartScan_button: "Сканувати AWR",

  gestacionConfig_screenTitle: "Налаштування гестації",
  gestacionConfig_chooseOptionTitle: "Оберіть варіант",
  gestacionConfig_chooseOptionDescription: "Визначте потік перед початком роботи зі зчитувачем.",

  gestacionConfig_entry: "Вхід",
  gestacionConfig_exit: "Вихід",
  gestacionConfig_reading: "Зчитування",
  gestacionConfig_search: "Пошук",

  gestacionConfig_entryParamsTitle: "Параметри входу",
  gestacionConfig_exitParamsTitle: "Параметри виходу",
  gestacionConfig_entryParamsDescription: "Оберіть загін і поведінку потоку.",
  gestacionConfig_exitParamsDescription: "Налаштуйте поведінку потоку виходу.",

  gestacionConfig_corralLabel: "Загін",
  gestacionConfig_corralPlaceholder: "Напр.: 1",
  gestacionConfig_corralRequired: "Введіть загін, щоб продовжити.",

  gestacionConfig_detectUnknownTitle: "Визначати невідомих тварин",
  gestacionConfig_detectUnknownDescription: "Коли ви зчитаєте неідентифіковану тварину, ви зможете призначити їй ID",

  gestacionConfig_confirmTitle: "Підтвердити надсилання",
  gestacionConfig_confirmDescription: "Перед надсиланням записів буде запитано підтвердження.",

  gestacionConfig_animalSearchTitle: "Пошук тварини",
  gestacionConfig_animalSearchDescription: "Оберіть пошук за біркою або за ID.",
  gestacionConfig_searchByCrotal: "За біркою",
  gestacionConfig_searchById: "За ID",
  gestacionConfig_manual: "Вручну",
  gestacionConfig_withSword: "Зі сканером",

  gestacionConfig_crotalLabelSearch: "Бірка",
  gestacionConfig_idLabelSearch: "ID",
  gestacionConfig_crotalPlaceholderSearch: "Напр.: 982091072397436",
  gestacionConfig_idPlaceholderSearch: "Напр.: A13",
  gestacionConfig_crotalRequiredSearch: "Введіть бірку, щоб продовжити.",
  gestacionConfig_idRequiredSearch: "Введіть ID, щоб продовжити.",

  gestacionConfig_searchWithSwordHelp: "Після продовження на цьому екрані буде виконано зчитування сканером, і тварину буде знайдено за цією біркою.",

  gestacionConfig_readingSword: "Зчитування сканером...",
  gestacionConfig_waitingMatch: "Очікування збігу",
  gestacionConfig_searchingAnimal: "Пошук тварини...",

  gestacionConfig_readingSwordDescription: "Піднесіть бірку до зчитувача, щоб ідентифікувати тварину.",
  gestacionConfig_waitingMatchDescription: "Тварину знайдено. Тепер піднесіть до сканера бірку {{crotal}}, щоб підтвердити збіг.",
  gestacionConfig_searchingAnimalDescription: "Перевірка інформації про тварину в backend.",

  gestacionConfig_awrDisconnectedTitle: "AWR не підключено",
  gestacionConfig_awrSavedDescription: "У вас є збережені сканери. Натисніть, щоб вибрати один.",
  gestacionConfig_awrNotSavedDescription: "У вас немає збережених сканерів. Натисніть, щоб відсканувати один.",

  gestacionConfig_scan: "Сканувати",
  gestacionConfig_continue: "Продовжити",

  gestacionConfig_alerts_error: "Помилка",
  gestacionConfig_alerts_networkError: "Помилка мережі",
  gestacionConfig_alerts_networkErrorMessage: "Не вдалося підключитися до сервера.",
  gestacionConfig_alerts_backendNoValidCrotal: "Backend не повернув дійсну бірку для порівняння.",
  gestacionConfig_alerts_awrNotConnected: "AWR не підключено",
  gestacionConfig_alerts_connectSwordBeforeContinue: "Підключіть сканер перед продовженням.",
  gestacionConfig_alerts_couldNotStartReading: "Не вдалося почати зчитування сканером.",

  gestacionConfig_alerts_missingData: "Бракує даних",
  gestacionConfig_alerts_writeCrotalToSearch: "Введіть бірку для пошуку.",
  gestacionConfig_alerts_writeIdToSearch: "Введіть ID для пошуку.",

  gestacionConfig_alerts_notFound: "Не знайдено",
  gestacionConfig_alerts_animalNotFoundByCrotal: "Тварини з такою біркою не існує.",
  gestacionConfig_alerts_animalNotFoundById: "Тварини з таким ID не існує.",

  gestacionConfig_alerts_warning: "Попередження",
  gestacionConfig_alerts_searchError: "Помилка пошуку",

  maternidadConfig_screenTitle: "Налаштування материнського відділення",
  maternidadConfig_chooseOptionTitle: "Оберіть варіант",
  maternidadConfig_chooseOptionDescription: "Визначте потік перед початком роботи зі зчитувачем.",
  maternidadConfig_entry: "Вхід",
  maternidadConfig_exit: "Вихід",
  maternidadConfig_reading: "Зчитування",
  maternidadConfig_search: "Пошук",
  maternidadConfig_entryParamsTitle: "Параметри входу",
  maternidadConfig_exitParamsTitle: "Параметри виходу",
  maternidadConfig_entryParamsDescription: "Виберіть загін і поведінку потоку.",
  maternidadConfig_exitParamsDescription: "Налаштуйте поведінку потоку виходу.",
  maternidadConfig_corralLabel: "Загін",
  maternidadConfig_corralPlaceholder: "Напр.: 1",
  maternidadConfig_corralRequired: "Введіть загін, щоб продовжити.",
  maternidadConfig_detectUnknownTitle: "Визначати невідомих тварин",
  maternidadConfig_detectUnknownDescription: "Коли ви зчитаєте неідентифіковану тварину, ви зможете призначити їй ID",
  maternidadConfig_confirmTitle: "Підтверджувати надсилання",
  maternidadConfig_confirmDescription: "Перед надсиланням кожного запису буде запитано підтвердження.",
  maternidadConfig_animalSearchTitle: "Пошук тварини",
  maternidadConfig_animalSearchDescription: "Оберіть пошук за crotal або за ID.",
  maternidadConfig_searchByCrotal: "За crotal",
  maternidadConfig_searchById: "За ID",
  maternidadConfig_manual: "Вручну",
  maternidadConfig_withSword: "Зі сканером",
  maternidadConfig_crotalLabelSearch: "Crotal",
  maternidadConfig_idLabelSearch: "ID",
  maternidadConfig_crotalPlaceholderSearch: "Напр.: 982091072397436",
  maternidadConfig_idPlaceholderSearch: "Напр.: A13",
  maternidadConfig_crotalRequiredSearch: "Введіть crotal, щоб продовжити.",
  maternidadConfig_idRequiredSearch: "Введіть ID, щоб продовжити.",
  maternidadConfig_searchWithSwordHelp: "Після натискання Сканувати сканер буде використано на цьому екрані, і тварину буде знайдено за цим crotal.",
  maternidadConfig_readingSword: "Зчитування сканера...",
  maternidadConfig_waitingMatch: "Очікування збігу",
  maternidadConfig_searchingAnimal: "Пошук тварини...",
  maternidadConfig_readingSwordDescription: "Піднесіть crotal до зчитувача, щоб визначити тварину.",
  maternidadConfig_waitingMatchDescription: "Тварину знайдено. Тепер піднесіть crotal {{crotal}} до сканера, щоб підтвердити збіг.",
  maternidadConfig_searchingAnimalDescription: "Отримання інформації про тварину з backend.",
  maternidadConfig_awrDisconnectedTitle: "AWR не підключено",
  maternidadConfig_awrSavedDescription: "У вас є збережені AWR. Натисніть, щоб вибрати одну.",
  maternidadConfig_awrNotSavedDescription: "У вас немає збережених AWR. Натисніть, щоб відсканувати одну.",
  maternidadConfig_scan: "Сканувати",
  maternidadConfig_continue: "Продовжити",
  maternidadConfig_alert_error: "Помилка",
  maternidadConfig_alert_invalidBackendCrotal: "Backend не повернув коректний crotal для порівняння.",
  maternidadConfig_alert_awrNotConnected: "AWR не підключено",
  maternidadConfig_alert_connectSwordBeforeContinue: "Підключіть сканер перед продовженням.",
  maternidadConfig_alert_couldNotStartReading: "Не вдалося розпочати зчитування сканером.",
  maternidadConfig_alert_missingData: "Бракує даних",
  maternidadConfig_alert_writeCrotalToSearch: "Введіть crotal для пошуку.",
  maternidadConfig_alert_writeIdToSearch: "Введіть ID для пошуку.",
  maternidadConfig_alert_notFound: "Не знайдено",
  maternidadConfig_alert_noAnimalWithCrotal: "Тварину з таким crotal не знайдено.",
  maternidadConfig_alert_noAnimalWithId: "Тварину з таким ID не знайдено.",
  maternidadConfig_alert_warning: "Попередження",
  maternidadConfig_alert_searchError: "Помилка пошуку",
  maternidadConfig_alert_networkError: "Помилка мережі",
  maternidadConfig_alert_networkErrorMessage: "Не вдалося підключитися до сервера.",


  gestationReader_screenTitle: "Зчитувач гестації",
  gestationReader_animalInfoTitle: "Інформація про тварину",
  gestationReader_animalInfoDescription: "Дані, знайдені під час пошуку.",
  gestationReader_animalCardTitle: "Картка тварини",
  gestationReader_animalIdLabel: "ID",
  gestationReader_animalCrotalLabel: "Бірка",
  gestationReader_fieldCorral: "Загін",
  gestationReader_fieldHouse: "Корпус",
  gestationReader_fieldState: "Стан",
  gestationReader_fieldBodyCondition: "Фізичний стан",
  gestationReader_fieldCycle: "Цикл",
  gestationReader_fieldSystemEntryDate: "Дата входу в систему",
  gestationReader_newSearch: "Новий пошук",
  gestationReader_summaryTitle: "Підсумок",
  gestationReader_summaryDescription: "Параметри, вибрані в налаштуваннях",
  gestationReader_mode: "Режим",
  gestationReader_corral: "Загін",
  gestationReader_modeEntry: "Вхід",
  gestationReader_modeExit: "Вихід",
  gestationReader_modeReading: "Зчитування",
  gestationReader_modeSearch: "Пошук",
  gestationReader_detectUnknownTitle: "Визначати невідомих тварин",
  gestationReader_detectUnknownDescription: "Якщо з'явиться тварина без ID, запропонувати призначити їй ID.",
  gestationReader_confirmSendTitle: "Підтвердження надсилання",
  gestationReader_confirmSendDescription: "Перед надсиланням кожного запису буде запитано підтвердження.",
  gestationReader_changeSettings: "Змінити налаштування",
  gestationReader_currentReadingTitle: "Поточне зчитування",
  gestationReader_currentReadingDescription: "Тут з'являться виявлена бірка та пов'язаний ID.",
  gestationReader_awrDisconnected: "AWR не підключено",
  gestationReader_readCrotal: "Зчитана бірка",
  gestationReader_readId: "ID",
  gestationReader_animalWithoutAssignedId: "Тварина без призначеного ID",
  gestationReader_unknownAnimal: "Невідома тварина",
  gestationReader_animalWithoutIdTitle: "Тварина без ID",
  gestationReader_animalWithoutIdDescription: "Введіть ID вручну, щоб оновити зчитану бірку.",
  gestationReader_newIdLabel: "Новий ID",
  gestationReader_newIdPlaceholder: "Напр.: A13",
  gestationReader_updateId: "Оновити ID",
  gestationReader_updatingId: "Оновлення...",
  gestationReader_sentRecordsTitle: "Надіслані записи",
  gestationReader_noRecords: "Немає записів.",
  gestationReader_tableHeaderCorral: "Загін",
  gestationReader_tableHeaderId: "ID",
  gestationReader_tableHeaderCrotal: "Бірка",
  gestationReader_buttonAutoReading: "Автоматичне зчитування активне",
  gestationReader_buttonAutoSending: "Автоматичне надсилання активне",
  gestationReader_buttonSending: "Надсилання...",
  gestationReader_buttonSend: "Надіслати",
  gestationReader_alertError: "Помилка",
  gestationReader_alertWarning: "Попередження",
  gestationReader_alertNetworkError: "Помилка мережі",
  gestationReader_alertMissingCrotalTitle: "Відсутня бірка",
  gestationReader_alertMissingCrotalMessage: "Піднесіть бірку до зчитувача перед надсиланням.",
  gestationReader_alertInvalidCrotalTitle: "Некоректна бірка",
  gestationReader_alertInvalidCrotalMessage: "Бірка має бути числовою.",
  gestationReader_alertReadErrorTitle: "Помилка зчитування",
  gestationReader_alertNetworkErrorMessage: "Не вдалося підключитися до сервера.",
  gestationReader_alertMissingCorralTitle: "Відсутній загін",
  gestationReader_alertMissingCorralMessage: "Введіть загін перед надсиланням.",
  gestationReader_alertInvalidCorralTitle: "Некоректний загін",
  gestationReader_alertInvalidCorralMessage: "Загін має бути числом.",
  gestationReader_alertSendErrorTitle: "Помилка під час надсилання",
  gestationReader_alertNoIpConfigured: "IP не налаштовано.",
  gestationReader_alertMissingIdTitle: "Відсутній ID",
  gestationReader_alertMissingIdMessage: "Введіть новий ID перед оновленням.",
  gestationReader_alertMissingAssociatedCrotalTitle: "Відсутня бірка",
  gestationReader_alertMissingAssociatedCrotalMessage: "Немає пов'язаної бірки для оновлення.",
  gestationReader_alertInvalidAssociatedCrotalTitle: "Некоректна бірка",
  gestationReader_alertInvalidAssociatedCrotalMessage: "Пов'язана бірка недійсна.",
  gestationReader_alertUpdateIdErrorTitle: "Помилка під час оновлення ID",


  maternityReader_screenTitle: "Зчитувач материнського відділення",
  maternityReader_alertMissingCrotalTitle: "Відсутня бірка",
  maternityReader_alertMissingCrotalMessage: "Піднесіть бірку до зчитувача перед відправленням.",
  maternityReader_alertInvalidCrotalTitle: "Невірна бірка",
  maternityReader_alertInvalidCrotalMessage: "Бірка має бути числовою.",
  maternityReader_alertReadErrorTitle: "Помилка зчитування",
  maternityReader_alertNetworkError: "Помилка мережі",
  maternityReader_alertNetworkErrorMessage: "Не вдалося підключитися до сервера.",
  maternityReader_alertMissingCorralTitle: "Відсутній загін",
  maternityReader_alertMissingCorralMessage: "Введіть загін перед відправленням.",
  maternityReader_alertInvalidCorralTitle: "Невірний загін",
  maternityReader_alertInvalidCorralMessage: "Загін має бути числом (наприклад: 8).",
  maternityReader_alertError: "Помилка",
  maternityReader_alertNoIpConfigured: "IP не налаштовано.",
  maternityReader_alertWarning: "Попередження",
  maternityReader_alertSendErrorTitle: "Помилка надсилання",
  maternityReader_alertMissingIdTitle: "Відсутній ID",
  maternityReader_alertMissingIdMessage: "Введіть новий ID перед оновленням.",
  maternityReader_alertMissingAssociatedCrotalTitle: "Відсутня бірка",
  maternityReader_alertMissingAssociatedCrotalMessage: "Немає пов'язаної бірки для оновлення.",
  maternityReader_alertInvalidAssociatedCrotalTitle: "Невірна бірка",
  maternityReader_alertInvalidAssociatedCrotalMessage: "Пов'язана бірка недійсна.",
  maternityReader_alertUpdateIdErrorTitle: "Помилка оновлення ID",
  maternityReader_animalInfoTitle: "Інформація про тварину",
  maternityReader_animalInfoDescription: "Дані, знайдені під час пошуку.",
  maternityReader_animalCardTitle: "Картка тварини",
  maternityReader_animalIdLabel: "ID",
  maternityReader_animalCrotalLabel: "Бірка",
  maternityReader_fieldCorral: "Загін",
  maternityReader_fieldHouse: "Приміщення",
  maternityReader_fieldState: "Стан",
  maternityReader_fieldBodyCondition: "Стан тіла",
  maternityReader_fieldCycle: "Цикл",
  maternityReader_fieldSystemEntryDate: "Внесено в систему",
  maternityReader_newSearch: "Новий пошук",
  maternityReader_summaryTitle: "Підсумок",
  maternityReader_summaryDescription: "Параметри, вибрані в налаштуваннях",
  maternityReader_mode: "Режим",
  maternityReader_modeEntry: "Вхід",
  maternityReader_modeExit: "Вихід",
  maternityReader_modeReading: "Зчитування",
  maternityReader_corral: "Загін",
  maternityReader_detectUnknownTitle: "Визначати невідомих тварин",
  maternityReader_detectUnknownDescription: "Якщо з’явиться тварина без ID, можна призначити їй ID.",
  maternityReader_confirmSendTitle: "Підтверджувати надсилання",
  maternityReader_confirmSendDescription: "Перед надсиланням кожного запису буде запитуватися підтвердження.",
  maternityReader_changeSettings: "Змінити налаштування",
  maternityReader_currentReadingTitle: "Поточне зчитування",
  maternityReader_currentReadingDescription: "Виявлена бірка з’явиться тут.",
  maternityReader_awrDisconnected: "AWR не підключено",
  maternityReader_readCrotal: "Зчитана бірка",
  maternityReader_readId: "ID",
  maternityReader_animalWithoutAssignedId: "Тварина без призначеного ID",
  maternityReader_unknownAnimal: "Невідома тварина",
  maternityReader_animalWithoutIdTitle: "Тварина без ID",
  maternityReader_animalWithoutIdDescription: "Введіть ID вручну, щоб оновити зчитану бірку.",
  maternityReader_newIdLabel: "Новий ID",
  maternityReader_newIdPlaceholder: "Напр.: A13",
  maternityReader_updatingId: "Оновлення...",
  maternityReader_updateId: "Оновити ID",
  maternityReader_sentRecordsTitle: "Надіслані записи",
  maternityReader_tableHeaderCorral: "Загін",
  maternityReader_tableHeaderId: "ID",
  maternityReader_tableHeaderCrotal: "Бірка",
  maternityReader_noRecords: "Немає записів.",
  maternityReader_buttonAutoReading: "Автоматичне зчитування активне",
  maternityReader_buttonAutoSending: "Автоматичне надсилання активне",
  maternityReader_buttonSending: "Надсилання...",
  maternityReader_buttonSend: "Надіслати",

  awrScanResults_title: "AWR – Результати сканування",
  awrScanResults_searching: "Пошук AWR…",
  awrScanResults_warningTitle: "Попередження",
  awrScanResults_noDevicesNearby: "Поруч не знайдено AWR.",
  awrScanResults_connecting: "Підключення…",
  awrScanResults_connectErrorFallback: "Не вдалося підключитися",
  awrScanResults_connectedTitle: "Підключено",
  awrScanResults_connectedMessage: "З’єднання встановлено з {{device}}.",
  awrScanResults_genericDevice: "пристроєм",

  awrSavedList_title: "Відскановані AWR",
  awrSavedList_connecting: "Підключення…",
  awrSavedList_empty: "Немає збережених AWR. Відскануйте один у розділі «Configuración AWR».",
  awrSavedList_connected: "Підключено",
  awrSavedList_disconnected: "Відключено",
  awrSavedList_renameAccessibility: "Перейменувати",
  awrSavedList_deleteAccessibility: "Видалити",
  awrSavedList_renameTitle: "Перейменувати AWR",
  awrSavedList_nameLabel: "Назва",
  awrSavedList_deleteTitle: "Видалити збережений AWR",
  awrSavedList_deleteMessage: "Ви впевнені, що хочете видалити цей AWR зі списку?",
  awrSavedList_deleteAction: "Видалити",

  ipConfig_title: "Налаштування IP",
  ipConfig_cardTitle: "Сервер CTIFEED",
  ipConfig_cardDescription: "Введіть IP сервера, на якому буде відкрито портал.",
  ipConfig_inputLabel: "IP (лише IP)",
  ipConfig_saved: "Збережено",
  ipConfig_alertSuccessTitle: "Успішно",
  ipConfig_alertSuccessMessage: "IP правильний",
  ipConfig_alertWarningTitle: "Попередження",
  ipConfig_alertServerNotUpdated: "Сервер не оновлено",
  ipConfig_alertErrorTitle: "Помилка",
  ipConfig_alertInvalidIp: "Неправильний IP",

  portal_preparing: "Підготовка порталу...",
  portal_noSessionToken: "Немає токена сесії. Увійдіть знову.",
  portal_noIpConfigured: "IP-адресу не налаштовано. Спочатку налаштуйте IP-адресу сервера.",
  portal_prepareUrlError: "Не вдалося підготувати URL порталу.",
  portal_loadError: "Не вдалося завантажити портал.",
  portal_checkingConnection: "Перевірка з’єднання з порталом...",
  portal_noConnectionTitle: "Немає з’єднання",
  portal_connectionTimeout: "Не вдалося підключитися до порталу. Перевірте, чи ви підключені до правильної мережі.",
  portal_connectionError: "Не вдалося підключитися до порталу. Перевірте мережу або налаштовану IP-адресу.",
  portal_httpError: "Не вдалося відкрити портал. Помилка HTTP {{status}}.",
  portal_retry: "Спробувати знову",
  portal_loading: "Завантаження порталу...",

  AltaDispositivos: "Реєстрація пристроїв",
  LectorMaternidad: "Зчитувач материнського відділення",
  LectorGestacion: "Зчитувач гестації",
  ConfiguracionIP: "Налаштування IP",
  ConfiguracionAWR: "Налаштування AWR",
  DarDeAltaAWR: "Зареєструвати AWR",
  AWREscaneados: "Скановані AWR",
  CerrarSesion: "Вийти",

  Config_lastReadMismatchTitle: "Зчитана тварина не відповідає пошуку",
  Config_lastReadMismatchCrotal: "Вушна бірка",
  Config_lastReadMismatchId: "ID",
  awrBluetoothPermissionMessage: "Увімкніть Bluetooth і надайте дозвіл, щоб можна було сканувати.",

  animalState: {
  gestation: "Гестація",
    maternity: "Материнство",
    out_of_gestation: "Поза гестацією",
    out_of_maternity: "Поза материнством"
  },

 
Reader_readingTitle: "Зчитування бирок",
Reader_labelId: "ID",
Reader_labelCrotal: "Бирка",
Reader_labelCorral: "Загін",
Reader_labelHouse: "Корпус",
Reader_labelState: "Стан",
Reader_autoReadingBadge: "Автоматичне зчитування",

gestacionConfig_flowSectionTitle: "Налаштування процесу",
gestacionConfig_workModeTitle: "Режим роботи",
gestacionConfig_workModeDescription: "Виберіть, що робитиме зчитувач.",
gestacionConfig_entryDescription: "Зареєструвати вхід",
gestacionConfig_exitDescription: "Зареєструвати вихід",
gestacionConfig_readingDescription: "Лише перегляд",
gestacionConfig_searchDescription: "Пошук тварини",

gestacionConfig_sendSettingsTitle: "Налаштування надсилання",
gestacionConfig_sendSettingsDescription: "Налаштуйте поведінку процесу під час зчитування тварин.",

gestacionConfig_corralSectionTitle: "Загін для входу",
gestacionConfig_corralSectionDescription: "Це поле є обов’язковим для продовження реєстрації.",

gestacionConfig_alerts_notice: "Повідомлення",
gestacionConfig_alerts_invalidCrotalFromBackend: "Сервер не повернув дійсну вушну мітку для порівняння.",

common_accept: "Прийняти",

maternidadConfig_flowSectionTitle: "Налаштування процесу",
maternidadConfig_workModeTitle: "Режим роботи",
maternidadConfig_workModeDescription: "Виберіть, що робитиме зчитувач.",
maternidadConfig_entryDescription: "Зареєструвати вхід",
maternidadConfig_exitDescription: "Зареєструвати вихід",
maternidadConfig_readingDescription: "Лише перегляд",
maternidadConfig_searchDescription: "Пошук тварини",

maternidadConfig_sendSettingsTitle: "Налаштування надсилання",
maternidadConfig_sendSettingsDescription: "Налаштуйте поведінку процесу під час зчитування тварин.",

maternidadConfig_corralSectionTitle: "Загін для входу",
maternidadConfig_corralSectionDescription: "Це поле є обов’язковим для продовження реєстрації.",

maternidadConfig_alert_invalidCrotalFromBackend: "Сервер не повернув дійсну вушну мітку для порівняння.",
  maternidadConfig_readOnlyTitle: "Дозвіл лише на читання",
maternidadConfig_readOnlyModifySettings: "Цей користувач має лише права на читання. Він не може змінювати цю конфігурацію.",
maternidadConfig_readOnlyUseFunction: "Цей користувач має лише права на читання. Він не може використовувати цю функцію.",

 ajustesEnvioMaternidad: {
    headerTitle: "Налаштування надсилання",
    headerSubtitle: "Налаштуйте поведінку процесу під час зчитування тварин.",
    cardTitle: "Надсилання записів",
    cardSubtitle: "Ці налаштування застосовуються під час продовження зчитування."
  },

  noAlimentadosMaternidad: {
  animalId: "ID ТВАРИНИ",
  corral: "Загін",
  consumption: "Споживання",
  withoutFeeding: "Без годування",
  day: "день",
  days: "днів",
  loadingAnimals: "Завантаження тварин...",
  title: "Тварини без годування",
  totalAnimalsMaternity: "Усього тварин у пологовому відділенні:",
  notSeen: "Не переглянуті",
  all: "Усі",
  sort: "Сортувати",
  emptyTitle: "Немає тварин в очікуванні",
  emptyText: "У пологовому відділенні не знайдено тварин без годування.",
  sortBy: "Сортувати за",
  daysWithoutFeeding: "Дні без годування",
  sortDaysHelp: "Сортує за кількістю днів без годування",
  sortCorralHelp: "Сортує за номером загону",
  descending: "За спаданням",
  ascending: "За зростанням",
  filterAnimals: "Фільтрувати тварин",
  allHelp: "Показує всіх тварин",
  unmarked: "Не позначені",
  unmarkedHelp: "Приховує вже перевірених тварин",
  clearMarkedTitle: "Очистити позначених тварин",
  clearMarkedText: "Усі позначки перевірених тварин буде видалено.",
  cancel: "Скасувати",
  clear: "Очистити",
  error: "Помилка",
  serverConnectionError: "Не вдалося підключитися до сервера."
},

noAlimentadosGestacion: {
  animalId: "ID ТВАРИНИ",
  corral: "Загін",
  consumption: "Споживання",
  withoutFeeding: "Без годування",
  day: "день",
  days: "днів",
  loadingAnimals: "Завантаження тварин...",
  title: "Тварини без годування",
  totalAnimalsGestation: "Усього тварин у відділенні поросності:",
  notSeen: "Не переглянуті",
  all: "Усі",
  sort: "Сортувати",
  emptyTitle: "Немає тварин в очікуванні",
  emptyText: "У відділенні поросності не знайдено тварин без годування.",
  sortBy: "Сортувати за",
  daysWithoutFeeding: "Дні без годування",
  sortDaysHelp: "Сортує за кількістю днів без годування",
  sortCorralHelp: "Сортує за номером загону",
  descending: "За спаданням",
  ascending: "За зростанням",
  filterAnimals: "Фільтрувати тварин",
  allHelp: "Показує всіх тварин",
  unmarked: "Не позначені",
  unmarkedHelp: "Приховує вже перевірених тварин",
  clearMarkedTitle: "Очистити позначених тварин",
  clearMarkedText: "Усі позначки перевірених тварин буде видалено.",
  cancel: "Скасувати",
  clear: "Очистити",
  error: "Помилка",
  serverConnectionError: "Не вдалося підключитися до сервера."
},
capturaAnimalHome: {
  selectOption: "Виберіть опцію",
  unfedAnimalsTitle: "Тварини без годування",
  unfedAnimalsDescription: "Переглянути тварин, які не отримали заплановане годування.",
  twoFeedsTitle: "2 корми",
  twoFeedsDescription: "Керування зміною корму у випускних отворах.",
  animalStatusTitle: "Стан тварини",
animalStatusDescription: "Переглянути або оновити стан тварини.",
},
cambioPiensoMaternidad: {
  error: "Помилка",
  loadTasksError: "Не вдалося завантажити завдання зміни корму.",
  loadingTasks: "Завантаження завдань...",
  title: "Зміна корму",
  pendingTask: "{{count}} завдання в очікуванні",
  pendingTasks: "{{count}} завдань в очікуванні",
  emptyTitle: "Немає завдань в очікуванні",
  emptyText: "Завдань зміни корму не знайдено.",
  animalId: "ID ТВАРИНИ",
  corral: "Загін",
  setTo: "Встановити на",
  destination: "Призначення"
},
estadoAnimal: {
  queryLabel: "Запит",
  title: "Стан тварини",
  subtitle: "Виберіть, як ви хочете ідентифікувати тварину.",
  corral: "Загін",
  corralDescription: "Введіть номер загону.",
  id: "ID",
  idDescription: "Введіть ідентифікатор тварини.",
  animalId: "ID тварини",
  requiredData: "Обов'язкові дані",
  enterCorral: "Введіть номер загону.",
  enterId: "Введіть ідентифікатор тварини.",
  consulting: "Перевірка...",
  continue: "Продовжити",
  accept: "Прийняти",
  serverConnectionError: "Не вдалося підключитися до сервера.",
  noIpConfigured: "IP-адресу не налаштовано.",
  nextScreenPending: "Екран інформації про тварину створимо на наступному кроці."
},

matCorralDetail: {
  animalStatus: "Стан тварини",
  id: "ID",
  earTag: "Бирка",
  cycle: "Цикл",
  day: "День",
  curve: "Крива",
  correction: "Корекція",
  entryDate: "Дата входу",
  farrowingDate: "Дата опоросу",
  house: "Корпус",
  pen: "Загін",
  lastFeeding: "Останнє годування",
  presentPiglets: "Наявні поросята",
  inseminationDate: "Дата осіменіння",
  teatsNumber: "Кількість сосків",
  operations: "Операції",
  consumption: "Споживання",
  ofGrams: "з {{amount}} гр",
  oneDayWithoutFeeding: "1 день без годування",
  daysWithoutFeeding: "{{count}} днів без годування",
  noAnimalData: "Немає даних про тварину",
  noAnimalDataText: "Інформацію для відображення не отримано.",
  back: "Назад",
  operationsPendingTitle: "Операції",
  operationsPendingText: "Операції додамо на наступному кроці.",
  moveToWeaning: "Перевести на відлучення",

}
};