export default {
    username: 'Utilisateur',
    password: 'Mot de passe',
    login: 'Connexion',
    welcome: 'Bienvenue',
    change_language: 'Changer de langue',
    Tabs: 'Accueil',

    Lista_instalaciones: 'Installations',
    Maintenance: 'Maintenance',
    DetallesInstalacion: 'Détails installation',
    Grabar: 'Enregistrer',
    EstadoStore: 'État store',
    Nodata: 'Pas de données',
    DosimacRegistration: 'Inscription',
    NewDmMaternity: 'Nouveau Dosimac maternité',
    DosimacG: 'Dosimac-G',
    DosimacI: 'Dosimac-I',
    UpdDmMaternity: 'Changement Dosimac maternité',
    NewDmGestation: 'Nouveau Dosimac gestation',
    UpdDmGestation: 'Changement Dosimac gestation',
    StartScan: 'Chercher appareils DOSIMAC',
    DosimacList: 'Appareils DOSIMAC',
    PressToScan: 'Appuyez',
    DosimacSetup: 'Configuration',
    TestoPresioneAlta: 'Appuyez sur le bouton pour rechercher des appareils',
    Instalación_seleccionada: 'Installation sélectionnée',
    NoInstalacionSeleccionada: 'Aucune installation sélectionnée',
    BorrarGranja: 'Supprimer la ferme',
    Deseaborrarlagranja: 'Voulez-vous supprimer la ferme ?',
    Guardar: 'Enregistrer',
    Cancelar: 'Annuler',
    Aceptar: 'Accepter',
    NombreGranja: 'Nom de la ferme',
    Localidad: 'Localité',
    Provincia: 'Province',
    NombreWifi: 'Wifi SSID',
    PasswordWifi: 'Mot de passe Wifi',
    No_hay_dispositivos: 'Aucun appareil',
    Aviso: 'Avis',
    SearchingDevices: 'Recherche des appareils...',
    NoSePuedeBorrarGranja: 'Impossible de supprimer une nouvelle ferme',
    settings: 'Paramètres',
    softwareVersion: 'Version du logiciel',
    numeroCoral: "Numéro d’enclos",
    numeroMaquina: 'Numéro de machine',
    Enviar: 'Envoyer',
    Salir: 'Quitter',
    Informacion: 'Information',

    InicioConfiguracion: "Démarrage de la connexion",
    ConfiguracionWifi: "Configuration...",
    ConfiguracionRealizada: "*Configuration réalisée*",
    ErrorConfiguracion: "*Erreur de configuration*",
    CapturaTagCorral: "Capturer l’étiquette de l’enclos",
    CorralTag: "Étiquette de l’enclos",
    versionUint16: "Cette version de l’appareil ne prend en charge que des enclos jusqu’à 65000",
    versionUint32: "Cette version de l’appareil prend en charge des enclos jusqu’à 4000000000",
    EnvioConfiguracion: "Envoi de la configuration",
    NumeroCorral: "Numéro d’enclos",
    NumeroMaquina: "Numéro de machine",
    Corralnovalida: "Enclos non valide",
    NumeroMaquinanovalida: "Numéro de machine non valide",
    configuarIntalacion: "Vous devez configurer l’installation avant d’utiliser cette fonction",

    login_title: "Se connecter",
    login_subtitle: "Saisissez vos données. Il est nécessaire de configurer l'IP avant de vous connecter depuis le menu Configuration IP.",
    login_username: "Utilisateur",
    login_password: "Mot de passe",
    login_button: "Se connecter",
    login_loading: "Connexion...",
    login_footer: "Panneau de contrôle",
    login_invalidCredentials: "Nom d'utilisateur ou mot de passe incorrect",

    login_ipRequiredTitle: "Configuration IP requise",
    login_ipRequiredMessage: "Vous n'avez pas configuré l'adresse IP du serveur. Saisissez-la pour pouvoir vous connecter.",
    login_serverIpLabel: "IP du serveur",
    login_cancel: "Annuler",
    login_accept: "Accepter",

    login_configTitle: "Configuration",
    login_errorTitle: "Erreur de connexion",
    login_genericErrorTitle: "Erreur",
    login_networkErrorTitle: "Erreur réseau",
    login_networkErrorMessage: "Impossible de se connecter au serveur.",
    login_noTokenMessage: "Le backend n'a renvoyé aucun jeton.",
    login_missingDataTitle: "Données manquantes",
    login_missingDataMessage: "Saisissez le nom d'utilisateur et le mot de passe.",
    login_invalidIpTitle: "IP invalide",
    login_invalidIpMessage: "Saisissez une IP ou une adresse serveur valide.",
    login_saveIpErrorMessage: "Impossible d'enregistrer la configuration IP.",
    gestacionConfig_screenTitle: "Configuration Gestation",
    gestacionConfig_chooseOptionTitle: "Choisissez une option",
    gestacionConfig_chooseOptionDescription: "Définissez le flux avant de commencer avec le lecteur.",

    gestacionConfig_entry: "Entrée",
    gestacionConfig_exit: "Sortie",
    gestacionConfig_reading: "Lecture",
    gestacionConfig_search: "Recherche",

    gestacionConfig_entryParamsTitle: "Paramètres d'entrée",
    gestacionConfig_exitParamsTitle: "Paramètres de sortie",
    gestacionConfig_entryParamsDescription: "Sélectionnez le corral et le comportement du flux.",
    gestacionConfig_exitParamsDescription: "Configurez le comportement du flux de sortie.",

    gestacionConfig_corralLabel: "Corral",
    gestacionConfig_corralPlaceholder: "Ex : 1",
    gestacionConfig_corralRequired: "Saisissez le corral pour continuer.",

    gestacionConfig_detectUnknownTitle: "Identifier les animaux inconnus",
    gestacionConfig_detectUnknownDescription: "Lorsque vous lirez un animal non identifié, vous pourrez lui attribuer un ID",

    gestacionConfig_confirmTitle: "Confirmer l'envoi",
    gestacionConfig_confirmDescription: "Une confirmation sera demandée avant l'envoi des enregistrements.",

    gestacionConfig_animalSearchTitle: "Recherche d'animal",
    gestacionConfig_animalSearchDescription: "Choisissez si vous souhaitez rechercher par crotal ou par ID.",
    gestacionConfig_searchByCrotal: "Par crotal",
    gestacionConfig_searchById: "Par ID",
    gestacionConfig_manual: "Manuel",
    gestacionConfig_withSword: "Avec épée",

    gestacionConfig_crotalLabelSearch: "Crotal",
    gestacionConfig_idLabelSearch: "ID",
    gestacionConfig_crotalPlaceholderSearch: "Ex : 982091072397436",
    gestacionConfig_idPlaceholderSearch: "Ex : A13",
    gestacionConfig_crotalRequiredSearch: "Saisissez un crotal pour continuer.",
    gestacionConfig_idRequiredSearch: "Saisissez un ID pour continuer.",

    gestacionConfig_searchWithSwordHelp: "En continuant, l'épée sera lue sur cet écran et l'animal sera recherché avec ce crotal.",

    gestacionConfig_readingSword: "Lecture de l'épée...",
    gestacionConfig_waitingMatch: "En attente de correspondance",
    gestacionConfig_searchingAnimal: "Recherche de l'animal...",

    gestacionConfig_readingSwordDescription: "Approchez le crotal du lecteur pour identifier l'animal.",
    gestacionConfig_waitingMatchDescription: "Animal localisé. Approchez maintenant à l'épée le crotal {{crotal}} pour confirmer la correspondance.",
    gestacionConfig_searchingAnimalDescription: "Consultation des informations de l'animal dans le backend.",

    gestacionConfig_awrDisconnectedTitle: "AWR non connecté",
    gestacionConfig_awrSavedDescription: "Vous avez des épées enregistrées. Appuyez pour en sélectionner une.",
    gestacionConfig_awrNotSavedDescription: "Vous n'avez aucune épée enregistrée. Appuyez pour en scanner une.",

    gestacionConfig_scan: "Scanner",
    gestacionConfig_continue: "Continuer",

    gestacionConfig_alerts_error: "Erreur",
    gestacionConfig_alerts_networkError: "Erreur réseau",
    gestacionConfig_alerts_networkErrorMessage: "Impossible de se connecter au serveur.",
    gestacionConfig_alerts_backendNoValidCrotal: "Le backend n'a pas renvoyé un crotal valide pour la comparaison.",
    gestacionConfig_alerts_awrNotConnected: "AWR non connecté",
    gestacionConfig_alerts_connectSwordBeforeContinue: "Connectez une épée avant de continuer.",
    gestacionConfig_alerts_couldNotStartReading: "Impossible de démarrer la lecture avec l'épée.",

    gestacionConfig_alerts_missingData: "Donnée manquante",
    gestacionConfig_alerts_writeCrotalToSearch: "Saisissez un crotal pour rechercher.",
    gestacionConfig_alerts_writeIdToSearch: "Saisissez un ID pour rechercher.",

    gestacionConfig_alerts_notFound: "Introuvable",
    gestacionConfig_alerts_animalNotFoundByCrotal: "Aucun animal n'existe avec ce crotal.",
    gestacionConfig_alerts_animalNotFoundById: "Aucun animal n'existe avec cet ID.",

    gestacionConfig_alerts_warning: "Avertissement",
    gestacionConfig_alerts_searchError: "Erreur de recherche",


    maternidadConfig_screenTitle: "Configuration Maternité",
    maternidadConfig_chooseOptionTitle: "Choisissez une option",
    maternidadConfig_chooseOptionDescription: "Définissez le flux avant de commencer avec le lecteur.",
    maternidadConfig_entry: "Entrée",
    maternidadConfig_exit: "Sortie",
    maternidadConfig_reading: "Lecture",
    maternidadConfig_search: "Recherche",
    maternidadConfig_entryParamsTitle: "Paramètres d'entrée",
    maternidadConfig_exitParamsTitle: "Paramètres de sortie",
    maternidadConfig_entryParamsDescription: "Sélectionnez le corral et le comportement du flux.",
    maternidadConfig_exitParamsDescription: "Configurez le comportement du flux de sortie.",
    maternidadConfig_corralLabel: "Corral",
    maternidadConfig_corralPlaceholder: "Ex : 1",
    maternidadConfig_corralRequired: "Saisissez le corral pour continuer.",
    maternidadConfig_detectUnknownTitle: "Identifier les animaux inconnus",
    maternidadConfig_detectUnknownDescription: "Lorsque vous lirez un animal non identifié, vous pourrez lui attribuer un ID",
    maternidadConfig_confirmTitle: "Confirmer l'envoi",
    maternidadConfig_confirmDescription: "Une confirmation sera demandée avant l'envoi de chaque enregistrement.",
    maternidadConfig_animalSearchTitle: "Recherche d'animal",
    maternidadConfig_animalSearchDescription: "Choisissez si vous voulez rechercher par crotal ou par ID.",
    maternidadConfig_searchByCrotal: "Par crotal",
    maternidadConfig_searchById: "Par ID",
    maternidadConfig_manual: "Manuel",
    maternidadConfig_withSword: "Avec baguette",
    maternidadConfig_crotalLabelSearch: "Crotal",
    maternidadConfig_idLabelSearch: "ID",
    maternidadConfig_crotalPlaceholderSearch: "Ex : 982091072397436",
    maternidadConfig_idPlaceholderSearch: "Ex : A13",
    maternidadConfig_crotalRequiredSearch: "Saisissez un crotal pour continuer.",
    maternidadConfig_idRequiredSearch: "Saisissez un ID pour continuer.",
    maternidadConfig_searchWithSwordHelp: "En appuyant sur Scanner, la baguette sera lue sur cet écran et l'animal sera recherché avec ce crotal.",
    maternidadConfig_readingSword: "Lecture de la baguette...",
    maternidadConfig_waitingMatch: "En attente de correspondance",
    maternidadConfig_searchingAnimal: "Recherche de l'animal...",
    maternidadConfig_readingSwordDescription: "Approchez le crotal du lecteur pour identifier l'animal.",
    maternidadConfig_waitingMatchDescription: "Animal localisé. Approchez maintenant le crotal {{crotal}} de la baguette pour confirmer la correspondance.",
    maternidadConfig_searchingAnimalDescription: "Consultation des informations de l'animal dans le backend.",
    maternidadConfig_awrDisconnectedTitle: "AWR non connecté",
    maternidadConfig_awrSavedDescription: "Vous avez des AWR enregistrés. Appuyez pour en sélectionner un.",
    maternidadConfig_awrNotSavedDescription: "Vous n'avez aucun AWR enregistré. Appuyez pour en scanner un.",
    maternidadConfig_scan: "Scanner",
    maternidadConfig_continue: "Continuer",
    maternidadConfig_alert_error: "Erreur",
    maternidadConfig_alert_invalidBackendCrotal: "Le backend n'a pas renvoyé un crotal valide pour la comparaison.",
    maternidadConfig_alert_awrNotConnected: "AWR non connecté",
    maternidadConfig_alert_connectSwordBeforeContinue: "Connectez une baguette avant de continuer.",
    maternidadConfig_alert_couldNotStartReading: "Impossible de démarrer la lecture avec la baguette.",
    maternidadConfig_alert_missingData: "Donnée manquante",
    maternidadConfig_alert_writeCrotalToSearch: "Saisissez un crotal pour rechercher.",
    maternidadConfig_alert_writeIdToSearch: "Saisissez un ID pour rechercher.",
    maternidadConfig_alert_notFound: "Introuvable",
    maternidadConfig_alert_noAnimalWithCrotal: "Aucun animal n'existe avec ce crotal.",
    maternidadConfig_alert_noAnimalWithId: "Aucun animal n'existe avec cet ID.",
    maternidadConfig_alert_warning: "Avis",
    maternidadConfig_alert_searchError: "Erreur de recherche",
    maternidadConfig_alert_networkError: "Erreur réseau",
    maternidadConfig_alert_networkErrorMessage: "Impossible de se connecter au serveur.",

    gestationReader_screenTitle: "Lecteur Gestation",
    gestationReader_animalInfoTitle: "Informations de l'animal",
    gestationReader_animalInfoDescription: "Données trouvées dans la recherche.",
    gestationReader_animalCardTitle: "Fiche Animal",
    gestationReader_animalIdLabel: "ID",
    gestationReader_animalCrotalLabel: "Crotal",
    gestationReader_fieldCorral: "Enclos",
    gestationReader_fieldHouse: "Bâtiment",
    gestationReader_fieldState: "État",
    gestationReader_fieldBodyCondition: "Condition corporelle",
    gestationReader_fieldCycle: "Cycle",
    gestationReader_fieldSystemEntryDate: "Entrée dans le système",
    gestationReader_newSearch: "Nouvelle recherche",
    gestationReader_summaryTitle: "Résumé",
    gestationReader_summaryDescription: "Paramètres choisis dans Configuration",
    gestationReader_mode: "Mode",
    gestationReader_corral: "Enclos",
    gestationReader_modeEntry: "Entrée",
    gestationReader_modeExit: "Sortie",
    gestationReader_modeReading: "Lecture",
    gestationReader_modeSearch: "Recherche",
    gestationReader_detectUnknownTitle: "Identifier les animaux inconnus",
    gestationReader_detectUnknownDescription: "Quand un animal sans ID apparaît, proposer de lui attribuer un ID.",
    gestationReader_confirmSendTitle: "Confirmer l'envoi",
    gestationReader_confirmSendDescription: "Demandera une confirmation avant d'envoyer chaque enregistrement.",
    gestationReader_changeSettings: "Changer la configuration",
    gestationReader_currentReadingTitle: "Lecture actuelle",
    gestationReader_currentReadingDescription: "Le crotal détecté et l'ID associé apparaîtront ici.",
    gestationReader_awrDisconnected: "AWR non connecté",
    gestationReader_readCrotal: "Crotal lu",
    gestationReader_readId: "ID",
    gestationReader_animalWithoutAssignedId: "Animal sans ID attribué",
    gestationReader_unknownAnimal: "Animal inconnu",
    gestationReader_animalWithoutIdTitle: "Animal sans ID",
    gestationReader_animalWithoutIdDescription: "Saisissez un ID manuel pour mettre à jour le crotal lu.",
    gestationReader_newIdLabel: "Nouvel ID",
    gestationReader_newIdPlaceholder: "Ex : A13",
    gestationReader_updateId: "Mettre à jour l'ID",
    gestationReader_updatingId: "Mise à jour...",
    gestationReader_sentRecordsTitle: "Enregistrements envoyés",
    gestationReader_noRecords: "Aucun enregistrement.",
    gestationReader_tableHeaderCorral: "Enclos",
    gestationReader_tableHeaderId: "ID",
    gestationReader_tableHeaderCrotal: "Crotal",
    gestationReader_buttonAutoReading: "Lecture automatique active",
    gestationReader_buttonAutoSending: "Envoi automatique actif",
    gestationReader_buttonSending: "Envoi...",
    gestationReader_buttonSend: "Envoyer",
    gestationReader_alertError: "Erreur",
    gestationReader_alertWarning: "Avis",
    gestationReader_alertNetworkError: "Erreur réseau",
    gestationReader_alertMissingCrotalTitle: "Crotal manquant",
    gestationReader_alertMissingCrotalMessage: "Approchez le crotal du lecteur avant d'envoyer.",
    gestationReader_alertInvalidCrotalTitle: "Crotal invalide",
    gestationReader_alertInvalidCrotalMessage: "Le crotal doit être numérique.",
    gestationReader_alertReadErrorTitle: "Erreur de lecture",
    gestationReader_alertNetworkErrorMessage: "Impossible de se connecter au serveur.",
    gestationReader_alertMissingCorralTitle: "Enclos manquant",
    gestationReader_alertMissingCorralMessage: "Saisissez l'enclos avant d'envoyer.",
    gestationReader_alertInvalidCorralTitle: "Enclos invalide",
    gestationReader_alertInvalidCorralMessage: "L'enclos doit être un nombre.",
    gestationReader_alertSendErrorTitle: "Erreur lors de l'envoi",
    gestationReader_alertNoIpConfigured: "Aucune IP configurée.",
    gestationReader_alertMissingIdTitle: "ID manquant",
    gestationReader_alertMissingIdMessage: "Saisissez le nouvel ID avant la mise à jour.",
    gestationReader_alertMissingAssociatedCrotalTitle: "Crotal manquant",
    gestationReader_alertMissingAssociatedCrotalMessage: "Aucun crotal associé à mettre à jour.",
    gestationReader_alertInvalidAssociatedCrotalTitle: "Crotal invalide",
    gestationReader_alertInvalidAssociatedCrotalMessage: "Le crotal associé n'est pas valide.",
    gestationReader_alertUpdateIdErrorTitle: "Erreur lors de la mise à jour de l'ID",

    maternityReader_screenTitle: "Lecteur Maternité",
    maternityReader_alertMissingCrotalTitle: "Boucle manquante",
    maternityReader_alertMissingCrotalMessage: "Approchez la boucle du lecteur avant d'envoyer.",
    maternityReader_alertInvalidCrotalTitle: "Boucle invalide",
    maternityReader_alertInvalidCrotalMessage: "La boucle doit être numérique.",
    maternityReader_alertReadErrorTitle: "Erreur de lecture",
    maternityReader_alertNetworkError: "Erreur réseau",
    maternityReader_alertNetworkErrorMessage: "Impossible de se connecter au serveur.",
    maternityReader_alertMissingCorralTitle: "Enclos manquant",
    maternityReader_alertMissingCorralMessage: "Saisissez l'enclos avant d'envoyer.",
    maternityReader_alertInvalidCorralTitle: "Enclos invalide",
    maternityReader_alertInvalidCorralMessage: "L'enclos doit être un nombre (ex. : 8).",
    maternityReader_alertError: "Erreur",
    maternityReader_alertNoIpConfigured: "Aucune IP configurée.",
    maternityReader_alertWarning: "Avertissement",
    maternityReader_alertSendErrorTitle: "Erreur d'envoi",
    maternityReader_alertMissingIdTitle: "ID manquant",
    maternityReader_alertMissingIdMessage: "Saisissez le nouvel ID avant la mise à jour.",
    maternityReader_alertMissingAssociatedCrotalTitle: "Boucle manquante",
    maternityReader_alertMissingAssociatedCrotalMessage: "Aucune boucle associée à mettre à jour.",
    maternityReader_alertInvalidAssociatedCrotalTitle: "Boucle invalide",
    maternityReader_alertInvalidAssociatedCrotalMessage: "La boucle associée n'est pas valide.",
    maternityReader_alertUpdateIdErrorTitle: "Erreur lors de la mise à jour de l'ID",
    maternityReader_animalInfoTitle: "Informations sur l'animal",
    maternityReader_animalInfoDescription: "Données trouvées dans la recherche.",
    maternityReader_animalCardTitle: "Fiche Animal",
    maternityReader_animalIdLabel: "ID",
    maternityReader_animalCrotalLabel: "Boucle",
    maternityReader_fieldCorral: "Enclos",
    maternityReader_fieldHouse: "Bâtiment",
    maternityReader_fieldState: "État",
    maternityReader_fieldBodyCondition: "État corporel",
    maternityReader_fieldCycle: "Cycle",
    maternityReader_fieldSystemEntryDate: "Entrée dans le système",
    maternityReader_newSearch: "Nouvelle recherche",
    maternityReader_summaryTitle: "Résumé",
    maternityReader_summaryDescription: "Paramètres sélectionnés dans la configuration",
    maternityReader_mode: "Mode",
    maternityReader_modeEntry: "Entrée",
    maternityReader_modeExit: "Sortie",
    maternityReader_modeReading: "Lecture",
    maternityReader_corral: "Enclos",
    maternityReader_detectUnknownTitle: "Identifier les animaux inconnus",
    maternityReader_detectUnknownDescription: "Quand un animal sans ID apparaît, proposer de lui en attribuer un.",
    maternityReader_confirmSendTitle: "Confirmer l'envoi",
    maternityReader_confirmSendDescription: "Demandera une confirmation avant d'envoyer chaque enregistrement.",
    maternityReader_changeSettings: "Modifier la configuration",
    maternityReader_currentReadingTitle: "Lecture actuelle",
    maternityReader_currentReadingDescription: "La boucle détectée apparaîtra ici.",
    maternityReader_awrDisconnected: "AWR non connecté",
    maternityReader_readCrotal: "Boucle lue",
    maternityReader_readId: "ID",
    maternityReader_animalWithoutAssignedId: "Animal sans ID attribué",
    maternityReader_unknownAnimal: "Animal inconnu",
    maternityReader_animalWithoutIdTitle: "Animal sans ID",
    maternityReader_animalWithoutIdDescription: "Saisissez un ID manuel pour mettre à jour la boucle lue.",
    maternityReader_newIdLabel: "Nouvel ID",
    maternityReader_newIdPlaceholder: "Ex. : A13",
    maternityReader_updatingId: "Mise à jour...",
    maternityReader_updateId: "Mettre à jour l'ID",
    maternityReader_sentRecordsTitle: "Enregistrements envoyés",
    maternityReader_tableHeaderCorral: "Enclos",
    maternityReader_tableHeaderId: "ID",
    maternityReader_tableHeaderCrotal: "Boucle",
    maternityReader_noRecords: "Aucun enregistrement.",
    maternityReader_buttonAutoReading: "Lecture automatique active",
    maternityReader_buttonAutoSending: "Envoi automatique actif",
    maternityReader_buttonSending: "Envoi en cours...",
    maternityReader_buttonSend: "Envoyer",

    awrScanResults_title: "AWR – Résultats du scan",
    awrScanResults_searching: "Recherche de l’AWR…",
    awrScanResults_warningTitle: "Avertissement",
    awrScanResults_noDevicesNearby: "Aucun AWR à proximité n’a été trouvé.",
    awrScanResults_connecting: "Connexion…",
    awrScanResults_connectErrorFallback: "Impossible de se connecter",
    awrScanResults_connectedTitle: "Connecté",
    awrScanResults_connectedMessage: "Connexion établie avec {{device}}.",
    awrScanResults_genericDevice: "l’appareil",

    awrSavedList_title: "AWR scannés",
    awrSavedList_connecting: "Connexion…",
    awrSavedList_empty: "Aucun AWR enregistré. Scannez-en un depuis « Configuration AWR ».",
    awrSavedList_connected: "Connecté",
    awrSavedList_disconnected: "Déconnecté",
    awrSavedList_renameAccessibility: "Renommer",
    awrSavedList_deleteAccessibility: "Supprimer",
    awrSavedList_renameTitle: "Renommer l’AWR",
    awrSavedList_nameLabel: "Nom",
    awrSavedList_deleteTitle: "Supprimer l’AWR enregistré",
    awrSavedList_deleteMessage: "Voulez-vous vraiment supprimer cet AWR de la liste ?",
    awrSavedList_deleteAction: "Supprimer",

    ipConfig_title: "Configuration IP",
    ipConfig_cardTitle: "Serveur CTIFEED",
    ipConfig_cardDescription: "Saisissez l'IP du serveur où le portail sera ouvert.",
    ipConfig_inputLabel: "IP (IP uniquement)",
    ipConfig_saved: "Enregistré",
    ipConfig_alertSuccessTitle: "Correct",
    ipConfig_alertSuccessMessage: "IP correcte",
    ipConfig_alertWarningTitle: "Avertissement",
    ipConfig_alertServerNotUpdated: "Serveur non mis à jour",
    ipConfig_alertErrorTitle: "Erreur",
    ipConfig_alertInvalidIp: "IP invalide",

    portal_preparing: "Préparation du portail...",
    portal_noSessionToken: "Aucun jeton de session n’est disponible. Veuillez vous reconnecter.",
    portal_noIpConfigured: "Aucune IP n’est configurée. Configurez d’abord l’IP du serveur.",
    portal_prepareUrlError: "Impossible de préparer l’URL du portail.",
    portal_loadError: "Impossible de charger le portail.",
    portal_checkingConnection: "Vérification de la connexion au portail...",
    portal_noConnectionTitle: "Pas de connexion",
    portal_connectionTimeout: "Impossible de se connecter au portail. Vérifiez que vous êtes connecté au bon réseau.",
    portal_connectionError: "Impossible de se connecter au portail. Vérifiez le réseau ou l’IP configurée.",
    portal_httpError: "Impossible d’ouvrir le portail. Erreur HTTP {{status}}.",
    portal_retry: "Réessayer",
    portal_loading: "Chargement du portail...",

    AltaDispositivos: "Enregistrement des appareils",
    LectorMaternidad: "Lecteur Maternité",
    LectorGestacion: "Lecteur Gestation",
    ConfiguracionIP: "Configuration IP",
    ConfiguracionAWR: "Configuration AWR",
    DarDeAltaAWR: "Enregistrer AWR",
    AWREscaneados: "AWR scannés",
    CerrarSesion: "Se déconnecter",

    Config_lastReadMismatchTitle: "L'animal lu ne correspond pas à la recherche",
    Config_lastReadMismatchCrotal: "Boucle",
    Config_lastReadMismatchId: "ID",
    awrBluetoothPermissionMessage: "Active le Bluetooth et acceptez l’autorisation pour pouvoir scanner.",

    animalState: {
    gestation: "Gestation",
    maternity: "Maternité",
    out_of_gestation: "Hors gestation",
    out_of_maternity: "Hors maternité"
  },


Reader_readingTitle: "Lecture des boucles",
Reader_labelId: "ID",
Reader_labelCrotal: "Boucle",
Reader_labelCorral: "Enclos",
Reader_labelHouse: "Bâtiment",
Reader_labelState: "État",
Reader_autoReadingBadge: "Lecture automatique",

};