export default {
    username: 'Utilisateur',
    password: 'Mot de passe',
    login: 'Connexion',
    welcome: 'Bienvenue',
    change_language: 'Changer de langue',
    Tabs: 'Accueil',

    Lista_instalaciones: 'Installations',
    Maintenance: 'Maintenance',
    DetallesInstalacion: 'Détails installation',
    Grabar: 'Enregistrer',
    EstadoStore: 'État store',
    Nodata: 'Pas de données',
    DosimacRegistration: 'Inscription',
    NewDmMaternity: 'Nouveau Dosimac maternité',
    DosimacG: 'Dosimac-G',
    DosimacI: 'Dosimac-I',
    UpdDmMaternity: 'Changement Dosimac maternité',
    NewDmGestation: 'Nouveau Dosimac gestation',
    UpdDmGestation: 'Changement Dosimac gestation',
    StartScan: 'Chercher appareils DOSIMAC',
    DosimacList: 'Appareils DOSIMAC',
    PressToScan: 'Appuyez',
    DosimacSetup: 'Configuration',
    TestoPresioneAlta: 'Appuyez sur le bouton pour rechercher des appareils',
    Instalación_seleccionada: 'Installation sélectionnée',
    NoInstalacionSeleccionada: 'Aucune installation sélectionnée',
    BorrarGranja: 'Supprimer la ferme',
    Deseaborrarlagranja: 'Voulez-vous supprimer la ferme ?',
    Guardar: 'Enregistrer',
    Cancelar: 'Annuler',
    Aceptar: 'Accepter',
    NombreGranja: 'Nom de la ferme',
    Localidad: 'Localité',
    Provincia: 'Province',
    NombreWifi: 'Wifi SSID',
    PasswordWifi: 'Mot de passe Wifi',
    No_hay_dispositivos: 'Aucun appareil',
    Aviso: 'Avis',
    SearchingDevices: 'Recherche des appareils...',
    NoSePuedeBorrarGranja: 'Impossible de supprimer une nouvelle ferme',
    settings: 'Paramètres',
    softwareVersion: 'Version du logiciel',
    numeroCoral: "Numéro d’enclos",
    numeroMaquina: 'Numéro de machine',
    Enviar: 'Envoyer',
    Salir: 'Quitter',
    Informacion: 'Information',

    InicioConfiguracion: "Démarrage de la connexion",
    ConfiguracionWifi: "Configuration...",
    ConfiguracionRealizada: "*Configuration réalisée*",
    ErrorConfiguracion: "*Erreur de configuration*",
    CapturaTagCorral: "Capturer l’étiquette de l’enclos",
    CorralTag: "Étiquette de l’enclos",
    versionUint16: "Cette version de l’appareil ne prend en charge que des enclos jusqu’à 65000",
    versionUint32: "Cette version de l’appareil prend en charge des enclos jusqu’à 4000000000",
    EnvioConfiguracion: "Envoi de la configuration",
    NumeroCorral: "Numéro d’enclos",
    NumeroMaquina: "Numéro de machine",
    Corralnovalida: "Enclos non valide",
    NumeroMaquinanovalida: "Numéro de machine non valide",
    configuarIntalacion: "Vous devez configurer l’installation avant d’utiliser cette fonction",

    login_title: "Se connecter",
    login_subtitle: "Saisissez vos données. Il est nécessaire de configurer l'IP avant de vous connecter depuis le menu Configuration IP.",
    login_username: "Utilisateur",
    login_password: "Mot de passe",
    login_button: "Se connecter",
    login_loading: "Connexion...",
    login_footer: "Panneau de contrôle",
    login_invalidCredentials: "Nom d'utilisateur ou mot de passe incorrect",

    login_ipRequiredTitle: "Configuration IP requise",
    login_ipRequiredMessage: "Vous n'avez pas configuré l'adresse IP du serveur. Saisissez-la pour pouvoir vous connecter.",
    login_serverIpLabel: "IP du serveur",
    login_cancel: "Annuler",
    login_accept: "Accepter",

    login_configTitle: "Configuration",
    login_errorTitle: "Erreur de connexion",
    login_genericErrorTitle: "Erreur",
    login_networkErrorTitle: "Erreur réseau",
    login_networkErrorMessage: "Impossible de se connecter au serveur.",
    login_noTokenMessage: "Le backend n'a renvoyé aucun jeton.",
    login_missingDataTitle: "Données manquantes",
    login_missingDataMessage: "Saisissez le nom d'utilisateur et le mot de passe.",
    login_invalidIpTitle: "IP invalide",
    login_invalidIpMessage: "Saisissez une IP ou une adresse serveur valide.",
    login_saveIpErrorMessage: "Impossible d'enregistrer la configuration IP.",
    gestacionConfig_screenTitle: "Configuration Gestation",
    gestacionConfig_chooseOptionTitle: "Choisissez une option",
    gestacionConfig_chooseOptionDescription: "Définissez le flux avant de commencer avec le lecteur.",

    gestacionConfig_entry: "Entrée",
    gestacionConfig_exit: "Sortie",
    gestacionConfig_reading: "Lecture",
    gestacionConfig_search: "Recherche",

    gestacionConfig_entryParamsTitle: "Paramètres d'entrée",
    gestacionConfig_exitParamsTitle: "Paramètres de sortie",
    gestacionConfig_entryParamsDescription: "Sélectionnez le corral et le comportement du flux.",
    gestacionConfig_exitParamsDescription: "Configurez le comportement du flux de sortie.",

    gestacionConfig_corralLabel: "Corral",
    gestacionConfig_corralPlaceholder: "Ex : 1",
    gestacionConfig_corralRequired: "Saisissez le corral pour continuer.",

    gestacionConfig_detectUnknownTitle: "Identifier les animaux inconnus",
    gestacionConfig_detectUnknownDescription: "Lorsque vous lirez un animal non identifié, vous pourrez lui attribuer un ID",

    gestacionConfig_confirmTitle: "Confirmer l'envoi",
    gestacionConfig_confirmDescription: "Une confirmation sera demandée avant l'envoi des enregistrements.",

    gestacionConfig_animalSearchTitle: "Recherche d'animal",
    gestacionConfig_animalSearchDescription: "Choisissez si vous souhaitez rechercher par crotal ou par ID.",
    gestacionConfig_searchByCrotal: "Par crotal",
    gestacionConfig_searchById: "Par ID",
    gestacionConfig_manual: "Manuel",
    gestacionConfig_withSword: "Avec épée",

    gestacionConfig_crotalLabelSearch: "Crotal",
    gestacionConfig_idLabelSearch: "ID",
    gestacionConfig_crotalPlaceholderSearch: "Ex : 982091072397436",
    gestacionConfig_idPlaceholderSearch: "Ex : A13",
    gestacionConfig_crotalRequiredSearch: "Saisissez un crotal pour continuer.",
    gestacionConfig_idRequiredSearch: "Saisissez un ID pour continuer.",

    gestacionConfig_searchWithSwordHelp: "En continuant, l'épée sera lue sur cet écran et l'animal sera recherché avec ce crotal.",

    gestacionConfig_readingSword: "Lecture de l'épée...",
    gestacionConfig_waitingMatch: "En attente de correspondance",
    gestacionConfig_searchingAnimal: "Recherche de l'animal...",

    gestacionConfig_readingSwordDescription: "Approchez le crotal du lecteur pour identifier l'animal.",
    gestacionConfig_waitingMatchDescription: "Animal localisé. Approchez maintenant à l'épée le crotal {{crotal}} pour confirmer la correspondance.",
    gestacionConfig_searchingAnimalDescription: "Consultation des informations de l'animal dans le backend.",

    gestacionConfig_awrDisconnectedTitle: "AWR non connecté",
    gestacionConfig_awrSavedDescription: "Vous avez des épées enregistrées. Appuyez pour en sélectionner une.",
    gestacionConfig_awrNotSavedDescription: "Vous n'avez aucune épée enregistrée. Appuyez pour en scanner une.",

    gestacionConfig_scan: "Scanner",
    gestacionConfig_continue: "Continuer",

    gestacionConfig_alerts_error: "Erreur",
    gestacionConfig_alerts_networkError: "Erreur réseau",
    gestacionConfig_alerts_networkErrorMessage: "Impossible de se connecter au serveur.",
    gestacionConfig_alerts_backendNoValidCrotal: "Le backend n'a pas renvoyé un crotal valide pour la comparaison.",
    gestacionConfig_alerts_awrNotConnected: "AWR non connecté",
    gestacionConfig_alerts_connectSwordBeforeContinue: "Connectez une épée avant de continuer.",
    gestacionConfig_alerts_couldNotStartReading: "Impossible de démarrer la lecture avec l'épée.",

    gestacionConfig_alerts_missingData: "Donnée manquante",
    gestacionConfig_alerts_writeCrotalToSearch: "Saisissez un crotal pour rechercher.",
    gestacionConfig_alerts_writeIdToSearch: "Saisissez un ID pour rechercher.",

    gestacionConfig_alerts_notFound: "Introuvable",
    gestacionConfig_alerts_animalNotFoundByCrotal: "Aucun animal n'existe avec ce crotal.",
    gestacionConfig_alerts_animalNotFoundById: "Aucun animal n'existe avec cet ID.",

    gestacionConfig_alerts_warning: "Avertissement",
    gestacionConfig_alerts_searchError: "Erreur de recherche",


    maternidadConfig_screenTitle: "Configuration Maternité",
    maternidadConfig_chooseOptionTitle: "Choisissez une option",
    maternidadConfig_chooseOptionDescription: "Définissez le flux avant de commencer avec le lecteur.",
    maternidadConfig_entry: "Entrée",
    maternidadConfig_exit: "Sortie",
    maternidadConfig_reading: "Lecture",
    maternidadConfig_search: "Recherche",
    maternidadConfig_entryParamsTitle: "Paramètres d'entrée",
    maternidadConfig_exitParamsTitle: "Paramètres de sortie",
    maternidadConfig_entryParamsDescription: "Sélectionnez le corral et le comportement du flux.",
    maternidadConfig_exitParamsDescription: "Configurez le comportement du flux de sortie.",
    maternidadConfig_corralLabel: "Corral",
    maternidadConfig_corralPlaceholder: "Ex : 1",
    maternidadConfig_corralRequired: "Saisissez le corral pour continuer.",
    maternidadConfig_detectUnknownTitle: "Identifier les animaux inconnus",
    maternidadConfig_detectUnknownDescription: "Lorsque vous lirez un animal non identifié, vous pourrez lui attribuer un ID",
    maternidadConfig_confirmTitle: "Confirmer l'envoi",
    maternidadConfig_confirmDescription: "Une confirmation sera demandée avant l'envoi de chaque enregistrement.",
    maternidadConfig_animalSearchTitle: "Recherche d'animal",
    maternidadConfig_animalSearchDescription: "Choisissez si vous voulez rechercher par crotal ou par ID.",
    maternidadConfig_searchByCrotal: "Par crotal",
    maternidadConfig_searchById: "Par ID",
    maternidadConfig_manual: "Manuel",
    maternidadConfig_withSword: "Avec baguette",
    maternidadConfig_crotalLabelSearch: "Crotal",
    maternidadConfig_idLabelSearch: "ID",
    maternidadConfig_crotalPlaceholderSearch: "Ex : 982091072397436",
    maternidadConfig_idPlaceholderSearch: "Ex : A13",
    maternidadConfig_crotalRequiredSearch: "Saisissez un crotal pour continuer.",
    maternidadConfig_idRequiredSearch: "Saisissez un ID pour continuer.",
    maternidadConfig_searchWithSwordHelp: "En appuyant sur Scanner, la baguette sera lue sur cet écran et l'animal sera recherché avec ce crotal.",
    maternidadConfig_readingSword: "Lecture de la baguette...",
    maternidadConfig_waitingMatch: "En attente de correspondance",
    maternidadConfig_searchingAnimal: "Recherche de l'animal...",
    maternidadConfig_readingSwordDescription: "Approchez le crotal du lecteur pour identifier l'animal.",
    maternidadConfig_waitingMatchDescription: "Animal localisé. Approchez maintenant le crotal {{crotal}} de la baguette pour confirmer la correspondance.",
    maternidadConfig_searchingAnimalDescription: "Consultation des informations de l'animal dans le backend.",
    maternidadConfig_awrDisconnectedTitle: "AWR non connecté",
    maternidadConfig_awrSavedDescription: "Vous avez des AWR enregistrés. Appuyez pour en sélectionner un.",
    maternidadConfig_awrNotSavedDescription: "Vous n'avez aucun AWR enregistré. Appuyez pour en scanner un.",
    maternidadConfig_scan: "Scanner",
    maternidadConfig_continue: "Continuer",
    maternidadConfig_alert_error: "Erreur",
    maternidadConfig_alert_invalidBackendCrotal: "Le backend n'a pas renvoyé un crotal valide pour la comparaison.",
    maternidadConfig_alert_awrNotConnected: "AWR non connecté",
    maternidadConfig_alert_connectSwordBeforeContinue: "Connectez une baguette avant de continuer.",
    maternidadConfig_alert_couldNotStartReading: "Impossible de démarrer la lecture avec la baguette.",
    maternidadConfig_alert_missingData: "Donnée manquante",
    maternidadConfig_alert_writeCrotalToSearch: "Saisissez un crotal pour rechercher.",
    maternidadConfig_alert_writeIdToSearch: "Saisissez un ID pour rechercher.",
    maternidadConfig_alert_notFound: "Introuvable",
    maternidadConfig_alert_noAnimalWithCrotal: "Aucun animal n'existe avec ce crotal.",
    maternidadConfig_alert_noAnimalWithId: "Aucun animal n'existe avec cet ID.",
    maternidadConfig_alert_warning: "Avis",
    maternidadConfig_alert_searchError: "Erreur de recherche",
    maternidadConfig_alert_networkError: "Erreur réseau",
    maternidadConfig_alert_networkErrorMessage: "Impossible de se connecter au serveur.",

    gestationReader_screenTitle: "Lecteur Gestation",
    gestationReader_animalInfoTitle: "Informations de l'animal",
    gestationReader_animalInfoDescription: "Données trouvées dans la recherche.",
    gestationReader_animalCardTitle: "Fiche Animal",
    gestationReader_animalIdLabel: "ID",
    gestationReader_animalCrotalLabel: "Crotal",
    gestationReader_fieldCorral: "Enclos",
    gestationReader_fieldHouse: "Bâtiment",
    gestationReader_fieldState: "État",
    gestationReader_fieldBodyCondition: "Condition corporelle",
    gestationReader_fieldCycle: "Cycle",
    gestationReader_fieldSystemEntryDate: "Entrée dans le système",
    gestationReader_newSearch: "Nouvelle recherche",
    gestationReader_summaryTitle: "Résumé",
    gestationReader_summaryDescription: "Paramètres choisis dans Configuration",
    gestationReader_mode: "Mode",
    gestationReader_corral: "Enclos",
    gestationReader_modeEntry: "Entrée",
    gestationReader_modeExit: "Sortie",
    gestationReader_modeReading: "Lecture",
    gestationReader_modeSearch: "Recherche",
    gestationReader_detectUnknownTitle: "Identifier les animaux inconnus",
    gestationReader_detectUnknownDescription: "Quand un animal sans ID apparaît, proposer de lui attribuer un ID.",
    gestationReader_confirmSendTitle: "Confirmer l'envoi",
    gestationReader_confirmSendDescription: "Demandera une confirmation avant d'envoyer chaque enregistrement.",
    gestationReader_changeSettings: "Changer la configuration",
    gestationReader_currentReadingTitle: "Lecture actuelle",
    gestationReader_currentReadingDescription: "Le crotal détecté et l'ID associé apparaîtront ici.",
    gestationReader_awrDisconnected: "AWR non connecté",
    gestationReader_readCrotal: "Crotal lu",
    gestationReader_readId: "ID",
    gestationReader_animalWithoutAssignedId: "Animal sans ID attribué",
    gestationReader_unknownAnimal: "Animal inconnu",
    gestationReader_animalWithoutIdTitle: "Animal sans ID",
    gestationReader_animalWithoutIdDescription: "Saisissez un ID manuel pour mettre à jour le crotal lu.",
    gestationReader_newIdLabel: "Nouvel ID",
    gestationReader_newIdPlaceholder: "Ex : A13",
    gestationReader_updateId: "Mettre à jour l'ID",
    gestationReader_updatingId: "Mise à jour...",
    gestationReader_sentRecordsTitle: "Enregistrements envoyés",
    gestationReader_noRecords: "Aucun enregistrement.",
    gestationReader_tableHeaderCorral: "Enclos",
    gestationReader_tableHeaderId: "ID",
    gestationReader_tableHeaderCrotal: "Crotal",
    gestationReader_buttonAutoReading: "Lecture automatique active",
    gestationReader_buttonAutoSending: "Envoi automatique actif",
    gestationReader_buttonSending: "Envoi...",
    gestationReader_buttonSend: "Envoyer",
    gestationReader_alertError: "Erreur",
    gestationReader_alertWarning: "Avis",
    gestationReader_alertNetworkError: "Erreur réseau",
    gestationReader_alertMissingCrotalTitle: "Crotal manquant",
    gestationReader_alertMissingCrotalMessage: "Approchez le crotal du lecteur avant d'envoyer.",
    gestationReader_alertInvalidCrotalTitle: "Crotal invalide",
    gestationReader_alertInvalidCrotalMessage: "Le crotal doit être numérique.",
    gestationReader_alertReadErrorTitle: "Erreur de lecture",
    gestationReader_alertNetworkErrorMessage: "Impossible de se connecter au serveur.",
    gestationReader_alertMissingCorralTitle: "Enclos manquant",
    gestationReader_alertMissingCorralMessage: "Saisissez l'enclos avant d'envoyer.",
    gestationReader_alertInvalidCorralTitle: "Enclos invalide",
    gestationReader_alertInvalidCorralMessage: "L'enclos doit être un nombre.",
    gestationReader_alertSendErrorTitle: "Erreur lors de l'envoi",
    gestationReader_alertNoIpConfigured: "Aucune IP configurée.",
    gestationReader_alertMissingIdTitle: "ID manquant",
    gestationReader_alertMissingIdMessage: "Saisissez le nouvel ID avant la mise à jour.",
    gestationReader_alertMissingAssociatedCrotalTitle: "Crotal manquant",
    gestationReader_alertMissingAssociatedCrotalMessage: "Aucun crotal associé à mettre à jour.",
    gestationReader_alertInvalidAssociatedCrotalTitle: "Crotal invalide",
    gestationReader_alertInvalidAssociatedCrotalMessage: "Le crotal associé n'est pas valide.",
    gestationReader_alertUpdateIdErrorTitle: "Erreur lors de la mise à jour de l'ID",
    gestationReader_readerMode: "Lecteur",
gestationReader_keyboardMode: "Clavier",

gestationReader_keyboardEntryTitle: "Entrée au clavier",
gestationReader_keyboardExitTitle: "Sortie au clavier",
gestationReader_keyboardDescription: "Saisissez la donnée manuellement avec le clavier du téléphone.",
gestationReader_keyboardId: "ID",
gestationReader_keyboardCrotal: "Boucle",
gestationReader_keyboardIdLabel: "ID animal",
gestationReader_keyboardCrotalLabel: "Boucle",
gestationReader_keyboardIdPlaceholder: "Saisissez l'ID",
gestationReader_keyboardCrotalPlaceholder: "Saisissez la boucle",
gestationReader_keyboardAdd: "Ajouter",
gestationReader_keyboardAdding: "Ajout...",

gestationReader_pendingRecordsTitle: "Enregistrements non envoyés",
gestationReader_buttonSendingBatch: "Envoi du lot...",
gestationReader_buttonSendBatch: "Envoyer le lot",
gestationReader_buttonSendBatchCount: "Envoyer le lot ({{count}})",

gestationReader_noPendingRecordsTitle: "Aucun enregistrement",
gestationReader_noPendingRecordsText: "Il n'y a aucun enregistrement en attente d'envoi.",
gestationReader_batchSentTitle: "Lot envoyé",
gestationReader_batchSentText: "{{count}} enregistrement(s) ont été envoyés correctement.",
gestationReader_batchWithErrorsTitle: "Lot avec erreurs",

gestationReader_recordSentTitle: "Enregistrement envoyé",
gestationReader_recordSentText: "Le mouvement a été envoyé correctement.",

gestationReader_invalidAnimalId: "L'ID de l'animal n'est pas valide.",
gestationReader_invalidPenRecord: "La case de l'enregistrement n'est pas valide.",
gestationReader_invalidCrotalRecord: "La boucle de l'enregistrement n'est pas valide.",
gestationReader_duplicateIdPending: "L'ID {{id}} est déjà dans le tableau des enregistrements non envoyés.",
gestationReader_duplicateCrotalPending: "La boucle {{crotal}} est déjà dans le tableau des enregistrements non envoyés.",
gestationReader_keyboardMissingId: "Saisissez l'ID de l'animal.",
gestationReader_keyboardMissingCrotal: "Saisissez la boucle de l'animal.",
gestationReader_keyboardMissingPen: "Sélectionnez une case valide avant d'ajouter l'animal.",
gestationReader_noAnimalById: "Aucun animal n'existe avec l'ID {{id}}.",
gestationReader_noAnimalByCrotal: "Aucun animal n'existe avec la boucle {{crotal}}.",
gestationReader_addAnimalError: "Impossible d'ajouter l'animal.",

gestationReader_pendingAnimalHint: "Les animaux lus apparaîtront ici.",

gestationReader_changePenTitle: "Changer de case",
gestationReader_changePenDescription: "Saisissez la nouvelle case d'entrée.",
gestationReader_newPenLabel: "Nouvelle case",
gestationReader_newPenPlaceholder: "Ex : 1",
gestationReader_cancel: "Annuler",
gestationReader_save: "Enregistrer",
gestationReader_accept: "Accepter",
gestationReader_sentHistoryTitle: "Historique des envois",

    maternityReader_screenTitle: "Lecteur Maternité",
    maternityReader_alertMissingCrotalTitle: "Boucle manquante",
    maternityReader_alertMissingCrotalMessage: "Approchez la boucle du lecteur avant d'envoyer.",
    maternityReader_alertInvalidCrotalTitle: "Boucle invalide",
    maternityReader_alertInvalidCrotalMessage: "La boucle doit être numérique.",
    maternityReader_alertReadErrorTitle: "Erreur de lecture",
    maternityReader_alertNetworkError: "Erreur réseau",
    maternityReader_alertNetworkErrorMessage: "Impossible de se connecter au serveur.",
    maternityReader_alertMissingCorralTitle: "Enclos manquant",
    maternityReader_alertMissingCorralMessage: "Saisissez l'enclos avant d'envoyer.",
    maternityReader_alertInvalidCorralTitle: "Enclos invalide",
    maternityReader_alertInvalidCorralMessage: "L'enclos doit être un nombre (ex. : 8).",
    maternityReader_alertError: "Erreur",
    maternityReader_alertNoIpConfigured: "Aucune IP configurée.",
    maternityReader_alertWarning: "Avertissement",
    maternityReader_alertSendErrorTitle: "Erreur d'envoi",
    maternityReader_alertMissingIdTitle: "ID manquant",
    maternityReader_alertMissingIdMessage: "Saisissez le nouvel ID avant la mise à jour.",
    maternityReader_alertMissingAssociatedCrotalTitle: "Boucle manquante",
    maternityReader_alertMissingAssociatedCrotalMessage: "Aucune boucle associée à mettre à jour.",
    maternityReader_alertInvalidAssociatedCrotalTitle: "Boucle invalide",
    maternityReader_alertInvalidAssociatedCrotalMessage: "La boucle associée n'est pas valide.",
    maternityReader_alertUpdateIdErrorTitle: "Erreur lors de la mise à jour de l'ID",
    maternityReader_animalInfoTitle: "Informations sur l'animal",
    maternityReader_animalInfoDescription: "Données trouvées dans la recherche.",
    maternityReader_animalCardTitle: "Fiche Animal",
    maternityReader_animalIdLabel: "ID",
    maternityReader_animalCrotalLabel: "Boucle",
    maternityReader_fieldCorral: "Enclos",
    maternityReader_fieldHouse: "Bâtiment",
    maternityReader_fieldState: "État",
    maternityReader_fieldBodyCondition: "État corporel",
    maternityReader_fieldCycle: "Cycle",
    maternityReader_fieldSystemEntryDate: "Entrée dans le système",
    maternityReader_newSearch: "Nouvelle recherche",
    maternityReader_summaryTitle: "Résumé",
    maternityReader_summaryDescription: "Paramètres sélectionnés dans la configuration",
    maternityReader_mode: "Mode",
    maternityReader_modeEntry: "Entrée",
    maternityReader_modeExit: "Sortie",
    maternityReader_modeReading: "Lecture",
    maternityReader_corral: "Enclos",
    maternityReader_detectUnknownTitle: "Identifier les animaux inconnus",
    maternityReader_detectUnknownDescription: "Quand un animal sans ID apparaît, proposer de lui en attribuer un.",
    maternityReader_confirmSendTitle: "Confirmer l'envoi",
    maternityReader_confirmSendDescription: "Demandera une confirmation avant d'envoyer chaque enregistrement.",
    maternityReader_changeSettings: "Modifier la configuration",
    maternityReader_currentReadingTitle: "Lecture actuelle",
    maternityReader_currentReadingDescription: "La boucle détectée apparaîtra ici.",
    maternityReader_awrDisconnected: "AWR non connecté",
    maternityReader_readCrotal: "Boucle lue",
    maternityReader_readId: "ID",
    maternityReader_animalWithoutAssignedId: "Animal sans ID attribué",
    maternityReader_unknownAnimal: "Animal inconnu",
    maternityReader_animalWithoutIdTitle: "Animal sans ID",
    maternityReader_animalWithoutIdDescription: "Saisissez un ID manuel pour mettre à jour la boucle lue.",
    maternityReader_newIdLabel: "Nouvel ID",
    maternityReader_newIdPlaceholder: "Ex. : A13",
    maternityReader_updatingId: "Mise à jour...",
    maternityReader_updateId: "Mettre à jour l'ID",
    maternityReader_sentRecordsTitle: "Enregistrements envoyés",
    maternityReader_tableHeaderCorral: "Enclos",
    maternityReader_tableHeaderId: "ID",
    maternityReader_tableHeaderCrotal: "Boucle",
    maternityReader_noRecords: "Aucun enregistrement.",
    maternityReader_buttonAutoReading: "Lecture automatique active",
    maternityReader_buttonAutoSending: "Envoi automatique actif",
    maternityReader_buttonSending: "Envoi en cours...",
    maternityReader_buttonSend: "Envoyer",

    awrScanResults_title: "AWR – Résultats du scan",
    awrScanResults_searching: "Recherche de l’AWR…",
    awrScanResults_warningTitle: "Avertissement",
    awrScanResults_noDevicesNearby: "Aucun AWR à proximité n’a été trouvé.",
    awrScanResults_connecting: "Connexion…",
    awrScanResults_connectErrorFallback: "Impossible de se connecter",
    awrScanResults_connectedTitle: "Connecté",
    awrScanResults_connectedMessage: "Connexion établie avec {{device}}.",
    awrScanResults_genericDevice: "l’appareil",

    awrSavedList_title: "AWR scannés",
    awrSavedList_connecting: "Connexion…",
    awrSavedList_empty: "Aucun AWR enregistré. Scannez-en un depuis « Configuration AWR ».",
    awrSavedList_connected: "Connecté",
    awrSavedList_disconnected: "Déconnecté",
    awrSavedList_renameAccessibility: "Renommer",
    awrSavedList_deleteAccessibility: "Supprimer",
    awrSavedList_renameTitle: "Renommer l’AWR",
    awrSavedList_nameLabel: "Nom",
    awrSavedList_deleteTitle: "Supprimer l’AWR enregistré",
    awrSavedList_deleteMessage: "Voulez-vous vraiment supprimer cet AWR de la liste ?",
    awrSavedList_deleteAction: "Supprimer",

    ipConfig_title: "Configuration IP",
    ipConfig_cardTitle: "Serveur CTIFEED",
    ipConfig_cardDescription: "Saisissez l'IP du serveur où le portail sera ouvert.",
    ipConfig_inputLabel: "IP (IP uniquement)",
    ipConfig_saved: "Enregistré",
    ipConfig_alertSuccessTitle: "Correct",
    ipConfig_alertSuccessMessage: "IP correcte",
    ipConfig_alertWarningTitle: "Avertissement",
    ipConfig_alertServerNotUpdated: "Serveur non mis à jour",
    ipConfig_alertErrorTitle: "Erreur",
    ipConfig_alertInvalidIp: "IP invalide",

    portal_preparing: "Préparation du portail...",
    portal_noSessionToken: "Aucun jeton de session n’est disponible. Veuillez vous reconnecter.",
    portal_noIpConfigured: "Aucune IP n’est configurée. Configurez d’abord l’IP du serveur.",
    portal_prepareUrlError: "Impossible de préparer l’URL du portail.",
    portal_loadError: "Impossible de charger le portail.",
    portal_checkingConnection: "Vérification de la connexion au portail...",
    portal_noConnectionTitle: "Pas de connexion",
    portal_connectionTimeout: "Impossible de se connecter au portail. Vérifiez que vous êtes connecté au bon réseau.",
    portal_connectionError: "Impossible de se connecter au portail. Vérifiez le réseau ou l’IP configurée.",
    portal_httpError: "Impossible d’ouvrir le portail. Erreur HTTP {{status}}.",
    portal_retry: "Réessayer",
    portal_loading: "Chargement du portail...",

    AltaDispositivos: "Enregistrement des appareils",
    LectorMaternidad: "Lecteur Maternité",
    LectorGestacion: "Lecteur Gestation",
    ConfiguracionIP: "Configuration IP",
    ConfiguracionAWR: "Configuration AWR",
    DarDeAltaAWR: "Enregistrer AWR",
    AWREscaneados: "AWR scannés",
    CerrarSesion: "Se déconnecter",

    Config_lastReadMismatchTitle: "L'animal lu ne correspond pas à la recherche",
    Config_lastReadMismatchCrotal: "Boucle",
    Config_lastReadMismatchId: "ID",
    awrBluetoothPermissionMessage: "Active le Bluetooth et acceptez l’autorisation pour pouvoir scanner.",

    animalState: {
    gestation: "Gestation",
    maternity: "Maternité",
    out_of_gestation: "Hors gestation",
    out_of_maternity: "Hors maternité"
  },


Reader_readingTitle: "Lecture des boucles",
Reader_labelId: "ID",
Reader_labelCrotal: "Boucle",
Reader_labelCorral: "Enclos",
Reader_labelHouse: "Bâtiment",
Reader_labelState: "État",
Reader_autoReadingBadge: "Lecture automatique",

gestacionConfig_flowSectionTitle: "Configuration du flux",
gestacionConfig_workModeTitle: "Mode de travail",
gestacionConfig_workModeDescription: "Sélectionnez ce que fera le lecteur.",
gestacionConfig_entryDescription: "Enregistrer l’entrée",
gestacionConfig_exitDescription: "Enregistrer la sortie",
gestacionConfig_readingDescription: "Consultation uniquement",
gestacionConfig_searchDescription: "Rechercher un animal",

gestacionConfig_sendSettingsTitle: "Paramètres d’envoi",
gestacionConfig_sendSettingsDescription: "Configurez le comportement du flux lors de la lecture des animaux.",

gestacionConfig_corralSectionTitle: "Enclos d’entrée",
gestacionConfig_corralSectionDescription: "Cette donnée est obligatoire pour continuer l’enregistrement.",

gestacionConfig_alerts_notice: "Avis",
gestacionConfig_alerts_invalidCrotalFromBackend: "Le backend n’a pas renvoyé de boucle valide à comparer.",

common_accept: "Accepter",

maternidadConfig_flowSectionTitle: "Configuration du flux",
maternidadConfig_workModeTitle: "Mode de travail",
maternidadConfig_workModeDescription: "Sélectionnez ce que fera le lecteur.",
maternidadConfig_entryDescription: "Enregistrer l’entrée",
maternidadConfig_exitDescription: "Enregistrer la sortie",
maternidadConfig_readingDescription: "Consultation uniquement",
maternidadConfig_searchDescription: "Rechercher un animal",

maternidadConfig_sendSettingsTitle: "Paramètres d’envoi",
maternidadConfig_sendSettingsDescription: "Configurez le comportement du flux lors de la lecture des animaux.",

maternidadConfig_corralSectionTitle: "Enclos d’entrée",
maternidadConfig_corralSectionDescription: "Cette donnée est obligatoire pour continuer l’enregistrement.",

maternidadConfig_alert_invalidCrotalFromBackend: "Le backend n’a pas renvoyé de boucle valide à comparer.",
  maternidadConfig_readOnlyTitle: "Autorisation en lecture seule",
maternidadConfig_readOnlyModifySettings: "Cet utilisateur dispose uniquement d’autorisations en lecture seule. Il ne peut pas modifier cette configuration.",
maternidadConfig_readOnlyUseFunction: "Cet utilisateur dispose uniquement d’autorisations en lecture seule. Il ne peut pas utiliser cette fonction.",

  ajustesEnvioMaternidad: {
    headerTitle: "Paramètres d'envoi",
    headerSubtitle: "Configurez le comportement du flux lors de la lecture des animaux.",
    cardTitle: "Envoi des enregistrements",
    cardSubtitle: "Ces paramètres s'appliquent lors de la poursuite de la lecture."
  },

  noAlimentadosMaternidad: {
    viewStatus: "Voir l'état",
animalIdNotFound: "Identifiant de l'animal introuvable.",
openAnimalInfoError: "Impossible d'ouvrir les informations de l'animal.",

  animalId: "ID ANIMAL",
  corral: "Enclos",
  consumption: "Consommation",
  withoutFeeding: "Non alimenté",
  day: "jour",
  days: "jours",
  loadingAnimals: "Chargement des animaux...",
  title: "Animaux non alimentés",
  totalAnimalsMaternity: "Total des animaux en maternité :",
  notSeen: "Non vus",
  all: "Tous",
  sort: "Trier",
  emptyTitle: "Aucun animal en attente",
  emptyText: "Aucun animal non alimenté n'a été trouvé en maternité.",
  sortBy: "Trier par",
  daysWithoutFeeding: "Jours sans alimentation",
  sortDaysHelp: "Trie selon le nombre de jours sans alimentation",
  sortCorralHelp: "Trie selon le numéro de l'enclos",
  descending: "Décroissant",
  ascending: "Croissant",
  filterAnimals: "Filtrer les animaux",
  allHelp: "Affiche tous les animaux",
  unmarked: "Non marqués",
  unmarkedHelp: "Masque les animaux déjà vérifiés",
  clearMarkedTitle: "Effacer les animaux marqués",
  clearMarkedText: "Toutes les marques des animaux vérifiés seront supprimées.",
  cancel: "Annuler",
  clear: "Effacer",
  error: "Erreur",
  serverConnectionError: "Impossible de se connecter au serveur."
},

noAlimentadosGestacion: {
  animalId: "ID ANIMAL",
  corral: "Enclos",
  consumption: "Consommation",
  withoutFeeding: "Non alimenté",
  day: "jour",
  days: "jours",
  loadingAnimals: "Chargement des animaux...",
  title: "Animaux non alimentés",
  totalAnimalsGestation: "Total des animaux en gestation :",
  notSeen: "Non vus",
  all: "Tous",
  sort: "Trier",
  emptyTitle: "Aucun animal en attente",
  emptyText: "Aucun animal non alimenté n'a été trouvé en gestation.",
  sortBy: "Trier par",
  daysWithoutFeeding: "Jours sans alimentation",
  sortDaysHelp: "Trie selon le nombre de jours sans alimentation",
  sortCorralHelp: "Trie selon le numéro de l'enclos",
  descending: "Décroissant",
  ascending: "Croissant",
  filterAnimals: "Filtrer les animaux",
  allHelp: "Affiche tous les animaux",
  unmarked: "Non marqués",
  unmarkedHelp: "Masque les animaux déjà vérifiés",
  clearMarkedTitle: "Effacer les animaux marqués",
  clearMarkedText: "Toutes les marques des animaux vérifiés seront supprimées.",
  cancel: "Annuler",
  clear: "Effacer",
  error: "Erreur",
  serverConnectionError: "Impossible de se connecter au serveur."
},
capturaAnimalHome: {
  selectOption: "Sélectionnez une option",
  unfedAnimalsTitle: "Animaux non alimentés",
  unfedAnimalsDescription: "Consulter les animaux qui n'ont pas reçu l'alimentation prévue.",
  twoFeedsTitle: "2 aliments",
  twoFeedsDescription: "Gérer le changement d'alimentation dans les sorties de distribution.",
  animalStatusTitle: "État de l'animal",
animalStatusDescription: "Consulter ou mettre à jour l'état de l'animal.",
birthCaptureTitle: "Saisie de mise bas",
birthCaptureDescription: "Enregistrez les nés vivants, morts et momifiés.",
},
cambioPiensoMaternidad: {
  error: "Erreur",
  loadTasksError: "Impossible de charger les tâches de changement d'aliment.",
  loadingTasks: "Chargement des tâches...",
  title: "Changement d'aliment",
  pendingTask: "{{count}} tâche en attente",
  pendingTasks: "{{count}} tâches en attente",
  emptyTitle: "Aucune tâche en attente",
  emptyText: "Aucune tâche de changement d'aliment n'a été trouvée.",
  animalId: "ID ANIMAL",
  corral: "Enclos",
  setTo: "Définir sur",
  destination: "Destination"
},
estadoAnimal: {
  queryLabel: "Consultation",
  title: "État de l'animal",
  subtitle: "Sélectionnez comment vous souhaitez identifier l'animal.",
  corral: "Enclos",
  corralDescription: "Saisissez le numéro de l'enclos.",
  id: "ID",
  idDescription: "Saisissez l'identifiant de l'animal.",
  animalId: "ID animal",
  requiredData: "Donnée requise",
  enterCorral: "Saisissez le numéro de l'enclos.",
  enterId: "Saisissez l'identifiant de l'animal.",
  consulting: "Consultation...",
  continue: "Continuer",
  accept: "Accepter",
  serverConnectionError: "Impossible de se connecter au serveur.",
  noIpConfigured: "Aucune IP n'est configurée.",
  nextScreenPending: "Nous créerons l'écran d'information de l'animal à l'étape suivante.",
  corralMaternityDescription: "Saisissez le numéro de la case de maternité.",
idAnimalDescription: "Rechercher l’animal en maternité et en gestation.",
animalNotFound: "Animal non trouvé",
},
matCorralDetail: {
  earTagAlreadyAssigned: "La boucle est attribuée à un autre animal",
  readOnlyPermission: "Permission en lecture seule",
readOnlyPermissionText: "Cet utilisateur dispose uniquement de permissions de lecture. Il ne peut pas effectuer d'opérations sur l'animal.",
  animalStatus: "État de l'animal",
  id: "ID",
  earTag: "Boucle",
  cycle: "Cycle",
  day: "Jour",

  curve: "Courbe",
  correction: "Correction",
  entryDate: "Date d'entrée",
  farrowingDate: "Date de mise bas",
  house: "Bâtiment",
  pen: "Case",
  lastFeeding: "Dernière alimentation",
  presentPiglets: "Porcelets présents",
  inseminationDate: "Date d'insémination",
  teatsNumber: "Nb de tétines",

  operations: "Opérations",

  consumption: "Consommation",
  ofGrams: "sur {{amount}} g",
  oneDayWithoutFeeding: "1 jour sans alimentation",
  daysWithoutFeeding: "{{count}} jours sans alimentation",

  noAnimalData: "Aucune donnée de l'animal",
  noAnimalDataText: "Aucune information n'a été reçue pour l'affichage.",
  back: "Retour",
  operationsPendingTitle: "Opérations",
  operationsPendingText: "Nous effectuerons les opérations à l'étape suivante.",
  moveToWeaning: "Passer au sevrage",
  chooseOption: "Sélectionnez une opération pour cet animal.",
  nextOperation: "Opération suivante",
  insertAnimal: "Insérer un animal",
  moveToLactation: "Passer en lactation",
  nextStep: "Étape suivante",
  actions: "Actions",

  bodyCondition: "État corporel",
  subState: "Sous-état",
  pigletCapture: "Saisie des porcelets",
  animalExit: "Sortie de l'animal",
  replaceEarTag: "Remplacer la boucle",
  changePen: "Changer de case",
  anonymousAnimalId: "Identifiant d'animal anonyme",

  cancel: "Annuler",
  accept: "Accepter",
  saving: "Enregistrement...",
  error: "Erreur",

  operationDone: "Opération réalisée avec succès.",
  changeStateDone: "Sous-état mis à jour avec succès.",
  changeStateError: "Impossible de changer l'état de l'animal.",
  confirmNextOperation: "Voulez-vous vraiment passer à l'opération suivante ?",
  pkidChangeStateNotFound: "L'identifiant interne de l'animal est introuvable.",

  selectExitType: "Sélectionnez le type de sortie à appliquer.",
  exitImmediate: "Sortie immédiate",
  exitScheduled: "Sortie programmée",
  exitScheduledEmptyHopper: "Sortie programmée avec trémie vide",
  cancelScheduledExit: "Annuler la sortie programmée",
  scheduledDate: "Date programmée",
  exitDateLimitText: "Vous ne pouvez pas sélectionner une date antérieure à aujourd'hui ni supérieure à 3 jours.",
  animalExitDone: "Sortie de l'animal réalisée avec succès.",
  animalExitError: "Impossible de réaliser la sortie de l'animal.",
  pkidExitNotFound: "L'identifiant interne de l'animal est introuvable.",

  selectCurve: "Sélectionner une courbe",
  selectCurveText: "Sélectionnez la nouvelle courbe de l'animal.",
  loadingCurves: "Chargement des courbes...",
  noCurvesAvailable: "Aucune courbe disponible.",
  confirmChangeCurve: "Voulez-vous vraiment changer la courbe ?",
  loadCurvesError: "Impossible de charger les courbes.",
  pkidChangeCurveNotFound: "L'identifiant interne de l'animal est introuvable.",
  changeCurveDone: "Courbe mise à jour avec succès.",
  changeCurveError: "Impossible de changer la courbe.",

  selectBodyConditionText: "Sélectionnez le nouvel état corporel de l'animal.",
  loadingBodyConditions: "Chargement des états corporels...",
  noBodyConditionsAvailable: "Aucun état corporel disponible.",
  confirmChangeBodyCondition: "Voulez-vous vraiment changer l'état corporel ?",
  loadBodyConditionsError: "Impossible de charger les états corporels.",
  pkidChangeBodyConditionNotFound: "L'identifiant interne de l'animal est introuvable.",
  changeBodyConditionDone: "État corporel mis à jour avec succès.",
  changeBodyConditionError: "Impossible de changer l'état corporel.",

  selectSubStateText: "Sélectionnez manuellement le nouveau sous-état de l'animal.",
  confirmChangeSubState: "Voulez-vous vraiment changer le sous-état ?",

  currentPen: "Case actuelle : {{pen}}",
  newPen: "Nouvelle case",
  enterNewPen: "Saisissez la nouvelle case.",
  pkidChangePenNotFound: "L'identifiant interne de l'animal est introuvable.",
  changePenDone: "Case mise à jour avec succès.",
  changePenError: "Impossible de changer la case.",

  currentEarTag: "Boucle actuelle : {{earTag}}",
  newEarTag: "Nouvelle boucle",
  enterNewEarTag: "Saisissez la nouvelle boucle.",
  pkidEarTagNotFound: "L'identifiant interne de l'animal est introuvable.",
  replaceEarTagDone: "Boucle mise à jour avec succès.",
  replaceEarTagError: "Impossible de remplacer la boucle.",

  identifyAnonymousAnimalText: "Choisissez si vous voulez attribuer un ID ou une boucle à l'animal.",
  newId: "Nouvel ID",
  enterNewId: "Saisissez le nouvel ID.",
  idExample: "Ex : 1010",
  earTagExample: "Ex : 123",
  notAnonymousAnimalText: "Cet animal n'est pas anonyme car il possède déjà un ID ou une boucle.",
  pkidIdentifyNotFound: "L'identifiant interne de l'animal est introuvable.",
  identifyAnonymousAnimalDone: "Identifiant de l'animal mis à jour avec succès.",
  identifyAnonymousAnimalError: "Impossible d'identifier l'animal anonyme.",

  livePiglets: "Vivants",
  deadPiglets: "Morts",
  mummifiedPiglets: "Momifiés",
  totalBornPiglets: "Total nés",
  pigletCaptureText: "Saisissez les porcelets vivants, morts et momifiés.",
  captureBeforeLactationText: "Enregistrez les naissances avant de passer en lactation.",
  weaningPigletsOnlyRead: "Au sevrage, les porcelets peuvent uniquement être consultés.",
  pkidPigletsNotFound: "L'identifiant interne de l'animal est introuvable.",
  pigletCaptureDone: "Saisie des porcelets enregistrée avec succès.",
  pigletCaptureError: "Impossible d'enregistrer la saisie des porcelets.",
  penNotFound: "Case non trouvée",

},
subState: {
  prepartum: "Pré-partum",
  lactation: "Lactation",
  weaning: "Sevrage",
},

capturaParto: {
  birthDataTitle: "Données de mise bas",
  birthDataSubtitle: "Vérifiez les données de l'animal avant d'enregistrer la mise bas.",
  corral: "Case",
  id: "ID",
  date: "Date",
  subState: "Sous-état",

  dataCollectionTitle: "Collecte des données",
  dataCollectionSubtitle: "Saisissez les nés vivants, morts et momifiés.",
  weaningReadOnly: "Au sevrage, les données peuvent uniquement être consultées.",

  totalBorn: "Total nés",
  live: "Vivants",
  dead: "Morts",
  mummified: "Momifiés",

  prepartum: "Pré-partum",
  farrowing: "Mise bas",
  lactation: "Lactation",
  weaning: "Sevrage",

  accept: "Accepter",
  cancel: "Annuler",
  saving: "Enregistrement...",

  sentTitle: "Saisie envoyée",
  sentMessage: "La saisie de mise bas a été enregistrée avec succès.",

  errorTitle: "Erreur",
  invalidAnimalTitle: "Animal non valide",
  invalidAnimalText: "L'identifiant interne de l'animal est introuvable.",
  reportSendError: "Impossible d'enregistrer la saisie de mise bas.",

  invalidDateTitle: "Date non valide",
  invalidDateMessage: "La date de mise bas ne peut pas être postérieure à aujourd'hui.",
  changeDate: "Changer la date",

  selectDateTitle: "Sélectionner une date",
  selectDateMessage: "Ajustez la date de mise bas avec les boutons.",
},

capturaMaternidadEntrada: {
  title: "Saisie de mise bas",
  description: "Recherchez l'animal par case ou par ID pour enregistrer la mise bas.",
  maternityLabel: "MATERNITÉ",

  corral: "Case",
  corralDescription: "Recherchez l'animal par numéro de case.",
  id: "ID",
  idDescription: "Recherchez l'animal par son identifiant.",
  animalId: "ID animal",

  corralExample: "Ex : 102",
  idExample: "Ex : 1234",

  consulting: "Recherche...",
  continue: "Continuer",
  accept: "Accepter",

  serverConnectionError: "Impossible de se connecter au serveur.",
},
altaBajaStack: {
  tituloPantalla: "Alta/Baixa de garrins",
  descripcionPantalla: "Busca la mare per corral o ID per registrar altes o baixes de garrins.",
},
altaBajaLechones: {
  heroTitle: "Mouvement de porcelets",
  statusAlta: "Entrée",
  statusBaja: "Sortie",

  corralUpper: "CASE",
  idUpper: "ID",
  dateUpper: "DATE",

  movementType: "Type de mouvement",
  movementSubtitle: "Sélectionnez si vous souhaitez enregistrer une entrée ou une sortie.",
  adoption: "Adoption",
  baja: "Sortie",

  adoptionData: "Données d'adoption",
  donorMother: "Truie donneuse",
  donatesPiglets: "Donne des porcelets",
  id: "ID",
  transferredPiglets: "Porcelets transférés",
  totalAdopted: "Total adoptés",
  total: "Total",

  bajaReason: "Motif de sortie",
  reasonCrushing: "Écrasement",
  reasonDiarrhea: "Diarrhée",
  reasonLowViability: "Faible viabilité",
  reasonDeformities: "Déformations",
  reasonOther: "Autres",

  piglet: "porcelet",
  piglets: "porcelets",
  description: "Description",

  editReason: "Modifier le motif",
  addReason: "Ajouter un motif",
  reasonModalText: "Indiquez le nombre de porcelets et décrivez le motif.",

  saving: "Enregistrement...",
  saveAlta: "Enregistrer l'entrée",
  saveBaja: "Enregistrer la sortie",
  accept: "Accepter",
  cancel: "Annuler",

  error: "Erreur",
  missingData: "Données manquantes",
  saveError: "Erreur d'enregistrement",
  saveErrorText: "Impossible d'enregistrer l'opération.",
  selectedAnimalPkidNotFound: "L'identifiant interne de l'animal sélectionné est introuvable.",

  enterTransferredPiglets: "Saisissez le nombre de porcelets transférés.",
  invalidTotalTitle: "Total non valide",
  invalidPigletsNumber: "Saisissez un nombre valide de porcelets.",

  missingDescriptionTitle: "Description obligatoire",
  missingDescriptionText: "Saisissez la description du motif.",
  invalidQuantityTitle: "Quantité non valide",
  invalidPigletQuantity: "Saisissez une quantité valide de porcelets.",

  selectReasonRequired: "Sélectionnez au moins un motif de sortie.",

  adoptionSavedTitle: "Entrée enregistrée",
  adoptionSavedMessage: "{{count}} porcelets ont été enregistrés correctement.",

  bajasSavedTitle: "Sorties enregistrées",
  bajasSavedMessage: "{{piglets}} sorties ont été enregistrées correctement pour {{reasons}} motif(s).",
},
avisoAplicacionNoConfigurada: {
  title: "Application non configurée",
  text: "Configurez l'adresse IP du serveur",
  link: "Appuyez ici",
},
generalHome: {
  movementAnimalTitle: "Mouvement animal",
  readerDescription: "Lecteur de boucles auriculaires.",
  keyboardDescription: "Clavier",

  ctifeedTitle: "CTIFEED",
  ctifeedDescription: "Accédez au portail principal.",

  modalApplicationNotConfiguredTitle: "Application non configurée",
  modalNoSessionTitle: "Session non démarrée",
  modalInstallationUnavailableTitle: "Installation non disponible",
  modalPreparingSessionTitle: "Préparation de la session",
  modalReadOnlyPermissionTitle: "Permission en lecture seule",

  modalApplicationNotConfiguredText: "Aucune installation n'est configurée. Allez dans Installations et sélectionnez-en une.",
  modalNoSessionText: "L'installation possède une IP, mais aucune session n'est démarrée. Vérifiez le nom d'utilisateur et le mot de passe dans Installations.",
  modalInstallationUnavailableText: "Impossible de se connecter à l'installation sélectionnée. Vérifiez que vous êtes connecté au bon réseau WiFi ou contrôlez l'IP du serveur.",
  modalPreparingSessionText: "La session est encore en cours de chargement. Réessayez dans quelques secondes.",
  modalReadOnlyPermissionText: "Votre utilisateur ne dispose pas des droits administrateur pour accéder à cette fonctionnalité.",

  accept: "Accepter",

  connectingTitle: "Connexion...",
  connectingText: "Vérification de la connexion avec l'installation sélectionnée.",
},
movimientoAnimalMaternidad: {
  smallLabel: "MOUVEMENT",
  title: "Maternité",
  subtitle: "Effectuez des entrées et sorties manuelles au clavier.",

  movementType: "Type de mouvement",
  entry: "Entrée",
  exit: "Sortie",

  searchAnimal: "Rechercher animal",
  entryHelper: "Saisissez la case de destination et l'ID de l'animal.",
  exitHelper: "Sélectionnez si vous voulez faire la sortie par case ou par ID.",

  pen: "Case",
  animalId: "ID animal",
  type: "Type",

  sending: "Envoi...",
  accept: "Accepter",
  cancel: "Annuler",

  confirmEntry: "Confirmer l'entrée",
  confirmExit: "Confirmer la sortie",
  confirmSubtitle: "Vérifiez les données avant d'envoyer le mouvement.",

  incompleteDataTitle: "Données incomplètes",
  entryIncompleteText: "Saisissez la case et l'ID de l'animal.",
  exitPenIncompleteText: "Saisissez la case pour effectuer la sortie.",
  exitIdIncompleteText: "Saisissez l'ID de l'animal pour effectuer la sortie.",

  invalidPenTitle: "Case non valide",
  invalidPenText: "La case doit être un nombre valide supérieur à 0.",

  sendErrorTitle: "Erreur d'envoi",
  connectionErrorTitle: "Erreur de connexion",
  noIpConfigured: "Aucune IP n'est configurée.",
  serverConnectionError: "Impossible de se connecter au serveur.",
  serverEmptyResponse: "Le serveur n'a renvoyé aucun message. Code HTTP {{status}}.",

  entrySentTitle: "Entrée envoyée",
  entrySentText: "Le mouvement d'entrée a été envoyé correctement.",

  exitSentTitle: "Sortie envoyée",
  exitByPenSentText: "La sortie par case a été envoyée correctement.",
  exitByIdSentText: "La sortie par ID a été envoyée correctement.",
},
movimientoAnimalGestacion: {
  smallLabel: "GESTATION",
  title: "Mouvement animal",
  subtitle: "Effectuez des entrées et sorties manuelles au clavier.",

  movementType: "Type de mouvement",
  entry: "Entrée",
  exit: "Sortie",

  searchAnimal: "Rechercher animal",
  entryHelper: "Saisissez la case de destination et l'ID de l'animal.",
  exitHelper: "Saisissez l'ID de l'animal pour effectuer la sortie de gestation.",

  pen: "Case",
  animalId: "ID animal",
  type: "Type",

  sending: "Envoi...",
  accept: "Accepter",
  cancel: "Annuler",

  confirmEntry: "Confirmer l'entrée",
  confirmExit: "Confirmer la sortie",
  confirmSubtitle: "Vérifiez les données avant d'envoyer le mouvement.",

  incompleteDataTitle: "Données incomplètes",
  entryIncompleteText: "Saisissez la case et l'ID de l'animal.",
  exitIdIncompleteText: "Saisissez l'ID de l'animal pour effectuer la sortie.",

  invalidPenTitle: "Case non valide",
  invalidPenText: "La case doit être un nombre valide supérieur à 0.",

  sendErrorTitle: "Erreur d'envoi",
  noIpConfigured: "Aucune IP n'est configurée.",
  serverConnectionError: "Impossible de se connecter au serveur.",
  serverEmptyResponse: "Le serveur n'a renvoyé aucun message. Code HTTP {{status}}.",

  entrySentTitle: "Entrée envoyée",
  entrySentText: "Le mouvement d'entrée en gestation a été envoyé correctement.",

  exitSentTitle: "Sortie envoyée",
  exitByIdSentText: "La sortie de gestation par ID a été envoyée correctement.",
},

gestCorralDetail: {
   title: "État animal gestation",
   emptyTitle: "Il n’y a pas d’animal dans cette case",

   id: "ID",
   crotal: "Boucle",
   cycle: "Cycle",
   day: "Jour",

   stateGestation: "Gestation",
   stateOutOfGestation: "Hors gestation",

   curve: "Courbe",
   correction: "Correction",
   entryDate: "Date d’entrée",
   inseminationDate: "Date d’insémination",
   house: "Bâtiment",
   corral: "Case",
   estimatedFarrowingDate: "Date estimée de mise bas",
   lastFeeding: "Dernière alimentation",

   oneDayWithoutFeeding: "1 jour sans alimentation",
   daysWithoutFeeding: "{{count}} jours sans alimentation",
   of: "sur",

   operationsButton: "Opérations",
   operationsTitle: "Opérations",
   operationsSubtitle: "Sélectionnez une opération",

   operationInseminationDate: "Date d’insémination",
   operationCurve: "Courbe",
   operationBodyCondition: "Condition corporelle",
   operationChangePen: "Changer de case",
   operationExitAnimal: "Sortie animal",
   operationReplaceEarTag: "Remplacer la boucle",

   cancel: "Annuler",
   accept: "Accepter",
   saving: "Enregistrement...",

   selectCurve: "Sélectionner une courbe",
   loadingCurves: "Chargement des courbes...",
   noCurvesAvailable: "Aucune courbe disponible",

   selectBodyCondition: "Sélectionner la condition corporelle",
   loadingBodyConditions: "Chargement des conditions corporelles...",
   noBodyConditionsAvailable: "Aucune condition corporelle disponible",

   changePenTitle: "Changer de case",
   currentPen: "Case actuelle : {{corral}}",
   newPen: "Nouvelle case",
   changePenPlaceholder: "Saisissez la case de destination",

   replaceEarTagTitle: "Remplacer la boucle",
   currentEarTag: "Boucle actuelle : {{crotal}}",
   newEarTag: "Nouvelle boucle",
   replaceEarTagPlaceholder: "Saisissez la nouvelle boucle",

   inseminationDateTitle: "Date d’insémination",
   selectDate: "Sélectionnez la date",
   noFutureInseminationDate: "Il n’est pas possible de sélectionner une date postérieure à la date actuelle.",

   exitAnimalTitle: "Sortie animal",
   exitAnimalGestation: "Sortie animal gestation",
   exitDate: "Date de sortie",
   noFutureExitDate: "La date de sortie ne peut pas être postérieure à la date actuelle.",

   penNotFound: "Case non trouvée",
   changePenGenericError: "Impossible de changer la case.",
   earTagAlreadyAssigned: "La boucle est attribuée à un autre animal",
   replaceEarTagGenericError: "Impossible de remplacer la boucle.",
},

};