export default {
    username: 'Utilisateur',
    password: 'Mot de passe',
    login: 'Connexion',
    welcome: 'Bienvenue',
    change_language: 'Changer de langue',
    Tabs: 'Accueil',

    Lista_instalaciones: 'Installations',
    Maintenance: 'Maintenance',
    DetallesInstalacion: 'Détails installation',
    Grabar: 'Enregistrer',
    EstadoStore: 'État store',
    Nodata: 'Pas de données',
    DosimacRegistration: 'Inscription',
    NewDmMaternity: 'Nouveau Dosimac maternité',
    DosimacG: 'Dosimac-G',
    DosimacI: 'Dosimac-I',
    UpdDmMaternity: 'Changement Dosimac maternité',
    NewDmGestation: 'Nouveau Dosimac gestation',
    UpdDmGestation: 'Changement Dosimac gestation',
    StartScan: 'Chercher appareils DOSIMAC',
    DosimacList: 'Appareils DOSIMAC',
    PressToScan: 'Appuyez',
    DosimacSetup: 'Configuration',
    TestoPresioneAlta: 'Appuyez sur le bouton pour rechercher des appareils',
    Instalación_seleccionada: 'Installation sélectionnée',
    NoInstalacionSeleccionada: 'Aucune installation sélectionnée',
    BorrarGranja: 'Supprimer la ferme',
    Deseaborrarlagranja: 'Voulez-vous supprimer la ferme ?',
    Guardar: 'Enregistrer',
    Cancelar: 'Annuler',
    Aceptar: 'Accepter',
    NombreGranja: 'Nom de la ferme',
    Localidad: 'Localité',
    Provincia: 'Province',
    NombreWifi: 'Wifi SSID',
    PasswordWifi: 'Mot de passe Wifi',
    No_hay_dispositivos: 'Aucun appareil',
    Aviso: 'Avis',
    SearchingDevices: 'Recherche des appareils...',
    NoSePuedeBorrarGranja: 'Impossible de supprimer une nouvelle ferme',
    settings: 'Paramètres',
    softwareVersion: 'Version du logiciel',
    numeroCoral: "Numéro d’enclos",
    numeroMaquina: 'Numéro de machine',
    Enviar: 'Envoyer',
    Salir: 'Quitter',
    Informacion: 'Information',
};