export default {
    username: '用戶名',
    password: '密碼',
    login: '登入',
    welcome: '歡迎',
    change_language: '切換語言',
    Tabs: '首頁',

    Lista_instalaciones: '安裝',
    Maintenance: '維護',
    DetallesInstalacion: '安裝詳情',
    Grabar: '保存',
    EstadoStore: '存儲狀態',
    Nodata: '沒有數據',
    DosimacRegistration: ' 註冊',
    NewDmMaternity: '新 Dosimac 產房',
    DosimacG: 'Dosimac-G',
    DosimacI: 'Dosimac-I',
    UpdDmMaternity: '更新 Dosimac 產房',
    NewDmGestation: '新 Dosimac 妊娠',
    UpdDmGestation: '更新 Dosimac 妊娠',
    StartScan: '搜尋 DOSIMAC 裝置',
    DosimacList: 'DOSIMAC 裝置',
    PressToScan: '按一下',
    DosimacSetup: '設定',
    TestoPresioneAlta: '按下按鈕以搜尋裝置',
    Instalación_seleccionada: '已選擇的安裝',
    NoInstalacionSeleccionada: '未選擇安裝',
    BorrarGranja: '刪除農場',
    Deseaborrarlagranja: '確定要刪除農場嗎？',
    Guardar: '保存',
    Cancelar: '取消',
    Aceptar: '接受',
    NombreGranja: '農場名稱',
    Localidad: '地點',
    Provincia: '省份',
    NombreWifi: 'Wifi SSID',
    PasswordWifi: 'Wifi 密碼',
    No_hay_dispositivos: '沒有裝置',
    Aviso: '通知',
    SearchingDevices: '正在搜尋裝置...',
    NoSePuedeBorrarGranja: '無法刪除新的農場',
    settings: '設定',
    softwareVersion: '軟體版本',
    numeroCoral: '畜欄編號',
    numeroMaquina: '機器編號',
    Enviar: '送出',
    Salir: '離開',
    Informacion: '資訊',
};