export default {
  username: '用戶名',
  password: '密碼',
  login: '登入',
  welcome: '歡迎',
  change_language: '切換語言',
  Tabs: '首頁',

  Lista_instalaciones: '安裝',
  Maintenance: '維護',
  DetallesInstalacion: '安裝詳情',
  Grabar: '保存',
  EstadoStore: '存儲狀態',
  Nodata: '沒有數據',
  DosimacRegistration: ' 註冊',
  NewDmMaternity: '新 Dosimac 產房',
  DosimacG: 'Dosimac-G',
  DosimacI: 'Dosimac-I',
  UpdDmMaternity: '更新 Dosimac 產房',
  NewDmGestation: '新 Dosimac 妊娠',
  UpdDmGestation: '更新 Dosimac 妊娠',
  StartScan: '搜尋 DOSIMAC 裝置',
  DosimacList: 'DOSIMAC 裝置',
  PressToScan: '按一下',
  DosimacSetup: '設定',
  TestoPresioneAlta: '按下按鈕以搜尋裝置',
  Instalación_seleccionada: '已選擇的安裝',
  NoInstalacionSeleccionada: '未選擇安裝',
  BorrarGranja: '刪除農場',
  Deseaborrarlagranja: '確定要刪除農場嗎？',
  Guardar: '保存',
  Cancelar: '取消',
  Aceptar: '接受',
  NombreGranja: '農場名稱',
  Localidad: '地點',
  Provincia: '省份',
  NombreWifi: 'Wifi SSID',
  PasswordWifi: 'Wifi 密碼',
  No_hay_dispositivos: '沒有裝置',
  Aviso: '通知',
  SearchingDevices: '正在搜尋裝置...',
  NoSePuedeBorrarGranja: '無法刪除新的農場',
  settings: '設定',
  softwareVersion: '軟體版本',
  numeroCoral: '畜欄編號',
  numeroMaquina: '機器編號',
  Enviar: '送出',
  Salir: '離開',
  Informacion: '資訊',
  InicioConfiguracion: "開始連線",
  ConfiguracionWifi: "正在設定…",
  ConfiguracionRealizada: "*設定完成*",
  ErrorConfiguracion: "*設定錯誤*",
  CapturaTagCorral: "擷取畜欄標籤",
  CorralTag: "畜欄標籤",
  versionUint16: "此裝置版本僅支援畜欄編號至 65000",
  versionUint32: "此裝置版本支援畜欄編號至 4000000000",
  EnvioConfiguracion: "傳送設定",
  NumeroCorral: "畜欄編號",
  NumeroMaquina: "機器編號",
  Corralnovalida: "無效的畜欄編號",
  NumeroMaquinanovalida: "無效的機器編號",
  configuarIntalacion: "在使用此功能之前需要設定安裝",

  login_title: "登入",
  login_subtitle: "請輸入您的資料。必須先在 IP 設定選單中設定 IP，才能登入。",
  login_username: "使用者",
  login_password: "密碼",
  login_button: "登入",
  login_loading: "登入中...",
  login_footer: "控制面板",

  login_ipRequiredTitle: "需要 IP 設定",
  login_ipRequiredMessage: "您尚未設定伺服器的 IP 位址。請輸入後才能登入。",
  login_serverIpLabel: "伺服器 IP",
  login_cancel: "取消",
  login_accept: "接受",
  login_invalidCredentials: "使用者名稱或密碼錯誤",

  login_configTitle: "設定",
  login_errorTitle: "登入錯誤",
  login_genericErrorTitle: "錯誤",
  login_networkErrorTitle: "網路錯誤",
  login_networkErrorMessage: "無法連線到伺服器。",
  login_noTokenMessage: "後端未回傳任何 token。",
  login_missingDataTitle: "缺少資料",
  login_missingDataMessage: "請輸入使用者名稱和密碼。",
  login_invalidIpTitle: "IP 無效",
  login_invalidIpMessage: "請輸入有效的 IP 或伺服器位址。",
  login_saveIpErrorMessage: "無法儲存 IP 設定。",

  awrStartScan_title: "AWR 設定",
  awrStartScan_description: "用於掃描 Agrident AWR 讀取器的畫面。",
  awrStartScan_button: "掃描 AWR",

  gestacionConfig_screenTitle: "妊娠設定",
  gestacionConfig_chooseOptionTitle: "選擇一個選項",
  gestacionConfig_chooseOptionDescription: "在開始使用讀取器之前，先定義流程。",

  gestacionConfig_entry: "進入",
  gestacionConfig_exit: "離開",
  gestacionConfig_reading: "讀取",
  gestacionConfig_search: "搜尋",

  gestacionConfig_entryParamsTitle: "進入參數",
  gestacionConfig_exitParamsTitle: "離開參數",
  gestacionConfig_entryParamsDescription: "選擇欄位與流程行為。",
  gestacionConfig_exitParamsDescription: "設定離開流程的行為。",

  gestacionConfig_corralLabel: "欄位",
  gestacionConfig_corralPlaceholder: "例：1",
  gestacionConfig_corralRequired: "請輸入欄位以繼續。",

  gestacionConfig_detectUnknownTitle: "識別未知動物",
  gestacionConfig_detectUnknownDescription: "當你讀取到未識別的動物時，可以為牠指定一個 ID",

  gestacionConfig_confirmTitle: "確認送出",
  gestacionConfig_confirmDescription: "送出紀錄前會要求確認。",

  gestacionConfig_animalSearchTitle: "動物搜尋",
  gestacionConfig_animalSearchDescription: "選擇要用耳標還是 ID 搜尋。",
  gestacionConfig_searchByCrotal: "依耳標",
  gestacionConfig_searchById: "依 ID",
  gestacionConfig_manual: "手動",
  gestacionConfig_withSword: "使用讀取器",

  gestacionConfig_crotalLabelSearch: "耳標",
  gestacionConfig_idLabelSearch: "ID",
  gestacionConfig_crotalPlaceholderSearch: "例：982091072397436",
  gestacionConfig_idPlaceholderSearch: "例：A13",
  gestacionConfig_crotalRequiredSearch: "請輸入耳標以繼續。",
  gestacionConfig_idRequiredSearch: "請輸入 ID 以繼續。",

  gestacionConfig_searchWithSwordHelp: "繼續後，會在此畫面使用讀取器讀取，並以該耳標搜尋動物。",

  gestacionConfig_readingSword: "正在讀取讀取器...",
  gestacionConfig_waitingMatch: "等待比對",
  gestacionConfig_searchingAnimal: "正在搜尋動物...",

  gestacionConfig_readingSwordDescription: "請將耳標靠近讀取器以識別動物。",
  gestacionConfig_waitingMatchDescription: "已找到動物。現在請將耳標 {{crotal}} 靠近讀取器以確認比對。",
  gestacionConfig_searchingAnimalDescription: "正在後端查詢動物資訊。",

  gestacionConfig_awrDisconnectedTitle: "AWR 未連線",
  gestacionConfig_awrSavedDescription: "你有已儲存的讀取器。點擊以選擇一個。",
  gestacionConfig_awrNotSavedDescription: "你沒有已儲存的讀取器。點擊以掃描一個。",

  gestacionConfig_scan: "掃描",
  gestacionConfig_continue: "繼續",

  gestacionConfig_alerts_error: "錯誤",
  gestacionConfig_alerts_networkError: "網路錯誤",
  gestacionConfig_alerts_networkErrorMessage: "無法連線到伺服器。",
  gestacionConfig_alerts_backendNoValidCrotal: "後端沒有回傳可供比對的有效耳標。",
  gestacionConfig_alerts_awrNotConnected: "AWR 未連線",
  gestacionConfig_alerts_connectSwordBeforeContinue: "請先連接讀取器再繼續。",
  gestacionConfig_alerts_couldNotStartReading: "無法使用讀取器開始讀取。",

  gestacionConfig_alerts_missingData: "缺少資料",
  gestacionConfig_alerts_writeCrotalToSearch: "請輸入耳標以搜尋。",
  gestacionConfig_alerts_writeIdToSearch: "請輸入 ID 以搜尋。",

  gestacionConfig_alerts_notFound: "找不到",
  gestacionConfig_alerts_animalNotFoundByCrotal: "找不到具有該耳標的動物。",
  gestacionConfig_alerts_animalNotFoundById: "找不到具有該 ID 的動物。",

  gestacionConfig_alerts_warning: "提醒",
  gestacionConfig_alerts_searchError: "搜尋錯誤",

  maternidadConfig_screenTitle: "分娩設定",
  maternidadConfig_chooseOptionTitle: "選擇一個選項",
  maternidadConfig_chooseOptionDescription: "開始使用讀取器之前，請先定義流程。",
  maternidadConfig_entry: "進入",
  maternidadConfig_exit: "離開",
  maternidadConfig_reading: "讀取",
  maternidadConfig_search: "搜尋",
  maternidadConfig_entryParamsTitle: "進入參數",
  maternidadConfig_exitParamsTitle: "離開參數",
  maternidadConfig_entryParamsDescription: "選擇欄位與流程行為。",
  maternidadConfig_exitParamsDescription: "設定離開流程的行為。",
  maternidadConfig_corralLabel: "欄位",
  maternidadConfig_corralPlaceholder: "例如：1",
  maternidadConfig_corralRequired: "請輸入欄位以繼續。",
  maternidadConfig_detectUnknownTitle: "識別未知動物",
  maternidadConfig_detectUnknownDescription: "當你讀取到未識別的動物時，可以為它指定一個 ID",
  maternidadConfig_confirmTitle: "確認送出",
  maternidadConfig_confirmDescription: "在送出每筆記錄前會要求確認。",
  maternidadConfig_animalSearchTitle: "動物搜尋",
  maternidadConfig_animalSearchDescription: "選擇要以耳標或 ID 搜尋。",
  maternidadConfig_searchByCrotal: "依耳標",
  maternidadConfig_searchById: "依 ID",
  maternidadConfig_manual: "手動",
  maternidadConfig_withSword: "用讀取器",
  maternidadConfig_crotalLabelSearch: "耳標",
  maternidadConfig_idLabelSearch: "ID",
  maternidadConfig_crotalPlaceholderSearch: "例如：982091072397436",
  maternidadConfig_idPlaceholderSearch: "例如：A13",
  maternidadConfig_crotalRequiredSearch: "請輸入耳標以繼續。",
  maternidadConfig_idRequiredSearch: "請輸入 ID 以繼續。",
  maternidadConfig_searchWithSwordHelp: "按下掃描後，系統會在此畫面讀取讀取器，並用該耳標搜尋動物。",
  maternidadConfig_readingSword: "正在讀取讀取器...",
  maternidadConfig_waitingMatch: "等待比對",
  maternidadConfig_searchingAnimal: "正在搜尋動物...",
  maternidadConfig_readingSwordDescription: "請將耳標靠近讀取器以識別動物。",
  maternidadConfig_waitingMatchDescription: "已找到動物。現在請將耳標 {{crotal}} 靠近讀取器以確認比對。",
  maternidadConfig_searchingAnimalDescription: "正在從後端查詢動物資訊。",
  maternidadConfig_awrDisconnectedTitle: "AWR 未連線",
  maternidadConfig_awrSavedDescription: "你有已儲存的 AWR。點擊以選擇一個。",
  maternidadConfig_awrNotSavedDescription: "你沒有任何已儲存的 AWR。點擊以掃描一個。",
  maternidadConfig_scan: "掃描",
  maternidadConfig_continue: "繼續",
  maternidadConfig_alert_error: "錯誤",
  maternidadConfig_alert_invalidBackendCrotal: "後端未回傳可用於比對的有效耳標。",
  maternidadConfig_alert_awrNotConnected: "AWR 未連線",
  maternidadConfig_alert_connectSwordBeforeContinue: "請先連接讀取器再繼續。",
  maternidadConfig_alert_couldNotStartReading: "無法使用讀取器開始讀取。",
  maternidadConfig_alert_missingData: "缺少資料",
  maternidadConfig_alert_writeCrotalToSearch: "請輸入耳標以搜尋。",
  maternidadConfig_alert_writeIdToSearch: "請輸入 ID 以搜尋。",
  maternidadConfig_alert_notFound: "找不到",
  maternidadConfig_alert_noAnimalWithCrotal: "找不到具有該耳標的動物。",
  maternidadConfig_alert_noAnimalWithId: "找不到具有該 ID 的動物。",
  maternidadConfig_alert_warning: "警告",
  maternidadConfig_alert_searchError: "搜尋錯誤",
  maternidadConfig_alert_networkError: "網路錯誤",
  maternidadConfig_alert_networkErrorMessage: "無法連接到伺服器。",

  gestationReader_screenTitle: "妊娠讀取器",
  gestationReader_animalInfoTitle: "動物資訊",
  gestationReader_animalInfoDescription: "搜尋中找到的資料。",
  gestationReader_animalCardTitle: "動物資料卡",
  gestationReader_animalIdLabel: "ID",
  gestationReader_animalCrotalLabel: "耳標",
  gestationReader_fieldCorral: "欄位",
  gestationReader_fieldHouse: "棟舍",
  gestationReader_fieldState: "狀態",
  gestationReader_fieldBodyCondition: "體況",
  gestationReader_fieldCycle: "週期",
  gestationReader_fieldSystemEntryDate: "系統登錄日期",
  gestationReader_newSearch: "重新搜尋",
  gestationReader_summaryTitle: "摘要",
  gestationReader_summaryDescription: "在設定中選擇的參數",
  gestationReader_mode: "模式",
  gestationReader_corral: "欄位",
  gestationReader_modeEntry: "進入",
  gestationReader_modeExit: "離開",
  gestationReader_modeReading: "讀取",
  gestationReader_modeSearch: "搜尋",
  gestationReader_detectUnknownTitle: "識別未知動物",
  gestationReader_detectUnknownDescription: "當出現沒有 ID 的動物時，可提供指派 ID。",
  gestationReader_confirmSendTitle: "確認送出",
  gestationReader_confirmSendDescription: "在送出每筆紀錄前會要求確認。",
  gestationReader_changeSettings: "變更設定",
  gestationReader_currentReadingTitle: "目前讀取",
  gestationReader_currentReadingDescription: "偵測到的耳標與其對應 ID 會顯示在這裡。",
  gestationReader_awrDisconnected: "AWR 未連線",
  gestationReader_readCrotal: "已讀取耳標",
  gestationReader_readId: "ID",
  gestationReader_animalWithoutAssignedId: "動物尚未指派 ID",
  gestationReader_unknownAnimal: "未知動物",
  gestationReader_animalWithoutIdTitle: "沒有 ID 的動物",
  gestationReader_animalWithoutIdDescription: "輸入手動 ID 以更新已讀取的耳標。",
  gestationReader_newIdLabel: "新 ID",
  gestationReader_newIdPlaceholder: "例如：A13",
  gestationReader_updateId: "更新 ID",
  gestationReader_updatingId: "更新中...",
  gestationReader_sentRecordsTitle: "已送出的紀錄",
  gestationReader_noRecords: "沒有紀錄。",
  gestationReader_tableHeaderCorral: "欄位",
  gestationReader_tableHeaderId: "ID",
  gestationReader_tableHeaderCrotal: "耳標",
  gestationReader_buttonAutoReading: "自動讀取已啟用",
  gestationReader_buttonAutoSending: "自動送出已啟用",
  gestationReader_buttonSending: "送出中...",
  gestationReader_buttonSend: "送出",
  gestationReader_alertError: "錯誤",
  gestationReader_alertWarning: "提醒",
  gestationReader_alertNetworkError: "網路錯誤",
  gestationReader_alertMissingCrotalTitle: "缺少耳標",
  gestationReader_alertMissingCrotalMessage: "送出前請將耳標靠近讀取器。",
  gestationReader_alertInvalidCrotalTitle: "耳標無效",
  gestationReader_alertInvalidCrotalMessage: "耳標必須為數字。",
  gestationReader_alertReadErrorTitle: "讀取錯誤",
  gestationReader_alertNetworkErrorMessage: "無法連線到伺服器。",
  gestationReader_alertMissingCorralTitle: "缺少欄位",
  gestationReader_alertMissingCorralMessage: "送出前請輸入欄位。",
  gestationReader_alertInvalidCorralTitle: "欄位無效",
  gestationReader_alertInvalidCorralMessage: "欄位必須為數字。",
  gestationReader_alertSendErrorTitle: "送出錯誤",
  gestationReader_alertNoIpConfigured: "尚未設定 IP。",
  gestationReader_alertMissingIdTitle: "缺少 ID",
  gestationReader_alertMissingIdMessage: "更新前請輸入新的 ID。",
  gestationReader_alertMissingAssociatedCrotalTitle: "缺少耳標",
  gestationReader_alertMissingAssociatedCrotalMessage: "沒有可更新的關聯耳標。",
  gestationReader_alertInvalidAssociatedCrotalTitle: "耳標無效",
  gestationReader_alertInvalidAssociatedCrotalMessage: "關聯耳標無效。",
  gestationReader_alertUpdateIdErrorTitle: "更新 ID 時發生錯誤",

  maternityReader_screenTitle: "分娩讀取器",
  maternityReader_alertMissingCrotalTitle: "缺少耳標",
  maternityReader_alertMissingCrotalMessage: "送出前請將耳標靠近讀取器。",
  maternityReader_alertInvalidCrotalTitle: "耳標無效",
  maternityReader_alertInvalidCrotalMessage: "耳標必須為數字。",
  maternityReader_alertReadErrorTitle: "讀取錯誤",
  maternityReader_alertNetworkError: "網路錯誤",
  maternityReader_alertNetworkErrorMessage: "無法連線到伺服器。",
  maternityReader_alertMissingCorralTitle: "缺少欄位",
  maternityReader_alertMissingCorralMessage: "送出前請輸入欄位。",
  maternityReader_alertInvalidCorralTitle: "欄位無效",
  maternityReader_alertInvalidCorralMessage: "欄位必須是數字（例如：8）。",
  maternityReader_alertError: "錯誤",
  maternityReader_alertNoIpConfigured: "尚未設定 IP。",
  maternityReader_alertWarning: "提示",
  maternityReader_alertSendErrorTitle: "送出錯誤",
  maternityReader_alertMissingIdTitle: "缺少 ID",
  maternityReader_alertMissingIdMessage: "更新前請輸入新的 ID。",
  maternityReader_alertMissingAssociatedCrotalTitle: "缺少耳標",
  maternityReader_alertMissingAssociatedCrotalMessage: "沒有可更新的關聯耳標。",
  maternityReader_alertInvalidAssociatedCrotalTitle: "耳標無效",
  maternityReader_alertInvalidAssociatedCrotalMessage: "關聯耳標無效。",
  maternityReader_alertUpdateIdErrorTitle: "更新 ID 時發生錯誤",
  maternityReader_animalInfoTitle: "動物資訊",
  maternityReader_animalInfoDescription: "搜尋到的資料。",
  maternityReader_animalCardTitle: "動物資料",
  maternityReader_animalIdLabel: "ID",
  maternityReader_animalCrotalLabel: "耳標",
  maternityReader_fieldCorral: "欄位",
  maternityReader_fieldHouse: "舍",
  maternityReader_fieldState: "狀態",
  maternityReader_fieldBodyCondition: "體況",
  maternityReader_fieldCycle: "週期",
  maternityReader_fieldSystemEntryDate: "系統登錄日期",
  maternityReader_newSearch: "重新搜尋",
  maternityReader_summaryTitle: "摘要",
  maternityReader_summaryDescription: "在設定中選擇的參數",
  maternityReader_mode: "模式",
  maternityReader_modeEntry: "進入",
  maternityReader_modeExit: "離開",
  maternityReader_modeReading: "讀取",
  maternityReader_corral: "欄位",
  maternityReader_detectUnknownTitle: "識別未知動物",
  maternityReader_detectUnknownDescription: "當出現沒有 ID 的動物時，可為其指定 ID。",
  maternityReader_confirmSendTitle: "確認送出",
  maternityReader_confirmSendDescription: "送出每筆紀錄前會要求確認。",
  maternityReader_changeSettings: "變更設定",
  maternityReader_currentReadingTitle: "目前讀取",
  maternityReader_currentReadingDescription: "偵測到的耳標會顯示在這裡。",
  maternityReader_awrDisconnected: "AWR 未連線",
  maternityReader_readCrotal: "已讀取耳標",
  maternityReader_readId: "ID",
  maternityReader_animalWithoutAssignedId: "動物尚未分配 ID",
  maternityReader_unknownAnimal: "未知動物",
  maternityReader_animalWithoutIdTitle: "沒有 ID 的動物",
  maternityReader_animalWithoutIdDescription: "請輸入手動 ID 以更新已讀取的耳標。",
  maternityReader_newIdLabel: "新 ID",
  maternityReader_newIdPlaceholder: "例如：A13",
  maternityReader_updatingId: "更新中...",
  maternityReader_updateId: "更新 ID",
  maternityReader_sentRecordsTitle: "已送出紀錄",
  maternityReader_tableHeaderCorral: "欄位",
  maternityReader_tableHeaderId: "ID",
  maternityReader_tableHeaderCrotal: "耳標",
  maternityReader_noRecords: "沒有紀錄。",
  maternityReader_buttonAutoReading: "自動讀取已啟用",
  maternityReader_buttonAutoSending: "自動送出已啟用",
  maternityReader_buttonSending: "送出中...",
  maternityReader_buttonSend: "送出",

  awrScanResults_title: "AWR－掃描結果",
  awrScanResults_searching: "正在搜尋 AWR…",
  awrScanResults_warningTitle: "警告",
  awrScanResults_noDevicesNearby: "找不到附近的 AWR 裝置。",
  awrScanResults_connecting: "連線中…",
  awrScanResults_connectErrorFallback: "無法連線",
  awrScanResults_connectedTitle: "已連線",
  awrScanResults_connectedMessage: "已與 {{device}} 建立連線。",
  awrScanResults_genericDevice: "裝置",

  awrSavedList_title: "已掃描的 AWR",
  awrSavedList_connecting: "連線中…",
  awrSavedList_empty: "沒有已儲存的 AWR。請從「Configuración AWR」掃描一個。",
  awrSavedList_connected: "已連線",
  awrSavedList_disconnected: "未連線",
  awrSavedList_renameAccessibility: "重新命名",
  awrSavedList_deleteAccessibility: "刪除",
  awrSavedList_renameTitle: "重新命名 AWR",
  awrSavedList_nameLabel: "名稱",
  awrSavedList_deleteTitle: "刪除已儲存的 AWR",
  awrSavedList_deleteMessage: "確定要將這個 AWR 從清單中刪除嗎？",
  awrSavedList_deleteAction: "刪除",

  ipConfig_title: "IP 設定",
  ipConfig_cardTitle: "CTIFEED 伺服器",
  ipConfig_cardDescription: "請輸入將開啟入口網站的伺服器 IP。",
  ipConfig_inputLabel: "IP（僅 IP）",
  ipConfig_saved: "已儲存",
  ipConfig_alertSuccessTitle: "正確",
  ipConfig_alertSuccessMessage: "IP 正確",
  ipConfig_alertWarningTitle: "警告",
  ipConfig_alertServerNotUpdated: "伺服器未更新",
  ipConfig_alertErrorTitle: "錯誤",
  ipConfig_alertInvalidIp: "IP 無效",

  portal_preparing: "正在準備入口網站...",
  portal_noSessionToken: "沒有工作階段權杖。請重新登入。",
  portal_noIpConfigured: "尚未設定 IP。請先設定伺服器 IP。",
  portal_prepareUrlError: "無法準備入口網站的 URL。",
  portal_loadError: "無法載入入口網站。",
  portal_checkingConnection: "正在檢查入口網站連線...",
  portal_noConnectionTitle: "沒有連線",
  portal_connectionTimeout: "無法連線到入口網站。請確認您已連上正確的網路。",
  portal_connectionError: "無法連線到入口網站。請檢查網路或已設定的 IP。",
  portal_httpError: "無法開啟入口網站。HTTP 錯誤 {{status}}。",
  portal_retry: "重試",
  portal_loading: "正在載入入口網站...",

  AltaDispositivos: "裝置註冊",
  LectorMaternidad: "母育讀取器",
  LectorGestacion: "妊娠讀取器",
  ConfiguracionIP: "IP 設定",
  ConfiguracionAWR: "AWR 設定",
  DarDeAltaAWR: "註冊 AWR",
  AWREscaneados: "已掃描的 AWR",
  CerrarSesion: "登出",

  Config_lastReadMismatchTitle: "讀取到的動物與搜尋結果不符",
  Config_lastReadMismatchCrotal: "耳標",
  Config_lastReadMismatchId: "ID",
  awrBluetoothPermissionMessage: "請開啟藍牙並允許權限，才能進行掃描。",

  animalState: {
    gestation: "妊娠",
    maternity: "哺乳期",
    out_of_gestation: "非妊娠期",
    out_of_maternity: "非哺乳期"
  },


  gestationReader_readingTitle: "耳標讀取",
  gestationReader_labelId: "ID",
  gestationReader_labelCrotal: "耳標",
  gestationReader_labelCorral: "欄舍",
  gestationReader_labelHouse: "棟舍",
  gestationReader_labelState: "狀態",
  gestationReader_autoReadingBadge: "自動讀取",

  gestacionConfig_flowSectionTitle: "流程設定",
  gestacionConfig_workModeTitle: "工作模式",
  gestacionConfig_workModeDescription: "選擇讀取器要執行的操作。",
  gestacionConfig_entryDescription: "登記進入",
  gestacionConfig_exitDescription: "登記離開",
  gestacionConfig_readingDescription: "僅查詢",
  gestacionConfig_searchDescription: "搜尋動物",

  gestacionConfig_sendSettingsTitle: "傳送設定",
  gestacionConfig_sendSettingsDescription: "設定讀取動物時流程的運作方式。",

  gestacionConfig_corralSectionTitle: "進入欄位",
  gestacionConfig_corralSectionDescription: "此資料為必填，才能繼續登記。",

  gestacionConfig_alerts_notice: "通知",
  gestacionConfig_alerts_invalidCrotalFromBackend: "後端沒有回傳可用於比對的有效耳標。",

  common_accept: "接受",

  maternidadConfig_flowSectionTitle: "流程設定",
  maternidadConfig_workModeTitle: "工作模式",
  maternidadConfig_workModeDescription: "選擇讀取器要執行的操作。",
  maternidadConfig_entryDescription: "登記進入",
  maternidadConfig_exitDescription: "登記離開",
  maternidadConfig_readingDescription: "僅查詢",
  maternidadConfig_searchDescription: "搜尋動物",

  maternidadConfig_sendSettingsTitle: "傳送設定",
  maternidadConfig_sendSettingsDescription: "設定讀取動物時流程的運作方式。",

  maternidadConfig_corralSectionTitle: "進入欄位",
  maternidadConfig_corralSectionDescription: "此資料為必填，才能繼續登記。",

  maternidadConfig_alert_invalidCrotalFromBackend: "後端沒有回傳可用於比對的有效耳標。",
  maternidadConfig_readOnlyTitle: "唯讀權限",
maternidadConfig_readOnlyModifySettings: "此使用者只有唯讀權限，無法修改此設定。",
maternidadConfig_readOnlyUseFunction: "此使用者只有唯讀權限，無法使用此功能。",
  ajustesEnvioMaternidad: {
    headerTitle: "傳送設定",
    headerSubtitle: "設定讀取動物時流程的行為方式。",
    cardTitle: "紀錄傳送",
    cardSubtitle: "這些設定會在繼續讀取時套用。"
  },


};