export default {
  username: '用戶名',
  password: '密碼',
  login: '登入',
  welcome: '歡迎',
  change_language: '切換語言',
  Tabs: '首頁',

  Lista_instalaciones: '安裝',
  Maintenance: '維護',
  DetallesInstalacion: '安裝詳情',
  Grabar: '保存',
  EstadoStore: '存儲狀態',
  Nodata: '沒有數據',
  DosimacRegistration: ' 註冊',
  NewDmMaternity: '新 Dosimac 產房',
  DosimacG: 'Dosimac-G',
  DosimacI: 'Dosimac-I',
  UpdDmMaternity: '更新 Dosimac 產房',
  NewDmGestation: '新 Dosimac 妊娠',
  UpdDmGestation: '更新 Dosimac 妊娠',
  StartScan: '搜尋 DOSIMAC 裝置',
  DosimacList: 'DOSIMAC 裝置',
  PressToScan: '按一下',
  DosimacSetup: '設定',
  TestoPresioneAlta: '按下按鈕以搜尋裝置',
  Instalación_seleccionada: '已選擇的安裝',
  NoInstalacionSeleccionada: '未選擇安裝',
  BorrarGranja: '刪除農場',
  Deseaborrarlagranja: '確定要刪除農場嗎？',
  Guardar: '保存',
  Cancelar: '取消',
  Aceptar: '接受',
  NombreGranja: '農場名稱',
  Localidad: '地點',
  Provincia: '省份',
  NombreWifi: 'Wifi SSID',
  PasswordWifi: 'Wifi 密碼',
  No_hay_dispositivos: '沒有裝置',
  Aviso: '通知',
  SearchingDevices: '正在搜尋裝置...',
  NoSePuedeBorrarGranja: '無法刪除新的農場',
  settings: '設定',
  softwareVersion: '軟體版本',
  numeroCoral: '畜欄編號',
  numeroMaquina: '機器編號',
  Enviar: '送出',
  Salir: '離開',
  Informacion: '資訊',
  InicioConfiguracion: "開始連線",
  ConfiguracionWifi: "正在設定…",
  ConfiguracionRealizada: "*設定完成*",
  ErrorConfiguracion: "*設定錯誤*",
  CapturaTagCorral: "擷取畜欄標籤",
  CorralTag: "畜欄標籤",
  versionUint16: "此裝置版本僅支援畜欄編號至 65000",
  versionUint32: "此裝置版本支援畜欄編號至 4000000000",
  EnvioConfiguracion: "傳送設定",
  NumeroCorral: "畜欄編號",
  NumeroMaquina: "機器編號",
  Corralnovalida: "無效的畜欄編號",
  NumeroMaquinanovalida: "無效的機器編號",
  configuarIntalacion: "在使用此功能之前需要設定安裝",

  login_title: "登入",
  login_subtitle: "請輸入您的資料。必須先在 IP 設定選單中設定 IP，才能登入。",
  login_username: "使用者",
  login_password: "密碼",
  login_button: "登入",
  login_loading: "登入中...",
  login_footer: "控制面板",

  login_ipRequiredTitle: "需要 IP 設定",
  login_ipRequiredMessage: "您尚未設定伺服器的 IP 位址。請輸入後才能登入。",
  login_serverIpLabel: "伺服器 IP",
  login_cancel: "取消",
  login_accept: "接受",
  login_invalidCredentials: "使用者名稱或密碼錯誤",

  login_configTitle: "設定",
  login_errorTitle: "登入錯誤",
  login_genericErrorTitle: "錯誤",
  login_networkErrorTitle: "網路錯誤",
  login_networkErrorMessage: "無法連線到伺服器。",
  login_noTokenMessage: "後端未回傳任何 token。",
  login_missingDataTitle: "缺少資料",
  login_missingDataMessage: "請輸入使用者名稱和密碼。",
  login_invalidIpTitle: "IP 無效",
  login_invalidIpMessage: "請輸入有效的 IP 或伺服器位址。",
  login_saveIpErrorMessage: "無法儲存 IP 設定。",

  awrStartScan_title: "AWR 設定",
  awrStartScan_description: "用於掃描 Agrident AWR 讀取器的畫面。",
  awrStartScan_button: "掃描 AWR",

  gestacionConfig_screenTitle: "妊娠設定",
  gestacionConfig_chooseOptionTitle: "選擇一個選項",
  gestacionConfig_chooseOptionDescription: "在開始使用讀取器之前，先定義流程。",

  gestacionConfig_entry: "進入",
  gestacionConfig_exit: "離開",
  gestacionConfig_reading: "讀取",
  gestacionConfig_search: "搜尋",

  gestacionConfig_entryParamsTitle: "進入參數",
  gestacionConfig_exitParamsTitle: "離開參數",
  gestacionConfig_entryParamsDescription: "選擇欄位與流程行為。",
  gestacionConfig_exitParamsDescription: "設定離開流程的行為。",

  gestacionConfig_corralLabel: "欄位",
  gestacionConfig_corralPlaceholder: "例：1",
  gestacionConfig_corralRequired: "請輸入欄位以繼續。",

  gestacionConfig_detectUnknownTitle: "識別未知動物",
  gestacionConfig_detectUnknownDescription: "當你讀取到未識別的動物時，可以為牠指定一個 ID",

  gestacionConfig_confirmTitle: "確認送出",
  gestacionConfig_confirmDescription: "送出紀錄前會要求確認。",

  gestacionConfig_animalSearchTitle: "動物搜尋",
  gestacionConfig_animalSearchDescription: "選擇要用耳標還是 ID 搜尋。",
  gestacionConfig_searchByCrotal: "依耳標",
  gestacionConfig_searchById: "依 ID",
  gestacionConfig_manual: "手動",
  gestacionConfig_withSword: "使用讀取器",

  gestacionConfig_crotalLabelSearch: "耳標",
  gestacionConfig_idLabelSearch: "ID",
  gestacionConfig_crotalPlaceholderSearch: "例：982091072397436",
  gestacionConfig_idPlaceholderSearch: "例：A13",
  gestacionConfig_crotalRequiredSearch: "請輸入耳標以繼續。",
  gestacionConfig_idRequiredSearch: "請輸入 ID 以繼續。",

  gestacionConfig_searchWithSwordHelp: "繼續後，會在此畫面使用讀取器讀取，並以該耳標搜尋動物。",

  gestacionConfig_readingSword: "正在讀取讀取器...",
  gestacionConfig_waitingMatch: "等待比對",
  gestacionConfig_searchingAnimal: "正在搜尋動物...",

  gestacionConfig_readingSwordDescription: "請將耳標靠近讀取器以識別動物。",
  gestacionConfig_waitingMatchDescription: "已找到動物。現在請將耳標 {{crotal}} 靠近讀取器以確認比對。",
  gestacionConfig_searchingAnimalDescription: "正在後端查詢動物資訊。",

  gestacionConfig_awrDisconnectedTitle: "AWR 未連線",
  gestacionConfig_awrSavedDescription: "你有已儲存的讀取器。點擊以選擇一個。",
  gestacionConfig_awrNotSavedDescription: "你沒有已儲存的讀取器。點擊以掃描一個。",

  gestacionConfig_scan: "掃描",
  gestacionConfig_continue: "繼續",

  gestacionConfig_alerts_error: "錯誤",
  gestacionConfig_alerts_networkError: "網路錯誤",
  gestacionConfig_alerts_networkErrorMessage: "無法連線到伺服器。",
  gestacionConfig_alerts_backendNoValidCrotal: "後端沒有回傳可供比對的有效耳標。",
  gestacionConfig_alerts_awrNotConnected: "AWR 未連線",
  gestacionConfig_alerts_connectSwordBeforeContinue: "請先連接讀取器再繼續。",
  gestacionConfig_alerts_couldNotStartReading: "無法使用讀取器開始讀取。",

  gestacionConfig_alerts_missingData: "缺少資料",
  gestacionConfig_alerts_writeCrotalToSearch: "請輸入耳標以搜尋。",
  gestacionConfig_alerts_writeIdToSearch: "請輸入 ID 以搜尋。",

  gestacionConfig_alerts_notFound: "找不到",
  gestacionConfig_alerts_animalNotFoundByCrotal: "找不到具有該耳標的動物。",
  gestacionConfig_alerts_animalNotFoundById: "找不到具有該 ID 的動物。",

  gestacionConfig_alerts_warning: "提醒",
  gestacionConfig_alerts_searchError: "搜尋錯誤",

  maternidadConfig_screenTitle: "分娩設定",
  maternidadConfig_chooseOptionTitle: "選擇一個選項",
  maternidadConfig_chooseOptionDescription: "開始使用讀取器之前，請先定義流程。",
  maternidadConfig_entry: "進入",
  maternidadConfig_exit: "離開",
  maternidadConfig_reading: "讀取",
  maternidadConfig_search: "搜尋",
  maternidadConfig_entryParamsTitle: "進入參數",
  maternidadConfig_exitParamsTitle: "離開參數",
  maternidadConfig_entryParamsDescription: "選擇欄位與流程行為。",
  maternidadConfig_exitParamsDescription: "設定離開流程的行為。",
  maternidadConfig_corralLabel: "欄位",
  maternidadConfig_corralPlaceholder: "例如：1",
  maternidadConfig_corralRequired: "請輸入欄位以繼續。",
  maternidadConfig_detectUnknownTitle: "識別未知動物",
  maternidadConfig_detectUnknownDescription: "當你讀取到未識別的動物時，可以為它指定一個 ID",
  maternidadConfig_confirmTitle: "確認送出",
  maternidadConfig_confirmDescription: "在送出每筆記錄前會要求確認。",
  maternidadConfig_animalSearchTitle: "動物搜尋",
  maternidadConfig_animalSearchDescription: "選擇要以耳標或 ID 搜尋。",
  maternidadConfig_searchByCrotal: "依耳標",
  maternidadConfig_searchById: "依 ID",
  maternidadConfig_manual: "手動",
  maternidadConfig_withSword: "用讀取器",
  maternidadConfig_crotalLabelSearch: "耳標",
  maternidadConfig_idLabelSearch: "ID",
  maternidadConfig_crotalPlaceholderSearch: "例如：982091072397436",
  maternidadConfig_idPlaceholderSearch: "例如：A13",
  maternidadConfig_crotalRequiredSearch: "請輸入耳標以繼續。",
  maternidadConfig_idRequiredSearch: "請輸入 ID 以繼續。",
  maternidadConfig_searchWithSwordHelp: "按下掃描後，系統會在此畫面讀取讀取器，並用該耳標搜尋動物。",
  maternidadConfig_readingSword: "正在讀取讀取器...",
  maternidadConfig_waitingMatch: "等待比對",
  maternidadConfig_searchingAnimal: "正在搜尋動物...",
  maternidadConfig_readingSwordDescription: "請將耳標靠近讀取器以識別動物。",
  maternidadConfig_waitingMatchDescription: "已找到動物。現在請將耳標 {{crotal}} 靠近讀取器以確認比對。",
  maternidadConfig_searchingAnimalDescription: "正在從後端查詢動物資訊。",
  maternidadConfig_awrDisconnectedTitle: "AWR 未連線",
  maternidadConfig_awrSavedDescription: "你有已儲存的 AWR。點擊以選擇一個。",
  maternidadConfig_awrNotSavedDescription: "你沒有任何已儲存的 AWR。點擊以掃描一個。",
  maternidadConfig_scan: "掃描",
  maternidadConfig_continue: "繼續",
  maternidadConfig_alert_error: "錯誤",
  maternidadConfig_alert_invalidBackendCrotal: "後端未回傳可用於比對的有效耳標。",
  maternidadConfig_alert_awrNotConnected: "AWR 未連線",
  maternidadConfig_alert_connectSwordBeforeContinue: "請先連接讀取器再繼續。",
  maternidadConfig_alert_couldNotStartReading: "無法使用讀取器開始讀取。",
  maternidadConfig_alert_missingData: "缺少資料",
  maternidadConfig_alert_writeCrotalToSearch: "請輸入耳標以搜尋。",
  maternidadConfig_alert_writeIdToSearch: "請輸入 ID 以搜尋。",
  maternidadConfig_alert_notFound: "找不到",
  maternidadConfig_alert_noAnimalWithCrotal: "找不到具有該耳標的動物。",
  maternidadConfig_alert_noAnimalWithId: "找不到具有該 ID 的動物。",
  maternidadConfig_alert_warning: "警告",
  maternidadConfig_alert_searchError: "搜尋錯誤",
  maternidadConfig_alert_networkError: "網路錯誤",
  maternidadConfig_alert_networkErrorMessage: "無法連接到伺服器。",

  gestationReader_screenTitle: "妊娠讀取器",
  gestationReader_animalInfoTitle: "動物資訊",
  gestationReader_animalInfoDescription: "搜尋中找到的資料。",
  gestationReader_animalCardTitle: "動物資料卡",
  gestationReader_animalIdLabel: "ID",
  gestationReader_animalCrotalLabel: "耳標",
  gestationReader_fieldCorral: "欄位",
  gestationReader_fieldHouse: "棟舍",
  gestationReader_fieldState: "狀態",
  gestationReader_fieldBodyCondition: "體況",
  gestationReader_fieldCycle: "週期",
  gestationReader_fieldSystemEntryDate: "系統登錄日期",
  gestationReader_newSearch: "重新搜尋",
  gestationReader_summaryTitle: "摘要",
  gestationReader_summaryDescription: "在設定中選擇的參數",
  gestationReader_mode: "模式",
  gestationReader_corral: "欄位",
  gestationReader_modeEntry: "進入",
  gestationReader_modeExit: "離開",
  gestationReader_modeReading: "讀取",
  gestationReader_modeSearch: "搜尋",
  gestationReader_detectUnknownTitle: "識別未知動物",
  gestationReader_detectUnknownDescription: "當出現沒有 ID 的動物時，可提供指派 ID。",
  gestationReader_confirmSendTitle: "確認送出",
  gestationReader_confirmSendDescription: "在送出每筆紀錄前會要求確認。",
  gestationReader_changeSettings: "變更設定",
  gestationReader_currentReadingTitle: "目前讀取",
  gestationReader_currentReadingDescription: "偵測到的耳標與其對應 ID 會顯示在這裡。",
  gestationReader_awrDisconnected: "AWR 未連線",
  gestationReader_readCrotal: "已讀取耳標",
  gestationReader_readId: "ID",
  gestationReader_animalWithoutAssignedId: "動物尚未指派 ID",
  gestationReader_unknownAnimal: "未知動物",
  gestationReader_animalWithoutIdTitle: "沒有 ID 的動物",
  gestationReader_animalWithoutIdDescription: "輸入手動 ID 以更新已讀取的耳標。",
  gestationReader_newIdLabel: "新 ID",
  gestationReader_newIdPlaceholder: "例如：A13",
  gestationReader_updateId: "更新 ID",
  gestationReader_updatingId: "更新中...",
  gestationReader_sentRecordsTitle: "已送出的紀錄",
  gestationReader_noRecords: "沒有紀錄。",
  gestationReader_tableHeaderCorral: "欄位",
  gestationReader_tableHeaderId: "ID",
  gestationReader_tableHeaderCrotal: "耳標",
  gestationReader_buttonAutoReading: "自動讀取已啟用",
  gestationReader_buttonAutoSending: "自動送出已啟用",
  gestationReader_buttonSending: "送出中...",
  gestationReader_buttonSend: "送出",
  gestationReader_alertError: "錯誤",
  gestationReader_alertWarning: "提醒",
  gestationReader_alertNetworkError: "網路錯誤",
  gestationReader_alertMissingCrotalTitle: "缺少耳標",
  gestationReader_alertMissingCrotalMessage: "送出前請將耳標靠近讀取器。",
  gestationReader_alertInvalidCrotalTitle: "耳標無效",
  gestationReader_alertInvalidCrotalMessage: "耳標必須為數字。",
  gestationReader_alertReadErrorTitle: "讀取錯誤",
  gestationReader_alertNetworkErrorMessage: "無法連線到伺服器。",
  gestationReader_alertMissingCorralTitle: "缺少欄位",
  gestationReader_alertMissingCorralMessage: "送出前請輸入欄位。",
  gestationReader_alertInvalidCorralTitle: "欄位無效",
  gestationReader_alertInvalidCorralMessage: "欄位必須為數字。",
  gestationReader_alertSendErrorTitle: "送出錯誤",
  gestationReader_alertNoIpConfigured: "尚未設定 IP。",
  gestationReader_alertMissingIdTitle: "缺少 ID",
  gestationReader_alertMissingIdMessage: "更新前請輸入新的 ID。",
  gestationReader_alertMissingAssociatedCrotalTitle: "缺少耳標",
  gestationReader_alertMissingAssociatedCrotalMessage: "沒有可更新的關聯耳標。",
  gestationReader_alertInvalidAssociatedCrotalTitle: "耳標無效",
  gestationReader_alertInvalidAssociatedCrotalMessage: "關聯耳標無效。",
  gestationReader_alertUpdateIdErrorTitle: "更新 ID 時發生錯誤",
  gestationReader_readerMode: "讀取器",
  gestationReader_keyboardMode: "鍵盤",

  gestationReader_keyboardEntryTitle: "鍵盤輸入",
  gestationReader_keyboardExitTitle: "鍵盤退出",
  gestationReader_keyboardDescription: "使用手機鍵盤手動輸入資料。",
  gestationReader_keyboardId: "ID",
  gestationReader_keyboardCrotal: "耳標",
  gestationReader_keyboardIdLabel: "動物 ID",
  gestationReader_keyboardCrotalLabel: "耳標",
  gestationReader_keyboardIdPlaceholder: "輸入 ID",
  gestationReader_keyboardCrotalPlaceholder: "輸入耳標",
  gestationReader_keyboardAdd: "新增",
  gestationReader_keyboardAdding: "新增中...",

  gestationReader_pendingRecordsTitle: "尚未傳送的記錄",
  gestationReader_buttonSendingBatch: "批次傳送中...",
  gestationReader_buttonSendBatch: "傳送批次",
  gestationReader_buttonSendBatchCount: "傳送批次 ({{count}})",

  gestationReader_noPendingRecordsTitle: "沒有記錄",
  gestationReader_noPendingRecordsText: "沒有待傳送的記錄。",
  gestationReader_batchSentTitle: "批次已傳送",
  gestationReader_batchSentText: "已成功傳送 {{count}} 筆記錄。",
  gestationReader_batchWithErrorsTitle: "批次有錯誤",

  gestationReader_recordSentTitle: "記錄已傳送",
  gestationReader_recordSentText: "移動已成功傳送。",

  gestationReader_invalidAnimalId: "動物 ID 無效。",
  gestationReader_invalidPenRecord: "記錄的欄位無效。",
  gestationReader_invalidCrotalRecord: "記錄的耳標無效。",
  gestationReader_duplicateIdPending: "ID {{id}} 已在尚未傳送的記錄表中。",
  gestationReader_duplicateCrotalPending: "耳標 {{crotal}} 已在尚未傳送的記錄表中。",
  gestationReader_keyboardMissingId: "請輸入動物 ID。",
  gestationReader_keyboardMissingCrotal: "請輸入動物耳標。",
  gestationReader_keyboardMissingPen: "新增動物前請選擇有效的欄位。",
  gestationReader_noAnimalById: "不存在 ID 為 {{id}} 的動物。",
  gestationReader_noAnimalByCrotal: "不存在耳標為 {{crotal}} 的動物。",
  gestationReader_addAnimalError: "無法新增動物。",

  gestationReader_pendingAnimalHint: "讀取到的動物會顯示在這裡。",

  gestationReader_changePenTitle: "變更欄位",
  gestationReader_changePenDescription: "輸入新的進入欄位。",
  gestationReader_newPenLabel: "新欄位",
  gestationReader_newPenPlaceholder: "例：1",
  gestationReader_cancel: "取消",
  gestationReader_save: "儲存",
  gestationReader_accept: "確認",
  gestationReader_sentHistoryTitle: "已傳送歷史",

  maternityReader_screenTitle: "分娩讀取器",
  maternityReader_alertMissingCrotalTitle: "缺少耳標",
  maternityReader_alertMissingCrotalMessage: "送出前請將耳標靠近讀取器。",
  maternityReader_alertInvalidCrotalTitle: "耳標無效",
  maternityReader_alertInvalidCrotalMessage: "耳標必須為數字。",
  maternityReader_alertReadErrorTitle: "讀取錯誤",
  maternityReader_alertNetworkError: "網路錯誤",
  maternityReader_alertNetworkErrorMessage: "無法連線到伺服器。",
  maternityReader_alertMissingCorralTitle: "缺少欄位",
  maternityReader_alertMissingCorralMessage: "送出前請輸入欄位。",
  maternityReader_alertInvalidCorralTitle: "欄位無效",
  maternityReader_alertInvalidCorralMessage: "欄位必須是數字（例如：8）。",
  maternityReader_alertError: "錯誤",
  maternityReader_alertNoIpConfigured: "尚未設定 IP。",
  maternityReader_alertWarning: "提示",
  maternityReader_alertSendErrorTitle: "送出錯誤",
  maternityReader_alertMissingIdTitle: "缺少 ID",
  maternityReader_alertMissingIdMessage: "更新前請輸入新的 ID。",
  maternityReader_alertMissingAssociatedCrotalTitle: "缺少耳標",
  maternityReader_alertMissingAssociatedCrotalMessage: "沒有可更新的關聯耳標。",
  maternityReader_alertInvalidAssociatedCrotalTitle: "耳標無效",
  maternityReader_alertInvalidAssociatedCrotalMessage: "關聯耳標無效。",
  maternityReader_alertUpdateIdErrorTitle: "更新 ID 時發生錯誤",
  maternityReader_animalInfoTitle: "動物資訊",
  maternityReader_animalInfoDescription: "搜尋到的資料。",
  maternityReader_animalCardTitle: "動物資料",
  maternityReader_animalIdLabel: "ID",
  maternityReader_animalCrotalLabel: "耳標",
  maternityReader_fieldCorral: "欄位",
  maternityReader_fieldHouse: "舍",
  maternityReader_fieldState: "狀態",
  maternityReader_fieldBodyCondition: "體況",
  maternityReader_fieldCycle: "週期",
  maternityReader_fieldSystemEntryDate: "系統登錄日期",
  maternityReader_newSearch: "重新搜尋",
  maternityReader_summaryTitle: "摘要",
  maternityReader_summaryDescription: "在設定中選擇的參數",
  maternityReader_mode: "模式",
  maternityReader_modeEntry: "進入",
  maternityReader_modeExit: "離開",
  maternityReader_modeReading: "讀取",
  maternityReader_corral: "欄位",
  maternityReader_detectUnknownTitle: "識別未知動物",
  maternityReader_detectUnknownDescription: "當出現沒有 ID 的動物時，可為其指定 ID。",
  maternityReader_confirmSendTitle: "確認送出",
  maternityReader_confirmSendDescription: "送出每筆紀錄前會要求確認。",
  maternityReader_changeSettings: "變更設定",
  maternityReader_currentReadingTitle: "目前讀取",
  maternityReader_currentReadingDescription: "偵測到的耳標會顯示在這裡。",
  maternityReader_awrDisconnected: "AWR 未連線",
  maternityReader_readCrotal: "已讀取耳標",
  maternityReader_readId: "ID",
  maternityReader_animalWithoutAssignedId: "動物尚未分配 ID",
  maternityReader_unknownAnimal: "未知動物",
  maternityReader_animalWithoutIdTitle: "沒有 ID 的動物",
  maternityReader_animalWithoutIdDescription: "請輸入手動 ID 以更新已讀取的耳標。",
  maternityReader_newIdLabel: "新 ID",
  maternityReader_newIdPlaceholder: "例如：A13",
  maternityReader_updatingId: "更新中...",
  maternityReader_updateId: "更新 ID",
  maternityReader_sentRecordsTitle: "已送出紀錄",
  maternityReader_tableHeaderCorral: "欄位",
  maternityReader_tableHeaderId: "ID",
  maternityReader_tableHeaderCrotal: "耳標",
  maternityReader_noRecords: "沒有紀錄。",
  maternityReader_buttonAutoReading: "自動讀取已啟用",
  maternityReader_buttonAutoSending: "自動送出已啟用",
  maternityReader_buttonSending: "送出中...",
  maternityReader_buttonSend: "送出",

  awrScanResults_title: "AWR－掃描結果",
  awrScanResults_searching: "正在搜尋 AWR…",
  awrScanResults_warningTitle: "警告",
  awrScanResults_noDevicesNearby: "找不到附近的 AWR 裝置。",
  awrScanResults_connecting: "連線中…",
  awrScanResults_connectErrorFallback: "無法連線",
  awrScanResults_connectedTitle: "已連線",
  awrScanResults_connectedMessage: "已與 {{device}} 建立連線。",
  awrScanResults_genericDevice: "裝置",

  awrSavedList_title: "已掃描的 AWR",
  awrSavedList_connecting: "連線中…",
  awrSavedList_empty: "沒有已儲存的 AWR。請從「Configuración AWR」掃描一個。",
  awrSavedList_connected: "已連線",
  awrSavedList_disconnected: "未連線",
  awrSavedList_renameAccessibility: "重新命名",
  awrSavedList_deleteAccessibility: "刪除",
  awrSavedList_renameTitle: "重新命名 AWR",
  awrSavedList_nameLabel: "名稱",
  awrSavedList_deleteTitle: "刪除已儲存的 AWR",
  awrSavedList_deleteMessage: "確定要將這個 AWR 從清單中刪除嗎？",
  awrSavedList_deleteAction: "刪除",

  ipConfig_title: "IP 設定",
  ipConfig_cardTitle: "CTIFEED 伺服器",
  ipConfig_cardDescription: "請輸入將開啟入口網站的伺服器 IP。",
  ipConfig_inputLabel: "IP（僅 IP）",
  ipConfig_saved: "已儲存",
  ipConfig_alertSuccessTitle: "正確",
  ipConfig_alertSuccessMessage: "IP 正確",
  ipConfig_alertWarningTitle: "警告",
  ipConfig_alertServerNotUpdated: "伺服器未更新",
  ipConfig_alertErrorTitle: "錯誤",
  ipConfig_alertInvalidIp: "IP 無效",

  portal_preparing: "正在準備入口網站...",
  portal_noSessionToken: "沒有工作階段權杖。請重新登入。",
  portal_noIpConfigured: "尚未設定 IP。請先設定伺服器 IP。",
  portal_prepareUrlError: "無法準備入口網站的 URL。",
  portal_loadError: "無法載入入口網站。",
  portal_checkingConnection: "正在檢查入口網站連線...",
  portal_noConnectionTitle: "沒有連線",
  portal_connectionTimeout: "無法連線到入口網站。請確認您已連上正確的網路。",
  portal_connectionError: "無法連線到入口網站。請檢查網路或已設定的 IP。",
  portal_httpError: "無法開啟入口網站。HTTP 錯誤 {{status}}。",
  portal_retry: "重試",
  portal_loading: "正在載入入口網站...",

  AltaDispositivos: "裝置註冊",
  LectorMaternidad: "母育讀取器",
  LectorGestacion: "妊娠讀取器",
  ConfiguracionIP: "IP 設定",
  ConfiguracionAWR: "AWR 設定",
  DarDeAltaAWR: "註冊 AWR",
  AWREscaneados: "已掃描的 AWR",
  CerrarSesion: "登出",

  Config_lastReadMismatchTitle: "讀取到的動物與搜尋結果不符",
  Config_lastReadMismatchCrotal: "耳標",
  Config_lastReadMismatchId: "ID",
  awrBluetoothPermissionMessage: "請開啟藍牙並允許權限，才能進行掃描。",

  animalState: {
    gestation: "妊娠",
    maternity: "哺乳期",
    out_of_gestation: "非妊娠期",
    out_of_maternity: "非哺乳期"
  },


  gestationReader_readingTitle: "耳標讀取",
  gestationReader_labelId: "ID",
  gestationReader_labelCrotal: "耳標",
  gestationReader_labelCorral: "欄舍",
  gestationReader_labelHouse: "棟舍",
  gestationReader_labelState: "狀態",
  gestationReader_autoReadingBadge: "自動讀取",

  gestacionConfig_flowSectionTitle: "流程設定",
  gestacionConfig_workModeTitle: "工作模式",
  gestacionConfig_workModeDescription: "選擇讀取器要執行的操作。",
  gestacionConfig_entryDescription: "登記進入",
  gestacionConfig_exitDescription: "登記離開",
  gestacionConfig_readingDescription: "僅查詢",
  gestacionConfig_searchDescription: "搜尋動物",

  gestacionConfig_sendSettingsTitle: "傳送設定",
  gestacionConfig_sendSettingsDescription: "設定讀取動物時流程的運作方式。",

  gestacionConfig_corralSectionTitle: "進入欄位",
  gestacionConfig_corralSectionDescription: "此資料為必填，才能繼續登記。",

  gestacionConfig_alerts_notice: "通知",
  gestacionConfig_alerts_invalidCrotalFromBackend: "後端沒有回傳可用於比對的有效耳標。",

  common_accept: "接受",

  maternidadConfig_flowSectionTitle: "流程設定",
  maternidadConfig_workModeTitle: "工作模式",
  maternidadConfig_workModeDescription: "選擇讀取器要執行的操作。",
  maternidadConfig_entryDescription: "登記進入",
  maternidadConfig_exitDescription: "登記離開",
  maternidadConfig_readingDescription: "僅查詢",
  maternidadConfig_searchDescription: "搜尋動物",

  maternidadConfig_sendSettingsTitle: "傳送設定",
  maternidadConfig_sendSettingsDescription: "設定讀取動物時流程的運作方式。",

  maternidadConfig_corralSectionTitle: "進入欄位",
  maternidadConfig_corralSectionDescription: "此資料為必填，才能繼續登記。",

  maternidadConfig_alert_invalidCrotalFromBackend: "後端沒有回傳可用於比對的有效耳標。",
  maternidadConfig_readOnlyTitle: "唯讀權限",
  maternidadConfig_readOnlyModifySettings: "此使用者只有唯讀權限，無法修改此設定。",
  maternidadConfig_readOnlyUseFunction: "此使用者只有唯讀權限，無法使用此功能。",
  ajustesEnvioMaternidad: {
    headerTitle: "傳送設定",
    headerSubtitle: "設定讀取動物時流程的行為方式。",
    cardTitle: "紀錄傳送",
    cardSubtitle: "這些設定會在繼續讀取時套用。"
  },

  noAlimentadosMaternidad: {
    viewStatus: "查看狀態",
    animalIdNotFound: "找不到動物識別碼。",
    openAnimalInfoError: "無法開啟動物資訊。",
    animalId: "動物 ID",
    corral: "欄舍",
    consumption: "採食量",
    withoutFeeding: "未餵食",
    day: "天",
    days: "天",
    loadingAnimals: "正在載入動物...",
    title: "未餵食動物",
    totalAnimalsMaternity: "分娩舍動物總數：",
    notSeen: "未查看",
    all: "全部",
    sort: "排序",
    emptyTitle: "沒有待處理的動物",
    emptyText: "分娩舍中沒有找到未餵食的動物。",
    sortBy: "排序依據",
    daysWithoutFeeding: "未餵食天數",
    sortDaysHelp: "依未餵食天數排序",
    sortCorralHelp: "依欄舍編號排序",
    descending: "遞減",
    ascending: "遞增",
    filterAnimals: "篩選動物",
    allHelp: "顯示所有動物",
    unmarked: "未標記",
    unmarkedHelp: "隱藏已檢查的動物",
    clearMarkedTitle: "清除已標記的動物",
    clearMarkedText: "將清除所有已檢查動物的標記。",
    cancel: "取消",
    clear: "清除",
    error: "錯誤",
    serverConnectionError: "無法連線到伺服器。"
  },

  noAlimentadosGestacion: {
    animalId: "動物 ID",
    corral: "欄舍",
    consumption: "採食量",
    withoutFeeding: "未餵食",
    day: "天",
    days: "天",
    loadingAnimals: "正在載入動物...",
    title: "未餵食動物",
    totalAnimalsGestation: "妊娠舍動物總數：",
    notSeen: "未查看",
    all: "全部",
    sort: "排序",
    emptyTitle: "沒有待處理的動物",
    emptyText: "妊娠舍中沒有找到未餵食的動物。",
    sortBy: "排序依據",
    daysWithoutFeeding: "未餵食天數",
    sortDaysHep: "依未餵食天數排序",
    sortCorralHelp: "依欄舍編號排序",
    descending: "遞減",
    ascending: "遞增",
    filterAnimals: "篩選動物",
    allHelp: "顯示所有動物",
    unmarked: "未標記",
    unmarkedHelp: "隱藏已檢查的動物",
    clearMarkedTitle: "清除已標記的動物",
    clearMarkedText: "將清除所有已檢查動物的標記。",
    cancel: "取消",
    clear: "清除",
    error: "錯誤",
    serverConnectionError: "無法連線到伺服器。",
    viewStatus: "查看狀態",
    animalIdNotFound: "找不到動物識別碼。",
    openAnimalInfoError: "無法開啟動物資訊。",
  },
  capturaAnimalHome: {
    selectOption: "選擇一個選項",
    unfedAnimalsTitle: "未餵食動物",
    unfedAnimalsDescription: "查看未收到預定餵食的動物。",
    twoFeedsTitle: "2 種飼料",
    twoFeedsDescription: "管理落料口的飼料更換。",
    animalStatusTitle: "動物狀態",
    animalStatusDescription: "查看或更新動物狀態。",
    birthCaptureTitle: "分娩記錄",
    birthCaptureDescription: "登記活仔、死仔和木乃伊胎。",
  },
  cambioPiensoMaternidad: {
    error: "錯誤",
    loadTasksError: "無法載入飼料更換任務。",
    loadingTasks: "正在載入任務...",
    title: "飼料更換",
    pendingTask: "{{count}} 個待處理任務",
    pendingTasks: "{{count}} 個待處理任務",
    emptyTitle: "沒有待處理任務",
    emptyText: "未找到飼料更換任務。",
    animalId: "動物 ID",
    corral: "欄舍",
    setTo: "設定為",
    destination: "目的地"
  },
  estadoAnimal: {
    queryLabel: "查詢",
    title: "動物狀態",
    subtitle: "選擇你要如何識別動物。",
    corral: "欄舍",
    corralDescription: "輸入欄舍編號。",
    id: "ID",
    idDescription: "輸入動物識別碼。",
    animalId: "動物 ID",
    requiredData: "必填資料",
    enterCorral: "輸入欄舍編號。",
    enterId: "輸入動物識別碼。",
    consulting: "查詢中...",
    continue: "繼續",
    accept: "接受",
    serverConnectionError: "無法連線到伺服器。",
    noIpConfigured: "尚未設定 IP。",
    nextScreenPending: "下一步我們會建立動物資訊畫面。",
    corralMaternityDescription: "請輸入分娩欄位編號。",
    idAnimalDescription: "在分娩區與妊娠區搜尋動物。",
    animalNotFound: "找不到動物",
  },

  matCorralDetail: {
    earTagAlreadyAssigned: "此耳標已分配給另一隻動物",
    penNotFound: "找不到欄位",
    readOnlyPermission: "Дозвіл лише на читання",
    readOnlyPermissionText: "Цей користувач має лише права на читання. Він не може виконувати операції з твариною.",
    animalStatus: "動物狀態",
    id: "ID",
    earTag: "耳牌",
    cycle: "週期",
    day: "天",

    curve: "曲線",
    correction: "校正",
    entryDate: "進入日期",
    farrowingDate: "分娩日期",
    house: "舍棟",
    pen: "欄位",
    lastFeeding: "最後餵食",
presentPiglets: "活仔豬",
    inseminationDate: "配種日期",
    teatsNumber: "乳頭數",

    operations: "操作",

    consumption: "採食量",
    ofGrams: "共 {{amount}} g",
    oneDayWithoutFeeding: "1 天未餵食",
    daysWithoutFeeding: "{{count}} 天未餵食",

    noAnimalData: "沒有動物資料",
    noAnimalDataText: "未收到可顯示的資訊。",
    back: "返回",
    operationsPendingTitle: "操作",
    operationsPendingText: "我們會在下一步執行這些操作。",
    moveToWeaning: "轉至離乳",
    chooseOption: "為此動物選擇一項操作。",
    nextOperation: "下一項操作",
    insertAnimal: "新增動物",
    moveToLactation: "轉至哺乳",
    nextStep: "下一步",
    actions: "動作",

    bodyCondition: "體況",
    subState: "子狀態",
    pigletCapture: "仔豬登記",
    animalExit: "動物離場",
    replaceEarTag: "更換耳牌",
    changePen: "更換欄位",
    anonymousAnimalId: "匿名動物識別碼",

    cancel: "取消",
    accept: "確認",
    saving: "儲存中...",
    error: "錯誤",

    operationDone: "操作已成功完成。",
    changeStateDone: "子狀態已成功更新。",
    changeStateError: "無法變更動物狀態。",
    confirmNextOperation: "確定要進入下一項操作嗎？",
    pkidChangeStateNotFound: "找不到動物的內部識別碼。",

    selectExitType: "選擇要套用的離場類型。",
    exitImmediate: "立即離場",
    exitScheduled: "預定離場",
    exitScheduledEmptyHopper: "料斗清空後預定離場",
    cancelScheduledExit: "取消預定離場",
    scheduledDate: "預定日期",
    exitDateLimitText: "不能選擇早於今天或超過 3 天後的日期。",
    animalExitDone: "動物離場已成功完成。",
    animalExitError: "無法完成動物離場。",
    pkidExitNotFound: "找不到動物的內部識別碼。",

    selectCurve: "選擇曲線",
    selectCurveText: "選擇動物的新曲線。",
    loadingCurves: "正在載入曲線...",
    noCurvesAvailable: "沒有可用的曲線。",
    confirmChangeCurve: "確定要變更曲線嗎？",
    loadCurvesError: "無法載入曲線。",
    pkidChangeCurveNotFound: "找不到動物的內部識別碼。",
    changeCurveDone: "曲線已成功更新。",
    changeCurveError: "無法變更曲線。",

    selectBodyConditionText: "選擇動物的新體況。",
    loadingBodyConditions: "正在載入體況...",
    noBodyConditionsAvailable: "沒有可用的體況。",
    confirmChangeBodyCondition: "確定要變更體況嗎？",
    loadBodyConditionsError: "無法載入體況。",
    pkidChangeBodyConditionNotFound: "找不到動物的內部識別碼。",
    changeBodyConditionDone: "體況已成功更新。",
    changeBodyConditionError: "無法變更體況。",

    selectSubStateText: "手動選擇動物的新子狀態。",
    confirmChangeSubState: "確定要變更子狀態嗎？",

    currentPen: "目前欄位：{{pen}}",
    newPen: "新欄位",
    enterNewPen: "請輸入新欄位。",
    pkidChangePenNotFound: "找不到動物的內部識別碼。",
    changePenDone: "欄位已成功更新。",
    changePenError: "無法變更欄位。",

    currentEarTag: "目前耳牌：{{earTag}}",
    newEarTag: "新耳牌",
    enterNewEarTag: "請輸入新耳牌。",
    pkidEarTagNotFound: "找不到動物的內部識別碼。",
    replaceEarTagDone: "耳牌已成功更新。",
    replaceEarTagError: "無法更換耳牌。",

    identifyAnonymousAnimalText: "選擇要為動物指定 ID 或耳牌。",
    newId: "新 ID",
    enterNewId: "請輸入新 ID。",
    idExample: "例：1010",
    earTagExample: "例：123",
    notAnonymousAnimalText: "此動物不是匿名動物，因為已指定 ID 或耳牌。",
    pkidIdentifyNotFound: "找不到動物的內部識別碼。",
    identifyAnonymousAnimalDone: "動物識別碼已成功更新。",
    identifyAnonymousAnimalError: "無法識別匿名動物。",

    livePiglets: "活仔",
    deadPiglets: "死仔",
    mummifiedPiglets: "木乃伊胎",
    totalBornPiglets: "總出生數",
    pigletCaptureText: "輸入活仔、死仔和木乃伊胎數量。",
    captureBeforeLactationText: "轉至哺乳前，請先登記出生仔豬。",
    weaningPigletsOnlyRead: "離乳階段只能查看仔豬資料。",
    pkidPigletsNotFound: "找不到動物的內部識別碼。",
    pigletCaptureDone: "仔豬登記已成功儲存。",
    pigletCaptureError: "無法儲存仔豬登記。",
  },
  subState: {
    prepartum: "產前",
    lactation: "哺乳",
    weaning: "離乳",
  },

  capturaParto: {
    birthDataTitle: "Дані опоросу",
    birthDataSubtitle: "Перевірте дані тварини перед реєстрацією опоросу.",
    corral: "Станок",
    id: "ID",
    date: "Дата",
    subState: "Підстан",

    dataCollectionTitle: "Збір даних",
    dataCollectionSubtitle: "Введіть кількість живонароджених, мертвих і муміфікованих поросят.",
    weaningReadOnly: "На етапі відлучення дані можна лише переглядати.",

    totalBorn: "Усього народжено",
    live: "Живі",
    dead: "Мертві",
    mummified: "Муміфіковані",

    prepartum: "Передпологовий період",
    farrowing: "Опорос",
    lactation: "Лактація",
    weaning: "Відлучення",

    accept: "Прийняти",
    cancel: "Скасувати",
    saving: "Збереження...",

    sentTitle: "Запис надіслано",
    sentMessage: "Реєстрацію опоросу успішно збережено.",

    errorTitle: "Помилка",
    invalidAnimalTitle: "Недійсна тварина",
    invalidAnimalText: "Внутрішній ідентифікатор тварини не знайдено.",
    reportSendError: "Не вдалося зберегти реєстрацію опоросу.",

    invalidDateTitle: "Недійсна дата",
    invalidDateMessage: "Дата опоросу не може бути пізнішою за сьогодні.",
    changeDate: "Змінити дату",

    selectDateTitle: "Вибрати дату",
    selectDateMessage: "Налаштуйте дату опоросу за допомогою кнопок.",
  },

  capturaMaternidadEntrada: {
    title: "分娩記錄",
    description: "透過欄位或 ID 搜尋動物，以登記分娩。",
    maternityLabel: "分娩區",

    corral: "欄位",
    corralDescription: "透過欄位編號搜尋動物。",
    id: "ID",
    idDescription: "透過動物識別碼搜尋。",
    animalId: "動物 ID",

    corralExample: "例：102",
    idExample: "例：1234",

    consulting: "查詢中...",
    continue: "繼續",
    accept: "確認",

    serverConnectionError: "無法連接到伺服器。",
  },
  altaBajaStack: {
    tituloPantalla: "Додавання/вибуття поросят",
    descripcionPantalla: "Знайдіть свиноматку за станком або ID, щоб зареєструвати додавання або вибуття поросят.",
  },
  altaBajaLechones: {
    heroTitle: "仔豬移動",
    statusAlta: "增加",
    statusBaja: "減少",

    corralUpper: "欄位",
    idUpper: "ID",
    dateUpper: "日期",

    movementType: "移動類型",
    movementSubtitle: "選擇要登記增加或減少。",
    adoption: "寄養",
    baja: "減少",

    adoptionData: "寄養資料",
    donorMother: "供仔母豬",
    donatesPiglets: "提供仔豬",
    id: "ID",
    transferredPiglets: "轉移仔豬",
    totalAdopted: "寄養總數",
    total: "總數",

    bajaReason: "減少原因",
    reasonCrushing: "壓死",
    reasonDiarrhea: "腹瀉",
    reasonLowViability: "低活力",
    reasonDeformities: "畸形",
    reasonOther: "其他",

    piglet: "仔豬",
    piglets: "仔豬",
    description: "描述",

    editReason: "編輯原因",
    addReason: "新增原因",
    reasonModalText: "請輸入仔豬數量並描述原因。",

    saving: "儲存中...",
    saveAlta: "儲存增加",
    saveBaja: "儲存減少",
    accept: "確認",
    cancel: "取消",

    error: "錯誤",
    missingData: "缺少資料",
    saveError: "儲存錯誤",
    saveErrorText: "無法儲存操作。",
    selectedAnimalPkidNotFound: "找不到所選動物的內部識別碼。",

    enterTransferredPiglets: "請輸入轉移仔豬數量。",
    invalidTotalTitle: "總數無效",
    invalidPigletsNumber: "請輸入有效的仔豬數量。",

    missingDescriptionTitle: "必須填寫描述",
    missingDescriptionText: "請輸入原因描述。",
    invalidQuantityTitle: "數量無效",
    invalidPigletQuantity: "請輸入有效的仔豬數量。",

    selectReasonRequired: "請至少選擇一個減少原因。",

    adoptionSavedTitle: "增加已儲存",
    adoptionSavedMessage: "已成功登記 {{count}} 隻仔豬。",

    bajasSavedTitle: "減少已儲存",
    bajasSavedMessage: "已成功登記 {{piglets}} 筆減少，原因數：{{reasons}}。",
  },
  avisoAplicacionNoConfigurada: {
    title: "應用程式尚未設定",
    text: "請設定伺服器 IP 位址",
    link: "點擊這裡",
  },
  generalHome: {
    movementAnimalTitle: "動物移動",
    readerDescription: "耳標讀取器。",
    keyboardDescription: "鍵盤",

    ctifeedTitle: "CTIFEED",
    ctifeedDescription: "進入主入口網站。",

    modalApplicationNotConfiguredTitle: "應用程式尚未設定",
    modalNoSessionTitle: "尚未登入",
    modalInstallationUnavailableTitle: "安裝項目無法使用",
    modalPreparingSessionTitle: "正在準備工作階段",
    modalReadOnlyPermissionTitle: "唯讀權限",

    modalApplicationNotConfiguredText: "尚未設定任何安裝項目。請前往安裝項目並選擇一個。",
    modalNoSessionText: "安裝項目已有 IP，但尚未登入。請在安裝項目中檢查使用者名稱和密碼。",
    modalInstallationUnavailableText: "無法連接到所選的安裝項目。請確認已連接到正確的 WiFi 網路，或檢查伺服器 IP。",
    modalPreparingSessionText: "工作階段仍在載入中。請幾秒後再試。",
    modalReadOnlyPermissionText: "您的使用者沒有管理員權限，無法使用此功能。",

    accept: "確認",

    connectingTitle: "連線中...",
    connectingText: "正在檢查與所選安裝項目的連線。",
  },
  movimientoAnimalMaternidad: {
    smallLabel: "移動",
    title: "分娩區",
    subtitle: "使用鍵盤手動執行進入和退出。",

    movementType: "移動類型",
    entry: "進入",
    exit: "退出",

    searchAnimal: "搜尋動物",
    entryHelper: "輸入目標欄位和動物 ID。",
    exitHelper: "選擇要依欄位或 ID 執行退出。",

    pen: "欄位",
    animalId: "動物 ID",
    type: "類型",

    sending: "傳送中...",
    accept: "確認",
    cancel: "取消",

    confirmEntry: "確認進入",
    confirmExit: "確認退出",
    confirmSubtitle: "傳送移動前請先檢查資料。",

    incompleteDataTitle: "資料不完整",
    entryIncompleteText: "請輸入欄位和動物 ID。",
    exitPenIncompleteText: "請輸入欄位以執行退出。",
    exitIdIncompleteText: "請輸入動物 ID 以執行退出。",

    invalidPenTitle: "欄位無效",
    invalidPenText: "欄位必須是大於 0 的有效數字。",

    sendErrorTitle: "傳送錯誤",
    connectionErrorTitle: "連線錯誤",
    noIpConfigured: "尚未設定 IP。",
    serverConnectionError: "無法連接到伺服器。",
    serverEmptyResponse: "伺服器未回傳訊息。HTTP 代碼 {{status}}。",

    entrySentTitle: "進入已傳送",
    entrySentText: "進入移動已成功傳送。",

    exitSentTitle: "退出已傳送",
    exitByPenSentText: "依欄位退出已成功傳送。",
    exitByIdSentText: "依 ID 退出已成功傳送。",
  },
  movimientoAnimalGestacion: {
    smallLabel: "妊娠區",
    title: "動物移動",
    subtitle: "使用鍵盤手動執行進入和退出。",

    movementType: "移動類型",
    entry: "進入",
    exit: "退出",

    searchAnimal: "搜尋動物",
    entryHelper: "輸入目標欄位和動物 ID。",
    exitHelper: "輸入動物 ID 以執行妊娠區退出。",

    pen: "欄位",
    animalId: "動物 ID",
    type: "類型",

    sending: "傳送中...",
    accept: "確認",
    cancel: "取消",

    confirmEntry: "確認進入",
    confirmExit: "確認退出",
    confirmSubtitle: "傳送移動前請先檢查資料。",

    incompleteDataTitle: "資料不完整",
    entryIncompleteText: "請輸入欄位和動物 ID。",
    exitIdIncompleteText: "請輸入動物 ID 以執行退出。",

    invalidPenTitle: "欄位無效",
    invalidPenText: "欄位必須是大於 0 的有效數字。",

    sendErrorTitle: "傳送錯誤",
    noIpConfigured: "尚未設定 IP。",
    serverConnectionError: "無法連接到伺服器。",
    serverEmptyResponse: "伺服器未回傳訊息。HTTP 代碼 {{status}}。",

    entrySentTitle: "進入已傳送",
    entrySentText: "妊娠區進入移動已成功傳送。",

    exitSentTitle: "退出已傳送",
    exitByIdSentText: "依 ID 的妊娠區退出已成功傳送。",
  },
  gestCorralDetail: {
    title: "妊娠動物狀態",
    emptyTitle: "此欄位沒有動物",

    id: "ID",
    crotal: "耳標",
    cycle: "週期",
    day: "天數",

    stateGestation: "妊娠",
    stateOutOfGestation: "非妊娠",

    curve: "曲線",
    correction: "修正",
    entryDate: "進入日期",
    inseminationDate: "配種日期",
    house: "舍區",
    corral: "欄位",
    estimatedFarrowingDate: "預計分娩日期",
    lastFeeding: "最後餵食",

    oneDayWithoutFeeding: "1 天未餵食",
    daysWithoutFeeding: "{{count}} 天未餵食",
    of: "共",

    operationsButton: "操作",
    operationsTitle: "操作",
    operationsSubtitle: "選擇一項操作",

    operationInseminationDate: "配種日期",
    operationCurve: "曲線",
    operationBodyCondition: "體況",
    operationChangePen: "更換欄位",
    operationExitAnimal: "動物離欄",
    operationReplaceEarTag: "更換耳標",

    cancel: "取消",
    accept: "確認",
    saving: "儲存中...",

    selectCurve: "選擇曲線",
    loadingCurves: "正在載入曲線...",
    noCurvesAvailable: "沒有可用的曲線",

    selectBodyCondition: "選擇體況",
    loadingBodyConditions: "正在載入體況...",
    noBodyConditionsAvailable: "沒有可用的體況",

    changePenTitle: "更換欄位",
    currentPen: "目前欄位：{{corral}}",
    newPen: "新欄位",
    changePenPlaceholder: "請輸入目標欄位",

    replaceEarTagTitle: "更換耳標",
    currentEarTag: "目前耳標：{{crotal}}",
    newEarTag: "新耳標",
    replaceEarTagPlaceholder: "請輸入新耳標",

    inseminationDateTitle: "配種日期",
    selectDate: "選擇日期",
    noFutureInseminationDate: "不可選擇晚於目前日期的日期。",

    exitAnimalTitle: "動物離欄",
    exitAnimalGestation: "妊娠動物離欄",
    exitDate: "離欄日期",
    noFutureExitDate: "離欄日期不可晚於目前日期。",

    penNotFound: "找不到欄位",
    changePenGenericError: "無法更換欄位。",
    earTagAlreadyAssigned: "此耳標已分配給另一隻動物",
    replaceEarTagGenericError: "無法更換耳標。",
  },
  tareasMovimientos: {
    tabs: {
      tareas: "任務",
      historial: "歷史紀錄"
    },

    secciones: {
      gestacion: "妊娠區",
      maternidad: "分娩區",
      todos: "全部",
      todas: "全部"
    },

    operaciones: {
      entrada: "進入",
      salida: "離開",
      realizada: "已完成"
    },

    tarjetas: {
      tareasPendientesMovimientos: "待處理的移動任務",
      idAnimal: "動物 ID",
      sinCrotal: "無耳標",
      corralDestino: "目標欄位",
      corralOrigen: "來源欄位",
      fecha: "日期"
    },

    filtros: {
      titulo: "篩選",
      filtrarPorFecha: "依日期篩選",
      hoy: "今天",
      ayer: "昨天",
      fecha: "日期",
      formatoFecha: "DD/MM/YYYY"
    },

    carga: {
      cargandoHistorial: "正在載入歷史紀錄..."
    },

    vacio: {
      sinResultados: "沒有結果",
      sinMovimientosConFiltros: "沒有符合這些篩選條件的已完成移動。",
      sinMovimientosTodavia: "目前尚無已完成的移動。"
    },

    errores: {
      actualizarServidorTareas: "必須更新伺服器才能使用移動任務功能。",
      noCargarTareas: "無法載入任務。",
      noCargarHistorialTitulo: "無法載入歷史紀錄",
      noCargarHistorial: "無法載入移動歷史紀錄。",
      historialNoDisponible: "歷史紀錄無法使用",
      actualizarServidorHistorial: "必須更新伺服器才能使用移動任務歷史紀錄。"
    }
  },
  tareasMovimientosDetalle: {
    tabs: {
      gestacion: "妊娠區",
      maternidad: "分娩區"
    },

    acciones: {
      filtros: "篩選",
      ordenar: "排序",
      marcarRealizado: "標記為已完成",
      marcarSeleccionadas: "標記（{{total}}）",
      marcando: "正在標記...",
      aceptar: "接受",
      cancelar: "取消",
      confirmar: "確認",
      validando: "正在驗證..."
    },

    orden: {
      corralAscendente: "欄位由小到大",
      corralDescendente: "欄位由大到小"
    },

    operaciones: {
      entrada: "進入",
      salida: "離開",
      trasladoEntrada: "轉移進入",
      trasladoSalida: "轉移離開"
    },

    tarjetas: {
      idAnimal: "動物 ID",
      sinCrotal: "無耳標",
      corralDestino: "目標欄位",
      corralOrigen: "來源欄位",
      fecha: "日期"
    },

    estados: {
      cargandoTareas: "正在載入任務...",
      noCargarTareasTitulo: "無法載入任務",
      pulsaReintentar: "點擊以重試",
      sinTareasConFiltros: "沒有符合這些篩選條件的任務",
      sinTareasPendientes: "沒有待處理任務",
      cambiaFiltros: "請嘗試變更已套用的篩選條件。",
      sinMovimientosPendientes: "未找到待處理的移動。"
    },

    modalResultado: {
      tareasRealizadasTitulo: "任務已完成",
      tareasRealizadasMensaje: "已將選取的任務標記為已完成。",
      tareaRealizadaTitulo: "任務已完成",
      tareaRealizadaMensaje: "分娩區進入已標記為已完成。",
      errorTitulo: "錯誤"
    },

    modalCorral: {
      titulo: "確認欄位",
      mensaje: "請檢查分娩區進入的目標欄位。",
      labelCorralDestino: "目標欄位",
      placeholderCorral: "輸入欄位"
    },

    errores: {
      noCargarTareas: "無法載入任務。",
      entradaMaternidadTitulo: "分娩區進入",
      soloUnaEntradaMaternidad: "一次只能標記一個分娩區進入。",
      soloUnaEntradaMaternidadCadaVez: "每次只能標記一個分娩區進入。",
      noMarcarTareas: "無法將任務標記為已完成。",
      corralMaximo9: "請輸入最多 9 位數的有效欄位。",
      corralNoExiste: "欄位不存在。",
      corralOcupado: "欄位已被占用。",
      noValidarCorral: "無法驗證欄位。",
      noValidarCorralMaternidad: "無法驗證分娩區欄位。"
    }
  },
  filtrosTareasMovimientos: {
  cabecera: {
    titulo: "篩選",
    subtituloTareasDe: "{{seccion}}任務",
    limpiar: "清除"
  },

  secciones: {
    gestacion: "妊娠區",
    maternidad: "分娩區"
  },

  bloques: {
    tipoMovimiento: "移動類型",
    fecha: "日期",
    corral: "欄位",
    idAnimal: "動物 ID"
  },

  opciones: {
    todos: "全部",
    entrada: "進入",
    salida: "離開",
    todasLasFechas: "所有日期",
    hoy: "今天",
    manana: "明天",
    fecha: "日期",
    todosLosCorrales: "所有欄位",
    porCorral: "依欄位",
    todosLosAnimales: "所有動物",
    porId: "依 ID"
  },

  placeholders: {
    dia: "DD",
    mes: "MM",
    anio: "YY/YYYY",
    introduceCorral: "輸入欄位",
    introduceIdAnimal: "輸入動物 ID"
  },

  validaciones: {
    fechaCompleta: "請輸入日、月和年。",
    diaDosCifras: "日期必須為 2 位數。",
    mesDosCifras: "月份必須為 2 位數。",
    anioDosOCuatroCifras: "年份必須為 2 位或 4 位數。",
    diaRango: "日期必須介於 01 和 31 之間。",
    mesRango: "月份必須介於 01 和 12 之間。",
    fechaNoExiste: "日期不存在。",
    introduceCorral: "請輸入欄位編號。",
    introduceIdAnimal: "請輸入動物 ID。"
  },

  botones: {
    cancelar: "取消",
    aceptar: "接受"
  }
},
filtrosHistorialMovimientos: {
  cabecera: {
    titulo: "篩選",
    subtitulo: "移動歷史紀錄",
    limpiar: "清除"
  },

  bloques: {
    tipoMovimiento: "移動類型",
    fecha: "日期",
    corral: "欄位",
    idAnimal: "動物 ID"
  },

  opciones: {
    todos: "全部",
    entrada: "進入",
    salida: "離開",
    todasLasFechas: "所有日期",
    hoy: "今天",
    manana: "明天",
    fecha: "日期",
    todosLosCorrales: "所有欄位",
    porCorral: "依欄位",
    todosLosAnimales: "所有動物",
    porId: "依 ID"
  },

  placeholders: {
    dia: "DD",
    mes: "MM",
    anio: "YY/YYYY",
    introduceCorral: "輸入欄位",
    introduceIdAnimal: "輸入動物 ID"
  },

  validaciones: {
    fechaCompleta: "請輸入日、月和年。",
    diaDosCifras: "日期必須為 2 位數。",
    mesDosCifras: "月份必須為 2 位數。",
    anioDosOCuatroCifras: "年份必須為 2 位或 4 位數。",
    diaRango: "日期必須介於 01 和 31 之間。",
    mesRango: "月份必須介於 01 和 12 之間。",
    fechaNoExiste: "日期不存在。",
    introduceCorral: "請輸入欄位編號。",
    introduceIdAnimal: "請輸入動物 ID。"
  },

  botones: {
    cancelar: "取消",
    aceptar: "接受"
  }
}
};